Ruby: ext/digest/sha1/sha1init.c File Reference
sha1init.c File Reference
#include "digest.h"
#include "sha1.h"
Functions
void Init_sha1 ()
Variables
static const rb_digest_metadata_t sha1
Function Documentation
void Init_sha1 ()
Definition at line 27 of file sha1init.c.
References Data_Wrap_Struct, rb_cObject, rb_define_class_under(), rb_define_module(), rb_intern, rb_ivar_set(), rb_path2class(), and rb_require().
Variable Documentation
const rb_digest_metadata_t sha1 static
Initial value:
= {
    RUBY_DIGEST_API_VERSION,
    SHA1_DIGEST_LENGTH,
    SHA1_BLOCK_LENGTH,
    sizeof(SHA1_CTX),
    (rb_digest_hash_init_func_t)SHA1_Init,
    (rb_digest_hash_update_func_t)SHA1_Update,
    (rb_digest_hash_finish_func_t)SHA1_Finish,
}
Definition at line 11 of file sha1init.c.