Ruby: include/ruby/encoding.h File Reference
encoding.h File Reference
#include <stdarg.h>
#include "ruby/oniguruma.h"
Macros
#define ENCODING_INLINE_MAX 1023
#define ENCODING_SHIFT (FL_USHIFT+10)
#define ENCODING_MASK (((VALUE)ENCODING_INLINE_MAX)<<ENCODING_SHIFT)
#define ENCODING_SET_INLINED(obj, i)
#define ENCODING_SET(obj, i)
#define ENCODING_GET_INLINED(obj) (int)((RBASIC(obj)->flags & ENCODING_MASK)>>ENCODING_SHIFT)
#define ENCODING_GET(obj)
#define ENCODING_IS_ASCII8BIT(obj) (ENCODING_GET_INLINED(obj) == 0)
#define ENCODING_MAXNAMELEN 42
#define ENC_CODERANGE_MASK ((int)(FL_USER8|FL_USER9))
#define ENC_CODERANGE_UNKNOWN 0
#define ENC_CODERANGE_7BIT ((int)FL_USER8)
#define ENC_CODERANGE_VALID ((int)FL_USER9)
#define ENC_CODERANGE_BROKEN ((int)(FL_USER8|FL_USER9))
#define ENC_CODERANGE(obj) ((int)RBASIC(obj)->flags & ENC_CODERANGE_MASK)
#define ENC_CODERANGE_ASCIIONLY(obj) (ENC_CODERANGE(obj) == ENC_CODERANGE_7BIT)
#define ENC_CODERANGE_SET(obj, cr)
#define ENC_CODERANGE_CLEAR(obj) ENC_CODERANGE_SET((obj),0)
#define ENC_CODERANGE_AND(a, b)
#define ENCODING_CODERANGE_SET(obj, encindex, cr)
#define rb_enc_to_index(enc) ((enc) ? ENC_TO_ENCINDEX(enc) : 0)
#define rb_enc_name(enc) (enc)->name
#define rb_enc_mbminlen(enc) (enc)->min_enc_len
#define rb_enc_mbmaxlen(enc) (enc)->max_enc_len
#define MBCLEN_CHARFOUND_P(ret) ONIGENC_MBCLEN_CHARFOUND_P(ret)
#define MBCLEN_CHARFOUND_LEN(ret) ONIGENC_MBCLEN_CHARFOUND_LEN(ret)
#define MBCLEN_INVALID_P(ret) ONIGENC_MBCLEN_INVALID_P(ret)
#define MBCLEN_NEEDMORE_P(ret) ONIGENC_MBCLEN_NEEDMORE_P(ret)
#define MBCLEN_NEEDMORE_LEN(ret) ONIGENC_MBCLEN_NEEDMORE_LEN(ret)
#define rb_enc_codepoint(p, e, enc) rb_enc_codepoint_len((p),(e),0,(enc))
#define rb_enc_mbc_to_codepoint(p, e, enc) ONIGENC_MBC_TO_CODE((enc),(UChar*)(p),(UChar*)(e))
#define rb_enc_mbcput(c, buf, enc) ONIGENC_CODE_TO_MBC((enc),(c),(UChar*)(buf))
#define rb_enc_prev_char(s, p, e, enc) ((char *)onigenc_get_prev_char_head((enc),(UChar*)(s),(UChar*)(p),(UChar*)(e)))
#define rb_enc_left_char_head(s, p, e, enc) ((char *)onigenc_get_left_adjust_char_head((enc),(UChar*)(s),(UChar*)(p),(UChar*)(e)))
#define rb_enc_right_char_head(s, p, e, enc) ((char *)onigenc_get_right_adjust_char_head((enc),(UChar*)(s),(UChar*)(p),(UChar*)(e)))
#define rb_enc_step_back(s, p, e, n, enc) ((char *)onigenc_step_back((enc),(UChar*)(s),(UChar*)(p),(UChar*)(e),(int)(n)))
#define rb_enc_is_newline(p, end, enc) ONIGENC_IS_MBC_NEWLINE((enc),(UChar*)(p),(UChar*)(end))
#define rb_enc_isctype(c, t, enc) ONIGENC_IS_CODE_CTYPE((enc),(c),(t))
#define rb_enc_isascii(c, enc) ONIGENC_IS_CODE_ASCII(c)
#define rb_enc_isalpha(c, enc) ONIGENC_IS_CODE_ALPHA((enc),(c))
#define rb_enc_islower(c, enc) ONIGENC_IS_CODE_LOWER((enc),(c))
#define rb_enc_isupper(c, enc) ONIGENC_IS_CODE_UPPER((enc),(c))
#define rb_enc_ispunct(c, enc) ONIGENC_IS_CODE_PUNCT((enc),(c))
#define rb_enc_isalnum(c, enc) ONIGENC_IS_CODE_ALNUM((enc),(c))
#define rb_enc_isprint(c, enc) ONIGENC_IS_CODE_PRINT((enc),(c))
#define rb_enc_isspace(c, enc) ONIGENC_IS_CODE_SPACE((enc),(c))
#define rb_enc_isdigit(c, enc) ONIGENC_IS_CODE_DIGIT((enc),(c))
#define rb_enc_asciicompat(enc) (rb_enc_mbminlen(enc)==1 && !rb_enc_dummy_p(enc))
#define rb_enc_str_asciicompat_p(str) rb_enc_asciicompat(rb_enc_get(str))
#define ENC_DUMMY_FLAG (1<<24)
#define ENC_INDEX_MASK (~(~0U<<24))
#define ENC_TO_ENCINDEX(enc) (int)((enc)->ruby_encoding_index & ENC_INDEX_MASK)
#define ENC_DUMMY_P(enc) ((enc)->ruby_encoding_index & ENC_DUMMY_FLAG)
#define ENC_SET_DUMMY(enc) ((enc)->ruby_encoding_index |= ENC_DUMMY_FLAG)
#define ECONV_ERROR_HANDLER_MASK 0x000000ff
#define ECONV_INVALID_MASK 0x0000000f
#define ECONV_INVALID_REPLACE 0x00000002
#define ECONV_UNDEF_MASK 0x000000f0
#define ECONV_UNDEF_REPLACE 0x00000020
#define ECONV_UNDEF_HEX_CHARREF 0x00000030
#define ECONV_DECORATOR_MASK 0x0000ff00
#define ECONV_NEWLINE_DECORATOR_MASK 0x00003f00
#define ECONV_NEWLINE_DECORATOR_READ_MASK 0x00000f00
#define ECONV_NEWLINE_DECORATOR_WRITE_MASK 0x00003000
#define ECONV_UNIVERSAL_NEWLINE_DECORATOR 0x00000100
#define ECONV_CRLF_NEWLINE_DECORATOR 0x00001000
#define ECONV_CR_NEWLINE_DECORATOR 0x00002000
#define ECONV_XML_TEXT_DECORATOR 0x00004000
#define ECONV_XML_ATTR_CONTENT_DECORATOR 0x00008000
#define ECONV_STATEFUL_DECORATOR_MASK 0x00f00000
#define ECONV_XML_ATTR_QUOTE_DECORATOR 0x00100000
#define ECONV_DEFAULT_NEWLINE_DECORATOR 0
#define ECONV_PARTIAL_INPUT 0x00010000
#define ECONV_AFTER_OUTPUT 0x00020000
#define ENCODING_INLINE_MAX 1023
#define ENCODING_SHIFT (FL_USHIFT+10)
#define ENCODING_MASK (((VALUE)ENCODING_INLINE_MAX)<<ENCODING_SHIFT)
#define ENCODING_SET_INLINED(obj, i)
#define ENCODING_SET(obj, i)
#define ENCODING_GET_INLINED(obj) (int)((RBASIC(obj)->flags & ENCODING_MASK)>>ENCODING_SHIFT)
#define ENCODING_GET(obj)
#define ENCODING_IS_ASCII8BIT(obj) (ENCODING_GET_INLINED(obj) == 0)
#define ENCODING_MAXNAMELEN 42
#define ENC_CODERANGE_MASK ((int)(FL_USER8|FL_USER9))
#define ENC_CODERANGE_UNKNOWN 0
#define ENC_CODERANGE_7BIT ((int)FL_USER8)
#define ENC_CODERANGE_VALID ((int)FL_USER9)
#define ENC_CODERANGE_BROKEN ((int)(FL_USER8|FL_USER9))
#define ENC_CODERANGE(obj) ((int)RBASIC(obj)->flags & ENC_CODERANGE_MASK)
#define ENC_CODERANGE_ASCIIONLY(obj) (ENC_CODERANGE(obj) == ENC_CODERANGE_7BIT)
#define ENC_CODERANGE_SET(obj, cr)
#define ENC_CODERANGE_CLEAR(obj) ENC_CODERANGE_SET((obj),0)
#define ENC_CODERANGE_AND(a, b)
#define ENCODING_CODERANGE_SET(obj, encindex, cr)
#define rb_enc_to_index(enc) ((enc) ? ENC_TO_ENCINDEX(enc) : 0)
#define rb_enc_name(enc) (enc)->name
#define rb_enc_mbminlen(enc) (enc)->min_enc_len
#define rb_enc_mbmaxlen(enc) (enc)->max_enc_len
#define MBCLEN_CHARFOUND_P(ret) ONIGENC_MBCLEN_CHARFOUND_P(ret)
#define MBCLEN_CHARFOUND_LEN(ret) ONIGENC_MBCLEN_CHARFOUND_LEN(ret)
#define MBCLEN_INVALID_P(ret) ONIGENC_MBCLEN_INVALID_P(ret)
#define MBCLEN_NEEDMORE_P(ret) ONIGENC_MBCLEN_NEEDMORE_P(ret)
#define MBCLEN_NEEDMORE_LEN(ret) ONIGENC_MBCLEN_NEEDMORE_LEN(ret)
#define rb_enc_codepoint(p, e, enc) rb_enc_codepoint_len((p),(e),0,(enc))
#define rb_enc_mbc_to_codepoint(p, e, enc) ONIGENC_MBC_TO_CODE((enc),(UChar*)(p),(UChar*)(e))
#define rb_enc_mbcput(c, buf, enc) ONIGENC_CODE_TO_MBC((enc),(c),(UChar*)(buf))
#define rb_enc_prev_char(s, p, e, enc) ((char *)onigenc_get_prev_char_head((enc),(UChar*)(s),(UChar*)(p),(UChar*)(e)))
#define rb_enc_left_char_head(s, p, e, enc) ((char *)onigenc_get_left_adjust_char_head((enc),(UChar*)(s),(UChar*)(p),(UChar*)(e)))
#define rb_enc_right_char_head(s, p, e, enc) ((char *)onigenc_get_right_adjust_char_head((enc),(UChar*)(s),(UChar*)(p),(UChar*)(e)))
#define rb_enc_step_back(s, p, e, n, enc) ((char *)onigenc_step_back((enc),(UChar*)(s),(UChar*)(p),(UChar*)(e),(int)(n)))
#define rb_enc_is_newline(p, end, enc) ONIGENC_IS_MBC_NEWLINE((enc),(UChar*)(p),(UChar*)(end))
#define rb_enc_isctype(c, t, enc) ONIGENC_IS_CODE_CTYPE((enc),(c),(t))
#define rb_enc_isascii(c, enc) ONIGENC_IS_CODE_ASCII(c)
#define rb_enc_isalpha(c, enc) ONIGENC_IS_CODE_ALPHA((enc),(c))
#define rb_enc_islower(c, enc) ONIGENC_IS_CODE_LOWER((enc),(c))
#define rb_enc_isupper(c, enc) ONIGENC_IS_CODE_UPPER((enc),(c))
#define rb_enc_ispunct(c, enc) ONIGENC_IS_CODE_PUNCT((enc),(c))
#define rb_enc_isalnum(c, enc) ONIGENC_IS_CODE_ALNUM((enc),(c))
#define rb_enc_isprint(c, enc) ONIGENC_IS_CODE_PRINT((enc),(c))
#define rb_enc_isspace(c, enc) ONIGENC_IS_CODE_SPACE((enc),(c))
#define rb_enc_isdigit(c, enc) ONIGENC_IS_CODE_DIGIT((enc),(c))
#define rb_enc_asciicompat(enc) (rb_enc_mbminlen(enc)==1 && !rb_enc_dummy_p(enc))
#define rb_enc_str_asciicompat_p(str) rb_enc_asciicompat(rb_enc_get(str))
#define ENC_DUMMY_FLAG (1<<24)
#define ENC_INDEX_MASK (~(~0U<<24))
#define ENC_TO_ENCINDEX(enc) (int)((enc)->ruby_encoding_index & ENC_INDEX_MASK)
#define ENC_DUMMY_P(enc) ((enc)->ruby_encoding_index & ENC_DUMMY_FLAG)
#define ENC_SET_DUMMY(enc) ((enc)->ruby_encoding_index |= ENC_DUMMY_FLAG)
#define ECONV_ERROR_HANDLER_MASK 0x000000ff
#define ECONV_INVALID_MASK 0x0000000f
#define ECONV_INVALID_REPLACE 0x00000002
#define ECONV_UNDEF_MASK 0x000000f0
#define ECONV_UNDEF_REPLACE 0x00000020
#define ECONV_UNDEF_HEX_CHARREF 0x00000030
#define ECONV_DECORATOR_MASK 0x0000ff00
#define ECONV_NEWLINE_DECORATOR_MASK 0x00003f00
#define ECONV_NEWLINE_DECORATOR_READ_MASK 0x00000f00
#define ECONV_NEWLINE_DECORATOR_WRITE_MASK 0x00003000
#define ECONV_UNIVERSAL_NEWLINE_DECORATOR 0x00000100
#define ECONV_CRLF_NEWLINE_DECORATOR 0x00001000
#define ECONV_CR_NEWLINE_DECORATOR 0x00002000
#define ECONV_XML_TEXT_DECORATOR 0x00004000
#define ECONV_XML_ATTR_CONTENT_DECORATOR 0x00008000
#define ECONV_STATEFUL_DECORATOR_MASK 0x00f00000
#define ECONV_XML_ATTR_QUOTE_DECORATOR 0x00100000
#define ECONV_DEFAULT_NEWLINE_DECORATOR 0
#define ECONV_PARTIAL_INPUT 0x00010000
#define ECONV_AFTER_OUTPUT 0x00020000
#define ENCODING_INLINE_MAX 1023
#define ENCODING_SHIFT (FL_USHIFT+10)
#define ENCODING_MASK (((VALUE)ENCODING_INLINE_MAX)<<ENCODING_SHIFT)
#define ENCODING_SET_INLINED(obj, i)
#define ENCODING_SET(obj, i)
#define ENCODING_GET_INLINED(obj) (int)((RBASIC(obj)->flags & ENCODING_MASK)>>ENCODING_SHIFT)
#define ENCODING_GET(obj)
#define ENCODING_IS_ASCII8BIT(obj) (ENCODING_GET_INLINED(obj) == 0)
#define ENCODING_MAXNAMELEN 42
#define ENC_CODERANGE_MASK ((int)(FL_USER8|FL_USER9))
#define ENC_CODERANGE_UNKNOWN 0
#define ENC_CODERANGE_7BIT ((int)FL_USER8)
#define ENC_CODERANGE_VALID ((int)FL_USER9)
#define ENC_CODERANGE_BROKEN ((int)(FL_USER8|FL_USER9))
#define ENC_CODERANGE(obj) ((int)RBASIC(obj)->flags & ENC_CODERANGE_MASK)
#define ENC_CODERANGE_ASCIIONLY(obj) (ENC_CODERANGE(obj) == ENC_CODERANGE_7BIT)
#define ENC_CODERANGE_SET(obj, cr)
#define ENC_CODERANGE_CLEAR(obj) ENC_CODERANGE_SET((obj),0)
#define ENC_CODERANGE_AND(a, b)
#define ENCODING_CODERANGE_SET(obj, encindex, cr)
#define rb_enc_to_index(enc) ((enc) ? ENC_TO_ENCINDEX(enc) : 0)
#define rb_enc_name(enc) (enc)->name
#define rb_enc_mbminlen(enc) (enc)->min_enc_len
#define rb_enc_mbmaxlen(enc) (enc)->max_enc_len
#define MBCLEN_CHARFOUND_P(ret) ONIGENC_MBCLEN_CHARFOUND_P(ret)
#define MBCLEN_CHARFOUND_LEN(ret) ONIGENC_MBCLEN_CHARFOUND_LEN(ret)
#define MBCLEN_INVALID_P(ret) ONIGENC_MBCLEN_INVALID_P(ret)
#define MBCLEN_NEEDMORE_P(ret) ONIGENC_MBCLEN_NEEDMORE_P(ret)
#define MBCLEN_NEEDMORE_LEN(ret) ONIGENC_MBCLEN_NEEDMORE_LEN(ret)
#define rb_enc_codepoint(p, e, enc) rb_enc_codepoint_len((p),(e),0,(enc))
#define rb_enc_mbc_to_codepoint(p, e, enc) ONIGENC_MBC_TO_CODE((enc),(UChar*)(p),(UChar*)(e))
#define rb_enc_mbcput(c, buf, enc) ONIGENC_CODE_TO_MBC((enc),(c),(UChar*)(buf))
#define rb_enc_prev_char(s, p, e, enc) ((char *)onigenc_get_prev_char_head((enc),(UChar*)(s),(UChar*)(p),(UChar*)(e)))
#define rb_enc_left_char_head(s, p, e, enc) ((char *)onigenc_get_left_adjust_char_head((enc),(UChar*)(s),(UChar*)(p),(UChar*)(e)))
#define rb_enc_right_char_head(s, p, e, enc) ((char *)onigenc_get_right_adjust_char_head((enc),(UChar*)(s),(UChar*)(p),(UChar*)(e)))
#define rb_enc_step_back(s, p, e, n, enc) ((char *)onigenc_step_back((enc),(UChar*)(s),(UChar*)(p),(UChar*)(e),(int)(n)))
#define rb_enc_is_newline(p, end, enc) ONIGENC_IS_MBC_NEWLINE((enc),(UChar*)(p),(UChar*)(end))
#define rb_enc_isctype(c, t, enc) ONIGENC_IS_CODE_CTYPE((enc),(c),(t))
#define rb_enc_isascii(c, enc) ONIGENC_IS_CODE_ASCII(c)
#define rb_enc_isalpha(c, enc) ONIGENC_IS_CODE_ALPHA((enc),(c))
#define rb_enc_islower(c, enc) ONIGENC_IS_CODE_LOWER((enc),(c))
#define rb_enc_isupper(c, enc) ONIGENC_IS_CODE_UPPER((enc),(c))
#define rb_enc_ispunct(c, enc) ONIGENC_IS_CODE_PUNCT((enc),(c))
#define rb_enc_isalnum(c, enc) ONIGENC_IS_CODE_ALNUM((enc),(c))
#define rb_enc_isprint(c, enc) ONIGENC_IS_CODE_PRINT((enc),(c))
#define rb_enc_isspace(c, enc) ONIGENC_IS_CODE_SPACE((enc),(c))
#define rb_enc_isdigit(c, enc) ONIGENC_IS_CODE_DIGIT((enc),(c))
#define rb_enc_asciicompat(enc) (rb_enc_mbminlen(enc)==1 && !rb_enc_dummy_p(enc))
#define rb_enc_str_asciicompat_p(str) rb_enc_asciicompat(rb_enc_get(str))
#define ENC_DUMMY_FLAG (1<<24)
#define ENC_INDEX_MASK (~(~0U<<24))
#define ENC_TO_ENCINDEX(enc) (int)((enc)->ruby_encoding_index & ENC_INDEX_MASK)
#define ENC_DUMMY_P(enc) ((enc)->ruby_encoding_index & ENC_DUMMY_FLAG)
#define ENC_SET_DUMMY(enc) ((enc)->ruby_encoding_index |= ENC_DUMMY_FLAG)
#define ECONV_ERROR_HANDLER_MASK 0x000000ff
#define ECONV_INVALID_MASK 0x0000000f
#define ECONV_INVALID_REPLACE 0x00000002
#define ECONV_UNDEF_MASK 0x000000f0
#define ECONV_UNDEF_REPLACE 0x00000020
#define ECONV_UNDEF_HEX_CHARREF 0x00000030
#define ECONV_DECORATOR_MASK 0x0000ff00
#define ECONV_NEWLINE_DECORATOR_MASK 0x00003f00
#define ECONV_NEWLINE_DECORATOR_READ_MASK 0x00000f00
#define ECONV_NEWLINE_DECORATOR_WRITE_MASK 0x00003000
#define ECONV_UNIVERSAL_NEWLINE_DECORATOR 0x00000100
#define ECONV_CRLF_NEWLINE_DECORATOR 0x00001000
#define ECONV_CR_NEWLINE_DECORATOR 0x00002000
#define ECONV_XML_TEXT_DECORATOR 0x00004000
#define ECONV_XML_ATTR_CONTENT_DECORATOR 0x00008000
#define ECONV_STATEFUL_DECORATOR_MASK 0x00f00000
#define ECONV_XML_ATTR_QUOTE_DECORATOR 0x00100000
#define ECONV_DEFAULT_NEWLINE_DECORATOR 0
#define ECONV_PARTIAL_INPUT 0x00010000
#define ECONV_AFTER_OUTPUT 0x00020000
Typedefs
typedef OnigEncodingType rb_encoding
typedef struct rb_econv_t rb_econv_t
Enumerations
enum rb_econv_result_t {
econv_invalid_byte_sequence, econv_undefined_conversion, econv_destination_buffer_full, econv_source_buffer_empty,
econv_finished, econv_after_output, econv_incomplete_input, econv_invalid_byte_sequence,
econv_undefined_conversion, econv_destination_buffer_full, econv_source_buffer_empty, econv_finished,
econv_after_output, econv_incomplete_input
}
Functions
int rb_char_to_option_kcode (int c, int *option, int *kcode)
int rb_enc_replicate (const char *, rb_encoding *)
int rb_define_dummy_encoding (const char *)
int rb_enc_get_index (VALUE obj)
void rb_enc_set_index (VALUE obj, int encindex)
int rb_enc_find_index (const char *name)
int rb_to_encoding_index (VALUE)
rb_encoding * rb_to_encoding (VALUE)
rb_encoding * rb_find_encoding (VALUE)
rb_encoding * rb_enc_get (VALUE)
rb_encoding * rb_enc_compatible (VALUE, VALUE)
rb_encoding * rb_enc_check (VALUE, VALUE)
VALUE rb_enc_associate_index (VALUE, int)
VALUE rb_enc_associate (VALUE, rb_encoding *)
void rb_enc_copy (VALUE dst, VALUE src)
VALUE rb_enc_str_new (const char *, long, rb_encoding *)
VALUE rb_enc_reg_new (const char *, long, rb_encoding *, int)
PRINTF_ARGS (VALUE rb_enc_sprintf(rb_encoding *, const char *,...), 2, 3)
VALUE rb_enc_vsprintf (rb_encoding *, const char *, va_list)
long rb_enc_strlen (const char *, const char *, rb_encoding *)
char * rb_enc_nth (const char *, const char *, long, rb_encoding *)
VALUE rb_obj_encoding (VALUE)
VALUE rb_enc_str_buf_cat (VALUE str, const char *ptr, long len, rb_encoding *enc)
VALUE rb_enc_uint_chr (unsigned int code, rb_encoding *enc)
VALUE rb_external_str_new_with_enc (const char *ptr, long len, rb_encoding *)
VALUE rb_str_export_to_enc (VALUE, rb_encoding *)
VALUE rb_str_conv_enc (VALUE str, rb_encoding *from, rb_encoding *to)
VALUE rb_str_conv_enc_opts (VALUE str, rb_encoding *from, rb_encoding *to, int ecflags, VALUE ecopts)
PRINTF_ARGS (NORETURN(void rb_enc_raise(rb_encoding *, VALUE, const char *,...)), 3, 4)
rb_encoding * rb_enc_from_index (int idx)
rb_encoding * rb_enc_find (const char *name)
int rb_enc_mbclen (const char *p, const char *e, rb_encoding *enc)
int rb_enc_fast_mbclen (const char *p, const char *e, rb_encoding *enc)
int rb_enc_precise_mbclen (const char *p, const char *e, rb_encoding *enc)
int rb_enc_ascget (const char *p, const char *e, int *len, rb_encoding *enc)
unsigned int rb_enc_codepoint_len (const char *p, const char *e, int *len, rb_encoding *enc)
unsigned int rb_enc_codepoint (const char *p, const char *e, rb_encoding *enc)
int rb_enc_codelen (int code, rb_encoding *enc)
int rb_enc_casefold (char *to, const char *p, const char *e, rb_encoding *enc)
int rb_enc_toupper (int c, rb_encoding *enc)
int rb_enc_tolower (int c, rb_encoding *enc)
ID rb_intern3 (const char *, long, rb_encoding *)
ID rb_interned_id_p (const char *, long, rb_encoding *)
int rb_enc_symname_p (const char *, rb_encoding *)
int rb_enc_symname2_p (const char *, long, rb_encoding *)
int rb_enc_str_coderange (VALUE)
long rb_str_coderange_scan_restartable (const char *, const char *, rb_encoding *, int *)
int rb_enc_str_asciionly_p (VALUE)
VALUE rb_enc_from_encoding (rb_encoding *enc)
int rb_enc_unicode_p (rb_encoding *enc)
rb_encoding * rb_ascii8bit_encoding (void)
rb_encoding * rb_utf8_encoding (void)
rb_encoding * rb_usascii_encoding (void)
rb_encoding * rb_locale_encoding (void)
rb_encoding * rb_filesystem_encoding (void)
rb_encoding * rb_default_external_encoding (void)
rb_encoding * rb_default_internal_encoding (void)
int rb_ascii8bit_encindex (void)
int rb_utf8_encindex (void)
int rb_usascii_encindex (void)
int rb_locale_encindex (void)
int rb_filesystem_encindex (void)
VALUE rb_enc_default_external (void)
VALUE rb_enc_default_internal (void)
void rb_enc_set_default_external (VALUE encoding)
void rb_enc_set_default_internal (VALUE encoding)
VALUE rb_locale_charmap (VALUE klass)
long rb_memsearch (const void *, long, const void *, long, rb_encoding *)
char * rb_enc_path_next (const char *, const char *, rb_encoding *)
char * rb_enc_path_skip_prefix (const char *, const char *, rb_encoding *)
char * rb_enc_path_last_separator (const char *, const char *, rb_encoding *)
char * rb_enc_path_end (const char *, const char *, rb_encoding *)
const char * ruby_enc_find_basename (const char *name, long *baselen, long *alllen, rb_encoding *enc)
const char * ruby_enc_find_extname (const char *name, long *len, rb_encoding *enc)
ID rb_check_id_cstr (const char *ptr, long len, rb_encoding *enc)
static int rb_enc_dummy_p (rb_encoding *enc)
VALUE rb_str_encode (VALUE str, VALUE to, int ecflags, VALUE ecopts)
int rb_econv_has_convpath_p (const char *from_encoding, const char *to_encoding)
int rb_econv_prepare_options (VALUE opthash, VALUE *ecopts, int ecflags)
int rb_econv_prepare_opts (VALUE opthash, VALUE *ecopts)
rb_econv_t * rb_econv_open (const char *source_encoding, const char *destination_encoding, int ecflags)
rb_econv_t * rb_econv_open_opts (const char *source_encoding, const char *destination_encoding, int ecflags, VALUE ecopts)
rb_econv_result_t rb_econv_convert (rb_econv_t *ec, const unsigned char **source_buffer_ptr, const unsigned char *source_buffer_end, unsigned char **destination_buffer_ptr, unsigned char *destination_buffer_end, int flags)
void rb_econv_close (rb_econv_t *ec)
int rb_econv_set_replacement (rb_econv_t *ec, const unsigned char *str, size_t len, const char *encname)
int rb_econv_decorate_at_first (rb_econv_t *ec, const char *decorator_name)
int rb_econv_decorate_at_last (rb_econv_t *ec, const char *decorator_name)
VALUE rb_econv_open_exc (const char *senc, const char *denc, int ecflags)
int rb_econv_insert_output (rb_econv_t *ec, const unsigned char *str, size_t len, const char *str_encoding)
const char * rb_econv_encoding_to_insert_output (rb_econv_t *ec)
void rb_econv_check_error (rb_econv_t *ec)
VALUE rb_econv_make_exception (rb_econv_t *ec)
int rb_econv_putbackable (rb_econv_t *ec)
void rb_econv_putback (rb_econv_t *ec, unsigned char *p, int n)
const char * rb_econv_asciicompat_encoding (const char *encname)
VALUE rb_econv_str_convert (rb_econv_t *ec, VALUE src, int flags)
VALUE rb_econv_substr_convert (rb_econv_t *ec, VALUE src, long byteoff, long bytesize, int flags)
VALUE rb_econv_str_append (rb_econv_t *ec, VALUE src, VALUE dst, int flags)
VALUE rb_econv_substr_append (rb_econv_t *ec, VALUE src, long byteoff, long bytesize, VALUE dst, int flags)
void rb_econv_binmode (rb_econv_t *ec)
Variables
RUBY_EXTERN VALUE rb_cEncoding
Macro Definition Documentation
#define ECONV_AFTER_OUTPUT 0x00020000
Referenced by econv_primitive_convert(), gzfile_getc(), Init_transcode(), more_char(), rb_econv_convert0(), rb_trans_conv(), and trans_sweep().
#define ECONV_AFTER_OUTPUT 0x00020000
Definition at line 340 of file parse.y.
#define ECONV_AFTER_OUTPUT 0x00020000
#define ECONV_CR_NEWLINE_DECORATOR 0x00002000
Referenced by decorator_names(), econv_description(), econv_opts(), Init_transcode(), and rb_econv_binmode().
#define ECONV_CR_NEWLINE_DECORATOR 0x00002000
Definition at line 323 of file parse.y.
#define ECONV_CR_NEWLINE_DECORATOR 0x00002000
#define ECONV_CRLF_NEWLINE_DECORATOR 0x00001000
Referenced by decorator_names(), econv_description(), econv_opts(), Init_transcode(), and rb_econv_binmode().
#define ECONV_CRLF_NEWLINE_DECORATOR 0x00001000
Definition at line 322 of file parse.y.
#define ECONV_CRLF_NEWLINE_DECORATOR 0x00001000
#define ECONV_DECORATOR_MASK 0x0000ff00
Definition at line 316 of file parse.y.
#define ECONV_DECORATOR_MASK 0x0000ff00
#define ECONV_DECORATOR_MASK 0x0000ff00
#define ECONV_DEFAULT_NEWLINE_DECORATOR 0
Definition at line 333 of file parse.y.
#define ECONV_DEFAULT_NEWLINE_DECORATOR 0
Referenced by argf_next_argv(), pipe_open(), prep_stdio(), rb_io_extract_modeenc(), and rb_io_s_pipe().
#define ECONV_DEFAULT_NEWLINE_DECORATOR 0
#define ECONV_ERROR_HANDLER_MASK 0x000000ff
Definition at line 307 of file parse.y.
#define ECONV_ERROR_HANDLER_MASK 0x000000ff
Referenced by make_writeconv(), and rb_econv_open().
#define ECONV_ERROR_HANDLER_MASK 0x000000ff
#define ECONV_INVALID_MASK 0x0000000f
Definition at line 309 of file parse.y.
#define ECONV_INVALID_MASK 0x0000000f
#define ECONV_INVALID_MASK 0x0000000f
Referenced by Init_transcode(), and rb_econv_convert().
#define ECONV_INVALID_REPLACE 0x00000002
Definition at line 310 of file parse.y.
#define ECONV_INVALID_REPLACE 0x00000002
#define ECONV_INVALID_REPLACE 0x00000002
Referenced by econv_opts(), Init_transcode(), rb_econv_convert(), rb_strftime_with_timespec(), rb_w32_write_console(), ruby__sfvextra(), and str_transcode0().
#define ECONV_NEWLINE_DECORATOR_MASK 0x00003f00
Definition at line 317 of file parse.y.
#define ECONV_NEWLINE_DECORATOR_MASK 0x00003f00
#define ECONV_NEWLINE_DECORATOR_MASK 0x00003f00
Referenced by argf_next_argv(), decorator_names(), do_writeconv(), econv_description(), econv_opts(), rb_econv_binmode(), rb_io_binmode(), str_transcode0(), and validate_enc_binmode().
#define ECONV_NEWLINE_DECORATOR_READ_MASK 0x00000f00
Definition at line 318 of file parse.y.
#define ECONV_NEWLINE_DECORATOR_READ_MASK 0x00000f00
#define ECONV_NEWLINE_DECORATOR_READ_MASK 0x00000f00
Referenced by make_writeconv().
#define ECONV_NEWLINE_DECORATOR_WRITE_MASK 0x00003000
Referenced by make_readconv().
#define ECONV_NEWLINE_DECORATOR_WRITE_MASK 0x00003000
Definition at line 319 of file parse.y.
#define ECONV_NEWLINE_DECORATOR_WRITE_MASK 0x00003000
#define ECONV_PARTIAL_INPUT 0x00010000
Definition at line 339 of file parse.y.
#define ECONV_PARTIAL_INPUT 0x00010000
Referenced by do_writeconv(), econv_convert(), econv_primitive_convert(), fill_cbuf(), gzfile_getc(), gzfile_newstr(), Init_transcode(), rb_econv_convert0(), rb_trans_conv(), trans_sweep(), transcode_restartable(), and transcode_restartable0().
#define ECONV_PARTIAL_INPUT 0x00010000
#define ECONV_STATEFUL_DECORATOR_MASK 0x00f00000
Referenced by make_writeconv().
#define ECONV_STATEFUL_DECORATOR_MASK 0x00f00000
Definition at line 327 of file parse.y.
#define ECONV_STATEFUL_DECORATOR_MASK 0x00f00000
#define ECONV_UNDEF_HEX_CHARREF 0x00000030
Definition at line 314 of file parse.y.
#define ECONV_UNDEF_HEX_CHARREF 0x00000030
#define ECONV_UNDEF_HEX_CHARREF 0x00000030
Referenced by econv_opts(), Init_transcode(), and rb_econv_convert().
#define ECONV_UNDEF_MASK 0x000000f0
Definition at line 312 of file parse.y.
#define ECONV_UNDEF_MASK 0x000000f0
#define ECONV_UNDEF_MASK 0x000000f0
Referenced by Init_transcode(), and rb_econv_convert().
#define ECONV_UNDEF_REPLACE 0x00000020
Definition at line 313 of file parse.y.
#define ECONV_UNDEF_REPLACE 0x00000020
#define ECONV_UNDEF_REPLACE 0x00000020
Referenced by econv_opts(), Init_transcode(), rb_econv_convert(), rb_strftime_with_timespec(), rb_w32_conv_from_wchar(), rb_w32_write_console(), ruby__sfvextra(), and str_transcode0().
#define ECONV_UNIVERSAL_NEWLINE_DECORATOR 0x00000100
Referenced by decorator_names(), econv_description(), econv_opts(), Init_transcode(), pipe_open(), prep_stdio(), rb_econv_binmode(), rb_io_extract_modeenc(), and rb_io_s_pipe().
#define ECONV_UNIVERSAL_NEWLINE_DECORATOR 0x00000100
Definition at line 321 of file parse.y.
#define ECONV_UNIVERSAL_NEWLINE_DECORATOR 0x00000100
#define ECONV_XML_ATTR_CONTENT_DECORATOR 0x00008000
Referenced by decorator_names(), econv_description(), econv_opts(), Init_transcode(), and str_transcode0().
#define ECONV_XML_ATTR_CONTENT_DECORATOR 0x00008000
Definition at line 325 of file parse.y.
#define ECONV_XML_ATTR_CONTENT_DECORATOR 0x00008000
#define ECONV_XML_ATTR_QUOTE_DECORATOR 0x00100000
Referenced by decorator_names(), econv_description(), econv_opts(), Init_transcode(), and str_transcode0().
#define ECONV_XML_ATTR_QUOTE_DECORATOR 0x00100000
Definition at line 328 of file parse.y.
#define ECONV_XML_ATTR_QUOTE_DECORATOR 0x00100000
#define ECONV_XML_TEXT_DECORATOR 0x00004000
Referenced by decorator_names(), econv_description(), econv_opts(), Init_transcode(), and str_transcode0().
#define ECONV_XML_TEXT_DECORATOR 0x00004000
#define ECONV_XML_TEXT_DECORATOR 0x00004000
Definition at line 324 of file parse.y.
#define ENC_CODERANGE (obj) ((int)RBASIC(obj)->flags & ENC_CODERANGE_MASK)
Definition at line 61 of file parse.y.
#define ENC_CODERANGE (obj) ((int)RBASIC(obj)->flags & ENC_CODERANGE_MASK)
#define ENC_CODERANGE (obj) ((int)RBASIC(obj)->flags & ENC_CODERANGE_MASK)
Referenced by rb_enc_cr_str_buf_cat(), rb_enc_cr_str_copy_for_substr(), rb_enc_cr_str_exact_copy(), rb_enc_str_coderange(), rb_str_append(), rb_str_buf_append(), rb_str_chomp_bang(), rb_str_chop_bang(), rb_str_concat(), rb_str_enumerate_chars(), rb_str_justify(), rb_str_plus(), rb_str_reverse(), rb_str_shared_replace(), rb_str_splice(), rb_str_sub_bang(), rb_str_sublen(), rb_str_subpos(), RUBY_ALIAS_FUNCTION(), single_byte_optimizable(), str_byte_substr(), str_modify_keep_cr(), str_strlen(), and tr_trans().
#define ENC_CODERANGE_7BIT ((int)FL_USER8)
#define ENC_CODERANGE_7BIT ((int)FL_USER8)
Definition at line 58 of file parse.y.
#define ENC_CODERANGE_7BIT ((int)FL_USER8)
Referenced by code_page(), coderange_scan(), enc_inspect(), enc_strlen(), fnmatch_brace(), io_getc(), pack_pack(), parser_str_new(), parser_yylex(), prepare_getline_args(), rb_enc_compatible(), rb_enc_cr_str_buf_cat(), rb_enc_cr_str_copy_for_substr(), rb_enc_str_asciionly_p(), rb_enc_strlen_cr(), rb_external_str_new_with_enc(), rb_file_expand_path_internal(), rb_reg_expr_str(), rb_reg_initialize_str(), rb_reg_prepare_enc(), rb_reg_preprocess_dregexp(), rb_str_buf_cat_ascii(), rb_str_chomp_bang(), rb_str_chop_bang(), rb_str_clear(), rb_str_coderange_scan_restartable(), rb_str_comparable(), rb_str_concat(), rb_str_delete_bang(), rb_str_dump(), rb_str_enumerate_chars(), rb_str_format(), rb_str_hash(), rb_str_is_ascii_only_p(), rb_str_reverse(), rb_str_sub_bang(), rb_usascii_str_new(), reg_fragment_setenc_gen(), RUBY_ALIAS_FUNCTION(), single_byte_optimizable(), str_byte_substr(), str_gsub(), str_new(), str_transcode0(), sym_check_asciionly(), tr_trans(), and w_symbol().
#define ENC_CODERANGE_AND (a, b)
Value:
((a) == ENC_CODERANGE_7BIT ? (b) : \
     (a) == ENC_CODERANGE_VALID ? ((b) == ENC_CODERANGE_7BIT ? ENC_CODERANGE_VALID : (b)) : \
     ENC_CODERANGE_UNKNOWN)
Referenced by rb_str_justify(), rb_str_plus(), and rb_str_splice().
#define ENC_CODERANGE_AND (a, b)
Value:
((a) == ENC_CODERANGE_7BIT ? (b) : \
     (a) == ENC_CODERANGE_VALID ? ((b) == ENC_CODERANGE_7BIT ? ENC_CODERANGE_VALID : (b)) : \
     ENC_CODERANGE_UNKNOWN)
#define ENC_CODERANGE_AND (a, b)
Value:
((a) == ENC_CODERANGE_7BIT ? (b) : \
     (a) == ENC_CODERANGE_VALID ? ((b) == ENC_CODERANGE_7BIT ? ENC_CODERANGE_VALID : (b)) : \
     ENC_CODERANGE_UNKNOWN)
Definition at line 68 of file parse.y.
#define ENC_CODERANGE_ASCIIONLY (obj) (ENC_CODERANGE(obj) == ENC_CODERANGE_7BIT)
Referenced by rb_enc_associate_index().
#define ENC_CODERANGE_ASCIIONLY (obj) (ENC_CODERANGE(obj) == ENC_CODERANGE_7BIT)
#define ENC_CODERANGE_ASCIIONLY (obj) (ENC_CODERANGE(obj) == ENC_CODERANGE_7BIT)
Definition at line 62 of file parse.y.
#define ENC_CODERANGE_BROKEN ((int)(FL_USER8|FL_USER9))
#define ENC_CODERANGE_BROKEN ((int)(FL_USER8|FL_USER9))
Definition at line 60 of file parse.y.
#define ENC_CODERANGE_BROKEN ((int)(FL_USER8|FL_USER9))
Referenced by coderange_scan(), io_getc(), rb_econv_prepare_options(), rb_enc_strlen_cr(), rb_io_getline_fast(), rb_reg_prepare_enc(), rb_str_coderange_scan_restartable(), rb_str_format(), rb_str_justify(), rb_str_splice(), rb_str_sub_bang(), rb_str_valid_encoding_p(), read_all(), str_modify_keep_cr(), sym_check_asciionly(), and tr_trans().
#define ENC_CODERANGE_CLEAR (obj) ENC_CODERANGE_SET((obj),0)
Referenced by rb_enc_associate_index(), rb_file_expand_path_internal(), rb_str_chomp_bang(), rb_str_chop_bang(), rb_str_drop_bytes(), rb_str_force_encoding(), rb_str_modify(), rb_str_modify_expand(), rb_str_resize(), and str_modify_keep_cr().
#define ENC_CODERANGE_CLEAR (obj) ENC_CODERANGE_SET((obj),0)
Definition at line 65 of file parse.y.
#define ENC_CODERANGE_CLEAR (obj) ENC_CODERANGE_SET((obj),0)
#define ENC_CODERANGE_MASK ((int)(FL_USER8|FL_USER9))
#define ENC_CODERANGE_MASK ((int)(FL_USER8|FL_USER9))
Definition at line 56 of file parse.y.
#define ENC_CODERANGE_MASK ((int)(FL_USER8|FL_USER9))
#define ENC_CODERANGE_SET (obj, cr)
Value:
(RBASIC(obj)->flags = \
                                   (RBASIC(obj)->flags & ~ENC_CODERANGE_MASK) | (cr))
Referenced by io_getc(), rb_enc_cr_str_copy_for_substr(), rb_enc_cr_str_exact_copy(), rb_enc_str_coderange(), rb_io_getline_fast(), rb_str_append(), rb_str_b(), rb_str_buf_append(), rb_str_clear(), rb_str_concat(), rb_str_delete_bang(), rb_str_dump(), rb_str_format(), rb_str_justify(), rb_str_reverse(), rb_str_shared_replace(), rb_str_splice(), rb_str_sub_bang(), read_all(), str_byte_substr(), str_encode_associate(), str_gsub(), str_new(), str_strlen(), and tr_trans().
#define ENC_CODERANGE_SET (obj, cr)
Value:
(RBASIC(obj)->flags = \
                                   (RBASIC(obj)->flags & ~ENC_CODERANGE_MASK) | (cr))
#define ENC_CODERANGE_SET (obj, cr)
Value:
(RBASIC(obj)->flags = \
                                   (RBASIC(obj)->flags & ~ENC_CODERANGE_MASK) | (cr))
Definition at line 63 of file parse.y.
#define ENC_CODERANGE_UNKNOWN 0
Referenced by parser_yylex(), rb_enc_cr_str_buf_cat(), rb_enc_str_buf_cat(), rb_enc_str_coderange(), rb_enc_strlen(), rb_reg_expr_str(), rb_str_coderange_scan_restartable(), rb_str_format(), rb_str_reverse(), rb_str_sub_bang(), and str_byte_substr().
#define ENC_CODERANGE_UNKNOWN 0
#define ENC_CODERANGE_UNKNOWN 0
Definition at line 57 of file parse.y.
#define ENC_CODERANGE_VALID ((int)FL_USER9)
Referenced by coderange_scan(), enc_strlen(), io_getc(), pack_unpack(), rb_enc_cr_str_buf_cat(), rb_enc_cr_str_copy_for_substr(), rb_enc_strlen_cr(), rb_reg_expr_str(), rb_str_b(), rb_str_buf_cat_ascii(), rb_str_clear(), rb_str_coderange_scan_restartable(), rb_str_concat(), rb_str_delete_bang(), rb_str_enumerate_chars(), rb_str_reverse(), rb_str_sub_bang(), rb_str_subpos(), str_byte_substr(), str_encode_associate(), str_gsub(), str_strlen(), and tr_trans().
#define ENC_CODERANGE_VALID ((int)FL_USER9)
#define ENC_CODERANGE_VALID ((int)FL_USER9)
Definition at line 59 of file parse.y.
#define ENC_DUMMY_FLAG (1<<24)
#define ENC_DUMMY_FLAG (1<<24)
#define ENC_DUMMY_FLAG (1<<24)
Definition at line 226 of file parse.y.
#define ENC_DUMMY_P (enc) ((enc)->ruby_encoding_index & ENC_DUMMY_FLAG)
#define ENC_DUMMY_P (enc) ((enc)->ruby_encoding_index & ENC_DUMMY_FLAG)
Referenced by enc_dummy_p(), and rb_enc_register().
#define ENC_DUMMY_P (enc) ((enc)->ruby_encoding_index & ENC_DUMMY_FLAG)
Definition at line 231 of file parse.y.
Referenced by rb_enc_dummy_p().
#define ENC_INDEX_MASK (~(~0U<<24))
#define ENC_INDEX_MASK (~(~0U<<24))
#define ENC_INDEX_MASK (~(~0U<<24))
Definition at line 227 of file parse.y.
#define ENC_SET_DUMMY (enc) ((enc)->ruby_encoding_index |= ENC_DUMMY_FLAG)
Definition at line 232 of file parse.y.
#define ENC_SET_DUMMY (enc) ((enc)->ruby_encoding_index |= ENC_DUMMY_FLAG)
#define ENC_SET_DUMMY (enc) ((enc)->ruby_encoding_index |= ENC_DUMMY_FLAG)
Referenced by rb_define_dummy_encoding(), rb_encdb_dummy(), and set_base_encoding().
#define ENC_TO_ENCINDEX (enc) (int)((enc)->ruby_encoding_index & ENC_INDEX_MASK)
#define ENC_TO_ENCINDEX (enc) (int)((enc)->ruby_encoding_index & ENC_INDEX_MASK)
Referenced by enc_autoload(), and rb_enc_from_encoding().
#define ENC_TO_ENCINDEX (enc) (int)((enc)->ruby_encoding_index & ENC_INDEX_MASK)
Definition at line 229 of file parse.y.
#define ENCODING_CODERANGE_SET (obj, encindex, cr)
Value:
do { \
        VALUE rb_encoding_coderange_obj = (obj); \
        ENCODING_SET(rb_encoding_coderange_obj, (encindex)); \
        ENC_CODERANGE_SET(rb_encoding_coderange_obj, (cr)); \
    } while (0)
#define ENCODING_CODERANGE_SET (obj, encindex, cr)
Value:
do { \
        VALUE rb_encoding_coderange_obj = (obj); \
        ENCODING_SET(rb_encoding_coderange_obj, (encindex)); \
        ENC_CODERANGE_SET(rb_encoding_coderange_obj, (cr)); \
    } while (0)
Referenced by code_page(), enc_inspect(), pack_pack(), pack_unpack(), rb_enc_cr_str_buf_cat(), rb_str_plus(), rb_usascii_str_new(), and RUBY_ALIAS_FUNCTION().
#define ENCODING_CODERANGE_SET (obj, encindex, cr)
Value:
do { \
        VALUE rb_encoding_coderange_obj = (obj); \
        ENCODING_SET(rb_encoding_coderange_obj, (encindex)); \
        ENC_CODERANGE_SET(rb_encoding_coderange_obj, (cr)); \
    } while (0)
Definition at line 73 of file parse.y.
#define ENCODING_GET (obj)
Value:
(ENCODING_GET_INLINED(obj) != ENCODING_INLINE_MAX ? \
     ENCODING_GET_INLINED(obj) : \
     rb_enc_get_index(obj))
#define ENCODING_GET (obj)
Value:
(ENCODING_GET_INLINED(obj) != ENCODING_INLINE_MAX ? \
     ENCODING_GET_INLINED(obj) : \
     rb_enc_get_index(obj))
Definition at line 47 of file parse.y.
#define ENCODING_GET (obj)
Value:
(ENCODING_GET_INLINED(obj) != ENCODING_INLINE_MAX ? \
     ENCODING_GET_INLINED(obj) : \
     rb_enc_get_index(obj))
Referenced by file_path_convert(), rb_enc_cr_str_buf_cat(), rb_reg_equal(), rb_reg_regcomp(), rb_str_buf_append(), rb_str_buf_cat_ascii(), rb_str_cmp(), rb_str_comparable(), rb_str_hash(), rb_str_new_frozen(), reg_fragment_setenc_gen(), str_enc_copy(), and str_end_with_asciichar().
#define ENCODING_GET_INLINED (obj) (int)((RBASIC(obj)->flags & ENCODING_MASK)>>ENCODING_SHIFT)
Referenced by rb_enc_get_index().
#define ENCODING_GET_INLINED (obj) (int)((RBASIC(obj)->flags & ENCODING_MASK)>>ENCODING_SHIFT)
#define ENCODING_GET_INLINED (obj) (int)((RBASIC(obj)->flags & ENCODING_MASK)>>ENCODING_SHIFT)
Definition at line 46 of file parse.y.
#define ENCODING_INLINE_MAX 1023
#define ENCODING_INLINE_MAX 1023
Definition at line 29 of file parse.y.
#define ENCODING_INLINE_MAX 1023
Referenced by enc_set_index(), and rb_enc_get_index().
#define ENCODING_IS_ASCII8BIT (obj) (ENCODING_GET_INLINED(obj) == 0)
#define ENCODING_IS_ASCII8BIT (obj) (ENCODING_GET_INLINED(obj) == 0)
Definition at line 52 of file parse.y.
#define ENCODING_IS_ASCII8BIT (obj) (ENCODING_GET_INLINED(obj) == 0)
Referenced by rb_enc_cr_str_buf_cat(), and reg_fragment_setenc_gen().
#define ENCODING_MASK (((VALUE)ENCODING_INLINE_MAX)<<ENCODING_SHIFT)
#define ENCODING_MASK (((VALUE)ENCODING_INLINE_MAX)<<ENCODING_SHIFT)
Definition at line 31 of file parse.y.
#define ENCODING_MASK (((VALUE)ENCODING_INLINE_MAX)<<ENCODING_SHIFT)
#define ENCODING_MAXNAMELEN 42
Definition at line 54 of file parse.y.
#define ENCODING_MAXNAMELEN 42
Referenced by parse_mode_enc().
#define ENCODING_MAXNAMELEN 42
#define ENCODING_SET (obj, i)
Value:
do {\
    VALUE rb_encoding_set_obj = (obj); \
    int encoding_set_enc_index = (i); \
    if (encoding_set_enc_index < ENCODING_INLINE_MAX) \
        ENCODING_SET_INLINED(rb_encoding_set_obj, encoding_set_enc_index); \
    else \
        rb_enc_set_index(rb_encoding_set_obj, encoding_set_enc_index); \
} while (0)
Referenced by reg_fragment_setenc_gen().
#define ENCODING_SET (obj, i)
Value:
do {\
    VALUE rb_encoding_set_obj = (obj); \
    int encoding_set_enc_index = (i); \
    if (encoding_set_enc_index < ENCODING_INLINE_MAX) \
        ENCODING_SET_INLINED(rb_encoding_set_obj, encoding_set_enc_index); \
    else \
        rb_enc_set_index(rb_encoding_set_obj, encoding_set_enc_index); \
} while (0)
#define ENCODING_SET (obj, i)
Value:
do {\
    VALUE rb_encoding_set_obj = (obj); \
    int encoding_set_enc_index = (i); \
    if (encoding_set_enc_index < ENCODING_INLINE_MAX) \
        ENCODING_SET_INLINED(rb_encoding_set_obj, encoding_set_enc_index); \
    else \
        rb_enc_set_index(rb_encoding_set_obj, encoding_set_enc_index); \
} while (0)
Definition at line 37 of file parse.y.
#define ENCODING_SET_INLINED (obj, i)
Value:
do {\
    RBASIC(obj)->flags &= ~ENCODING_MASK;\
    RBASIC(obj)->flags |= (VALUE)(i) << ENCODING_SHIFT;\
} while (0)
#define ENCODING_SET_INLINED (obj, i)
Value:
do {\
    RBASIC(obj)->flags &= ~ENCODING_MASK;\
    RBASIC(obj)->flags |= (VALUE)(i) << ENCODING_SHIFT;\
} while (0)
Referenced by enc_set_index().
#define ENCODING_SET_INLINED (obj, i)
Value:
do {\
    RBASIC(obj)->flags &= ~ENCODING_MASK;\
    RBASIC(obj)->flags |= (VALUE)(i) << ENCODING_SHIFT;\
} while (0)
Definition at line 33 of file parse.y.
#define ENCODING_SHIFT (FL_USHIFT+10)
#define ENCODING_SHIFT (FL_USHIFT+10)
#define ENCODING_SHIFT (FL_USHIFT+10)
Definition at line 30 of file parse.y.
#define MBCLEN_CHARFOUND_LEN (ret) ONIGENC_MBCLEN_CHARFOUND_LEN(ret)
#define MBCLEN_CHARFOUND_LEN (ret) ONIGENC_MBCLEN_CHARFOUND_LEN(ret)
Referenced by coderange_scan(), enc_pred_char(), enc_succ_char(), gzreader_charboundary(), io_getc(), make_econv_exception(), rb_enc_codepoint_len(), rb_enc_mbclen(), rb_enc_strlen_cr(), rb_io_each_codepoint(), rb_reg_expr_str(), rb_str_coderange_scan_restartable(), rb_str_dump(), rb_str_inspect(), and unescape_nonascii().
#define MBCLEN_CHARFOUND_LEN (ret) ONIGENC_MBCLEN_CHARFOUND_LEN(ret)
Definition at line 139 of file parse.y.
#define MBCLEN_CHARFOUND_P (ret) ONIGENC_MBCLEN_CHARFOUND_P(ret)
#define MBCLEN_CHARFOUND_P (ret) ONIGENC_MBCLEN_CHARFOUND_P(ret)
Definition at line 138 of file parse.y.
#define MBCLEN_CHARFOUND_P (ret) ONIGENC_MBCLEN_CHARFOUND_P(ret)
Referenced by coderange_scan(), enc_pred_char(), enc_succ_char(), fnmatch_helper(), gzreader_charboundary(), io_getc(), make_econv_exception(), parser_tokadd_mbchar(), rb_enc_ascget(), rb_enc_codepoint_len(), rb_enc_mbclen(), rb_enc_strlen_cr(), rb_io_each_codepoint(), rb_reg_expr_str(), rb_str_coderange_scan_restartable(), rb_str_dump(), rb_str_inspect(), and unescape_nonascii().
#define MBCLEN_INVALID_P (ret) ONIGENC_MBCLEN_INVALID_P(ret)
Definition at line 140 of file parse.y.
#define MBCLEN_INVALID_P (ret) ONIGENC_MBCLEN_INVALID_P(ret)
#define MBCLEN_INVALID_P (ret) ONIGENC_MBCLEN_INVALID_P(ret)
Referenced by enc_pred_char(), enc_succ_char(), io_getc(), rb_io_each_codepoint(), rb_str_coderange_scan_restartable(), and unescape_escaped_nonascii().
#define MBCLEN_NEEDMORE_LEN (ret) ONIGENC_MBCLEN_NEEDMORE_LEN(ret)
#define MBCLEN_NEEDMORE_LEN (ret) ONIGENC_MBCLEN_NEEDMORE_LEN(ret)
Definition at line 142 of file parse.y.
#define MBCLEN_NEEDMORE_LEN (ret) ONIGENC_MBCLEN_NEEDMORE_LEN(ret)
Referenced by gzreader_charboundary().
#define MBCLEN_NEEDMORE_P (ret) ONIGENC_MBCLEN_NEEDMORE_P(ret)
Referenced by gzreader_charboundary(), io_getc(), rb_io_each_codepoint(), rb_io_getline_1(), and unescape_escaped_nonascii().
#define MBCLEN_NEEDMORE_P (ret) ONIGENC_MBCLEN_NEEDMORE_P(ret)
#define MBCLEN_NEEDMORE_P (ret) ONIGENC_MBCLEN_NEEDMORE_P(ret)
Definition at line 141 of file parse.y.
#define rb_enc_asciicompat (enc) (rb_enc_mbminlen(enc)==1 && !rb_enc_dummy_p(enc))
Referenced by check_path_encoding(), coderange_scan(), do_writeconv(), enc_ascii_compatible_p(), enc_strlen(), fnmatch_brace(), intern_str(), io_encoding_set(), io_getc(), must_be_ascii_compatible(), must_not_be_anonymous(), parser_set_encode(), parser_str_new(), prepare_getline_args(), rb_enc_ascget(), rb_enc_associate_index(), rb_enc_compatible(), rb_enc_cr_str_buf_cat(), rb_enc_cr_str_copy_for_substr(), rb_enc_str_asciionly_p(), rb_enc_strlen_cr(), rb_inspect(), rb_io_getline_1(), rb_mod_const_get(), rb_must_asciicompat(), rb_path_to_class(), rb_reg_desc(), rb_reg_expr_str(), rb_reg_prepare_enc(), rb_reg_preprocess(), rb_reg_regsub(), rb_reg_s_union(), rb_str_buf_cat_ascii(), rb_str_clear(), rb_str_coderange_scan_restartable(), rb_str_comparable(), rb_str_count(), rb_str_delete_bang(), rb_str_downcase_bang(), rb_str_dump(), rb_str_ellipsize(), rb_str_inspect(), rb_str_split_m(), rb_str_squeeze_bang(), rb_str_succ(), rb_str_upcase_bang(), rb_to_encoding_index(), RUBY_ALIAS_FUNCTION(), str_byte_substr(), str_encode_associate(), str_find_encindex(), str_gsub(), str_nth_len(), str_transcode0(), sym_check_asciionly(), syserr_initialize(), and validate_enc_binmode().
#define rb_enc_asciicompat (enc) (rb_enc_mbminlen(enc)==1 && !rb_enc_dummy_p(enc))
#define rb_enc_asciicompat (enc) (rb_enc_mbminlen(enc)==1 && !rb_enc_dummy_p(enc))
Definition at line 184 of file parse.y.
#define rb_enc_codepoint (p, e, enc) rb_enc_codepoint_len((p),(e),0,(enc))
Definition at line 154 of file parse.y.
#define rb_enc_codepoint (p, e, enc) rb_enc_codepoint_len((p),(e),0,(enc))
#define rb_enc_codepoint (p, e, enc) rb_enc_codepoint_len((p),(e),0,(enc))
Referenced by bracket(), fnmatch_helper(), rb_enc_codepoint(), rb_io_each_codepoint(), rb_str_enumerate_lines(), rb_str_inspect(), rb_str_ord(), and rb_str_rstrip_bang().
#define rb_enc_is_newline (p, end, enc) ONIGENC_IS_MBC_NEWLINE((enc),(UChar*)(p),(UChar*)(end))
Definition at line 171 of file parse.y.
#define rb_enc_is_newline (p, end, enc) ONIGENC_IS_MBC_NEWLINE((enc),(UChar*)(p),(UChar*)(end))
Referenced by rb_str_chomp_bang(), and rb_str_enumerate_lines().
#define rb_enc_is_newline (p, end, enc) ONIGENC_IS_MBC_NEWLINE((enc),(UChar*)(p),(UChar*)(end))
#define rb_enc_isalnum (c, enc) ONIGENC_IS_CODE_ALNUM((enc),(c))
Referenced by parser_yylex().
#define rb_enc_isalnum (c, enc) ONIGENC_IS_CODE_ALNUM((enc),(c))
#define rb_enc_isalnum (c, enc) ONIGENC_IS_CODE_ALNUM((enc),(c))
Definition at line 179 of file parse.y.
#define rb_enc_isalpha (c, enc) ONIGENC_IS_CODE_ALPHA((enc),(c))
Referenced by rb_enc_symname_type().
#define rb_enc_isalpha (c, enc) ONIGENC_IS_CODE_ALPHA((enc),(c))
Definition at line 175 of file parse.y.
#define rb_enc_isalpha (c, enc) ONIGENC_IS_CODE_ALPHA((enc),(c))
#define rb_enc_isascii (c, enc) ONIGENC_IS_CODE_ASCII(c)
Referenced by intern_str(), rb_enc_ascget(), rb_str_downcase_bang(), rb_str_inspect(), and rb_str_upcase_bang().
#define rb_enc_isascii (c, enc) ONIGENC_IS_CODE_ASCII(c)
#define rb_enc_isascii (c, enc) ONIGENC_IS_CODE_ASCII(c)
Definition at line 174 of file parse.y.
#define rb_enc_isctype (c, t, enc) ONIGENC_IS_CODE_CTYPE((enc),(c),(t))
#define rb_enc_isctype (c, t, enc) ONIGENC_IS_CODE_CTYPE((enc),(c),(t))
Definition at line 173 of file parse.y.
#define rb_enc_isctype (c, t, enc) ONIGENC_IS_CODE_CTYPE((enc),(c),(t))
Referenced by enc_succ_alnum_char().
#define rb_enc_isdigit (c, enc) ONIGENC_IS_CODE_DIGIT((enc),(c))
Referenced by intern_str(), and is_special_global_name().
#define rb_enc_isdigit (c, enc) ONIGENC_IS_CODE_DIGIT((enc),(c))
#define rb_enc_isdigit (c, enc) ONIGENC_IS_CODE_DIGIT((enc),(c))
Definition at line 182 of file parse.y.
#define rb_enc_islower (c, enc) ONIGENC_IS_CODE_LOWER((enc),(c))
#define rb_enc_islower (c, enc) ONIGENC_IS_CODE_LOWER((enc),(c))
Definition at line 176 of file parse.y.
#define rb_enc_islower (c, enc) ONIGENC_IS_CODE_LOWER((enc),(c))
Referenced by rb_str_capitalize_bang(), rb_str_swapcase_bang(), rb_str_upcase_bang(), and reg_named_capture_assign_iter().
#define rb_enc_isprint (c, enc) ONIGENC_IS_CODE_PRINT((enc),(c))
Referenced by rb_reg_expr_str(), rb_str_format(), rb_str_inspect(), and sym_printable().
#define rb_enc_isprint (c, enc) ONIGENC_IS_CODE_PRINT((enc),(c))
#define rb_enc_isprint (c, enc) ONIGENC_IS_CODE_PRINT((enc),(c))
Definition at line 180 of file parse.y.
#define rb_enc_ispunct (c, enc) ONIGENC_IS_CODE_PUNCT((enc),(c))
#define rb_enc_ispunct (c, enc) ONIGENC_IS_CODE_PUNCT((enc),(c))
Referenced by intern_str().
#define rb_enc_ispunct (c, enc) ONIGENC_IS_CODE_PUNCT((enc),(c))
Definition at line 178 of file parse.y.
#define rb_enc_isspace (c, enc) ONIGENC_IS_CODE_SPACE((enc),(c))
Definition at line 181 of file parse.y.
#define rb_enc_isspace (c, enc) ONIGENC_IS_CODE_SPACE((enc),(c))
Referenced by parser_yylex(), and rb_reg_expr_str().
#define rb_enc_isspace (c, enc) ONIGENC_IS_CODE_SPACE((enc),(c))
#define rb_enc_isupper (c, enc) ONIGENC_IS_CODE_UPPER((enc),(c))
#define rb_enc_isupper (c, enc) ONIGENC_IS_CODE_UPPER((enc),(c))
Definition at line 177 of file parse.y.
#define rb_enc_isupper (c, enc) ONIGENC_IS_CODE_UPPER((enc),(c))
Referenced by intern_str(), rb_enc_symname_type(), rb_str_capitalize_bang(), rb_str_downcase_bang(), and rb_str_swapcase_bang().
#define rb_enc_left_char_head (s, p, e, enc) ((char *)onigenc_get_left_adjust_char_head((enc),(UChar*)(s),(UChar*)(p),(UChar*)(e)))
Referenced by gzreader_charboundary(), rb_io_getline_1(), rb_str_chomp_bang(), rb_str_end_with(), rb_str_enumerate_lines(), realpath_rec(), and rmext().
#define rb_enc_left_char_head (s, p, e, enc) ((char *)onigenc_get_left_adjust_char_head((enc),(UChar*)(s),(UChar*)(p),(UChar*)(e)))
#define rb_enc_left_char_head (s, p, e, enc) ((char *)onigenc_get_left_adjust_char_head((enc),(UChar*)(s),(UChar*)(p),(UChar*)(e)))
Definition at line 166 of file parse.y.
#define rb_enc_mbc_to_codepoint (p, e, enc) ONIGENC_MBC_TO_CODE((enc),(UChar*)(p),(UChar*)(e))
#define rb_enc_mbc_to_codepoint (p, e, enc) ONIGENC_MBC_TO_CODE((enc),(UChar*)(p),(UChar*)(e))
Definition at line 155 of file parse.y.
#define rb_enc_mbc_to_codepoint (p, e, enc) ONIGENC_MBC_TO_CODE((enc),(UChar*)(p),(UChar*)(e))
Referenced by enc_succ_alnum_char(), make_econv_exception(), rb_enc_ascget(), rb_enc_codepoint_len(), rb_reg_expr_str(), rb_str_dump(), and rb_str_inspect().
#define rb_enc_mbcput (c, buf, enc) ONIGENC_CODE_TO_MBC((enc),(c),(UChar*)(buf))
#define rb_enc_mbcput (c, buf, enc) ONIGENC_CODE_TO_MBC((enc),(c),(UChar*)(buf))
Referenced by parser_tokaddmbc(), rb_enc_uint_chr(), rb_reg_quote(), rb_str_buf_cat_ascii(), rb_str_capitalize_bang(), rb_str_concat(), rb_str_delete_bang(), rb_str_downcase_bang(), rb_str_format(), rb_str_squeeze_bang(), rb_str_swapcase_bang(), rb_str_upcase_bang(), strio_ungetc(), and tr_trans().
#define rb_enc_mbcput (c, buf, enc) ONIGENC_CODE_TO_MBC((enc),(c),(UChar*)(buf))
Definition at line 161 of file parse.y.
#define rb_enc_mbmaxlen (enc) (enc)->max_enc_len
Definition at line 128 of file parse.y.
#define rb_enc_mbmaxlen (enc) (enc)->max_enc_len
#define rb_enc_mbmaxlen (enc) (enc)->max_enc_len
Referenced by enc_strlen(), gzfile_getc(), gzreader_gets(), rb_enc_strlen_cr(), rb_str_buf_cat_ascii(), rb_str_subpos(), single_byte_optimizable(), str_nth_len(), tr_trans(), unescape_escaped_nonascii(), and update_char_offset().
#define rb_enc_mbminlen (enc) (enc)->min_enc_len
#define rb_enc_mbminlen (enc) (enc)->min_enc_len
Definition at line 127 of file parse.y.
#define rb_enc_mbminlen (enc) (enc)->min_enc_len
Referenced by enc_strlen(), rb_enc_mbclen(), rb_enc_strlen_cr(), rb_enc_vsprintf(), rb_str_chomp_bang(), rb_str_ellipsize(), rb_str_inspect(), rb_str_subpos(), str_end_with_asciichar(), str_nth_len(), and swallow().
#define rb_enc_name (enc) (enc)->name
Definition at line 124 of file parse.y.
#define rb_enc_name (enc) (enc)->name
Referenced by check_path_encoding(), code_page(), decorate_convpath(), do_writeconv(), econv_args(), econv_set_replacement(), enc_arg(), enc_autoload(), enc_inspect(), enc_name(), literal_concat0(), make_readconv(), make_writeconv(), ole_vstr2wc(), parser_set_encode(), prepare_getline_args(), rb_econv_open_opts(), rb_econv_prepare_options(), rb_enc_aliases_enc_i(), rb_enc_check(), rb_enc_codelen(), rb_enc_codepoint_len(), rb_enc_cr_str_buf_cat(), rb_enc_register(), rb_enc_uint_chr(), rb_enc_vsprintf(), rb_io_each_codepoint(), rb_io_extract_encoding_option(), rb_must_asciicompat(), rb_reg_prepare_enc(), rb_reg_preprocess_dregexp(), rb_reg_s_union(), rb_str_check_dummy_enc(), rb_str_concat(), rb_str_split_m(), rb_str_sub_bang(), rb_w32_write_console(), reg_enc_error(), reg_fragment_setenc_gen(), str_transcode_enc_args(), transcode_loop(), and w_encoding().
#define rb_enc_name (enc) (enc)->name
#define rb_enc_prev_char (s, p, e, enc) ((char *)onigenc_get_prev_char_head((enc),(UChar*)(s),(UChar*)(p),(UChar*)(e)))
Referenced by chopped_length(), parser_yyerror(), rb_str_rindex(), rb_str_rstrip_bang(), rb_str_subpos(), and rb_str_succ().
#define rb_enc_prev_char (s, p, e, enc) ((char *)onigenc_get_prev_char_head((enc),(UChar*)(s),(UChar*)(p),(UChar*)(e)))
Definition at line 164 of file parse.y.
#define rb_enc_prev_char (s, p, e, enc) ((char *)onigenc_get_prev_char_head((enc),(UChar*)(s),(UChar*)(p),(UChar*)(e)))
#define rb_enc_right_char_head (s, p, e, enc) ((char *)onigenc_get_right_adjust_char_head((enc),(UChar*)(s),(UChar*)(p),(UChar*)(e)))
Referenced by rb_str_format(), rb_str_index(), rb_str_split_m(), and strio_getline().
#define rb_enc_right_char_head (s, p, e, enc) ((char *)onigenc_get_right_adjust_char_head((enc),(UChar*)(s),(UChar*)(p),(UChar*)(e)))
#define rb_enc_right_char_head (s, p, e, enc) ((char *)onigenc_get_right_adjust_char_head((enc),(UChar*)(s),(UChar*)(p),(UChar*)(e)))
Definition at line 167 of file parse.y.
#define rb_enc_step_back (s, p, e, n, enc) ((char *)onigenc_step_back((enc),(UChar*)(s),(UChar*)(p),(UChar*)(e),(int)(n)))
Referenced by rb_str_ellipsize().
#define rb_enc_step_back (s, p, e, n, enc) ((char *)onigenc_step_back((enc),(UChar*)(s),(UChar*)(p),(UChar*)(e),(int)(n)))
#define rb_enc_step_back (s, p, e, n, enc) ((char *)onigenc_step_back((enc),(UChar*)(s),(UChar*)(p),(UChar*)(e),(int)(n)))
Definition at line 168 of file parse.y.
#define rb_enc_str_asciicompat_p (str) rb_enc_asciicompat(rb_enc_get(str))
Referenced by date_s__parse_internal(), date_s__strptime_internal(), date_strftime_internal(), rb_reg_prepare_enc(), rb_reg_s_union(), time_strftime(), and utc_offset_arg().
#define rb_enc_str_asciicompat_p (str) rb_enc_asciicompat(rb_enc_get(str))
Definition at line 196 of file parse.y.
#define rb_enc_str_asciicompat_p (str) rb_enc_asciicompat(rb_enc_get(str))
#define rb_enc_to_index (enc) ((enc) ? ENC_TO_ENCINDEX(enc) : 0)
Referenced by check_encoding(), coderange_scan(), enc_set_default_encoding(), enc_set_filesystem_encoding(), Init_tcltklib(), rb_enc_associate(), rb_enc_str_buf_cat(), rb_str_coderange_scan_restartable(), and rb_str_plus().
#define rb_enc_to_index (enc) ((enc) ? ENC_TO_ENCINDEX(enc) : 0)
Definition at line 86 of file parse.y.
#define rb_enc_to_index (enc) ((enc) ? ENC_TO_ENCINDEX(enc) : 0)
Typedef Documentation
typedef struct rb_econv_t rb_econv_t
Definition at line 252 of file encoding.h.
typedef OnigEncodingType rb_encoding
Definition at line 80 of file encoding.h.
Enumeration Type Documentation
enum rb_econv_result_t
Enumerator:
econv_invalid_byte_sequence
econv_undefined_conversion
econv_destination_buffer_full
econv_source_buffer_empty
econv_finished
econv_after_output
econv_incomplete_input
econv_invalid_byte_sequence
econv_undefined_conversion
econv_destination_buffer_full
econv_source_buffer_empty
econv_finished
econv_after_output
econv_incomplete_input
Definition at line 242 of file encoding.h.
Function Documentation
PRINTF_ARGS (VALUE rb_enc_sprintfrb_encoding *, const char *,..., 2 , 3)
PRINTF_ARGS (NORETURN(void rb_enc_raise(rb_encoding *, VALUE, const char *,...)) , 3 , 4)
int rb_ascii8bit_encindex (void)
Definition at line 1160 of file encoding.c.
References ENCINDEX_ASCII.
Referenced by enc_set_filesystem_encoding(), pack_unpack(), parser_regx_options(), rb_char_to_option_kcode(), rb_filesystem_encindex(), rb_locale_encindex(), and transcode_io().
rb_encoding* rb_ascii8bit_encoding (void)
Definition at line 1151 of file encoding.c.
References enc_table, ENCINDEX_ASCII, and rb_enc_init().
Referenced by code_page(), do_opendir(), do_writeconv(), file_path_convert(), int_chr(), load_file_internal(), make_writeconv(), parser_str_new(), rb_define_dummy_encoding(), rb_encdb_dummy(), rb_external_str_new_with_enc(), rb_file_open_internal(), rb_glob(), rb_gzreader_ungetc(), rb_gzwriter_write(), rb_io_ascii8bit_binmode(), rb_io_ext_int_to_encs(), rb_io_extract_modeenc(), rb_reg_initialize(), rb_reg_initialize_m(), rb_reg_initialize_str(), rb_reg_new(), rb_reg_prepare_enc(), rb_reg_preprocess_dregexp(), rb_reg_s_union(), rb_str_concat(), rb_str_dump(), rb_str_encode_ospath(), rb_strftime_with_timespec(), rb_symname_p(), rb_w32_conv_from_wchar(), rb_w32_readdir(), reg_fragment_setenc_gen(), RUBY_ALIAS_FUNCTION(), ruby_brace_glob(), ruby_glob(), strio_read(), strio_ungetc(), and strio_write().
int rb_char_to_option_kcode (int c, int * option, int * kcode)
Definition at line 301 of file re.c.
References ARG_ENCODING_FIXED, ARG_ENCODING_NONE, char_to_option(), rb_ascii8bit_encindex(), rb_enc_find_index(), and rb_utf8_encindex().
ID rb_check_id_cstr (const char * ptr, long len, rb_encoding * enc)
Definition at line 16209 of file ripper.c.
References RString::as, RString::basic, RBasic::flags, global_symbols, RString::heap, id, RBasic::klass, RString::len, rb_cString, rb_enc_associate(), rb_id_attrset(), rb_is_attrset_name(), RSTRING_NOEMBED, st_lookup(), sym_check_asciionly(), symbols::sym_id, and T_STRING.
Referenced by rb_mod_const_get(), rb_path_to_class(), and rb_str_format().
rb_encoding* rb_default_external_encoding (void)
Definition at line 1286 of file encoding.c.
References default_encoding::enc, default_encoding::index, rb_enc_from_index(), and rb_locale_encoding().
Referenced by argf_external_encoding(), argf_internal_encoding(), enc_set_filesystem_encoding(), gzfile_new(), io_read_encoding(), ole_init_cp(), rb_enc_default_external(), rb_enc_reg_error_desc(), rb_external_str_new(), rb_external_str_new_cstr(), rb_inspect(), rb_io_ext_int_to_encs(), rb_reg_desc(), rb_str_export(), rb_str_inspect(), rb_str_quote_unprintable(), rb_str_symname_p(), require_libraries(), strio_init(), strio_set_encoding(), and validate_enc_binmode().
rb_encoding* rb_default_internal_encoding (void)
Definition at line 1371 of file encoding.c.
References default_encoding::enc, default_encoding::index, and rb_enc_from_index().
Referenced by file_path_convert(), int_chr(), ole_init_cp(), parse(), process_options(), rb_enc_default_internal(), rb_enc_reg_error_desc(), rb_external_str_new_with_enc(), rb_io_ext_int_to_encs(), rb_reg_desc(), rb_str_inspect(), rb_str_quote_unprintable(), and rb_str_symname_p().
int rb_define_dummy_encoding (const char *)
Definition at line 400 of file encoding.c.
References rb_encoding_entry::enc, ENC_SET_DUMMY, enc_table, rb_ascii8bit_encoding(), and rb_enc_replicate().
Referenced by create_dummy_encoding_for_tk_core(), make_dummy_encoding(), ole_cp2encoding(), rb_nkf_enc_get(), and str_transcode0().
const char* rb_econv_asciicompat_encoding (const char * encname)
Definition at line 1786 of file transcode.c.
References asciicompat_encoding_t::ascii_compat_name, asciicompat_encoding_t::ascii_incompat_name, asciicompat_encoding_i(), NULL, st_table::num_entries, st_foreach(), st_lookup(), and v.
void rb_econv_binmode (rb_econv_t * ec)
Definition at line 1934 of file transcode.c.
References ECONV_CR_NEWLINE_DECORATOR, ECONV_CRLF_NEWLINE_DECORATOR, ECONV_NEWLINE_DECORATOR_MASK, ECONV_UNIVERSAL_NEWLINE_DECORATOR, rb_econv_t::elems, rb_econv_t::flags, get_transcoder_entry(), i, rb_econv_t::num_trans, rb_econv_elem_t::out_buf_start, rb_transcoding_close(), rb_econv_elem_t::tc, rb_transcoding::transcoder, transcoder_entry_t::transcoder, and xfree.
void rb_econv_check_error (rb_econv_t * ec)
Definition at line 4194 of file transcode.c.
References make_econv_exception(), NIL_P, and rb_exc_raise().
void rb_econv_close (rb_econv_t * ec)
Definition at line 1702 of file transcode.c.
References rb_econv_t::elems, i, rb_econv_t::in_buf_start, rb_econv_t::num_trans, rb_econv_elem_t::out_buf_start, rb_transcoding_close(), rb_econv_t::replacement_allocated, rb_econv_t::replacement_str, rb_econv_elem_t::tc, and xfree.
rb_econv_result_t rb_econv_convert (rb_econv_t * ec, const unsigned char ** source_buffer_ptr, const unsigned char * source_buffer_end, unsigned char ** destination_buffer_ptr, unsigned char * destination_buffer_end, int flags)
Definition at line 1446 of file transcode.c.
References econv_incomplete_input, econv_invalid_byte_sequence, ECONV_INVALID_MASK, ECONV_INVALID_REPLACE, ECONV_UNDEF_HEX_CHARREF, ECONV_UNDEF_MASK, ECONV_UNDEF_REPLACE, econv_undefined_conversion, rb_econv_t::flags, output_hex_charref(), output_replacement_character(), rb_econv_convert0(), and rb_econv_t::started.
int rb_econv_decorate_at_first (rb_econv_t * ec, const char * decorator_name)
Definition at line 1900 of file transcode.c.
References asciicompat_decoder, rb_transcoder::asciicompat_type, DECORATOR_P, rb_transcoder::dst_encoding, rb_econv_t::elems, rb_econv_t::num_trans, rb_econv_decorate_at(), rb_transcoder::src_encoding, rb_econv_elem_t::tc, and rb_transcoding::transcoder.
int rb_econv_decorate_at_last (rb_econv_t * ec, const char * decorator_name)
Definition at line 1917 of file transcode.c.
References asciicompat_encoder, rb_transcoder::asciicompat_type, DECORATOR_P, rb_transcoder::dst_encoding, rb_econv_t::elems, rb_econv_t::num_trans, rb_econv_decorate_at(), rb_transcoder::src_encoding, rb_econv_elem_t::tc, and rb_transcoding::transcoder.
const char* rb_econv_encoding_to_insert_output (rb_econv_t * ec)
Definition at line 1503 of file transcode.c.
References asciicompat_encoder, rb_transcoder::asciicompat_type, rb_transcoder::dst_encoding, rb_econv_t::last_tc, NULL, rb_transcoder::src_encoding, and rb_transcoding::transcoder.
int rb_econv_has_convpath_p (const char * from_encoding, const char * to_encoding)
Definition at line 3150 of file transcode.c.
References Qnil, RTEST, search_convpath_i(), and transcode_search_path().
int rb_econv_insert_output (rb_econv_t * ec, const unsigned char * str, size_t len, const char * str_encoding)
Definition at line 1587 of file transcode.c.
References allocate_converted_string(), asciicompat_encoder, rb_transcoder::asciicompat_type, buf, rb_econv_t::elems, encoding_equal, fail, rb_econv_t::in_buf_end, rb_econv_t::in_buf_start, rb_econv_t::in_data_end, rb_econv_t::in_data_start, MEMMOVE, NULL, rb_econv_t::num_trans, rb_econv_elem_t::out_buf_end, rb_econv_elem_t::out_buf_start, rb_econv_elem_t::out_data_end, rb_econv_elem_t::out_data_start, rb_econv_encoding_to_insert_output(), rb_transcoding::readagain_len, rb_transcoding::recognized_len, rb_econv_t::started, rb_econv_elem_t::tc, rb_transcoding::transcoder, TRANSCODING_READBUF, xfree, xmalloc, and xrealloc.
VALUE rb_econv_make_exception (rb_econv_t * ec)
Definition at line 4188 of file transcode.c.
References make_econv_exception().
rb_econv_t* rb_econv_open (const char * source_encoding, const char * destination_encoding, int ecflags)
Definition at line 1067 of file transcode.c.
References decorator_names(), ECONV_ERROR_HANDLER_MASK, rb_econv_t::flags, i, MAX_ECFLAGS_DECORATORS, NULL, rb_econv_close(), rb_econv_decorate_at_last(), and rb_econv_open0().
VALUE rb_econv_open_exc (const char * senc, const char * denc, int ecflags)
Definition at line 2028 of file transcode.c.
References econv_description(), rb_eConverterNotFoundError, rb_exc_new3(), rb_str_cat2(), and rb_str_new_cstr().
rb_econv_t* rb_econv_open_opts (const char * source_encoding, const char * destination_encoding, int ecflags, VALUE ecopts)
Definition at line 2570 of file transcode.c.
References NIL_P, NULL, OBJ_FROZEN, Qnil, rb_bug(), rb_econv_close(), rb_econv_open(), rb_econv_set_replacement(), rb_enc_get(), rb_enc_name, rb_hash_aref(), RB_TYPE_P, RSTRING_LEN, RSTRING_PTR, sym_replace, and T_HASH.
int rb_econv_prepare_options (VALUE opthash, VALUE * ecopts, int ecflags)
Definition at line 2519 of file transcode.c.
References econv_opts(), ENC_CODERANGE_BROKEN, NIL_P, Qnil, rb_check_hash_type(), rb_eArgError, rb_enc_get(), rb_enc_name, rb_enc_str_coderange(), rb_hash_aref(), rb_hash_aset(), rb_hash_freeze(), rb_hash_new(), rb_obj_is_method(), rb_obj_is_proc(), rb_raise(), rb_respond_to(), rb_str_dump(), rb_str_new_frozen(), StringValue, StringValueCStr, sym_aref, sym_fallback, sym_replace, and v.
int rb_econv_prepare_opts (VALUE opthash, VALUE * ecopts)
Definition at line 2564 of file transcode.c.
References rb_econv_prepare_options().
void rb_econv_putback (rb_econv_t * ec, unsigned char * p, int n)
Definition at line 1753 of file transcode.c.
References rb_econv_t::elems, rb_econv_t::num_trans, rb_transcoding::readagain_len, rb_transcoding::recognized_len, rb_econv_elem_t::tc, and TRANSCODING_READBUF.
int rb_econv_putbackable (rb_econv_t * ec)
Definition at line 1742 of file transcode.c.
References rb_econv_t::elems, rb_econv_t::num_trans, rb_transcoding::readagain_len, and rb_econv_elem_t::tc.
int rb_econv_set_replacement (rb_econv_t * ec, const unsigned char * str, size_t len, const char * encname)
Definition at line 2190 of file transcode.c.
References allocate_converted_string(), encoding_equal, MEMCPY, NULL, rb_econv_encoding_to_insert_output(), rb_econv_t::replacement_allocated, rb_econv_t::replacement_enc, rb_econv_t::replacement_len, rb_econv_t::replacement_str, xfree, and xmalloc.
VALUE rb_econv_str_append (rb_econv_t * ec, VALUE src, VALUE dst, int flags)
Definition at line 1857 of file transcode.c.
References rb_econv_substr_append(), and RSTRING_LEN.
VALUE rb_econv_str_convert (rb_econv_t * ec, VALUE src, int flags)
Definition at line 1869 of file transcode.c.
References Qnil, rb_econv_substr_append(), and RSTRING_LEN.
VALUE rb_econv_substr_append (rb_econv_t * ec, VALUE src, long byteoff, long bytesize, VALUE dst, int flags)
Definition at line 1813 of file transcode.c.
References rb_econv_t::destination_encoding, dp, econv_destination_buffer_full, rb_econv_t::last_tc, LONG_MAX, rb_transcoder::max_output, NIL_P, rb_eArgError, rb_econv_check_error(), rb_econv_convert(), rb_enc_associate(), rb_raise(), rb_str_buf_new(), rb_str_capacity(), rb_str_resize(), rb_str_set_len(), RSTRING_LEN, RSTRING_PTR, and rb_transcoding::transcoder.
VALUE rb_econv_substr_convert (rb_econv_t * ec, VALUE src, long byteoff, long bytesize, int flags)
Definition at line 1863 of file transcode.c.
References Qnil, and rb_econv_substr_append().
int rb_enc_ascget (const char * p, const char * e, int * len, rb_encoding * enc)
Definition at line 908 of file encoding.c.
References c, ISASCII, MBCLEN_CHARFOUND_P, rb_enc_asciicompat, rb_enc_isascii, rb_enc_mbc_to_codepoint, and rb_enc_precise_mbclen().
Referenced by check_pipe_command(), chopped_length(), rb_reg_expr_str(), rb_reg_quote(), rb_str_casecmp(), rb_str_chomp_bang(), rb_str_split_m(), rmext(), str_end_with_asciichar(), swallow(), tr_setup_table(), tr_trans(), and trnext().
VALUE rb_enc_associate (VALUE , rb_encoding *)
Definition at line 764 of file encoding.c.
References rb_enc_associate_index(), and rb_enc_to_index.
Referenced by append_fspath(), econv_primitive_convert(), econv_putback(), gzfile_getc(), gzfile_newstr(), intern_str(), io_enc_str(), io_shift_cbuf(), lex_getline(), load_file_internal(), locale_path(), parser_nextc(), parser_str_new(), process_options(), rb_ary_join(), rb_check_id_cstr(), rb_dir_getwd(), rb_econv_substr_append(), rb_enc_reg_error_desc(), rb_enc_str_new(), rb_enc_vsprintf(), rb_external_str_new_with_enc(), rb_file_expand_path_internal(), rb_file_join(), rb_home_dir(), rb_intern3(), rb_nkf_convert(), rb_reg_desc(), rb_reg_initialize(), rb_reg_preprocess(), rb_reg_preprocess_dregexp(), rb_reg_quote(), rb_reg_s_union(), rb_str_append(), rb_str_concat(), rb_str_dump(), rb_str_ellipsize(), rb_str_encode_ospath(), rb_str_force_encoding(), rb_str_format(), rb_str_inspect(), rb_str_justify(), rb_str_shared_replace(), rb_str_splice(), rb_str_sub_bang(), rb_str_subpat_set(), reg_fragment_setenc_gen(), require_libraries(), ruby__sfvextra(), RUBY_ALIAS_FUNCTION(), str_gsub(), strio_read(), strio_set_encoding(), syserr_initialize(), and tr_trans().
VALUE rb_enc_associate_index (VALUE , int)
Definition at line 746 of file encoding.c.
References ENC_CODERANGE_ASCIIONLY, ENC_CODERANGE_CLEAR, enc_set_index(), rb_check_frozen, rb_eArgError, rb_enc_asciicompat, rb_enc_from_index(), rb_enc_get_index(), rb_raise(), and SPECIAL_CONST_P.
Referenced by encoded_dup(), lib_fromUTF8_core(), lib_split_tklist_core(), lib_toUTF8_core(), lib_UTF_backslash_core(), make_econv_exception(), parser_set_encode(), r_ivar(), r_symreal(), rb_enc_associate(), rb_enc_copy(), rb_find_file_ext_safe(), rb_find_file_safe(), str_encode_associate(), and str_encode_bang().
int rb_enc_casefold (char * to, const char * p, const char * e, rb_encoding * enc)
rb_encoding* rb_enc_check (VALUE , VALUE)
Definition at line 776 of file encoding.c.
References rb_encoding_entry::enc, rb_eEncCompatError, rb_enc_compatible(), rb_enc_get(), rb_enc_name, and rb_raise().
Referenced by append_fspath(), rb_file_expand_path_internal(), rb_file_join(), rb_str_append(), rb_str_chomp_bang(), rb_str_count(), rb_str_delete_bang(), rb_str_end_with(), rb_str_enumerate_lines(), rb_str_format(), rb_str_index(), rb_str_index_m(), rb_str_justify(), rb_str_plus(), rb_str_rindex(), rb_str_splice(), rb_str_split_m(), rb_str_squeeze_bang(), rb_str_start_with(), rb_str_subpat_set(), rb_str_upto(), readline_attempted_completion_function(), realpath_rec(), and tr_trans().
int rb_enc_codelen (int code, rb_encoding * enc)
Definition at line 952 of file encoding.c.
References ONIGENC_CODE_TO_MBCLEN, rb_eArgError, rb_enc_name, and rb_raise().
Referenced by parser_tokaddmbc(), rb_enc_uint_chr(), rb_str_buf_cat_ascii(), rb_str_concat(), rb_str_format(), strio_ungetc(), and tr_trans().
unsigned int rb_enc_codepoint (const char * p, const char * e, rb_encoding * enc)
Definition at line 946 of file encoding.c.
References rb_enc_codepoint, and rb_enc_codepoint_len().
unsigned int rb_enc_codepoint_len (const char * p, const char * e, int * len, rb_encoding * enc)
Definition at line 931 of file encoding.c.
References MBCLEN_CHARFOUND_LEN, MBCLEN_CHARFOUND_P, rb_eArgError, rb_enc_mbc_to_codepoint, rb_enc_name, rb_enc_precise_mbclen(), and rb_raise().
Referenced by rb_enc_codepoint(), rb_str_capitalize_bang(), rb_str_count(), rb_str_delete_bang(), rb_str_downcase_bang(), rb_str_enumerate_codepoints(), rb_str_enumerate_lines(), rb_str_format(), rb_str_lstrip_bang(), rb_str_split_m(), rb_str_squeeze_bang(), rb_str_swapcase_bang(), rb_str_upcase_bang(), readline_attempted_completion_function(), rmext(), strio_each_codepoint(), sym_printable(), tr_trans(), and trnext().
rb_encoding* rb_enc_compatible (VALUE , VALUE)
Definition at line 787 of file encoding.c.
References ENC_CODERANGE_7BIT, ENCINDEX_US_ASCII, rb_enc_asciicompat, rb_enc_from_index(), rb_enc_get_index(), rb_enc_str_asciionly_p(), rb_enc_str_coderange(), RB_TYPE_P, RSTRING_LEN, and T_STRING.
Referenced by enc_compatible_p(), file_s_fnmatch(), literal_concat0(), location_format(), rb_enc_check(), rb_file_s_basename(), rb_str_casecmp(), rb_str_sub_bang(), and ruby__sfvextra().
void rb_enc_copy (VALUE dst, VALUE src)
Definition at line 854 of file encoding.c.
References rb_enc_associate_index(), and rb_enc_get_index().
Referenced by ary_join_0(), ary_join_1(), date_s__parse_internal(), date_s__strptime_internal(), date_strftime_internal(), inspect_ary(), inspect_i(), rb_attr(), rb_check_id(), rb_file_dirname(), rb_file_expand_path_internal(), rb_file_join(), rb_file_s_basename(), rb_reg_desc(), rb_reg_quote(), rb_reg_s_union(), rb_reg_to_s(), rb_str_format(), RUBY_ALIAS_FUNCTION(), str_new(), and strio_read().
VALUE rb_enc_default_external (void)
Definition at line 1300 of file encoding.c.
References rb_default_external_encoding(), and rb_enc_from_encoding().
Referenced by encoding_table_get_name_core(), and get_default_external().
VALUE rb_enc_default_internal (void)
Definition at line 1380 of file encoding.c.
References rb_default_internal_encoding(), and rb_enc_from_encoding().
Referenced by encoding_table_get_name_core(), get_default_internal(), and str_transcode0().
static int rb_enc_dummy_p (rb_encoding * enc) inline static
Definition at line 235 of file encoding.h.
References ENC_DUMMY_P.
int rb_enc_fast_mbclen (const char * p, const char * e, rb_encoding * enc)
Definition at line 878 of file encoding.c.
References ONIGENC_MBC_ENC_LEN, and UChar.
Referenced by enc_strlen(), rb_str_enumerate_chars(), rb_str_reverse(), rb_str_split_m(), scan_once(), and str_gsub().
rb_encoding* rb_enc_find (const char * name)
Definition at line 657 of file encoding.c.
References rb_enc_find_index(), and rb_enc_from_index().
Referenced by econv_get_replacement(), econv_insert_output(), make_encoding(), make_replacement(), rb_str_inspect(), rb_w32_conv_from_wchar(), rb_w32_write_console(), and transcode_loop().
int rb_enc_find_index (const char * name)
Definition at line 633 of file encoding.c.
References rb_encoding_entry::enc, enc_autoload(), enc_autoload_p, i, load_encoding(), rb_eArgError, rb_enc_from_index(), rb_enc_registered(), rb_raise(), rb_warn(), and UNSPECIFIED_ENCODING.
Referenced by create_dummy_encoding_for_tk_core(), create_encoding_table_core(), enc_set_filesystem_encoding(), encoding_table_get_name_core(), id2encidx(), Init_tcltklib(), io_strip_bom(), lib_fromUTF8_core(), make_econv_exception(), ole_cp2encoding(), opt_enc_index(), parse_mode_enc(), parser_set_encode(), process_options(), rb_char_to_option_kcode(), rb_econv_open0(), rb_enc_alias(), rb_enc_find(), rb_locale_encindex(), rb_nkf_enc_get(), rb_to_encoding_index(), str_find_encindex(), transcode_io(), transcode_string(), and update_encoding_table().
VALUE rb_enc_from_encoding (rb_encoding * enc)
Definition at line 103 of file encoding.c.
References ENC_TO_ENCINDEX, Qnil, and rb_enc_from_encoding_index().
Referenced by argf_external_encoding(), argf_internal_encoding(), code_page(), create_dummy_encoding_for_tk_core(), create_encoding_table_core(), do_writeconv(), econv_destination_encoding(), econv_insert_output(), econv_s_asciicompat_encoding(), econv_source_encoding(), enc_compatible_p(), encoding_table_get_name_core(), fix_string_encoding(), get_user_from_path(), gettable_gen(), Init_nkf(), io_set_encoding_by_bom(), load_file_internal(), make_econv_exception(), make_encobj(), process_options(), rb_enc_default_external(), rb_enc_default_internal(), rb_file_expand_path_internal(), rb_io_external_encoding(), rb_io_getline_1(), rb_io_internal_encoding(), rb_nkf_guess(), rb_parser_encoding(), rb_str_ellipsize(), rb_str_encode_ospath(), rb_w32_conv_from_wchar(), rb_w32_write_console(), readline_attempted_completion_function(), set_encoding_const(), strio_external_encoding(), and update_encoding_table().
rb_encoding* rb_enc_from_index (int idx)
Definition at line 548 of file encoding.c.
References enc_table, and rb_enc_init().
Referenced by check_encoding(), create_dummy_encoding_for_tk_core(), create_encoding_table_core(), econv_args(), enc_alias(), enc_arg(), enc_replicate_with_index(), encoding_table_get_name_core(), file_path_convert(), io_set_encoding_by_bom(), load_file_internal(), make_dummy_encoding(), make_econv_exception(), ole_cp2encoding(), opt_enc_index(), parse_mode_enc(), parser_set_encode(), process_options(), rb_default_external_encoding(), rb_default_internal_encoding(), rb_econv_open0(), rb_enc_aliases_enc_i(), rb_enc_associate_index(), rb_enc_compatible(), rb_enc_cr_str_buf_cat(), rb_enc_find(), rb_enc_find_index(), rb_enc_get(), rb_enc_register(), rb_enc_replicate(), rb_enc_set_base(), rb_encdb_declare(), rb_encdb_replicate(), rb_encdb_set_unicode(), rb_filesystem_encoding(), rb_find_encoding(), rb_io_extract_encoding_option(), rb_locale_encoding(), rb_nkf_enc_get(), rb_str_buf_cat_ascii(), rb_str_comparable(), str_encode_associate(), str_end_with_asciichar(), str_to_encoding(), str_transcode_enc_args(), update_encoding_table(), and w_encoding().
rb_encoding* rb_enc_get (VALUE)
Definition at line 770 of file encoding.c.
References rb_enc_from_index(), and rb_enc_get_index().
Referenced by check_dirname(), check_path_encoding(), check_pipe_command(), do_writeconv(), econv_set_replacement(), file_s_fnmatch(), fnmatch_brace(), intern_str(), io_encoding_set(), literal_concat0(), must_be_ascii_compatible(), must_not_be_anonymous(), ole_vstr2wc(), parser_prepare(), parser_yyerror(), path_check_0(), path_sub_ext(), prepare_getline_args(), push_glob(), rb_econv_open_opts(), rb_econv_prepare_options(), rb_enc_check(), rb_file_dirname(), rb_file_expand_path_internal(), rb_file_join(), rb_file_s_basename(), rb_file_s_extname(), rb_gzreader_ungetc(), rb_gzwriter_write(), rb_inspect(), rb_mod_const_get(), rb_must_asciicompat(), rb_path_to_class(), rb_push_glob(), rb_realpath_internal(), rb_reg_check_preprocess(), rb_reg_desc(), rb_reg_error_desc(), rb_reg_init_copy(), rb_reg_initialize_m(), rb_reg_initialize_str(), rb_reg_prepare_enc(), rb_reg_preprocess_dregexp(), rb_reg_quote(), rb_reg_regsub(), rb_reg_s_union(), rb_reg_source(), rb_reg_to_s(), rb_str_chomp_bang(), rb_str_dump(), rb_str_each_char_size(), rb_str_ellipsize(), rb_str_encode_ospath(), rb_str_enumerate_chars(), rb_str_enumerate_lines(), rb_str_format(), rb_str_symname_type(), rb_to_encoding_index(), rb_w32_write_console(), realpath_rec(), reg_enc_error(), reg_fragment_setenc_gen(), reg_named_capture_assign_gen(), ruby__sfvextra(), RUBY_ALIAS_FUNCTION(), str_find_encindex(), strio_each_codepoint(), strio_external_encoding(), strio_getc(), strio_getline(), strio_substr(), strio_ungetc(), strio_write(), strscan_getch(), sym_check_asciionly(), syserr_initialize(), time_strftime(), transcode_loop(), and update_char_offset().
int rb_enc_get_index (VALUE obj)
Definition at line 688 of file encoding.c.
References BUILTIN_TYPE, enc_check_encoding(), ENCODING_GET_INLINED, ENCODING_INLINE_MAX, i, is_data_encoding, NIL_P, NUM2INT, rb_funcall(), rb_id2str(), rb_id_encoding(), rb_intern, rb_ivar_get(), SPECIAL_CONST_P, SYM2ID, SYMBOL_P, T_DATA, T_FILE, T_REGEXP, and T_STRING.
Referenced by lib_fromUTF8_core(), lib_split_tklist_core(), rb_enc_associate_index(), rb_enc_compatible(), rb_enc_copy(), rb_enc_get(), rb_obj_encoding(), str_transcode_enc_args(), transcode_string(), w_encoding(), and w_symbol().
int rb_enc_mbclen (const char * p, const char * e, rb_encoding * enc)
Definition at line 884 of file encoding.c.
References MBCLEN_CHARFOUND_LEN, MBCLEN_CHARFOUND_P, ONIGENC_PRECISE_MBC_ENC_LEN, rb_enc_mbminlen, and UChar.
Referenced by bracket(), enc_strlen(), gzfile_getc(), intern_str(), io_getc(), is_special_global_name(), rb_enc_symname_type(), rb_str_casecmp(), rb_str_each_char_size(), rb_str_enumerate_chars(), rb_str_enumerate_lines(), rb_str_format(), rb_str_reverse(), str_nth_len(), strio_getc(), strio_ungetc(), and strscan_getch().
char* rb_enc_nth (const char * , const char * , long , rb_encoding *)
Definition at line 1582 of file string.c.
References str_nth_len().
char* rb_enc_path_end (const char * , const char * , rb_encoding *)
Definition at line 2840 of file file.c.
References chompdirsep(), and isdirsep.
char* rb_enc_path_last_separator (const char * , const char * , rb_encoding *)
Definition at line 2806 of file file.c.
References Inc, isdirsep, last, and NULL.
char* rb_enc_path_next (const char * , const char * , rb_encoding *)
Definition at line 2758 of file file.c.
References Inc, and isdirsep.
char* rb_enc_path_skip_prefix (const char * , const char * , rb_encoding *)
Definition at line 2772 of file file.c.
References isdirsep, and rb_enc_path_next().
int rb_enc_precise_mbclen (const char * p, const char * e, rb_encoding * enc)
Definition at line 896 of file encoding.c.
References ONIGENC_CONSTRUCT_MBCLEN_NEEDMORE, ONIGENC_PRECISE_MBC_ENC_LEN, and UChar.
Referenced by coderange_scan(), enc_pred_char(), enc_succ_char(), fnmatch_helper(), gzreader_charboundary(), io_getc(), make_econv_exception(), rb_enc_ascget(), rb_enc_codepoint_len(), rb_enc_strlen_cr(), rb_enc_uint_chr(), rb_io_each_codepoint(), rb_io_getline_1(), rb_reg_expr_str(), rb_str_coderange_scan_restartable(), rb_str_concat(), rb_str_dump(), rb_str_inspect(), rb_str_succ(), unescape_escaped_nonascii(), and unescape_nonascii().
VALUE rb_enc_reg_new (const char * , long , rb_encoding * , int)
Definition at line 2511 of file re.c.
References err, NULL, rb_enc_reg_raise(), rb_reg_alloc(), and rb_reg_initialize().
int rb_enc_replicate (const char * , rb_encoding *)
Definition at line 343 of file encoding.c.
References enc_check_duplication(), enc_register(), rb_enc_from_index(), set_base_encoding(), and set_encoding_const().
Referenced by enc_replicate(), and rb_define_dummy_encoding().
void rb_enc_set_default_external (VALUE encoding)
Definition at line 1338 of file encoding.c.
References enc_set_default_encoding(), NIL_P, rb_eArgError, and rb_raise().
Referenced by process_options(), and set_default_external().
void rb_enc_set_default_internal (VALUE encoding)
Definition at line 1424 of file encoding.c.
References enc_set_default_encoding().
Referenced by process_options(), and set_default_internal().
void rb_enc_set_index (VALUE obj, int encindex)
Definition at line 739 of file encoding.c.
References enc_set_index(), and rb_check_frozen.
Referenced by pack_pack(), and str_enc_copy().
int rb_enc_str_asciionly_p (VALUE)
Definition at line 340 of file string.c.
References ENC_CODERANGE_7BIT, FALSE, rb_enc_asciicompat, rb_enc_str_coderange(), STR_ENC_GET, and TRUE.
VALUE rb_enc_str_buf_cat (VALUE str, const char * ptr, long len, rb_encoding * enc)
Definition at line 2067 of file string.c.
References ENC_CODERANGE_UNKNOWN, NULL, rb_enc_cr_str_buf_cat(), and rb_enc_to_index.
int rb_enc_str_coderange (VALUE)
Definition at line 327 of file string.c.
References coderange_scan(), ENC_CODERANGE, ENC_CODERANGE_SET, ENC_CODERANGE_UNKNOWN, RSTRING_LEN, RSTRING_PTR, and STR_ENC_GET.
VALUE rb_enc_str_new (const char * , long , rb_encoding *)
Definition at line 439 of file string.c.
References rb_enc_associate(), and rb_str_new().
long rb_enc_strlen (const char * , const char * , rb_encoding *)
Definition at line 1025 of file string.c.
References ENC_CODERANGE_UNKNOWN, and enc_strlen().
int rb_enc_symname2_p (const char * , long , rb_encoding *)
Definition at line 15804 of file ripper.c.
References rb_enc_symname_type().
Referenced by rb_enc_symname_p(), rb_mod_const_get(), and reg_named_capture_assign_iter().
int rb_enc_symname_p (const char * , rb_encoding *)
Definition at line 15703 of file ripper.c.
References rb_enc_symname2_p(), and strlen().
Referenced by rb_str_symname_p(), and rb_symname_p().
int rb_enc_tolower (int c, rb_encoding * enc)
Definition at line 968 of file encoding.c.
References ONIGENC_ASCII_CODE_TO_LOWER_CASE, and ONIGENC_IS_ASCII_CODE.
Referenced by rb_str_capitalize_bang(), rb_str_downcase_bang(), and rb_str_swapcase_bang().
int rb_enc_toupper (int c, rb_encoding * enc)
Definition at line 962 of file encoding.c.
References ONIGENC_ASCII_CODE_TO_UPPER_CASE, and ONIGENC_IS_ASCII_CODE.
Referenced by bracket(), fnmatch_helper(), rb_str_capitalize_bang(), rb_str_format(), rb_str_swapcase_bang(), and rb_str_upcase_bang().
VALUE rb_enc_uint_chr (unsigned int code, rb_encoding * enc)
Definition at line 2417 of file numeric.c.
References ONIGERR_INVALID_CODE_POINT_VALUE, ONIGERR_TOO_BIG_WIDE_CHAR_VALUE, rb_enc_codelen(), rb_enc_mbcput, rb_enc_name, rb_enc_precise_mbclen(), rb_enc_str_new(), rb_eRangeError, rb_raise(), RSTRING_END, and RSTRING_PTR.
int rb_enc_unicode_p (rb_encoding * enc)
Definition at line 459 of file encoding.c.
References ONIGENC_IS_UNICODE.
Referenced by rb_reg_expr_str(), and rb_str_inspect().
VALUE rb_enc_vsprintf (rb_encoding * , const char * , va_list)
Definition at line 1218 of file sprintf.c.
References __SSTR, __SWR, BSD_vfprintf(), f, rb_cString, rb_eArgError, rb_enc_associate(), rb_enc_mbminlen, rb_enc_name, rb_raise(), rb_str_buf_new(), rb_str_resize(), RBASIC, result, RSTRING_PTR, ruby__sfvextra(), ruby__sfvwrite(), and rb_printf_buffer_extra::value.
VALUE rb_external_str_new_with_enc (const char * ptr, long len, rb_encoding *)
Definition at line 569 of file string.c.
References ENC_CODERANGE_7BIT, rb_ascii8bit_encoding(), rb_default_internal_encoding(), rb_enc_associate(), rb_enc_str_coderange(), rb_str_conv_enc(), rb_tainted_str_new(), and rb_usascii_encoding().
int rb_filesystem_encindex (void)
Definition at line 1237 of file encoding.c.
References rb_ascii8bit_encindex(), and rb_enc_registered().
Referenced by rb_filesystem_encoding().
rb_encoding* rb_filesystem_encoding (void)
Definition at line 1246 of file encoding.c.
References rb_enc_from_index(), and rb_filesystem_encindex().
Referenced by coverage(), debug_lines(), dir_initialize(), env_fetch(), etc_systmpdir(), file_path_convert(), gettable_gen(), push_glob(), rb_dir_getwd(), rb_f_getenv(), rb_file_expand_path_internal(), rb_filesystem_str_new(), rb_filesystem_str_new_cstr(), rb_home_dir(), rb_str_encode_ospath(), and rb_w32_special_folder().
rb_encoding* rb_find_encoding (VALUE)
Definition at line 201 of file encoding.c.
References enc_check_encoding(), NULL, rb_enc_from_index(), RDATA, and str_find_encindex().
Referenced by find_encoding().
ID rb_intern3 (const char * , long , rb_encoding *)
Definition at line 15856 of file ripper.c.
References RString::as, RString::basic, RBasic::flags, global_symbols, RString::heap, intern_str(), RBasic::klass, RString::len, OBJ_FREEZE, rb_cString, rb_enc_associate(), rb_enc_str_new(), RSTRING_NOEMBED, st_lookup(), symbols::sym_id, and T_STRING.
Referenced by intern_str(), rb_intern2(), rb_mod_const_get(), and reg_named_capture_assign_iter().
ID rb_interned_id_p (const char * , long , rb_encoding *)
VALUE rb_locale_charmap (VALUE klass)
Definition at line 1477 of file encoding.c.
References nl_langinfo_codeset(), Qnil, rb_usascii_str_new2, and snprintf.
Referenced by encoding_table_get_name_core(), Init_Encoding(), and rb_locale_encindex().
int rb_locale_encindex (void)
Definition at line 1196 of file encoding.c.
References enc_alias_internal(), NIL_P, rb_ascii8bit_encindex(), rb_cEncoding, rb_enc_find_index(), rb_enc_registered(), rb_locale_charmap(), rb_usascii_encindex(), and StringValueCStr.
Referenced by rb_locale_encoding().
rb_encoding* rb_locale_encoding (void)
Definition at line 1212 of file encoding.c.
References rb_enc_from_index(), and rb_locale_encindex().
Referenced by env_str_new(), load_file_internal(), locale_path(), process_options(), rb_default_external_encoding(), rb_loaderror(), rb_loaderror_with_path(), rb_locale_str_new(), rb_locale_str_new_cstr(), rb_str_export_locale(), rb_strftime_with_timespec(), readline_attempted_completion_function(), and syserr_initialize().
long rb_memsearch (const void * , long , const void * , long , rb_encoding *)
Definition at line 227 of file re.c.
References memcmp(), rb_memsearch_qs(), rb_memsearch_qs_utf8(), rb_memsearch_ss(), rb_utf8_encoding(), and SIZEOF_VALUE.
VALUE rb_obj_encoding (VALUE)
Definition at line 868 of file encoding.c.
References rb_enc_from_encoding_index(), rb_enc_get_index(), rb_eTypeError, and rb_raise().
Referenced by Init_Regexp(), Init_String(), lib_toUTF8_core(), str_transcode0(), and sym_encoding().
long rb_str_coderange_scan_restartable (const char * , const char * , rb_encoding * , int *)
Definition at line 232 of file string.c.
References ENC_CODERANGE_7BIT, ENC_CODERANGE_BROKEN, ENC_CODERANGE_UNKNOWN, ENC_CODERANGE_VALID, MBCLEN_CHARFOUND_LEN, MBCLEN_CHARFOUND_P, MBCLEN_INVALID_P, p, rb_enc_asciicompat, rb_enc_precise_mbclen(), rb_enc_to_index, and search_nonascii().
VALUE rb_str_conv_enc (VALUE str, rb_encoding * from, rb_encoding * to)
Definition at line 563 of file string.c.
References Qnil, and rb_str_conv_enc_opts().
VALUE rb_str_conv_enc_opts (VALUE str, rb_encoding * from, rb_encoding * to, int ecflags, VALUE ecopts)
VALUE rb_str_encode (VALUE str, VALUE to, int ecflags, VALUE ecopts)
Definition at line 2867 of file transcode.c.
References argc, argv, encoded_dup(), and str_transcode0().
VALUE rb_str_export_to_enc (VALUE , rb_encoding *)
Definition at line 632 of file string.c.
References rb_str_conv_enc(), and STR_ENC_GET.
rb_encoding* rb_to_encoding (VALUE)
Definition at line 194 of file encoding.c.
References enc_check_encoding(), RDATA, and str_to_encoding().
Referenced by decorate_convpath(), dir_initialize(), enc_replicate(), enc_set_default_encoding(), int_chr(), rb_io_extract_encoding_option(), rb_str_force_encoding(), and strio_set_encoding().
int rb_to_encoding_index (VALUE)
Definition at line 146 of file encoding.c.
References enc_check_encoding(), NIL_P, rb_check_string_type(), rb_enc_asciicompat, rb_enc_find_index(), rb_enc_get(), and StringValueCStr.
Referenced by econv_args(), enc_arg(), enc_names(), lib_fromUTF8_core(), rb_io_extract_encoding_option(), and transcode_io().
int rb_usascii_encindex (void)
Definition at line 1190 of file encoding.c.
References ENCINDEX_US_ASCII.
Referenced by code_page(), enc_inspect(), id2encidx(), pack_pack(), rb_find_file_ext_safe(), rb_find_file_safe(), rb_locale_encindex(), rb_usascii_str_new(), RUBY_ALIAS_FUNCTION(), transcode_io(), w_encoding(), and w_symbol().
rb_encoding* rb_usascii_encoding (void)
Definition at line 1181 of file encoding.c.
References enc_table, ENCINDEX_US_ASCII, and rb_enc_init().
Referenced by code_page(), do_opendir(), file_path_convert(), Init_id(), intern_str(), mk_inspect(), of2str(), parser_str_new(), push_glob(), rb_ary_join(), rb_external_str_new_with_enc(), rb_intern2(), rb_nkf_convert(), rb_reg_desc(), rb_reg_initialize(), rb_reg_quote(), rb_str_concat(), rb_str_inspect(), rb_str_upto(), rb_strftime_with_timespec(), reg_fragment_setenc_gen(), setup_exception(), time_asctime(), and time_to_s().
int rb_utf8_encindex (void)
Definition at line 1175 of file encoding.c.
References ENCINDEX_UTF_8.
Referenced by id2encidx(), io_strip_bom(), pack_pack(), parse(), rb_char_to_option_kcode(), transcode_io(), transcode_string(), and w_encoding().
rb_encoding* rb_utf8_encoding (void)
Definition at line 1166 of file encoding.c.
References enc_table, ENCINDEX_UTF_8, and rb_enc_init().
Referenced by alias(), append_utf8(), do_opendir(), env_fetch(), env_str_new(), fix_string_encoding(), get_user_from_path(), Init_nkf(), Init_tcltklib(), load_file_internal(), make_econv_exception(), parser_initialize(), parser_prepare(), parser_str_new(), parser_tokadd_utf8(), rb_f_getenv(), rb_file_expand_path_internal(), rb_memsearch(), rb_str_dump(), rb_str_encode_ospath(), rb_str_subpos(), scalar(), start_document(), start_mapping(), start_sequence(), str_strlen(), and transcode_string().
const char* ruby_enc_find_basename (const char * name, long * baselen, long * alllen, rb_encoding * enc)
Definition at line 3654 of file file.c.
References chompdirsep(), Inc, isdirsep, name, p, skipprefix, strlen(), and strrdirsep.
const char* ruby_enc_find_extname (const char * name, long * len, rb_encoding * enc)
Definition at line 3847 of file file.c.
References Inc, isdirsep, istrailinggarbage, last, name, p, strlen(), and strrdirsep.
Variable Documentation
RUBY_EXTERN VALUE rb_cEncoding
Definition at line 225 of file encoding.h.