Ruby: missing/strchr.c File Reference
strchr.c File Reference
#include "ruby/missing.h"
Functions
size_t strlen (const char *)
char * strchr (const char *s, int c)
char * strrchr (const char *s, int c)
Function Documentation
char* strchr (const char * s, int c)
Definition at line 8 of file strchr.c.
References strlen().
size_t strlen (const char *)
Referenced by append_fspath(), argf_memsize(), argf_next_argv(), BigDecimal_dump(), BigDecimal_inspect(), BigDecimal_split(), BigDecimal_to_s(), BSD_vfprintf(), code_page(), compat_init_setproctitle(), CONF_get1_default_config_file(), coverage(), date__strptime_internal(), date_s__strptime_internal(), date_strftime_alloc(), date_strftime_internal(), date_strftime_with_tmx(), date_zone_to_diff(), debug_lines(), dlcfunc_memsize(), dlhandle_sym(), dln_find_1(), dln_load(), do_opendir(), do_spawn(), env_fetch(), env_has_value(), env_key(), env_rassoc(), env_str_new2(), envix(), fiddle_handle_sym(), fmt_setup(), fnmatch(), fnmatch_brace(), fnmatch_helper(), fole_missing(), fole_s_show_help(), foletypelib_name(), foletypelib_path(), get_backup_filename(), getnameinfo(), gettable_gen(), GetVpValueWithPrec(), glob_helper(), global_id(), host_str(), Init_readline(), insert(), io_encname_bom_p(), ip_make_menu_embeddable_core(), ip_rb_threadTkWaitCommand(), ip_rb_threadUpdateCommand(), ip_rbTkWaitCommand(), ip_rbUpdateCommand(), ip_ruby_cmd_receiver_get(), is_batch(), is_command_com(), join_path(), load_transcoder_entry(), loaded_feature_path_i(), main(), match_aref(), match_at(), match_backref_number(), Messaging_HandleMessage(), moreswitches(), ole_excepinfo2msg(), ole_hresult2msg(), ole_wc2vstr(), onigenc_property_list_add_property(), ossl_bn_to_s(), ossl_make_error(), ossl_spki_to_pem(), output_hex_charref(), parse_comp(), parse_mode_enc(), parser_memsize(), PEM_def_callback(), port_str(), proc_exec_cmd(), proc_options(), pruby_cstr_to_var(), pruby_var_prefixed_p(), push_pattern(), rb_async_bug_errno(), rb_cstr_to_inum(), rb_digest_instance_inspect(), rb_enc_symname_p(), rb_exc_new2(), rb_exec_fillarg(), rb_execarg_fixup(), rb_external_str_new_cstr(), rb_f_getenv(), rb_feature_p(), rb_file_expand_path_internal(), rb_filesystem_str_new_cstr(), rb_home_dir(), rb_intern(), rb_io_inspect(), rb_locale_str_new_cstr(), rb_path_check(), rb_push_glob(), rb_str_buf_cat2(), rb_str_buf_cat_ascii(), rb_str_buf_cat_escaped_char(), rb_str_buf_new_cstr(), rb_str_cat2(), rb_str_dump(), rb_str_format(), rb_str_inspect(), rb_str_new_cstr(), rb_str_symname_p(), rb_strftime_alloc(), rb_strftime_with_timespec(), rb_sys_warning(), rb_w32_aspawn_flags(), rb_w32_getenv(), rb_w32_pipe(), rb_w32_spawn(), rb_w32_strerror(), rb_w32_ugetenv(), rb_write_error(), read_comp(), read_digits(), readline_attempted_completion_function(), realpath_rec(), remove_sign_bits(), rsock_getaddrinfo(), ruby_brace_expand(), ruby_enc_find_basename(), ruby_enc_find_extname(), ruby_glob0(), ruby_init_loadpath_safe(), ruby_script(), ruby_setenv(), ruby_strdup(), sdbm_open(), set_encoding_const(), set_option_encoding_once(), setproctitle(), strchr(), strhash(), strlcat(), strrchr(), strstr(), stub_sysinit(), tcltklib_compile_info(), time_strftime(), tk_uninstall_cmd(), token_info_get_column(), token_info_has_nonspaces(), VpAlloc(), VpFormatSt(), VpSzMantissa(), VpToFString(), VpToString(), yaml_alias_event_initialize(), yaml_document_add_mapping(), yaml_document_add_scalar(), yaml_document_add_sequence(), yaml_document_initialize(), yaml_document_start_event_initialize(), yaml_emitter_analyze_anchor(), yaml_emitter_analyze_tag(), yaml_emitter_analyze_tag_directive(), yaml_emitter_emit_document_start(), yaml_emitter_write_indicator(), yaml_mapping_start_event_initialize(), yaml_parser_parse_node(), yaml_parser_scan_tag(), yaml_parser_scan_tag_uri(), yaml_scalar_event_initialize(), and yaml_sequence_start_event_initialize().
char* strrchr (const char * s, int c)
Definition at line 20 of file strchr.c.
References strlen().