Ruby: ext/psych/psych_emitter.c File Reference
psych_emitter.c File Reference
#include <psych.h>
Functions
static void emit (yaml_emitter_t *emitter, yaml_event_t *event)
static int writer (void *ctx, unsigned char *buffer, size_t size)
static void dealloc (void *ptr)
static VALUE allocate (VALUE klass)
static VALUE initialize (int argc, VALUE *argv, VALUE self)
static VALUE start_stream (VALUE self, VALUE encoding)
static VALUE end_stream (VALUE self)
static VALUE start_document (VALUE self, VALUE version, VALUE tags, VALUE imp)
static VALUE end_document (VALUE self, VALUE imp)
static VALUE scalar (VALUE self, VALUE value, VALUE anchor, VALUE tag, VALUE plain, VALUE quoted, VALUE style)
static VALUE start_sequence (VALUE self, VALUE anchor, VALUE tag, VALUE implicit, VALUE style)
static VALUE end_sequence (VALUE self)
static VALUE start_mapping (VALUE self, VALUE anchor, VALUE tag, VALUE implicit, VALUE style)
static VALUE end_mapping (VALUE self)
static VALUE alias (VALUE self, VALUE anchor)
static VALUE set_canonical (VALUE self, VALUE style)
static VALUE canonical (VALUE self)
static VALUE set_indentation (VALUE self, VALUE level)
static VALUE indentation (VALUE self)
static VALUE line_width (VALUE self)
static VALUE set_line_width (VALUE self, VALUE width)
void Init_psych_emitter ()
Variables
VALUE cPsychEmitter
static ID id_write
static ID id_line_width
static ID id_indentation
static ID id_canonical
Function Documentation
static VALUE alias (VALUE self, VALUE anchor) static
Definition at line 405 of file psych_emitter.c.
References Check_Type, Data_Get_Struct, emit(), NIL_P, NULL, rb_str_export_to_enc(), rb_utf8_encoding(), StringValuePtr, T_STRING, and yaml_alias_event_initialize().
static VALUE allocate (VALUE klass) static
Definition at line 32 of file psych_emitter.c.
References Data_Wrap_Struct, dealloc(), xmalloc, yaml_emitter_initialize(), yaml_emitter_set_indent(), and yaml_emitter_set_unicode().
Referenced by Init_psych_emitter().
static VALUE canonical (VALUE self) static
Definition at line 446 of file psych_emitter.c.
References yaml_emitter_s::canonical, Data_Get_Struct, Qfalse, and Qtrue.
Referenced by Init_psych_emitter(), and initialize().
static void dealloc (void * ptr) static
Definition at line 23 of file psych_emitter.c.
References xfree, and yaml_emitter_delete().
Referenced by allocate().
static void emit (yaml_emitter_t * emitter, yaml_event_t * event) static
Definition at line 9 of file psych_emitter.c.
References yaml_emitter_s::problem, rb_eRuntimeError, rb_raise(), and yaml_emitter_emit().
Referenced by alias(), end_document(), end_mapping(), end_sequence(), end_stream(), scalar(), start_document(), start_mapping(), start_sequence(), and start_stream().
static VALUE end_document (VALUE self, VALUE imp) static
Definition at line 197 of file psych_emitter.c.
References Data_Get_Struct, emit(), and yaml_document_end_event_initialize().
Referenced by Init_psych_emitter().
static VALUE end_mapping (VALUE self) static
Definition at line 386 of file psych_emitter.c.
References Data_Get_Struct, emit(), and yaml_mapping_end_event_initialize().
Referenced by Init_psych_emitter().
static VALUE end_sequence (VALUE self) static
Definition at line 319 of file psych_emitter.c.
References Data_Get_Struct, emit(), and yaml_sequence_end_event_initialize().
Referenced by Init_psych_emitter().
static VALUE end_stream (VALUE self) static
Definition at line 100 of file psych_emitter.c.
References Data_Get_Struct, emit(), and yaml_stream_end_event_initialize().
Referenced by Init_psych_emitter().
static VALUE indentation (VALUE self) static
Definition at line 473 of file psych_emitter.c.
References yaml_emitter_s::best_indent, Data_Get_Struct, and INT2NUM.
Referenced by Init_psych_emitter().
void Init_psych_emitter ()
Definition at line 507 of file psych_emitter.c.
References alias, allocate(), canonical(), cPsychEmitter, end_document(), end_mapping(), end_sequence(), end_stream(), id_canonical, id_indentation, id_line_width, id_write, indentation(), initialize(), line_width(), rb_cObject, rb_define_alloc_func(), rb_define_class_under(), rb_define_method(), rb_define_module(), rb_intern, scalar(), set_canonical(), set_indentation(), set_line_width(), start_document(), start_mapping(), start_sequence(), and start_stream().
Referenced by Init_psych().
static VALUE initialize (int argc, VALUE * argv, VALUE self) static
Definition at line 49 of file psych_emitter.c.
References canonical(), Data_Get_Struct, id_canonical, id_indentation, id_line_width, line_width(), NUM2INT, options(), Qtrue, rb_funcall(), rb_scan_args(), writer(), yaml_emitter_set_canonical(), yaml_emitter_set_indent(), yaml_emitter_set_output(), and yaml_emitter_set_width().
Referenced by Init_psych_emitter().
static VALUE line_width (VALUE self) static
Definition at line 485 of file psych_emitter.c.
References yaml_emitter_s::best_width, Data_Get_Struct, and INT2NUM.
Referenced by Init_psych_emitter(), and initialize().
static VALUE scalar (VALUE self, VALUE value, VALUE anchor, VALUE tag, VALUE plain, VALUE quoted, VALUE style) static
Definition at line 217 of file psych_emitter.c.
References Check_Type, Data_Get_Struct, emit(), NIL_P, NULL, NUM2INT, rb_str_export_to_enc(), rb_utf8_encoding(), RSTRING_LEN, StringValuePtr, T_STRING, and yaml_scalar_event_initialize().
Referenced by Init_psych_emitter().
static VALUE set_canonical (VALUE self, VALUE style) static
Definition at line 432 of file psych_emitter.c.
References Data_Get_Struct, Qtrue, and yaml_emitter_set_canonical().
Referenced by Init_psych_emitter().
static VALUE set_indentation (VALUE self, VALUE level) static
Definition at line 459 of file psych_emitter.c.
References Data_Get_Struct, NUM2INT, and yaml_emitter_set_indent().
Referenced by Init_psych_emitter().
static VALUE set_line_width (VALUE self, VALUE width) static
Definition at line 497 of file psych_emitter.c.
References Data_Get_Struct, NUM2INT, and yaml_emitter_set_width().
Referenced by Init_psych_emitter().
static VALUE start_document (VALUE self, VALUE version, VALUE tags, VALUE imp) static
Definition at line 120 of file psych_emitter.c.
References Check_Type, Data_Get_Struct, emit(), yaml_tag_directive_s::handle, head, i, yaml_version_directive_s::major, major, yaml_version_directive_s::minor, minor, name, NULL, NUM2INT, yaml_tag_directive_s::prefix, RARRAY_LEN, RARRAY_PTR, rb_ary_entry(), rb_eRuntimeError, rb_raise(), rb_str_export_to_enc(), rb_utf8_encoding(), RTEST, StringValuePtr, T_ARRAY, tail, xcalloc, xfree, and yaml_document_start_event_initialize().
Referenced by Init_psych_emitter().
static VALUE start_mapping (VALUE self, VALUE anchor, VALUE tag, VALUE implicit, VALUE style) static
Definition at line 339 of file psych_emitter.c.
References Check_Type, Data_Get_Struct, emit(), NIL_P, NULL, NUM2INT, rb_str_export_to_enc(), rb_utf8_encoding(), StringValuePtr, T_STRING, and yaml_mapping_start_event_initialize().
Referenced by Init_psych_emitter().
static VALUE start_sequence (VALUE self, VALUE anchor, VALUE tag, VALUE implicit, VALUE style) static
Definition at line 274 of file psych_emitter.c.
References Check_Type, Data_Get_Struct, emit(), NIL_P, NULL, NUM2INT, rb_str_export_to_enc(), rb_utf8_encoding(), StringValuePtr, T_STRING, and yaml_sequence_start_event_initialize().
Referenced by Init_psych_emitter().
static VALUE start_stream (VALUE self, VALUE encoding) static
Definition at line 80 of file psych_emitter.c.
References Check_Type, Data_Get_Struct, emit(), NUM2INT, T_FIXNUM, and yaml_stream_start_event_initialize().
Referenced by Init_psych_emitter().
static int writer (void * ctx, unsigned char * buffer, size_t size) static
Definition at line 15 of file psych_emitter.c.
References id_write, NUM2INT, rb_funcall(), and rb_str_new().
Referenced by initialize().
Variable Documentation
VALUE cPsychEmitter
Definition at line 3 of file psych_emitter.c.
Referenced by Init_psych_emitter().
ID id_canonical static
Definition at line 7 of file psych_emitter.c.
Referenced by Init_psych_emitter(), and initialize().
ID id_indentation static
Definition at line 6 of file psych_emitter.c.
Referenced by Init_psych_emitter(), and initialize().
ID id_line_width static
Definition at line 5 of file psych_emitter.c.
Referenced by Init_psych_emitter(), and initialize().
ID id_write static
Definition at line 4 of file psych_emitter.c.
Referenced by Init_psych_emitter(), and writer().