Ruby: ext/win32ole/win32ole.c File Reference
win32ole.c File Reference
#include "ruby/ruby.h"
#include "ruby/st.h"
#include "ruby/encoding.h"
#include <ctype.h>
#include <windows.h>
#include <ocidl.h>
#include <olectl.h>
#include <ole2.h>
#include <stdlib.h>
#include <math.h>
#include <varargs.h>
#include <objidl.h>
Data Structures
struct IEventSink
struct IEventSinkVtbl
struct tagIEVENTSINKOBJ
struct oledata
struct oletypelibdata
struct oletypedata
struct olemethoddata
struct olevariabledata
struct oleparamdata
struct oleeventdata
struct oleparam
struct olevariantdata
struct _Win32OLEIDispatch
struct myCPINFOEX
Macros
#define GNUC_OLDER_3_4_4
#define va_init_list(a, b) va_start(a)
#define DOUT fprintf(stderr,"[%d]\n",__LINE__)
#define DOUTS(x) fprintf(stderr,"[%d]:" #x "=%s\n",__LINE__,x)
#define DOUTMSG(x) fprintf(stderr, "[%d]:" #x "\n",__LINE__)
#define DOUTI(x) fprintf(stderr, "[%ld]:" #x "=%d\n",__LINE__,x)
#define DOUTD(x) fprintf(stderr, "[%d]:" #x "=%f\n",__LINE__,x)
#define V_UNION1(X, Y) ((X)->Y)
#define V_I1REF(X) V_UNION(X, pcVal)
#define V_UI2REF(X) V_UNION(X, puiVal)
#define V_INT(X) V_UNION(X, intVal)
#define V_INTREF(X) V_UNION(X, pintVal)
#define V_UINT(X) V_UNION(X, uintVal)
#define V_UINTREF(X) V_UNION(X, puintVal)
#define OLE_RELEASE(X) (X) ? ((X)->lpVtbl->Release(X)) : 0
#define OLE_ADDREF(X) (X) ? ((X)->lpVtbl->AddRef(X)) : 0
#define OLE_GET_TYPEATTR(X, Y) ((X)->lpVtbl->GetTypeAttr((X), (Y)))
#define OLE_RELEASE_TYPEATTR(X, Y) ((X)->lpVtbl->ReleaseTypeAttr((X), (Y)))
#define OLE_FREE(x)
#define OLEData_Get_Struct(obj, pole)
#define I8_2_NUM INT2NUM
#define UI8_2_NUM UINT2NUM
#define NUM2I8 NUM2INT
#define NUM2UI8 NUM2UINT
#define WC2VSTR(x) ole_wc2vstr((x), TRUE)
#define WIN32OLE_VERSION "1.5.4"
#define g_ole_initialized (BOOL)TlsGetValue(g_ole_initialized_key)
#define g_ole_initialized_init() (g_ole_initialized_key = TlsAlloc())
#define g_ole_initialized_set(val) TlsSetValue(g_ole_initialized_key, (void*)(val))
#define pIMultiLanguage NULL /* dummy */
#define ENC_MACHING_CP(enc, encname, cp) if(strcasecmp(rb_enc_name((enc)),(encname)) == 0) return cp
#define load_conv_function51932() failed_load_conv51932()
#define conv_51932(cp) ((cp) == 51932 && (load_conv_function51932(), 1))
Typedefs
typedef IUnknown DWORD
typedef IUnknown COSERVERINFO
MULTI_QI *typedef HWND (WINAPI FNHTMLHELP)(HWND hwndCaller
typedef IUnknown COSERVERINFO
MULTI_QI *typedef LPCSTR pszFile
typedef IUnknown COSERVERINFO
MULTI_QI *typedef LPCSTR UINT uCommand
typedef IUnknown COSERVERINFO
MULTI_QI *typedef LPCSTR UINT
DWORD dwData
typedef BOOL(FNENUMSYSEMCODEPAGES)(CODEPAGE_ENUMPROC, DWORD)
typedef struct IEventSink * PEVENTSINK
typedef struct IEventSinkVtbl IEventSinkVtbl
typedef struct tagIEVENTSINKOBJ IEVENTSINKOBJ
typedef struct tagIEVENTSINKOBJ * PIEVENTSINKOBJ
typedef struct _Win32OLEIDispatch Win32OLEIDispatch
Functions
typedef HRESULT (STDAPICALLTYPE FNCOCREATEINSTANCEEX)(REFCLSID
static HRESULT (STDMETHODCALLTYPE QueryInterface)(IDispatch __RPC_FAR *
static ULONG (STDMETHODCALLTYPE AddRef)(IDispatch __RPC_FAR *This)
static IDispatch * val2dispatch (VALUE val)
static double rbtime2vtdate (VALUE tmobj)
static VALUE vtdate2rbtime (double date)
static rb_encoding * ole_cp2encoding (UINT cp)
static UINT ole_encoding2cp (rb_encoding *enc)
NORETURN (static void failed_load_conv51932(void))
static UINT ole_init_cp (void)
static char * ole_wc2mb (LPWSTR pw)
static VALUE ole_hresult2msg (HRESULT hr)
static void ole_freeexceptinfo (EXCEPINFO *pExInfo)
static VALUE ole_excepinfo2msg (EXCEPINFO *pExInfo)
static void ole_raise (HRESULT hr, VALUE ecs, const char *fmt,...)
static void ole_initialize (void)
static void ole_msg_loop (void)
static void ole_free (struct oledata *pole)
static void oletypelib_free (struct oletypelibdata *poletypelib)
static void oletype_free (struct oletypedata *poletype)
static void olemethod_free (struct olemethoddata *polemethod)
static void olevariable_free (struct olevariabledata *polevar)
static void oleparam_free (struct oleparamdata *pole)
static LPWSTR ole_vstr2wc (VALUE vstr)
static LPWSTR ole_mb2wc (char *pm, int len)
static VALUE ole_wc2vstr (LPWSTR pw, BOOL isfree)
static VALUE ole_ary_m_entry (VALUE val, long *pid)
static void * get_ptr_of_variant (VARIANT *pvar)
static VALUE is_all_index_under (long *pid, long *pub, long dim)
static void ole_set_safe_array (long n, SAFEARRAY *psa, long *pid, long *pub, VALUE val, long dim, VARTYPE vt)
static long dimension (VALUE val)
static long ary_len_of_dim (VALUE ary, long dim)
static HRESULT ole_val_ary2variant_ary (VALUE val, VARIANT *var, VARTYPE vt)
static void ole_val2variant (VALUE val, VARIANT *var)
static void ole_val2variant_ex (VALUE val, VARIANT *var, VARTYPE vt)
static void ole_val2ptr_variant (VALUE val, VARIANT *var)
static void ole_set_byref (VARIANT *realvar, VARIANT *var, VARTYPE vt)
static void ole_val2olevariantdata (VALUE val, VARTYPE vt, struct olevariantdata *pvar)
static void ole_val2variant2 (VALUE val, VARIANT *var)
static VALUE make_inspect (const char *class_name, VALUE detail)
static VALUE default_inspect (VALUE self, const char *class_name)
static VALUE ole_set_member (VALUE self, IDispatch *dispatch)
static VALUE fole_s_allocate (VALUE klass)
static VALUE create_win32ole_object (VALUE klass, IDispatch *pDispatch, int argc, VALUE *argv)
static VALUE ary_new_dim (VALUE myary, long *pid, long *plb, long dim)
static void ary_store_dim (VALUE myary, long *pid, long *plb, long dim, VALUE val)
static VALUE ole_variant2val (VARIANT *pvar)
static LONG reg_open_key (HKEY hkey, const char *name, HKEY *phkey)
static LONG reg_open_vkey (HKEY hkey, VALUE key, HKEY *phkey)
static VALUE reg_enum_key (HKEY hkey, DWORD i)
static VALUE reg_get_val (HKEY hkey, const char *subkey)
static VALUE reg_get_typelib_file_path (HKEY hkey)
static VALUE typelib_file_from_clsid (VALUE ole)
static VALUE typelib_file_from_typelib (VALUE ole)
static VALUE typelib_file (VALUE ole)
static void ole_const_load (ITypeLib *pTypeLib, VALUE klass, VALUE self)
static HRESULT clsid_from_remote (VALUE host, VALUE com, CLSID *pclsid)
static VALUE ole_create_dcom (int argc, VALUE *argv, VALUE self)
static VALUE ole_bind_obj (VALUE moniker, int argc, VALUE *argv, VALUE self)
static VALUE fole_s_connect (int argc, VALUE *argv, VALUE self)
static VALUE fole_s_const_load (int argc, VALUE *argv, VALUE self)
static VALUE ole_types_from_typelib (ITypeLib *pTypeLib, VALUE classes)
static ULONG reference_count (struct oledata *pole)
static VALUE fole_s_reference_count (VALUE self, VALUE obj)
static VALUE fole_s_free (VALUE self, VALUE obj)
static HWND ole_show_help (VALUE helpfile, VALUE helpcontext)
static VALUE fole_s_show_help (int argc, VALUE *argv, VALUE self)
static VALUE fole_s_get_code_page (VALUE self)
static BOOL CALLBACK installed_code_page_proc (LPTSTR str)
static BOOL code_page_installed (UINT cp)
static VALUE fole_s_set_code_page (VALUE self, VALUE vcp)
static VALUE fole_s_get_locale (VALUE self)
static BOOL CALLBACK installed_lcid_proc (LPTSTR str)
static BOOL lcid_installed (LCID lcid)
static VALUE fole_s_set_locale (VALUE self, VALUE vlcid)
static VALUE fole_s_create_guid (VALUE self)
static VALUE fole_s_ole_initialize (VALUE self)
static VALUE fole_s_ole_uninitialize (VALUE self)
static VALUE fole_initialize (int argc, VALUE *argv, VALUE self)
static VALUE hash2named_arg (VALUE pair, struct oleparam *pOp)
static VALUE set_argv (VARIANTARG *realargs, unsigned int beg, unsigned int end)
static VALUE ole_invoke (int argc, VALUE *argv, VALUE self, USHORT wFlags, BOOL is_bracket)
static VALUE fole_invoke (int argc, VALUE *argv, VALUE self)
static VALUE ole_invoke2 (VALUE self, VALUE dispid, VALUE args, VALUE types, USHORT dispkind)
static VALUE fole_invoke2 (VALUE self, VALUE dispid, VALUE args, VALUE types)
static VALUE fole_getproperty2 (VALUE self, VALUE dispid, VALUE args, VALUE types)
static VALUE fole_setproperty2 (VALUE self, VALUE dispid, VALUE args, VALUE types)
static VALUE fole_setproperty_with_bracket (int argc, VALUE *argv, VALUE self)
static VALUE fole_setproperty (int argc, VALUE *argv, VALUE self)
static VALUE fole_getproperty_with_bracket (int argc, VALUE *argv, VALUE self)
static VALUE ole_propertyput (VALUE self, VALUE property, VALUE value)
static VALUE fole_free (VALUE self)
static VALUE ole_each_sub (VALUE pEnumV)
static VALUE ole_ienum_free (VALUE pEnumV)
static VALUE fole_each (VALUE self)
static VALUE fole_missing (int argc, VALUE *argv, VALUE self)
static VALUE ole_method_sub (VALUE self, ITypeInfo *pOwnerTypeInfo, ITypeInfo *pTypeInfo, VALUE name)
static VALUE olemethod_from_typeinfo (VALUE self, ITypeInfo *pTypeInfo, VALUE name)
static VALUE ole_methods_sub (ITypeInfo *pOwnerTypeInfo, ITypeInfo *pTypeInfo, VALUE methods, int mask)
static VALUE ole_methods_from_typeinfo (ITypeInfo *pTypeInfo, int mask)
static HRESULT typeinfo_from_ole (struct oledata *pole, ITypeInfo **ppti)
static VALUE ole_methods (VALUE self, int mask)
static VALUE fole_methods (VALUE self)
static VALUE fole_get_methods (VALUE self)
static VALUE fole_put_methods (VALUE self)
static VALUE fole_func_methods (VALUE self)
static VALUE ole_type_from_itypeinfo (ITypeInfo *pTypeInfo)
static VALUE fole_type (VALUE self)
static VALUE ole_typelib_from_itypeinfo (ITypeInfo *pTypeInfo)
static VALUE fole_typelib (VALUE self)
static VALUE fole_query_interface (VALUE self, VALUE str_iid)
static VALUE fole_respond_to (VALUE self, VALUE method)
static HRESULT ole_docinfo_from_type (ITypeInfo *pTypeInfo, BSTR *name, BSTR *helpstr, DWORD *helpcontext, BSTR *helpfile)
static VALUE ole_usertype2val (ITypeInfo *pTypeInfo, TYPEDESC *pTypeDesc, VALUE typedetails)
static VALUE ole_ptrtype2val (ITypeInfo *pTypeInfo, TYPEDESC *pTypeDesc, VALUE typedetails)
static VALUE ole_typedesc2val (ITypeInfo *pTypeInfo, TYPEDESC *pTypeDesc, VALUE typedetails)
static VALUE fole_method_help (VALUE self, VALUE cmdname)
static VALUE fole_activex_initialize (VALUE self)
static VALUE foletype_s_ole_classes (VALUE self, VALUE typelib)
static VALUE foletype_s_typelibs (VALUE self)
static VALUE foletype_s_progids (VALUE self)
static VALUE foletype_s_allocate (VALUE klass)
static VALUE oletype_set_member (VALUE self, ITypeInfo *pTypeInfo, VALUE name)
static VALUE oleclass_from_typelib (VALUE self, ITypeLib *pTypeLib, VALUE oleclass)
static VALUE oletypelib_set_member (VALUE self, ITypeLib *pTypeLib)
static ITypeLib * oletypelib_get_typelib (VALUE self)
static void oletypelib_get_libattr (ITypeLib *pTypeLib, TLIBATTR **ppTLibAttr)
static VALUE foletypelib_s_typelibs (VALUE self)
static VALUE make_version_str (VALUE major, VALUE minor)
static VALUE oletypelib_search_registry2 (VALUE self, VALUE args)
static VALUE oletypelib_search_registry (VALUE self, VALUE typelib)
static VALUE foletypelib_s_allocate (VALUE klass)
static VALUE foletypelib_initialize (VALUE self, VALUE args)
static VALUE foletypelib_guid (VALUE self)
static VALUE foletypelib_name (VALUE self)
static VALUE foletypelib_version (VALUE self)
static VALUE foletypelib_major_version (VALUE self)
static VALUE foletypelib_minor_version (VALUE self)
static VALUE oletypelib_path (VALUE guid, VALUE version)
static HRESULT oletypelib_from_guid (VALUE guid, VALUE version, ITypeLib **ppTypeLib)
static VALUE foletypelib_path (VALUE self)
static VALUE foletypelib_visible (VALUE self)
static VALUE foletypelib_library_name (VALUE self)
static VALUE foletypelib_ole_types (VALUE self)
static VALUE foletypelib_inspect (VALUE self)
static VALUE foletype_initialize (VALUE self, VALUE typelib, VALUE oleclass)
static VALUE foletype_name (VALUE self)
static VALUE ole_ole_type (ITypeInfo *pTypeInfo)
static VALUE foletype_ole_type (VALUE self)
static VALUE ole_type_guid (ITypeInfo *pTypeInfo)
static VALUE foletype_guid (VALUE self)
static VALUE ole_type_progid (ITypeInfo *pTypeInfo)
static VALUE foletype_progid (VALUE self)
static VALUE ole_type_visible (ITypeInfo *pTypeInfo)
static VALUE foletype_visible (VALUE self)
static VALUE ole_type_major_version (ITypeInfo *pTypeInfo)
static VALUE foletype_major_version (VALUE self)
static VALUE ole_type_minor_version (ITypeInfo *pTypeInfo)
static VALUE foletype_minor_version (VALUE self)
static VALUE ole_type_typekind (ITypeInfo *pTypeInfo)
static VALUE foletype_typekind (VALUE self)
static VALUE ole_type_helpstring (ITypeInfo *pTypeInfo)
static VALUE foletype_helpstring (VALUE self)
static VALUE ole_type_src_type (ITypeInfo *pTypeInfo)
static VALUE foletype_src_type (VALUE self)
static VALUE ole_type_helpfile (ITypeInfo *pTypeInfo)
static VALUE foletype_helpfile (VALUE self)
static VALUE ole_type_helpcontext (ITypeInfo *pTypeInfo)
static VALUE foletype_helpcontext (VALUE self)
static VALUE foletype_ole_typelib (VALUE self)
static VALUE ole_type_impl_ole_types (ITypeInfo *pTypeInfo, int implflags)
static VALUE foletype_impl_ole_types (VALUE self)
static VALUE foletype_source_ole_types (VALUE self)
static VALUE foletype_default_event_sources (VALUE self)
static VALUE foletype_default_ole_types (VALUE self)
static VALUE foletype_inspect (VALUE self)
static VALUE ole_variables (ITypeInfo *pTypeInfo)
static VALUE foletype_variables (VALUE self)
static VALUE foletype_methods (VALUE self)
static VALUE folevariable_name (VALUE self)
static VALUE ole_variable_ole_type (ITypeInfo *pTypeInfo, UINT var_index)
static VALUE folevariable_ole_type (VALUE self)
static VALUE ole_variable_ole_type_detail (ITypeInfo *pTypeInfo, UINT var_index)
static VALUE folevariable_ole_type_detail (VALUE self)
static VALUE ole_variable_value (ITypeInfo *pTypeInfo, UINT var_index)
static VALUE folevariable_value (VALUE self)
static VALUE ole_variable_visible (ITypeInfo *pTypeInfo, UINT var_index)
static VALUE folevariable_visible (VALUE self)
static VALUE ole_variable_kind (ITypeInfo *pTypeInfo, UINT var_index)
static VALUE folevariable_variable_kind (VALUE self)
static VALUE ole_variable_varkind (ITypeInfo *pTypeInfo, UINT var_index)
static VALUE folevariable_varkind (VALUE self)
static VALUE folevariable_inspect (VALUE self)
static VALUE olemethod_set_member (VALUE self, ITypeInfo *pTypeInfo, ITypeInfo *pOwnerTypeInfo, int index, VALUE name)
static VALUE folemethod_s_allocate (VALUE klass)
static VALUE folemethod_initialize (VALUE self, VALUE oletype, VALUE method)
static VALUE folemethod_name (VALUE self)
static VALUE ole_method_return_type (ITypeInfo *pTypeInfo, UINT method_index)
static VALUE folemethod_return_type (VALUE self)
static VALUE ole_method_return_vtype (ITypeInfo *pTypeInfo, UINT method_index)
static VALUE folemethod_return_vtype (VALUE self)
static VALUE ole_method_return_type_detail (ITypeInfo *pTypeInfo, UINT method_index)
static VALUE folemethod_return_type_detail (VALUE self)
static VALUE ole_method_invkind (ITypeInfo *pTypeInfo, UINT method_index)
static VALUE ole_method_invoke_kind (ITypeInfo *pTypeInfo, UINT method_index)
static VALUE folemethod_invkind (VALUE self)
static VALUE folemethod_invoke_kind (VALUE self)
static VALUE ole_method_visible (ITypeInfo *pTypeInfo, UINT method_index)
static VALUE folemethod_visible (VALUE self)
static VALUE ole_method_event (ITypeInfo *pTypeInfo, UINT method_index, VALUE method_name)
static VALUE folemethod_event (VALUE self)
static VALUE folemethod_event_interface (VALUE self)
static VALUE ole_method_docinfo_from_type (ITypeInfo *pTypeInfo, UINT method_index, BSTR *name, BSTR *helpstr, DWORD *helpcontext, BSTR *helpfile)
static VALUE ole_method_helpstring (ITypeInfo *pTypeInfo, UINT method_index)
static VALUE folemethod_helpstring (VALUE self)
static VALUE ole_method_helpfile (ITypeInfo *pTypeInfo, UINT method_index)
static VALUE folemethod_helpfile (VALUE self)
static VALUE ole_method_helpcontext (ITypeInfo *pTypeInfo, UINT method_index)
static VALUE folemethod_helpcontext (VALUE self)
static VALUE ole_method_dispid (ITypeInfo *pTypeInfo, UINT method_index)
static VALUE folemethod_dispid (VALUE self)
static VALUE ole_method_offset_vtbl (ITypeInfo *pTypeInfo, UINT method_index)
static VALUE folemethod_offset_vtbl (VALUE self)
static VALUE ole_method_size_params (ITypeInfo *pTypeInfo, UINT method_index)
static VALUE folemethod_size_params (VALUE self)
static VALUE ole_method_size_opt_params (ITypeInfo *pTypeInfo, UINT method_index)
static VALUE folemethod_size_opt_params (VALUE self)
static VALUE ole_method_params (ITypeInfo *pTypeInfo, UINT method_index)
static VALUE folemethod_params (VALUE self)
static VALUE folemethod_inspect (VALUE self)
static VALUE foleparam_s_allocate (VALUE klass)
static VALUE oleparam_ole_param_from_index (VALUE self, ITypeInfo *pTypeInfo, UINT method_index, int param_index)
static VALUE oleparam_ole_param (VALUE self, VALUE olemethod, int n)
static VALUE foleparam_initialize (VALUE self, VALUE olemethod, VALUE n)
static VALUE foleparam_name (VALUE self)
static VALUE ole_param_ole_type (ITypeInfo *pTypeInfo, UINT method_index, UINT index)
static VALUE foleparam_ole_type (VALUE self)
static VALUE ole_param_ole_type_detail (ITypeInfo *pTypeInfo, UINT method_index, UINT index)
static VALUE foleparam_ole_type_detail (VALUE self)
static VALUE ole_param_flag_mask (ITypeInfo *pTypeInfo, UINT method_index, UINT index, USHORT mask)
static VALUE foleparam_input (VALUE self)
static VALUE foleparam_output (VALUE self)
static VALUE foleparam_optional (VALUE self)
static VALUE foleparam_retval (VALUE self)
static VALUE ole_param_default (ITypeInfo *pTypeInfo, UINT method_index, UINT index)
static VALUE foleparam_default (VALUE self)
static VALUE foleparam_inspect (VALUE self)
static long ole_search_event_at (VALUE ary, VALUE ev)
static VALUE ole_search_event (VALUE ary, VALUE ev, BOOL *is_default)
static VALUE ole_search_handler_method (VALUE handler, VALUE ev, BOOL *is_default_handler)
static void ole_delete_event (VALUE ary, VALUE ev)
static void hash2ptr_dispparams (VALUE hash, ITypeInfo *pTypeInfo, DISPID dispid, DISPPARAMS *pdispparams)
static VALUE hash2result (VALUE hash)
static void ary2ptr_dispparams (VALUE ary, DISPPARAMS *pdispparams)
static VALUE exec_callback (VALUE arg)
static VALUE rescue_callback (VALUE arg)
static HRESULT find_iid (VALUE ole, char *pitf, IID *piid, ITypeInfo **ppTypeInfo)
static HRESULT find_coclass (ITypeInfo *pTypeInfo, TYPEATTR *pTypeAttr, ITypeInfo **pTypeInfo2, TYPEATTR **pTypeAttr2)
static HRESULT find_default_source_from_typeinfo (ITypeInfo *pTypeInfo, TYPEATTR *pTypeAttr, ITypeInfo **ppTypeInfo)
static HRESULT find_default_source (VALUE ole, IID *piid, ITypeInfo **ppTypeInfo)
static void ole_event_free (struct oleeventdata *poleev)
static VALUE fev_s_allocate (VALUE klass)
static VALUE ev_advise (int argc, VALUE *argv, VALUE self)
static VALUE fev_initialize (int argc, VALUE *argv, VALUE self)
static VALUE fev_s_msg_loop (VALUE klass)
static void add_event_call_back (VALUE obj, VALUE event, VALUE data)
static VALUE ev_on_event (int argc, VALUE *argv, VALUE self, VALUE is_ary_arg)
static VALUE fev_on_event (int argc, VALUE *argv, VALUE self)
static VALUE fev_on_event_with_outargs (int argc, VALUE *argv, VALUE self)
static VALUE fev_off_event (int argc, VALUE *argv, VALUE self)
static VALUE fev_unadvise (VALUE self)
static VALUE fev_set_handler (VALUE self, VALUE val)
static VALUE fev_get_handler (VALUE self)
static VALUE evs_push (VALUE ev)
static VALUE evs_delete (long i)
static VALUE evs_entry (long i)
static VALUE evs_length (void)
static void olevariant_free (struct olevariantdata *pvar)
static VALUE folevariant_s_allocate (VALUE klass)
static VALUE folevariant_s_array (VALUE klass, VALUE dims, VALUE vvt)
static VALUE folevariant_initialize (VALUE self, VALUE args)
static long * ary2safe_array_index (int ary_size, VALUE *ary, SAFEARRAY *psa)
static void unlock_safe_array (SAFEARRAY *psa)
static SAFEARRAY * get_locked_safe_array (VALUE val)
static VALUE folevariant_ary_aref (int argc, VALUE *argv, VALUE self)
static VOID * val2variant_ptr (VALUE val, VARIANT *var, VARTYPE vt)
static VALUE folevariant_ary_aset (int argc, VALUE *argv, VALUE self)
static VALUE folevariant_value (VALUE self)
static VALUE folevariant_vartype (VALUE self)
static VALUE folevariant_set_value (VALUE self, VALUE val)
static void init_enc2cp (void)
static void free_enc2cp (void)
static DWORD (STDMETHODCALLTYPE mf_HandleInComingCall)(IMessageFilter __RPC_FAR *pThis
free (psz)
for (i=0;i< args;i++)
if (dispIdMember==DISPID_VALUE)
ole_val2variant (v, pVarResult)
static void failed_load_conv51932 (void)
static void set_ole_codepage (UINT cp)
void ole_uninitialize (void)
static void ole_uninitialize_hook (rb_event_flag_t evflag, VALUE data, VALUE self, ID mid, VALUE klass)
static VALUE reg_get_val2 (HKEY hkey, const char *subkey)
void EVENTSINK_Destructor (PIEVENTSINKOBJ)
STDMETHODIMP EVENTSINK_QueryInterface (PEVENTSINK pEV, REFIID iid, LPVOID *ppv)
EVENTSINK_AddRef (PEVENTSINK pEV)
STDMETHODIMP_ (ULONG)
STDMETHODIMP EVENTSINK_GetTypeInfoCount (PEVENTSINK pEV, UINT *pct)
STDMETHODIMP EVENTSINK_GetTypeInfo (PEVENTSINK pEV, UINT info, LCID lcid, ITypeInfo **pInfo)
STDMETHODIMP EVENTSINK_GetIDsOfNames (PEVENTSINK pEventSink, REFIID riid, OLECHAR **szNames, UINT cNames, LCID lcid, DISPID *pDispID)
STDMETHODIMP EVENTSINK_Invoke (PEVENTSINK pEventSink, DISPID dispid, REFIID riid, LCID lcid, WORD wFlags, DISPPARAMS *pdispparams, VARIANT *pvarResult, EXCEPINFO *pexcepinfo, UINT *puArgErr)
PIEVENTSINKOBJ EVENTSINK_Constructor ()
void Init_win32ole (void)
Variables
VALUE cWIN32OLE
VALUE cWIN32OLE_TYPELIB
VALUE cWIN32OLE_TYPE
VALUE cWIN32OLE_VARIABLE
VALUE cWIN32OLE_METHOD
VALUE cWIN32OLE_PARAM
VALUE cWIN32OLE_EVENT
VALUE cWIN32OLE_VARIANT
VALUE eWIN32OLERuntimeError
VALUE mWIN32OLE_VARIANT
VALUE cWIN32OLE_PROPERTY
static VALUE ary_ole_event
static ID id_events
static volatile DWORD g_ole_initialized_key = TLS_OUT_OF_INDEXES
static BOOL g_uninitialize_hooked = FALSE
static BOOL g_cp_installed = FALSE
static BOOL g_lcid_installed = FALSE
static HINSTANCE ghhctrl = NULL
static HINSTANCE gole32 = NULL
static FNCOCREATEINSTANCEEX * gCoCreateInstanceEx = NULL
static VALUE com_hash
static IDispatchVtbl com_vtbl
static UINT cWIN32OLE_cp = CP_ACP
static LCID cWIN32OLE_lcid = LOCALE_SYSTEM_DEFAULT
static rb_encoding * cWIN32OLE_enc
static UINT g_cp_to_check = CP_ACP
static char g_lcid_to_check [8+1]
static VARTYPE g_nil_to = VT_ERROR
static st_table * enc2cp_table
static IMessageFilterVtbl message_filter
static IMessageFilter imessage_filter = { &message_filter }
static IMessageFilter * previous_filter
static REFIID riid
static REFIID void __RPC_FAR
*__RPC_FAR * ppvObject
static UINT __RPC_FAR * pctinfo
static UINT iTInfo
static UINT LCID lcid
static UINT LCID ITypeInfo
__RPC_FAR *__RPC_FAR * ppTInfo
static REFIID LPOLESTR __RPC_FAR * rgszNames
static REFIID LPOLESTR
__RPC_FAR UINT cNames
static REFIID LPOLESTR
__RPC_FAR UINT LCID DISPID
__RPC_FAR * rgDispId
static DISPID dispIdMember
static DISPID REFIID LCID WORD wFlags
static DISPID REFIID LCID WORD
DISPPARAMS __RPC_FAR * pDispParams
static DISPID REFIID LCID WORD
DISPPARAMS __RPC_FAR VARIANT
__RPC_FAR * pVarResult
static DISPID REFIID LCID WORD
DISPPARAMS __RPC_FAR VARIANT
__RPC_FAR EXCEPINFO __RPC_FAR * pExcepInfo
static DISPID REFIID LCID WORD
DISPPARAMS __RPC_FAR VARIANT
__RPC_FAR EXCEPINFO __RPC_FAR
UINT __RPC_FAR * puArgErr
static DWORD dwCallType
static DWORD HTASK threadIDCaller
static DWORD HTASK DWORD dwTickCount
static DWORD HTASK DWORD
LPINTERFACEINFO lpInterfaceInfo
static HTASK threadIDCallee
static HTASK DWORD DWORD dwRejectType
static HTASK DWORD DWORD dwPendingType
return S_OK
int i
int args = pDispParams->cArgs
Win32OLEIDispatch * p = (Win32OLEIDispatch*)This
VALUE * parg = ALLOCA_N(VALUE, args)
v = rb_funcall2(p->obj, dispIdMember, args, parg)
static IEventSinkVtbl vtEventSink
static BOOL g_IsEventSinkVtblInitialized = FALSE
Macro Definition Documentation
#define conv_51932 (cp) ((cp) == 51932 && (load_conv_function51932(), 1))
Definition at line 958 of file win32ole.c.
Referenced by ole_mb2wc(), ole_vstr2wc(), and ole_wc2mb().
#define DOUT fprintf(stderr,"[%d]\n",__LINE__)
Definition at line 53 of file win32ole.c.
#define DOUTD (x) fprintf(stderr, "[%d]:" #x "=%f\n",__LINE__,x)
Definition at line 57 of file win32ole.c.
#define DOUTI (x) fprintf(stderr, "[%ld]:" #x "=%d\n",__LINE__,x)
Definition at line 56 of file win32ole.c.
#define DOUTMSG (x) fprintf(stderr, "[%d]:" #x "\n",__LINE__)
Definition at line 55 of file win32ole.c.
#define DOUTS (x) fprintf(stderr,"[%d]:" #x "=%s\n",__LINE__,x)
Definition at line 54 of file win32ole.c.
#define ENC_MACHING_CP (enc, encname, cp) if(strcasecmp(rb_enc_name((enc)),(encname)) == 0) return cp
Definition at line 861 of file win32ole.c.
Referenced by ole_encoding2cp().
#define g_ole_initialized (BOOL)TlsGetValue(g_ole_initialized_key)
Definition at line 223 of file win32ole.c.
Referenced by ole_initialize(), and ole_uninitialize().
#define g_ole_initialized_init () (g_ole_initialized_key = TlsAlloc())
Definition at line 224 of file win32ole.c.
Referenced by Init_win32ole().
#define g_ole_initialized_set (val) TlsSetValue(g_ole_initialized_key, (void*)(val))
Definition at line 225 of file win32ole.c.
Referenced by ole_initialize(), and ole_uninitialize().
#define GNUC_OLDER_3_4_4
Value:
((__GNUC__ < 3) || \
     ((__GNUC__ <= 3) && (__GNUC_MINOR__ < 4)) || \
     ((__GNUC__ <= 3) && (__GNUC_MINOR__ <= 4) && (__GNUC_PATCHLEVEL__ <= 4)))
Definition at line 22 of file win32ole.c.
#define I8_2_NUM INT2NUM
Definition at line 138 of file win32ole.c.
Referenced by ole_variant2val().
#define load_conv_function51932 () failed_load_conv51932()
Definition at line 955 of file win32ole.c.
Referenced by ole_cp2encoding(), and set_ole_codepage().
#define NUM2I8 NUM2INT
Definition at line 140 of file win32ole.c.
Referenced by ole_val2variant_ex().
#define NUM2UI8 NUM2UINT
Definition at line 141 of file win32ole.c.
Referenced by ole_val2variant_ex().
#define OLE_ADDREF (X) (X) ? ((X)->lpVtbl->AddRef(X)) : 0
Definition at line 111 of file win32ole.c.
Referenced by ole_method_params(), ole_val2variant(), ole_variables(), ole_variant2val(), olemethod_set_member(), oleparam_ole_param_from_index(), oletype_set_member(), and reference_count().
#define OLE_FREE (x)
Value:
{\
    if(g_ole_initialized == TRUE) {\
        if(x) {\
            OLE_RELEASE(x);\
            (x) = 0;\
        }\
    }\
}
Definition at line 116 of file win32ole.c.
Referenced by fole_free(), ole_free(), olemethod_free(), oleparam_free(), oletype_free(), oletypelib_free(), and olevariable_free().
#define OLE_GET_TYPEATTR (X, Y) ((X)->lpVtbl->GetTypeAttr((X), (Y)))
Definition at line 113 of file win32ole.c.
Referenced by find_coclass(), find_default_source(), find_iid(), ole_const_load(), ole_method_event(), ole_method_sub(), ole_methods_from_typeinfo(), ole_methods_sub(), ole_ole_type(), ole_type_guid(), ole_type_impl_ole_types(), ole_type_major_version(), ole_type_minor_version(), ole_type_progid(), ole_type_src_type(), ole_type_typekind(), ole_type_visible(), ole_variables(), and olemethod_from_typeinfo().
#define OLE_RELEASE (X) (X) ? ((X)->lpVtbl->Release(X)) : 0
Definition at line 109 of file win32ole.c.
Referenced by ev_advise(), EVENTSINK_Destructor(), fev_unadvise(), find_coclass(), find_default_source(), find_iid(), fole_activex_initialize(), fole_method_help(), fole_s_connect(), fole_s_const_load(), fole_s_free(), fole_type(), fole_typelib(), foletype_initialize(), ole_bind_obj(), ole_const_load(), ole_docinfo_from_type(), ole_event_free(), ole_ienum_free(), ole_method_event(), ole_methods(), ole_methods_from_typeinfo(), ole_set_member(), ole_type_from_itypeinfo(), ole_type_impl_ole_types(), ole_types_from_typelib(), ole_usertype2val(), oleclass_from_typelib(), olemethod_from_typeinfo(), reference_count(), and typeinfo_from_ole().
#define OLE_RELEASE_TYPEATTR (X, Y) ((X)->lpVtbl->ReleaseTypeAttr((X), (Y)))
Definition at line 114 of file win32ole.c.
Referenced by find_coclass(), find_default_source(), find_iid(), ole_method_event(), ole_method_sub(), ole_methods_from_typeinfo(), ole_methods_sub(), ole_ole_type(), ole_type_guid(), ole_type_impl_ole_types(), ole_type_major_version(), ole_type_minor_version(), ole_type_progid(), ole_type_src_type(), ole_type_typekind(), ole_type_visible(), ole_variables(), and olemethod_from_typeinfo().
#define OLEData_Get_Struct (obj, pole)
Value:
{\
    Data_Get_Struct(obj, struct oledata, pole);\
    if(!pole->pDispatch) {\
        rb_raise(rb_eRuntimeError, "failed to get Dispatch Interface");\
    }\
}
Definition at line 125 of file win32ole.c.
Referenced by ev_advise(), find_default_source(), find_iid(), fole_activex_initialize(), fole_each(), fole_free(), fole_method_help(), fole_query_interface(), fole_respond_to(), fole_s_const_load(), fole_s_free(), fole_s_reference_count(), fole_type(), fole_typelib(), ole_invoke(), ole_invoke2(), ole_methods(), and ole_propertyput().
#define pIMultiLanguage NULL /* dummy */
Definition at line 251 of file win32ole.c.
Referenced by ole_mb2wc(), ole_vstr2wc(), and ole_wc2mb().
#define UI8_2_NUM UINT2NUM
Definition at line 139 of file win32ole.c.
Referenced by ole_variant2val().
#define V_I1REF (X) V_UNION(X, pcVal)
Definition at line 77 of file win32ole.c.
Referenced by ole_set_byref(), and ole_variant2val().
#define V_INT (X) V_UNION(X, intVal)
Definition at line 85 of file win32ole.c.
Referenced by get_ptr_of_variant(), ole_set_byref(), and ole_variant2val().
#define V_INTREF (X) V_UNION(X, pintVal)
Definition at line 89 of file win32ole.c.
Referenced by ole_set_byref(), and ole_variant2val().
#define V_UI2REF (X) V_UNION(X, puiVal)
Definition at line 81 of file win32ole.c.
Referenced by ole_set_byref(), and ole_variant2val().
#define V_UINT (X) V_UNION(X, uintVal)
Definition at line 93 of file win32ole.c.
Referenced by get_ptr_of_variant(), ole_set_byref(), and ole_variant2val().
#define V_UINTREF (X) V_UNION(X, puintVal)
Definition at line 97 of file win32ole.c.
Referenced by ole_set_byref(), and ole_variant2val().
#define V_UNION1 (X, Y) ((X)->Y)
Definition at line 62 of file win32ole.c.
Referenced by ole_const_load(), ole_param_default(), ole_param_flag_mask(), ole_ptrtype2val(), ole_usertype2val(), and ole_variable_value().
#define va_init_list (a, b) va_start(a)
Definition at line 49 of file win32ole.c.
Referenced by ole_raise().
#define WC2VSTR (x) ole_wc2vstr((x), TRUE)
Definition at line 144 of file win32ole.c.
Referenced by EVENTSINK_Invoke(), folemethod_event_interface(), foletypelib_library_name(), foletypelib_name(), foletypelib_path(), hash2ptr_dispparams(), ole_method_event(), ole_method_helpfile(), ole_method_helpstring(), ole_method_params(), ole_method_sub(), ole_methods_sub(), ole_type_from_itypeinfo(), ole_type_helpfile(), ole_type_helpstring(), ole_types_from_typelib(), ole_usertype2val(), ole_variables(), oleclass_from_typelib(), oleparam_ole_param_from_index(), and typeinfo_from_ole().
#define WIN32OLE_VERSION "1.5.4"
Definition at line 146 of file win32ole.c.
Referenced by Init_win32ole().
Typedef Documentation
typedef IUnknown COSERVERINFO MULTI_QI* typedef LPCSTR UINT DWORD dwData
Definition at line 151 of file win32ole.c.
static DWORD
Definition at line 149 of file win32ole.c.
typedef BOOL(FNENUMSYSEMCODEPAGES)(CODEPAGE_ENUMPROC, DWORD)
Definition at line 153 of file win32ole.c.
typedef IUnknown COSERVERINFO MULTI_QI* typedef HWND(WINAPI FNHTMLHELP)(HWND hwndCaller
Definition at line 151 of file win32ole.c.
typedef struct tagIEVENTSINKOBJ IEVENTSINKOBJ
typedef struct IEventSinkVtbl IEventSinkVtbl
Definition at line 158 of file win32ole.c.
typedef struct IEventSink * PEVENTSINK
typedef struct tagIEVENTSINKOBJ * PIEVENTSINKOBJ
typedef IUnknown COSERVERINFO MULTI_QI* typedef LPCSTR pszFile
Definition at line 151 of file win32ole.c.
typedef IUnknown COSERVERINFO MULTI_QI* typedef LPCSTR UINT uCommand
Definition at line 151 of file win32ole.c.
typedef struct _Win32OLEIDispatch Win32OLEIDispatch
Function Documentation
static void add_event_call_back (VALUE obj, VALUE event, VALUE data) static
Definition at line 8398 of file win32ole.c.
References id_events, NIL_P, ole_delete_event(), rb_ary_new(), rb_ary_push(), rb_ivar_get(), rb_ivar_set(), T_ARRAY, and TYPE.
Referenced by ev_on_event().
static void ary2ptr_dispparams (VALUE ary, DISPPARAMS * pdispparams) static
Definition at line 7774 of file win32ole.c.
References i, ole_val2ptr_variant(), RARRAY_LEN, rb_ary_entry(), and v.
Referenced by EVENTSINK_Invoke().
static long * ary2safe_array_index (int ary_size, VALUE * ary, SAFEARRAY * psa) static
Definition at line 8813 of file win32ole.c.
References ALLOC_N, i, NULL, NUM2INT, rb_eArgError, rb_eRuntimeError, and rb_raise().
Referenced by folevariant_ary_aref(), and folevariant_ary_aset().
static long ary_len_of_dim (VALUE ary, long dim) static
Definition at line 1543 of file win32ole.c.
References RARRAY_LEN, rb_ary_entry(), T_ARRAY, TYPE, and val.
Referenced by ole_val_ary2variant_ary().
static VALUE ary_new_dim (VALUE myary, long * pid, long * plb, long dim) static
Definition at line 2043 of file win32ole.c.
References ALLOC_N, free(), i, Qnil, rb_ary_entry(), rb_ary_new(), rb_ary_store(), rb_eRuntimeError, and rb_raise().
Referenced by ary_store_dim(), and ole_variant2val().
static void ary_store_dim (VALUE myary, long * pid, long * plb, long dim, VALUE val) static
Definition at line 2069 of file win32ole.c.
References ary_new_dim(), and rb_ary_store().
Referenced by ole_variant2val().
static HRESULT clsid_from_remote (VALUE host, VALUE com, CLSID * pclsid) static
Definition at line 2578 of file win32ole.c.
References err, HRESULT(), NULL, ole_mb2wc(), rb_str_cat2(), rb_str_concat(), rb_str_new2, S_OK, and StringValuePtr.
Referenced by ole_create_dcom().
static BOOL code_page_installed (UINT cp) static
Definition at line 3033 of file win32ole.c.
References FALSE, g_cp_installed, g_cp_to_check, and installed_code_page_proc().
Referenced by ole_cp2encoding(), ole_vstr2wc(), and set_ole_codepage().
static VALUE create_win32ole_object (VALUE klass, IDispatch * pDispatch, int argc, VALUE * argv) static
Definition at line 2035 of file win32ole.c.
References fole_s_allocate(), and ole_set_member().
Referenced by fole_query_interface(), fole_s_connect(), ole_bind_obj(), and ole_variant2val().
static VALUE default_inspect (VALUE self, const char * class_name) static
Definition at line 2003 of file win32ole.c.
References make_inspect(), rb_funcall(), and rb_intern.
Referenced by folemethod_inspect(), foletype_inspect(), foletypelib_inspect(), and tracepoint_inspect().
static long dimension (VALUE val) static
Definition at line 1524 of file win32ole.c.
References RARRAY_LEN, rb_ary_entry(), T_ARRAY, and TYPE.
Referenced by ole_val_ary2variant_ary().
static DWORD (STDMETHODCALLTYPE mf_HandleInComingCall) static
static VALUE ev_advise (int argc, VALUE * argv, VALUE self) static
Definition at line 8283 of file win32ole.c.
References cWIN32OLE, Data_Get_Struct, oleeventdata::dwCookie, oleeventdata::event_id, EVENTSINK_Constructor(), evs_length(), find_default_source(), find_iid(), HRESULT(), tagIEVENTSINKOBJ::m_event_id, tagIEVENTSINKOBJ::m_iid, NUM2INT, OBJ_TAINTED, ole_raise(), OLE_RELEASE, OLEData_Get_Struct, p, oleeventdata::pConnectionPoint, oledata::pDispatch, tagIEVENTSINKOBJ::pTypeInfo, rb_eRuntimeError, rb_eSecurityError, rb_eTypeError, rb_obj_is_kind_of(), rb_raise(), rb_safe_level, rb_scan_args(), rb_secure(), SafeStringValue, StringValuePtr, T_NIL, and TYPE.
Referenced by fev_initialize().
static VALUE ev_on_event (int argc, VALUE * argv, VALUE self, VALUE is_ary_arg) static
Definition at line 8410 of file win32ole.c.
References add_event_call_back(), args, Data_Get_Struct, eWIN32OLERuntimeError, NIL_P, NULL, oleeventdata::pConnectionPoint, Qnil, rb_ary_new3(), rb_block_proc(), rb_eTypeError, rb_raise(), rb_scan_args(), rb_sym_to_s(), T_STRING, T_SYMBOL, and TYPE.
Referenced by fev_on_event(), and fev_on_event_with_outargs().
EVENTSINK_AddRef (PEVENTSINK pEV)
Definition at line 7604 of file win32ole.c.
References tagIEVENTSINKOBJ::m_cRef.
Referenced by EVENTSINK_Constructor().
PIEVENTSINKOBJ EVENTSINK_Constructor ()
Definition at line 7919 of file win32ole.c.
References ALLOC_N, EVENTSINK_AddRef(), EVENTSINK_GetIDsOfNames(), EVENTSINK_GetTypeInfo(), EVENTSINK_GetTypeInfoCount(), EVENTSINK_Invoke(), EVENTSINK_QueryInterface(), tagIEVENTSINKOBJ::lpVtbl, tagIEVENTSINKOBJ::m_cRef, tagIEVENTSINKOBJ::m_event_id, NULL, tagIEVENTSINKOBJ::pTypeInfo, IEventSinkVtbl::QueryInterface(), TRUE, and vtEventSink.
Referenced by ev_advise().
void EVENTSINK_Destructor (PIEVENTSINKOBJ pEVObj)
Definition at line 7941 of file win32ole.c.
References free(), NULL, OLE_RELEASE, and tagIEVENTSINKOBJ::pTypeInfo.
Referenced by STDMETHODIMP_().
STDMETHODIMP EVENTSINK_GetIDsOfNames (PEVENTSINK pEventSink, REFIID riid, OLECHAR ** szNames, UINT cNames, LCID lcid, DISPID * pDispID)
Definition at line 7640 of file win32ole.c.
References tagIEVENTSINKOBJ::pTypeInfo, and oleparamdata::pTypeInfo.
Referenced by EVENTSINK_Constructor().
STDMETHODIMP EVENTSINK_GetTypeInfo (PEVENTSINK pEV, UINT info, LCID lcid, ITypeInfo ** pInfo)
Definition at line 7630 of file win32ole.c.
References NULL.
Referenced by EVENTSINK_Constructor().
STDMETHODIMP EVENTSINK_GetTypeInfoCount (PEVENTSINK pEV, UINT * pct)
Definition at line 7622 of file win32ole.c.
Referenced by EVENTSINK_Constructor().
STDMETHODIMP EVENTSINK_Invoke (PEVENTSINK pEventSink, DISPID dispid, REFIID riid, LCID lcid, WORD wFlags, DISPPARAMS * pdispparams, VARIANT * pvarResult, EXCEPINFO * pexcepinfo, UINT * puArgErr)
Definition at line 7814 of file win32ole.c.
References arg, args, ary2ptr_dispparams(), count, cWIN32OLE_EVENT, ev, evs_entry(), exec_callback(), FALSE, hash2ptr_dispparams(), hash2result(), HRESULT(), i, id_events, tagIEVENTSINKOBJ::m_event_id, NIL_P, ole_search_event(), ole_search_handler_method(), ole_val2variant(), ole_variant2val(), tagIEVENTSINKOBJ::pTypeInfo, oleparamdata::pTypeInfo, Qfalse, Qnil, Qtrue, rb_ary_entry(), rb_ary_new(), rb_ary_push(), rb_intern, rb_ivar_get(), rb_obj_is_kind_of(), rb_protect(), rescue_callback(), result, T_ARRAY, T_HASH, TYPE, and WC2VSTR.
Referenced by EVENTSINK_Constructor().
STDMETHODIMP EVENTSINK_QueryInterface (PEVENTSINK pEV, REFIID iid, LPVOID * ppv)
Definition at line 7585 of file win32ole.c.
References NULL.
Referenced by EVENTSINK_Constructor().
static VALUE evs_delete (long i) static
Definition at line 8563 of file win32ole.c.
References ary_ole_event, Qnil, and rb_ary_store().
Referenced by fev_unadvise().
static VALUE evs_entry (long i) static
Definition at line 8570 of file win32ole.c.
References ary_ole_event, and rb_ary_entry().
Referenced by EVENTSINK_Invoke().
static VALUE evs_length (void) static
Definition at line 8576 of file win32ole.c.
References ary_ole_event, rb_funcall(), and rb_intern.
Referenced by ev_advise().
static VALUE evs_push (VALUE ev) static
Definition at line 8557 of file win32ole.c.
References ary_ole_event, and rb_ary_push().
Referenced by fev_initialize().
static VALUE exec_callback (VALUE arg) static
Definition at line 7787 of file win32ole.c.
References rb_apply().
Referenced by EVENTSINK_Invoke().
static void failed_load_conv51932 (void) static
Definition at line 929 of file win32ole.c.
References eWIN32OLERuntimeError, and rb_raise().
static VALUE fev_get_handler (VALUE self) static
Definition at line 8634 of file win32ole.c.
References rb_intern, and rb_ivar_get().
Referenced by Init_win32ole().
static VALUE fev_initialize (int argc, VALUE * argv, VALUE self) static
Definition at line 8374 of file win32ole.c.
References ev_advise(), evs_push(), fev_set_handler(), id_events, Qnil, rb_ary_new(), and rb_ivar_set().
Referenced by Init_win32ole().
static VALUE fev_off_event (int argc, VALUE * argv, VALUE self) static
Definition at line 8503 of file win32ole.c.
References id_events, NIL_P, ole_delete_event(), Qnil, rb_eTypeError, rb_ivar_get(), rb_raise(), rb_scan_args(), rb_secure(), rb_sym_to_s(), T_STRING, T_SYMBOL, and TYPE.
Referenced by Init_win32ole().
static VALUE fev_on_event (int argc, VALUE * argv, VALUE self) static
Definition at line 8462 of file win32ole.c.
References ev_on_event(), and Qfalse.
Referenced by Init_win32ole().
static VALUE fev_on_event_with_outargs (int argc, VALUE * argv, VALUE self) static
Definition at line 8482 of file win32ole.c.
References ev_on_event(), and Qtrue.
Referenced by Init_win32ole().
static VALUE fev_s_allocate (VALUE klass) static
Definition at line 8271 of file win32ole.c.
References Data_Make_Struct, oleeventdata::dwCookie, oleeventdata::event_id, NULL, ole_event_free(), and oleeventdata::pConnectionPoint.
Referenced by Init_win32ole().
static VALUE fev_s_msg_loop (VALUE klass) static
Definition at line 8390 of file win32ole.c.
References ole_msg_loop(), and Qnil.
Referenced by Init_win32ole().
static VALUE fev_set_handler (VALUE self, VALUE val) static
Definition at line 8621 of file win32ole.c.
References rb_intern, and rb_ivar_set().
Referenced by fev_initialize(), and Init_win32ole().
static VALUE fev_unadvise (VALUE self) static
Definition at line 8542 of file win32ole.c.
References Data_Get_Struct, oleeventdata::dwCookie, oleeventdata::event_id, evs_delete(), NULL, ole_msg_loop(), OLE_RELEASE, oleeventdata::pConnectionPoint, and Qnil.
Referenced by Init_win32ole().
static HRESULT find_coclass (ITypeInfo * pTypeInfo, TYPEATTR * pTypeAttr, ITypeInfo ** pTypeInfo2, TYPEATTR ** pTypeAttr2) static
Definition at line 8063 of file win32ole.c.
References count, FALSE, HRESULT(), i, NULL, OLE_GET_TYPEATTR, OLE_RELEASE, OLE_RELEASE_TYPEATTR, S_OK, and TRUE.
Referenced by find_default_source().
static HRESULT find_default_source (VALUE ole, IID * piid, ITypeInfo ** ppTypeInfo) static
Definition at line 8174 of file win32ole.c.
References cWIN32OLE_lcid, find_coclass(), find_default_source_from_typeinfo(), find_iid(), HRESULT(), NULL, OLE_GET_TYPEATTR, OLE_RELEASE, OLE_RELEASE_TYPEATTR, OLEData_Get_Struct, p, and oledata::pDispatch.
Referenced by ev_advise().
static HRESULT find_default_source_from_typeinfo (ITypeInfo * pTypeInfo, TYPEATTR * pTypeAttr, ITypeInfo ** ppTypeInfo) static
Definition at line 8138 of file win32ole.c.
References HRESULT().
Referenced by find_default_source().
static HRESULT find_iid (VALUE ole, char * pitf, IID * piid, ITypeInfo ** ppTypeInfo) static
Definition at line 7952 of file win32ole.c.
References count, cWIN32OLE_lcid, FALSE, free(), HRESULT(), NULL, OLE_GET_TYPEATTR, OLE_RELEASE, OLE_RELEASE_TYPEATTR, ole_wc2mb(), OLEData_Get_Struct, oledata::pDispatch, oleparamdata::pTypeInfo, TRUE, and type.
Referenced by ev_advise(), and find_default_source().
static VALUE fole_activex_initialize (VALUE self) static
Definition at line 4773 of file win32ole.c.
References eWIN32OLERuntimeError, HRESULT(), ole_raise(), OLE_RELEASE, OLEData_Get_Struct, p, oledata::pDispatch, Qnil, and S_OK.
Referenced by Init_win32ole().
static VALUE fole_each (VALUE self) static
Definition at line 4013 of file win32ole.c.
References cWIN32OLE_lcid, eWIN32OLERuntimeError, HRESULT(), NULL, ole_each_sub(), ole_ienum_free(), ole_raise(), OLEData_Get_Struct, p, oledata::pDispatch, Qnil, rb_ensure(), rb_eRuntimeError, result, and RETURN_ENUMERATOR.
Referenced by Init_win32ole().
static VALUE fole_free (VALUE self) static
Definition at line 3964 of file win32ole.c.
References NULL, OLE_FREE, OLEData_Get_Struct, oledata::pDispatch, Qnil, and rb_secure().
Referenced by Init_win32ole().
static VALUE fole_func_methods (VALUE self) static
Definition at line 4354 of file win32ole.c.
References ole_methods().
Referenced by Init_win32ole().
static VALUE fole_get_methods (VALUE self) static
Definition at line 4321 of file win32ole.c.
References ole_methods().
Referenced by Init_win32ole().
static VALUE fole_getproperty2 (VALUE self, VALUE dispid, VALUE args, VALUE types) static
Definition at line 3809 of file win32ole.c.
References ole_invoke2().
Referenced by Init_win32ole().
static VALUE fole_getproperty_with_bracket (int argc, VALUE * argv, VALUE self) static
Definition at line 3892 of file win32ole.c.
References ole_invoke(), and TRUE.
Referenced by Init_win32ole().
static VALUE fole_initialize (int argc, VALUE * argv, VALUE self) static
Definition at line 3229 of file win32ole.c.
References eWIN32OLERuntimeError, HRESULT(), NIL_P, NULL, OBJ_TAINTED, ole_create_dcom(), ole_raise(), ole_set_member(), ole_vstr2wc(), p, oledata::pDispatch, rb_call_super(), rb_eSecurityError, rb_raise(), rb_safe_level, rb_scan_args(), rb_secure(), SafeStringValue, and StringValuePtr.
Referenced by Init_win32ole().
static VALUE fole_invoke (int argc, VALUE * argv, VALUE self) static
Definition at line 3583 of file win32ole.c.
References FALSE, and ole_invoke().
Referenced by Init_win32ole().
static VALUE fole_invoke2 (VALUE self, VALUE dispid, VALUE args, VALUE types) static
Definition at line 3791 of file win32ole.c.
References ole_invoke2().
Referenced by Init_win32ole().
static VALUE fole_method_help (VALUE self, VALUE cmdname) static
Definition at line 4731 of file win32ole.c.
References cWIN32OLE_METHOD, eWIN32OLERuntimeError, folemethod_s_allocate(), HRESULT(), ole_raise(), OLE_RELEASE, OLEData_Get_Struct, olemethod_from_typeinfo(), Qnil, rb_eRuntimeError, rb_raise(), SafeStringValue, StringValuePtr, and typeinfo_from_ole().
Referenced by Init_win32ole().
static VALUE fole_methods (VALUE self) static
Definition at line 4305 of file win32ole.c.
References ole_methods().
Referenced by Init_win32ole().
static VALUE fole_missing (int argc, VALUE * argv, VALUE self) static
Definition at line 4076 of file win32ole.c.
References FALSE, id, ole_invoke(), ole_propertyput(), rb_enc_str_new(), rb_eRuntimeError, rb_id2name(), rb_raise(), rb_to_id(), and strlen().
Referenced by Init_win32ole().
static VALUE fole_put_methods (VALUE self) static
Definition at line 4337 of file win32ole.c.
References ole_methods().
Referenced by Init_win32ole().
static VALUE fole_query_interface (VALUE self, VALUE str_iid) static
Definition at line 4477 of file win32ole.c.
References create_win32ole_object(), cWIN32OLE, eWIN32OLERuntimeError, HRESULT(), ole_raise(), ole_vstr2wc(), OLEData_Get_Struct, p, oledata::pDispatch, rb_eRuntimeError, rb_raise(), and StringValuePtr.
Referenced by Init_win32ole().
static VALUE fole_respond_to (VALUE self, VALUE method) static
Definition at line 4522 of file win32ole.c.
References cWIN32OLE_lcid, HRESULT(), ole_vstr2wc(), OLEData_Get_Struct, oledata::pDispatch, Qfalse, Qtrue, rb_eTypeError, rb_raise(), rb_secure(), rb_sym_to_s(), T_STRING, T_SYMBOL, and TYPE.
Referenced by Init_win32ole().
static VALUE fole_s_allocate (VALUE klass) static
Definition at line 2024 of file win32ole.c.
References Data_Make_Struct, NULL, ole_free(), ole_initialize(), and oledata::pDispatch.
Referenced by create_win32ole_object(), and Init_win32ole().
static VALUE fole_s_connect (int argc, VALUE * argv, VALUE self) static
Definition at line 2717 of file win32ole.c.
References create_win32ole_object(), eWIN32OLERuntimeError, HRESULT(), OBJ_TAINTED, ole_bind_obj(), ole_initialize(), ole_raise(), OLE_RELEASE, ole_vstr2wc(), p, oledata::pDispatch, rb_eSecurityError, rb_raise(), rb_safe_level, rb_scan_args(), rb_secure(), SafeStringValue, and StringValuePtr.
Referenced by Init_win32ole().
static VALUE fole_s_const_load (int argc, VALUE * argv, VALUE self) static
Definition at line 2799 of file win32ole.c.
References cWIN32OLE, cWIN32OLE_lcid, eWIN32OLERuntimeError, HRESULT(), ole_const_load(), ole_raise(), OLE_RELEASE, ole_vstr2wc(), OLEData_Get_Struct, oledata::pDispatch, Qnil, rb_eRuntimeError, rb_eTypeError, rb_obj_is_kind_of(), rb_raise(), rb_scan_args(), rb_secure(), T_CLASS, T_MODULE, T_NIL, T_STRING, TYPE, and typelib_file().
Referenced by Init_win32ole().
static VALUE fole_s_create_guid (VALUE self) static
Definition at line 3136 of file win32ole.c.
References eWIN32OLERuntimeError, FALSE, HRESULT(), ole_raise(), ole_wc2vstr(), rb_eRuntimeError, and rb_raise().
Referenced by Init_win32ole().
static VALUE fole_s_free (VALUE self, VALUE obj) static
Definition at line 2933 of file win32ole.c.
References INT2NUM, OLE_RELEASE, OLEData_Get_Struct, oledata::pDispatch, reference_count(), and ULONG().
Referenced by Init_win32ole().
static VALUE fole_s_get_code_page (VALUE self) static
Definition at line 3018 of file win32ole.c.
References cWIN32OLE_cp, and INT2FIX.
Referenced by Init_win32ole().
static VALUE fole_s_get_locale (VALUE self) static
Definition at line 3075 of file win32ole.c.
References cWIN32OLE_lcid, and INT2FIX.
Referenced by Init_win32ole().
static VALUE fole_s_ole_initialize (VALUE self) static
Definition at line 3161 of file win32ole.c.
References ole_initialize(), and Qnil.
Referenced by Init_win32ole().
static VALUE fole_s_ole_uninitialize (VALUE self) static
Definition at line 3169 of file win32ole.c.
References ole_uninitialize(), and Qnil.
Referenced by Init_win32ole().
static VALUE fole_s_reference_count (VALUE self, VALUE obj) static
Definition at line 2916 of file win32ole.c.
References INT2NUM, OLEData_Get_Struct, and reference_count().
Referenced by Init_win32ole().
static VALUE fole_s_set_code_page (VALUE self, VALUE vcp) static
Definition at line 3055 of file win32ole.c.
References FIX2INT, Qnil, and set_ole_codepage().
Referenced by Init_win32ole().
static VALUE fole_s_set_locale (VALUE self, VALUE vlcid) static
Definition at line 3110 of file win32ole.c.
References cWIN32OLE_lcid, eWIN32OLERuntimeError, FIX2INT, lcid, lcid_installed(), Qnil, and rb_raise().
Referenced by Init_win32ole().
static VALUE fole_s_show_help (int argc, VALUE * argv, VALUE self) static
Definition at line 2979 of file win32ole.c.
References cWIN32OLE_METHOD, cWIN32OLE_TYPE, name, ole_show_help(), Qnil, rb_eRuntimeError, rb_eTypeError, rb_funcall(), rb_intern, rb_ivar_get(), rb_obj_is_kind_of(), rb_raise(), rb_scan_args(), StringValuePtr, strlen(), T_STRING, and TYPE.
Referenced by Init_win32ole().
static VALUE fole_setproperty (int argc, VALUE * argv, VALUE self) static
Definition at line 3870 of file win32ole.c.
References FALSE, and ole_invoke().
Referenced by Init_win32ole().
static VALUE fole_setproperty2 (VALUE self, VALUE dispid, VALUE args, VALUE types) static
Definition at line 3827 of file win32ole.c.
References ole_invoke2().
Referenced by Init_win32ole().
static VALUE fole_setproperty_with_bracket (int argc, VALUE * argv, VALUE self) static
Definition at line 3851 of file win32ole.c.
References ole_invoke(), and TRUE.
Referenced by Init_win32ole().
static VALUE fole_type (VALUE self) static
Definition at line 4393 of file win32ole.c.
References cWIN32OLE_lcid, HRESULT(), ole_raise(), OLE_RELEASE, ole_type_from_itypeinfo(), OLEData_Get_Struct, oledata::pDispatch, Qnil, rb_eRuntimeError, rb_raise(), and type.
Referenced by Init_win32ole().
static VALUE fole_typelib (VALUE self) static
Definition at line 4444 of file win32ole.c.
References cWIN32OLE_lcid, HRESULT(), ole_raise(), OLE_RELEASE, ole_typelib_from_itypeinfo(), OLEData_Get_Struct, oledata::pDispatch, Qnil, rb_eRuntimeError, and rb_raise().
Referenced by Init_win32ole().
static VALUE folemethod_dispid (VALUE self) static
Definition at line 7062 of file win32ole.c.
References Data_Get_Struct, olemethoddata::index, ole_method_dispid(), and olemethoddata::pTypeInfo.
Referenced by Init_win32ole().
static VALUE folemethod_event (VALUE self) static
Definition at line 6890 of file win32ole.c.
References Data_Get_Struct, olemethoddata::index, ole_method_event(), olemethoddata::pOwnerTypeInfo, Qfalse, rb_intern, and rb_ivar_get().
Referenced by folemethod_event_interface(), and Init_win32ole().
static VALUE folemethod_event_interface (VALUE self) static
Definition at line 6911 of file win32ole.c.
References Data_Get_Struct, folemethod_event(), HRESULT(), name, NULL, ole_docinfo_from_type(), olemethoddata::pTypeInfo, Qnil, Qtrue, and WC2VSTR.
Referenced by Init_win32ole().
static VALUE folemethod_helpcontext (VALUE self) static
Definition at line 7031 of file win32ole.c.
References Data_Get_Struct, olemethoddata::index, ole_method_helpcontext(), and olemethoddata::pTypeInfo.
Referenced by Init_win32ole().
static VALUE folemethod_helpfile (VALUE self) static
Definition at line 7001 of file win32ole.c.
References Data_Get_Struct, olemethoddata::index, ole_method_helpfile(), and olemethoddata::pTypeInfo.
Referenced by Init_win32ole().
static VALUE folemethod_helpstring (VALUE self) static
Definition at line 6971 of file win32ole.c.
References Data_Get_Struct, olemethoddata::index, ole_method_helpstring(), and olemethoddata::pTypeInfo.
Referenced by Init_win32ole().
static VALUE folemethod_initialize (VALUE self, VALUE oletype, VALUE method) static
Definition at line 6569 of file win32ole.c.
References cWIN32OLE_TYPE, Data_Get_Struct, eWIN32OLERuntimeError, olemethod_from_typeinfo(), oletypedata::pTypeInfo, Qnil, rb_eTypeError, rb_obj_is_kind_of(), rb_raise(), SafeStringValue, and StringValuePtr.
Referenced by Init_win32ole().
static VALUE folemethod_inspect (VALUE self) static
Definition at line 7232 of file win32ole.c.
References default_inspect().
Referenced by Init_win32ole().
static VALUE folemethod_invkind (VALUE self) static
Definition at line 6752 of file win32ole.c.
References Data_Get_Struct, olemethoddata::index, ole_method_invkind(), and olemethoddata::pTypeInfo.
Referenced by Init_win32ole().
static VALUE folemethod_invoke_kind (VALUE self) static
Definition at line 6771 of file win32ole.c.
References Data_Get_Struct, olemethoddata::index, ole_method_invoke_kind(), and olemethoddata::pTypeInfo.
Referenced by Init_win32ole().
static VALUE folemethod_name (VALUE self) static
Definition at line 6600 of file win32ole.c.
References rb_intern, and rb_ivar_get().
Referenced by Init_win32ole().
static VALUE folemethod_offset_vtbl (VALUE self) static
Definition at line 7093 of file win32ole.c.
References Data_Get_Struct, olemethoddata::index, ole_method_offset_vtbl(), and olemethoddata::pTypeInfo.
Referenced by Init_win32ole().
static VALUE folemethod_params (VALUE self) static
Definition at line 7217 of file win32ole.c.
References Data_Get_Struct, olemethoddata::index, ole_method_params(), and olemethoddata::pTypeInfo.
Referenced by Init_win32ole().
static VALUE folemethod_return_type (VALUE self) static
Definition at line 6632 of file win32ole.c.
References Data_Get_Struct, olemethoddata::index, ole_method_return_type(), and olemethoddata::pTypeInfo.
Referenced by Init_win32ole().
static VALUE folemethod_return_type_detail (VALUE self) static
Definition at line 6700 of file win32ole.c.
References Data_Get_Struct, olemethoddata::index, ole_method_return_type_detail(), and olemethoddata::pTypeInfo.
Referenced by Init_win32ole().
static VALUE folemethod_return_vtype (VALUE self) static
Definition at line 6666 of file win32ole.c.
References Data_Get_Struct, olemethoddata::index, ole_method_return_vtype(), and olemethoddata::pTypeInfo.
Referenced by Init_win32ole().
static VALUE folemethod_s_allocate (VALUE klass) static
Definition at line 6542 of file win32ole.c.
References Data_Make_Struct, olemethoddata::index, NULL, olemethod_free(), olemethoddata::pOwnerTypeInfo, and olemethoddata::pTypeInfo.
Referenced by fole_method_help(), Init_win32ole(), and ole_methods_sub().
static VALUE folemethod_size_opt_params (VALUE self) static
Definition at line 7156 of file win32ole.c.
References Data_Get_Struct, olemethoddata::index, ole_method_size_opt_params(), and olemethoddata::pTypeInfo.
Referenced by Init_win32ole().
static VALUE folemethod_size_params (VALUE self) static
Definition at line 7125 of file win32ole.c.
References Data_Get_Struct, olemethoddata::index, ole_method_size_params(), and olemethoddata::pTypeInfo.
Referenced by Init_win32ole().
static VALUE folemethod_visible (VALUE self) static
Definition at line 6808 of file win32ole.c.
References Data_Get_Struct, olemethoddata::index, ole_method_visible(), and olemethoddata::pTypeInfo.
Referenced by Init_win32ole().
static VALUE foleparam_default (VALUE self) static
Definition at line 7545 of file win32ole.c.
References Data_Get_Struct, oleparamdata::index, oleparamdata::method_index, ole_param_default(), and oleparamdata::pTypeInfo.
Referenced by foleparam_inspect(), and Init_win32ole().
static VALUE foleparam_initialize (VALUE self, VALUE olemethod, VALUE n) static
Definition at line 7302 of file win32ole.c.
References cWIN32OLE_METHOD, FIX2INT, oleparam_ole_param(), rb_eTypeError, rb_obj_is_kind_of(), and rb_raise().
Referenced by Init_win32ole().
static VALUE foleparam_input (VALUE self) static
Definition at line 7421 of file win32ole.c.
References Data_Get_Struct, oleparamdata::index, oleparamdata::method_index, ole_param_flag_mask(), and oleparamdata::pTypeInfo.
Referenced by Init_win32ole().
static VALUE foleparam_inspect (VALUE self) static
Definition at line 7562 of file win32ole.c.
References foleparam_default(), foleparam_name(), make_inspect(), Qnil, rb_funcall(), rb_intern, rb_str_cat2(), and rb_str_concat().
Referenced by Init_win32ole().
static VALUE foleparam_name (VALUE self) static
Definition at line 7323 of file win32ole.c.
References rb_intern, and rb_ivar_get().
Referenced by foleparam_inspect(), and Init_win32ole().
static VALUE foleparam_ole_type (VALUE self) static
Definition at line 7354 of file win32ole.c.
References Data_Get_Struct, oleparamdata::index, oleparamdata::method_index, ole_param_ole_type(), and oleparamdata::pTypeInfo.
Referenced by Init_win32ole().
static VALUE foleparam_ole_type_detail (VALUE self) static
Definition at line 7388 of file win32ole.c.
References Data_Get_Struct, oleparamdata::index, oleparamdata::method_index, ole_param_ole_type_detail(), and oleparamdata::pTypeInfo.
Referenced by Init_win32ole().
static VALUE foleparam_optional (VALUE self) static
Definition at line 7466 of file win32ole.c.
References Data_Get_Struct, oleparamdata::index, oleparamdata::method_index, ole_param_flag_mask(), and oleparamdata::pTypeInfo.
Referenced by Init_win32ole().
static VALUE foleparam_output (VALUE self) static
Definition at line 7448 of file win32ole.c.
References Data_Get_Struct, oleparamdata::index, oleparamdata::method_index, ole_param_flag_mask(), and oleparamdata::pTypeInfo.
Referenced by Init_win32ole().
static VALUE foleparam_retval (VALUE self) static
Definition at line 7485 of file win32ole.c.
References Data_Get_Struct, oleparamdata::index, oleparamdata::method_index, ole_param_flag_mask(), and oleparamdata::pTypeInfo.
Referenced by Init_win32ole().
static VALUE foleparam_s_allocate (VALUE klass) static
Definition at line 7243 of file win32ole.c.
References Data_Make_Struct, oleparamdata::index, oleparamdata::method_index, NULL, oleparam_free(), and oleparamdata::pTypeInfo.
Referenced by Init_win32ole().
static VALUE foletype_default_event_sources (VALUE self) static
Definition at line 6081 of file win32ole.c.
References Data_Get_Struct, ole_type_impl_ole_types(), and oletypedata::pTypeInfo.
Referenced by Init_win32ole().
static VALUE foletype_default_ole_types (VALUE self) static
Definition at line 6099 of file win32ole.c.
References Data_Get_Struct, ole_type_impl_ole_types(), and oletypedata::pTypeInfo.
Referenced by Init_win32ole().
static VALUE foletype_guid (VALUE self) static
Definition at line 5690 of file win32ole.c.
References Data_Get_Struct, ole_type_guid(), and oletypedata::pTypeInfo.
Referenced by Init_win32ole().
static VALUE foletype_helpcontext (VALUE self) static
Definition at line 5971 of file win32ole.c.
References Data_Get_Struct, ole_type_helpcontext(), and oletypedata::pTypeInfo.
Referenced by Init_win32ole().
static VALUE foletype_helpfile (VALUE self) static
Definition at line 5943 of file win32ole.c.
References Data_Get_Struct, ole_type_helpfile(), and oletypedata::pTypeInfo.
Referenced by Init_win32ole().
static VALUE foletype_helpstring (VALUE self) static
Definition at line 5879 of file win32ole.c.
References Data_Get_Struct, ole_type_helpstring(), and oletypedata::pTypeInfo.
Referenced by Init_win32ole().
static VALUE foletype_impl_ole_types (VALUE self) static
Definition at line 6046 of file win32ole.c.
References Data_Get_Struct, ole_type_impl_ole_types(), and oletypedata::pTypeInfo.
Referenced by Init_win32ole().
static VALUE foletype_initialize (VALUE self, VALUE typelib, VALUE oleclass) static
Definition at line 5559 of file win32ole.c.
References eWIN32OLERuntimeError, HRESULT(), ole_raise(), OLE_RELEASE, ole_vstr2wc(), oleclass_from_typelib(), oletypelibdata::pTypeLib, Qfalse, Qnil, rb_raise(), SafeStringValue, StringValuePtr, and typelib_file().
Referenced by Init_win32ole().
static VALUE foletype_inspect (VALUE self) static
Definition at line 6116 of file win32ole.c.
References default_inspect().
Referenced by Init_win32ole().
static VALUE foletype_major_version (VALUE self) static
Definition at line 5790 of file win32ole.c.
References Data_Get_Struct, ole_type_major_version(), and oletypedata::pTypeInfo.
Referenced by Init_win32ole().
static VALUE foletype_methods (VALUE self) static
Definition at line 6204 of file win32ole.c.
References Data_Get_Struct, ole_methods_from_typeinfo(), and oletypedata::pTypeInfo.
Referenced by Init_win32ole().
static VALUE foletype_minor_version (VALUE self) static
Definition at line 5820 of file win32ole.c.
References Data_Get_Struct, ole_type_minor_version(), and oletypedata::pTypeInfo.
Referenced by Init_win32ole().
static VALUE foletype_name (VALUE self) static
Definition at line 5595 of file win32ole.c.
References rb_intern, and rb_ivar_get().
Referenced by Init_win32ole().
static VALUE foletype_ole_type (VALUE self) static
Definition at line 5655 of file win32ole.c.
References Data_Get_Struct, ole_ole_type(), and oletypedata::pTypeInfo.
Referenced by Init_win32ole().
static VALUE foletype_ole_typelib (VALUE self) static
Definition at line 5988 of file win32ole.c.
References Data_Get_Struct, ole_typelib_from_itypeinfo(), and oletypedata::pTypeInfo.
Referenced by Init_win32ole().
static VALUE foletype_progid (VALUE self) static
Definition at line 5725 of file win32ole.c.
References Data_Get_Struct, ole_type_progid(), and oletypedata::pTypeInfo.
Referenced by Init_win32ole().
static VALUE foletype_s_allocate (VALUE klass) static
Definition at line 4878 of file win32ole.c.
References Data_Make_Struct, NULL, ole_initialize(), oletype_free(), and oletypedata::pTypeInfo.
Referenced by Init_win32ole(), ole_type_from_itypeinfo(), and ole_types_from_typelib().
static VALUE foletype_s_ole_classes (VALUE self, VALUE typelib) static
Definition at line 4808 of file win32ole.c.
References cWIN32OLE_TYPELIB, rb_funcall(), and rb_intern.
Referenced by Init_win32ole().
static VALUE foletype_s_progids (VALUE self) static
Definition at line 4847 of file win32ole.c.
References err, i, Qnil, rb_ary_new(), rb_ary_push(), rb_str_new2, reg_enum_key(), reg_get_val2(), reg_open_key(), and reg_open_vkey().
Referenced by Init_win32ole().
static VALUE foletype_s_typelibs (VALUE self) static
Definition at line 4830 of file win32ole.c.
References rb_eval_string().
Referenced by Init_win32ole().
static VALUE foletype_source_ole_types (VALUE self) static
Definition at line 6064 of file win32ole.c.
References Data_Get_Struct, ole_type_impl_ole_types(), and oletypedata::pTypeInfo.
Referenced by Init_win32ole().
static VALUE foletype_src_type (VALUE self) static
Definition at line 5914 of file win32ole.c.
References Data_Get_Struct, ole_type_src_type(), and oletypedata::pTypeInfo.
Referenced by Init_win32ole().
static VALUE foletype_typekind (VALUE self) static
Definition at line 5851 of file win32ole.c.
References Data_Get_Struct, ole_type_typekind(), and oletypedata::pTypeInfo.
Referenced by Init_win32ole().
static VALUE foletype_variables (VALUE self) static
Definition at line 6184 of file win32ole.c.
References Data_Get_Struct, ole_variables(), and oletypedata::pTypeInfo.
Referenced by Init_win32ole().
static VALUE foletype_visible (VALUE self) static
Definition at line 5760 of file win32ole.c.
References Data_Get_Struct, ole_type_visible(), and oletypedata::pTypeInfo.
Referenced by Init_win32ole().
static VALUE foletypelib_guid (VALUE self) static
Definition at line 5246 of file win32ole.c.
References FALSE, ole_wc2vstr(), oletypelib_get_libattr(), oletypelib_get_typelib(), oletypelibdata::pTypeLib, and Qnil.
Referenced by Init_win32ole().
static VALUE foletypelib_initialize (VALUE self, VALUE args) static
Definition at line 5197 of file win32ole.c.
References eWIN32OLERuntimeError, HRESULT(), ole_vstr2wc(), oletypelib_search_registry(), oletypelib_search_registry2(), oletypelib_set_member(), oletypelibdata::pTypeLib, Qfalse, Qnil, Qtrue, RARRAY_LEN, rb_ary_entry(), rb_eArgError, rb_raise(), S_OK, SafeStringValue, and StringValuePtr.
Referenced by Init_win32ole().
static VALUE foletypelib_inspect (VALUE self) static
Definition at line 5536 of file win32ole.c.
References default_inspect().
Referenced by Init_win32ole().
static VALUE foletypelib_library_name (VALUE self) static
Definition at line 5489 of file win32ole.c.
References eWIN32OLERuntimeError, HRESULT(), NULL, ole_raise(), oletypelib_get_typelib(), oletypelibdata::pTypeLib, Qnil, and WC2VSTR.
Referenced by Init_win32ole().
static VALUE foletypelib_major_version (VALUE self) static
Definition at line 5326 of file win32ole.c.
References INT2NUM, major, oletypelib_get_libattr(), oletypelib_get_typelib(), and oletypelibdata::pTypeLib.
Referenced by Init_win32ole().
static VALUE foletypelib_minor_version (VALUE self) static
Definition at line 5349 of file win32ole.c.
References INT2NUM, minor, oletypelib_get_libattr(), oletypelib_get_typelib(), and oletypelibdata::pTypeLib.
Referenced by Init_win32ole().
static VALUE foletypelib_name (VALUE self) static
Definition at line 5274 of file win32ole.c.
References eWIN32OLERuntimeError, HRESULT(), name, NULL, ole_raise(), oletypelib_get_typelib(), oletypelibdata::pTypeLib, rb_enc_str_new(), StringValuePtr, strlen(), and WC2VSTR.
Referenced by Init_win32ole().
static VALUE foletypelib_ole_types (VALUE self) static
Definition at line 5517 of file win32ole.c.
References NULL, ole_types_from_typelib(), oletypelib_get_typelib(), oletypelibdata::pTypeLib, and rb_ary_new().
Referenced by Init_win32ole().
static VALUE foletypelib_path (VALUE self) static
Definition at line 5420 of file win32ole.c.
References cWIN32OLE_lcid, eWIN32OLERuntimeError, HRESULT(), ole_raise(), oletypelib_get_libattr(), oletypelib_get_typelib(), oletypelibdata::pTypeLib, rb_enc_str_new(), S_OK, StringValuePtr, strlen(), and WC2VSTR.
Referenced by Init_win32ole().
static VALUE foletypelib_s_allocate (VALUE klass) static
Definition at line 5160 of file win32ole.c.
References Data_Make_Struct, NULL, ole_initialize(), oletypelib_free(), and oletypelibdata::pTypeLib.
Referenced by Init_win32ole().
static VALUE foletypelib_s_typelibs (VALUE self) static
Definition at line 4976 of file win32ole.c.
References cWIN32OLE_TYPELIB, err, HRESULT(), i, name, oletypelib_from_guid(), oletypelib_set_member(), oletypelibdata::pTypeLib, Qnil, rb_ary_new(), rb_ary_push(), rb_funcall(), rb_intern, reg_enum_key(), reg_get_val2(), reg_open_key(), reg_open_vkey(), StringValuePtr, and version().
Referenced by Init_win32ole().
static VALUE foletypelib_version (VALUE self) static
Definition at line 5301 of file win32ole.c.
References INT2NUM, major, make_version_str(), minor, oletypelib_get_libattr(), oletypelib_get_typelib(), oletypelibdata::pTypeLib, and rb_Float().
Referenced by Init_win32ole().
static VALUE foletypelib_visible (VALUE self) static
Definition at line 5460 of file win32ole.c.
References NULL, oletypelib_get_libattr(), oletypelib_get_typelib(), oletypelibdata::pTypeLib, Qfalse, and Qtrue.
Referenced by Init_win32ole().
static VALUE folevariable_inspect (VALUE self) static
Definition at line 6513 of file win32ole.c.
References make_inspect(), rb_funcall(), rb_intern, rb_str_cat2(), and rb_str_concat().
Referenced by Init_win32ole().
static VALUE folevariable_name (VALUE self) static
Definition at line 6238 of file win32ole.c.
References rb_intern, and rb_ivar_get().
Referenced by Init_win32ole().
static VALUE folevariable_ole_type (VALUE self) static
Definition at line 6278 of file win32ole.c.
References Data_Get_Struct, olevariabledata::index, ole_variable_ole_type(), and olevariabledata::pTypeInfo.
Referenced by Init_win32ole().
static VALUE folevariable_ole_type_detail (VALUE self) static
Definition at line 6312 of file win32ole.c.
References Data_Get_Struct, olevariabledata::index, ole_variable_ole_type_detail(), and olevariabledata::pTypeInfo.
Referenced by Init_win32ole().
static VALUE folevariable_value (VALUE self) static
Definition at line 6356 of file win32ole.c.
References Data_Get_Struct, olevariabledata::index, ole_variable_value(), and olevariabledata::pTypeInfo.
Referenced by Init_win32ole().
static VALUE folevariable_variable_kind (VALUE self) static
Definition at line 6458 of file win32ole.c.
References Data_Get_Struct, olevariabledata::index, ole_variable_kind(), and olevariabledata::pTypeInfo.
Referenced by Init_win32ole().
static VALUE folevariable_varkind (VALUE self) static
Definition at line 6498 of file win32ole.c.
References Data_Get_Struct, olevariabledata::index, ole_variable_varkind(), and olevariabledata::pTypeInfo.
Referenced by Init_win32ole().
static VALUE folevariable_visible (VALUE self) static
Definition at line 6402 of file win32ole.c.
References Data_Get_Struct, olevariabledata::index, ole_variable_visible(), and olevariabledata::pTypeInfo.
Referenced by Init_win32ole().
static VALUE folevariant_ary_aref (int argc, VALUE * argv, VALUE self) static
Definition at line 8863 of file win32ole.c.
References ary2safe_array_index(), Data_Get_Struct, eWIN32OLERuntimeError, free(), get_locked_safe_array(), HRESULT(), NULL, ole_raise(), ole_variant2val(), Qnil, rb_raise(), unlock_safe_array(), val, and olevariantdata::var.
Referenced by Init_win32ole().
static VALUE folevariant_ary_aset (int argc, VALUE * argv, VALUE self) static
Definition at line 8943 of file win32ole.c.
References ary2safe_array_index(), Data_Get_Struct, eWIN32OLERuntimeError, free(), get_locked_safe_array(), HRESULT(), NULL, ole_raise(), rb_eRuntimeError, rb_raise(), unlock_safe_array(), val2variant_ptr(), and olevariantdata::var.
Referenced by Init_win32ole().
static VALUE folevariant_initialize (VALUE self, VALUE args) static
Definition at line 8744 of file win32ole.c.
References cWIN32OLE, cWIN32OLE_VARIANT, Data_Get_Struct, NUM2INT, ole_val2olevariantdata(), ole_val2variant(), RARRAY_LEN, rb_ary_entry(), rb_cTime, rb_eArgError, rb_eTypeError, rb_obj_classname(), rb_obj_is_kind_of(), rb_raise(), T_ARRAY, T_BIGNUM, T_FALSE, T_FIXNUM, T_FLOAT, T_NIL, T_STRING, T_TRUE, TYPE, val, and olevariantdata::var.
Referenced by Init_win32ole().
static VALUE folevariant_s_allocate (VALUE klass) static
Definition at line 8648 of file win32ole.c.
References Data_Make_Struct, ole_initialize(), olevariant_free(), olevariantdata::realvar, and olevariantdata::var.
Referenced by folevariant_s_array(), and Init_win32ole().
static VALUE folevariant_s_array (VALUE klass, VALUE dims, VALUE vvt) static
Definition at line 8676 of file win32ole.c.
References ALLOC_N, Check_Type, Data_Get_Struct, FIX2INT, folevariant_s_allocate(), free(), i, NULL, NUM2UINT, ole_initialize(), Qnil, RARRAY_LEN, rb_ary_entry(), rb_eRuntimeError, rb_raise(), olevariantdata::realvar, T_ARRAY, and olevariantdata::var.
Referenced by Init_win32ole().
static VALUE folevariant_set_value (VALUE self, VALUE val) static
Definition at line 9053 of file win32ole.c.
References Data_Get_Struct, eWIN32OLERuntimeError, ole_val2olevariantdata(), Qnil, rb_raise(), T_STRING, TYPE, and olevariantdata::var.
Referenced by Init_win32ole().
static VALUE folevariant_value (VALUE self) static
Definition at line 8992 of file win32ole.c.
References Data_Get_Struct, ole_variant2val(), Qnil, rb_funcall(), rb_intern, rb_str_new2, val, and olevariantdata::var.
Referenced by Init_win32ole().
static VALUE folevariant_vartype (VALUE self) static
Definition at line 9031 of file win32ole.c.
References Data_Get_Struct, INT2FIX, and olevariantdata::var.
Referenced by Init_win32ole().
for ()
Definition at line 788 of file win32ole.c.
References i, and ole_variant2val().
Referenced by glob_helper(), objspace_each_objects(), and parse_char_class().
free (psz)
Referenced by aligned_free(), ary_new_dim(), check_if_dir(), cmdglob(), dln_find_exe_r(), do_spawn(), EVENTSINK_Destructor(), exit_handler(), fgdbm_clear(), fgdbm_empty_p(), fgdbm_length(), fgdbm_values(), filename_completion_proc_call(), find_iid(), fitpair(), folevariant_ary_aref(), folevariant_ary_aset(), folevariant_s_array(), free_invoke_arguments(), free_stack_chunks(), freeaddrinfo(), get_addr(), get_name(), getaddrinfo(), init_heap(), Init_readline(), ip_invoke_core(), ip_ruby_cmd_receiver_const_get(), link(), Messaging_HandleMessage(), nsdr(), ole_const_load(), ole_event_free(), ole_excepinfo2msg(), ole_free(), ole_val_ary2variant_ary(), ole_variant2val(), ole_wc2vstr(), olemethod_free(), oleparam_free(), oletype_free(), oletypelib_free(), olevariable_free(), olevariant_free(), open_ifs_socket(), rb_gdbm_fetch(), rb_gdbm_firstkey(), rb_gdbm_nextkey(), rb_objspace_free(), rb_remove_history(), rb_vm_bugreport(), rb_w32_aspawn_flags(), rb_w32_closedir(), rb_w32_cmdvector(), rb_w32_free_environ(), rb_w32_getcwd(), rb_w32_getenv(), rb_w32_mkdir(), rb_w32_open(), rb_w32_opendir(), rb_w32_rename(), rb_w32_rmdir(), rb_w32_spawn(), rb_w32_stati64(), rb_w32_uchdir(), rb_w32_uchmod(), rb_w32_ugetenv(), rb_w32_ulink(), rb_w32_umkdir(), rb_w32_unlink(), rb_w32_uopen(), rb_w32_uopendir(), rb_w32_urename(), rb_w32_urmdir(), rb_w32_ustati64(), rb_w32_utime(), rb_w32_uunlink(), rb_w32_uutime(), readdir_internal(), readline_readline(), reg_get_val(), ruby_setenv(), sdbm_close(), sdbm_open(), sdbm_prep(), shrink_stack_chunk_cache(), sip_hash_free(), subst_free(), tcl_eval(), tcl_global_eval(), thread_free(), username_completion_proc_call(), vm_xfree(), and yaml_free().
static void free_enc2cp (void) static
Definition at line 9074 of file win32ole.c.
References st_free_table().
Referenced by Init_win32ole().
static SAFEARRAY * get_locked_safe_array (VALUE val) static
Definition at line 8792 of file win32ole.c.
References Data_Get_Struct, HRESULT(), NULL, ole_raise(), rb_eRuntimeError, rb_eTypeError, rb_raise(), and olevariantdata::var.
Referenced by folevariant_ary_aref(), and folevariant_ary_aset().
static void * get_ptr_of_variant (VARIANT * pvar) static
Definition at line 1411 of file win32ole.c.
References NULL, V_INT, and V_UINT.
Referenced by val2variant_ptr().
static VALUE hash2named_arg (VALUE pair, struct oleparam * pOp) static
Definition at line 3285 of file win32ole.c.
References oleparam::dp, i, key, ole_val2variant(), ole_vstr2wc(), oleparam::pNamedArgs, Qnil, rb_ary_entry(), rb_eTypeError, rb_raise(), rb_sym_to_s(), T_STRING, T_SYMBOL, and TYPE.
Referenced by ole_invoke().
static void hash2ptr_dispparams (VALUE hash, ITypeInfo * pTypeInfo, DISPID dispid, DISPPARAMS * pdispparams) static
Definition at line 7735 of file win32ole.c.
References ALLOCA_N, HRESULT(), i, INT2FIX, key, ole_val2ptr_variant(), Qnil, rb_hash_aref(), rb_str_intern(), val, and WC2VSTR.
Referenced by EVENTSINK_Invoke().
static VALUE hash2result (VALUE hash) static
Definition at line 7764 of file win32ole.c.
References Qnil, rb_hash_aref(), rb_str_intern(), and rb_str_new2.
Referenced by EVENTSINK_Invoke().
typedef HRESULT (STDAPICALLTYPE FNCOCREATEINSTANCEEX)
Referenced by clsid_from_remote(), ev_advise(), EVENTSINK_Invoke(), find_coclass(), find_default_source(), find_default_source_from_typeinfo(), find_iid(), fole_activex_initialize(), fole_each(), fole_initialize(), fole_method_help(), fole_query_interface(), fole_respond_to(), fole_s_connect(), fole_s_const_load(), fole_s_create_guid(), fole_type(), fole_typelib(), folemethod_event_interface(), foletype_initialize(), foletypelib_initialize(), foletypelib_library_name(), foletypelib_name(), foletypelib_path(), foletypelib_s_typelibs(), folevariant_ary_aref(), folevariant_ary_aset(), get_locked_safe_array(), hash2ptr_dispparams(), ole_bind_obj(), ole_const_load(), ole_create_dcom(), ole_docinfo_from_type(), ole_initialize(), ole_invoke(), ole_invoke2(), ole_mb2wc(), ole_method_dispid(), ole_method_docinfo_from_type(), ole_method_event(), ole_method_helpcontext(), ole_method_helpfile(), ole_method_helpstring(), ole_method_invkind(), ole_method_offset_vtbl(), ole_method_params(), ole_method_return_type(), ole_method_return_type_detail(), ole_method_return_vtype(), ole_method_size_opt_params(), ole_method_size_params(), ole_method_sub(), ole_method_visible(), ole_methods(), ole_methods_from_typeinfo(), ole_methods_sub(), ole_ole_type(), ole_param_default(), ole_param_flag_mask(), ole_param_ole_type(), ole_param_ole_type_detail(), ole_propertyput(), ole_set_safe_array(), ole_type_from_itypeinfo(), ole_type_guid(), ole_type_helpcontext(), ole_type_helpfile(), ole_type_helpstring(), ole_type_impl_ole_types(), ole_type_major_version(), ole_type_minor_version(), ole_type_progid(), ole_type_src_type(), ole_type_typekind(), ole_type_visible(), ole_typelib_from_itypeinfo(), ole_types_from_typelib(), ole_usertype2val(), ole_val2olevariantdata(), ole_val_ary2variant_ary(), ole_variable_kind(), ole_variable_ole_type(), ole_variable_ole_type_detail(), ole_variable_value(), ole_variable_varkind(), ole_variable_visible(), ole_variables(), ole_variant2val(), ole_vstr2wc(), ole_wc2mb(), oleclass_from_typelib(), olemethod_from_typeinfo(), oleparam_ole_param_from_index(), oletypelib_from_guid(), oletypelib_get_libattr(), oletypelib_search_registry(), oletypelib_search_registry2(), typeinfo_from_ole(), unlock_safe_array(), and val2variant_ptr().
static HRESULT (STDMETHODCALLTYPE QueryInterface) static
if (dispIdMember = = DISPID_VALUE)
Definition at line 791 of file win32ole.c.
References rb_intern.
static void init_enc2cp (void) static
Definition at line 9068 of file win32ole.c.
References st_init_numtable().
Referenced by Init_win32ole().
void Init_win32ole (void)
Definition at line 9080 of file win32ole.c.
References ary_ole_event, com_hash, com_vtbl, cWIN32OLE, cWIN32OLE_EVENT, cWIN32OLE_METHOD, cWIN32OLE_PARAM, cWIN32OLE_TYPE, cWIN32OLE_TYPELIB, cWIN32OLE_VARIABLE, cWIN32OLE_VARIANT, Data_Wrap_Struct, eWIN32OLERuntimeError, fev_get_handler(), fev_initialize(), fev_off_event(), fev_on_event(), fev_on_event_with_outargs(), fev_s_allocate(), fev_s_msg_loop(), fev_set_handler(), fev_unadvise(), fole_activex_initialize(), fole_each(), fole_free(), fole_func_methods(), fole_get_methods(), fole_getproperty2(), fole_getproperty_with_bracket(), fole_initialize(), fole_invoke(), fole_invoke2(), fole_method_help(), fole_methods(), fole_missing(), fole_put_methods(), fole_query_interface(), fole_respond_to(), fole_s_allocate(), fole_s_connect(), fole_s_const_load(), fole_s_create_guid(), fole_s_free(), fole_s_get_code_page(), fole_s_get_locale(), fole_s_ole_initialize(), fole_s_ole_uninitialize(), fole_s_reference_count(), fole_s_set_code_page(), fole_s_set_locale(), fole_s_show_help(), fole_setproperty(), fole_setproperty2(), fole_setproperty_with_bracket(), fole_type(), fole_typelib(), folemethod_dispid(), folemethod_event(), folemethod_event_interface(), folemethod_helpcontext(), folemethod_helpfile(), folemethod_helpstring(), folemethod_initialize(), folemethod_inspect(), folemethod_invkind(), folemethod_invoke_kind(), folemethod_name(), folemethod_offset_vtbl(), folemethod_params(), folemethod_return_type(), folemethod_return_type_detail(), folemethod_return_vtype(), folemethod_s_allocate(), folemethod_size_opt_params(), folemethod_size_params(), folemethod_visible(), foleparam_default(), foleparam_initialize(), foleparam_input(), foleparam_inspect(), foleparam_name(), foleparam_ole_type(), foleparam_ole_type_detail(), foleparam_optional(), foleparam_output(), foleparam_retval(), foleparam_s_allocate(), foletype_default_event_sources(), foletype_default_ole_types(), foletype_guid(), foletype_helpcontext(), foletype_helpfile(), foletype_helpstring(), foletype_impl_ole_types(), foletype_initialize(), foletype_inspect(), foletype_major_version(), foletype_methods(), foletype_minor_version(), foletype_name(), foletype_ole_type(), foletype_ole_typelib(), foletype_progid(), foletype_s_allocate(), foletype_s_ole_classes(), foletype_s_progids(), foletype_s_typelibs(), foletype_source_ole_types(), foletype_src_type(), foletype_typekind(), foletype_variables(), foletype_visible(), foletypelib_guid(), foletypelib_initialize(), foletypelib_inspect(), foletypelib_library_name(), foletypelib_major_version(), foletypelib_minor_version(), foletypelib_name(), foletypelib_ole_types(), foletypelib_path(), foletypelib_s_allocate(), foletypelib_s_typelibs(), foletypelib_version(), foletypelib_visible(), folevariable_inspect(), folevariable_name(), folevariable_ole_type(), folevariable_ole_type_detail(), folevariable_value(), folevariable_variable_kind(), folevariable_varkind(), folevariable_visible(), folevariant_ary_aref(), folevariant_ary_aset(), folevariant_initialize(), folevariant_s_allocate(), folevariant_s_array(), folevariant_set_value(), folevariant_value(), folevariant_vartype(), free_enc2cp(), g_ole_initialized_init, id_events, init_enc2cp(), INT2FIX, message_filter, mWIN32OLE_VARIANT, ole_init_cp(), Qnil, rb_ary_new(), rb_cData, rb_cObject, rb_define_alias(), rb_define_alloc_func(), rb_define_class(), rb_define_const(), rb_define_method(), rb_define_module_under(), rb_define_singleton_method(), rb_eRuntimeError, rb_funcall(), rb_gc_register_mark_object(), rb_intern, rb_mark_hash(), rb_str_new2, st_free_table(), st_init_numtable(), and WIN32OLE_VERSION.
static BOOL CALLBACK installed_code_page_proc (LPTSTR str) static
Definition at line 3024 of file win32ole.c.
References FALSE, g_cp_installed, g_cp_to_check, NULL, and TRUE.
Referenced by code_page_installed().
static BOOL CALLBACK installed_lcid_proc (LPTSTR str) static
Definition at line 3081 of file win32ole.c.
References FALSE, g_lcid_installed, g_lcid_to_check, and TRUE.
Referenced by lcid_installed().
static VALUE is_all_index_under (long * pid, long * pub, long dim) static
Definition at line 1480 of file win32ole.c.
References Qfalse, and Qtrue.
Referenced by ole_set_safe_array().
static BOOL lcid_installed (LCID lcid) static
Definition at line 3091 of file win32ole.c.
References FALSE, g_lcid_installed, g_lcid_to_check, installed_lcid_proc(), and snprintf.
Referenced by fole_s_set_locale().
static VALUE make_inspect (const char * class_name, VALUE detail) static
Definition at line 1991 of file win32ole.c.
References rb_str_cat2(), rb_str_concat(), and rb_str_new2.
Referenced by default_inspect(), foleparam_inspect(), and folevariable_inspect().
static VALUE make_version_str (VALUE major, VALUE minor) static
Definition at line 5020 of file win32ole.c.
References Qnil, rb_str_append(), rb_str_cat2(), and rb_String().
Referenced by foletypelib_version(), and oletypelib_search_registry2().
NORETURN (static void failed_load_conv51932void)
static VALUE ole_ary_m_entry (VALUE val, long * pid) static
Definition at line 1398 of file win32ole.c.
References Qnil, rb_ary_entry(), T_ARRAY, and TYPE.
Referenced by ole_set_safe_array().
static VALUE ole_bind_obj (VALUE moniker, int argc, VALUE * argv, VALUE self) static
Definition at line 2666 of file win32ole.c.
References create_win32ole_object(), eWIN32OLERuntimeError, HRESULT(), NULL, ole_initialize(), ole_raise(), OLE_RELEASE, ole_vstr2wc(), p, oledata::pDispatch, StringValuePtr, and ULONG().
Referenced by fole_s_connect().
static void ole_const_load (ITypeLib * pTypeLib, VALUE klass, VALUE self) static
Definition at line 2515 of file win32ole.c.
References count, free(), HRESULT(), id, NULL, OLE_GET_TYPEATTR, OLE_RELEASE, ole_variant2val(), ole_wc2mb(), rb_define_const(), rb_hash_aset(), rb_hash_new(), rb_intern, rb_is_const_id(), rb_str_new2, V_UNION1, and val.
Referenced by fole_s_const_load().
static rb_encoding * ole_cp2encoding (UINT cp) static
Definition at line 1013 of file win32ole.c.
References ALLOCA_N, buf, code_page_installed(), myCPINFOEX::CodePage, enc_name(), eWIN32OLERuntimeError, load_conv_function51932, NULL, rb_define_dummy_encoding(), rb_enc_find_index(), rb_enc_from_index(), rb_raise(), rb_sprintf(), and StringValueCStr.
Referenced by set_ole_codepage().
static VALUE ole_create_dcom (int argc, VALUE * argv, VALUE self) static
Definition at line 2616 of file win32ole.c.
References clsid_from_remote(), eWIN32OLERuntimeError, gCoCreateInstanceEx, gole32, HRESULT(), NULL, ole_raise(), ole_set_member(), ole_vstr2wc(), rb_eRuntimeError, rb_raise(), rb_scan_args(), and StringValuePtr.
Referenced by fole_initialize().
static void ole_delete_event (VALUE ary, VALUE ev) static
Definition at line 7725 of file win32ole.c.
References ole_search_event_at(), and rb_ary_delete_at().
Referenced by add_event_call_back(), and fev_off_event().
static HRESULT ole_docinfo_from_type (ITypeInfo * pTypeInfo, BSTR * name, BSTR * helpstr, DWORD * helpcontext, BSTR * helpfile) static
Definition at line 4544 of file win32ole.c.
References HRESULT(), i, and OLE_RELEASE.
Referenced by folemethod_event_interface(), ole_type_helpcontext(), ole_type_helpfile(), ole_type_helpstring(), and ole_usertype2val().
static VALUE ole_each_sub (VALUE pEnumV) static
Definition at line 3975 of file win32ole.c.
References NULL, ole_variant2val(), Qnil, rb_yield(), and S_OK.
Referenced by fole_each().
static UINT ole_encoding2cp (rb_encoding * enc) static
Definition at line 863 of file win32ole.c.
References ENC_MACHING_CP.
Referenced by ole_init_cp(), and ole_vstr2wc().
static void ole_event_free (struct oleeventdata * poleev) static
Definition at line 8260 of file win32ole.c.
References oleeventdata::dwCookie, free(), NULL, OLE_RELEASE, and oleeventdata::pConnectionPoint.
Referenced by fev_s_allocate().
static VALUE ole_excepinfo2msg (EXCEPINFO * pExInfo) static
Definition at line 1151 of file win32ole.c.
References free(), NULL, ole_freeexceptinfo(), ole_wc2mb(), rb_str_cat(), rb_str_cat2(), rb_str_new2, and strlen().
Referenced by ole_invoke(), ole_invoke2(), and ole_propertyput().
static void ole_free (struct oledata * pole) static
Definition at line 1260 of file win32ole.c.
References free(), OLE_FREE, and oledata::pDispatch.
Referenced by fole_s_allocate().
static void ole_freeexceptinfo (EXCEPINFO * pExInfo) static
Definition at line 1143 of file win32ole.c.
Referenced by ole_excepinfo2msg(), and ole_invoke().
static VALUE ole_hresult2msg (HRESULT hr) static
Definition at line 1103 of file win32ole.c.
References cWIN32OLE_lcid, msg, NULL, Qnil, rb_str_cat2(), rb_str_new2, and strlen().
Referenced by ole_raise().
static VALUE ole_ienum_free (VALUE pEnumV) static
Definition at line 3991 of file win32ole.c.
References OLE_RELEASE, and Qnil.
Referenced by fole_each().
static UINT ole_init_cp (void) static
Definition at line 990 of file win32ole.c.
References ole_encoding2cp(), rb_default_external_encoding(), rb_default_internal_encoding(), and set_ole_codepage().
Referenced by Init_win32ole().
static void ole_initialize (void) static
Definition at line 1226 of file win32ole.c.
References FALSE, g_ole_initialized, g_ole_initialized_set, g_uninitialize_hooked, HRESULT(), imessage_filter, NULL, ole_raise(), ole_uninitialize_hook(), previous_filter, Qnil, rb_add_event_hook(), rb_eRuntimeError, RUBY_EVENT_THREAD_END, and TRUE.
Referenced by fole_s_allocate(), fole_s_connect(), fole_s_ole_initialize(), foletype_s_allocate(), foletypelib_s_allocate(), folevariant_s_allocate(), folevariant_s_array(), and ole_bind_obj().
static VALUE ole_invoke (int argc, VALUE * argv, VALUE self, USHORT wFlags, BOOL is_bracket) static
Definition at line 3337 of file win32ole.c.
References ALLOCA_N, cWIN32OLE_lcid, cWIN32OLE_VARIANT, Data_Get_Struct, oleparam::dp, eWIN32OLERuntimeError, hash2named_arg(), HRESULT(), i, NULL, NUM2INT, ole_excepinfo2msg(), ole_freeexceptinfo(), ole_raise(), ole_val2variant(), ole_val2variant2(), ole_variant2val(), ole_vstr2wc(), OLEData_Get_Struct, param, oledata::pDispatch, oleparam::pNamedArgs, rb_ary_entry(), rb_ary_unshift(), rb_block_call(), rb_eNoMethodError, rb_eRuntimeError, rb_eTypeError, rb_funcall(), rb_intern, rb_obj_is_kind_of(), rb_raise(), rb_scan_args(), rb_sym_to_s(), result, set_argv(), StringValuePtr, T_HASH, T_STRING, T_SYMBOL, TYPE, v, and olevariantdata::var.
Referenced by fole_getproperty_with_bracket(), fole_invoke(), fole_missing(), fole_setproperty(), and fole_setproperty_with_bracket().
static VALUE ole_invoke2 (VALUE self, VALUE dispid, VALUE args, VALUE types, USHORT dispkind) static
Definition at line 3589 of file win32ole.c.
References ALLOCA_N, Check_Type, cWIN32OLE_lcid, eWIN32OLERuntimeError, FIX2INT, HRESULT(), i, NULL, NUM2INT, ole_excepinfo2msg(), ole_raise(), ole_val2variant(), ole_variant2val(), OLEData_Get_Struct, param, oledata::pDispatch, Qnil, RARRAY_LEN, rb_ary_entry(), rb_eTypeError, rb_raise(), result, S_OK, set_argv(), StringValuePtr, T_ARRAY, and v.
Referenced by fole_getproperty2(), fole_invoke2(), and fole_setproperty2().
static LPWSTR ole_mb2wc (char * pm, int len) static
Definition at line 1357 of file win32ole.c.
References conv_51932, cWIN32OLE_cp, eWIN32OLERuntimeError, HRESULT(), NULL, ole_raise(), pIMultiLanguage, and size.
Referenced by clsid_from_remote().
static VALUE ole_method_dispid (ITypeInfo * pTypeInfo, UINT method_index) static
Definition at line 7039 of file win32ole.c.
References HRESULT(), INT2NUM, and Qnil.
Referenced by folemethod_dispid().
static VALUE ole_method_docinfo_from_type (ITypeInfo * pTypeInfo, UINT method_index, BSTR * name, BSTR * helpstr, DWORD * helpcontext, BSTR * helpfile) static
Definition at line 6926 of file win32ole.c.
References HRESULT().
Referenced by ole_method_helpcontext(), ole_method_helpfile(), and ole_method_helpstring().
static VALUE ole_method_event (ITypeInfo * pTypeInfo, UINT method_index, VALUE method_name) static
Definition at line 6816 of file win32ole.c.
References HRESULT(), i, name, NULL, OLE_GET_TYPEATTR, OLE_RELEASE, OLE_RELEASE_TYPEATTR, Qfalse, Qtrue, rb_str_cmp(), and WC2VSTR.
Referenced by folemethod_event().
static VALUE ole_method_helpcontext (ITypeInfo * pTypeInfo, UINT method_index) static
Definition at line 7010 of file win32ole.c.
References HRESULT(), INT2FIX, NULL, ole_method_docinfo_from_type(), and Qnil.
Referenced by folemethod_helpcontext().
static VALUE ole_method_helpfile (ITypeInfo * pTypeInfo, UINT method_index) static
Definition at line 6979 of file win32ole.c.
References HRESULT(), NULL, ole_method_docinfo_from_type(), Qnil, and WC2VSTR.
Referenced by folemethod_helpfile().
static VALUE ole_method_helpstring (ITypeInfo * pTypeInfo, UINT method_index) static
Definition at line 6948 of file win32ole.c.
References HRESULT(), NULL, ole_method_docinfo_from_type(), Qnil, and WC2VSTR.
Referenced by folemethod_helpstring().
static VALUE ole_method_invkind (ITypeInfo * pTypeInfo, UINT method_index) static
Definition at line 6708 of file win32ole.c.
References eWIN32OLERuntimeError, HRESULT(), INT2FIX, and ole_raise().
Referenced by folemethod_invkind(), and ole_method_invoke_kind().
static VALUE ole_method_invoke_kind (ITypeInfo * pTypeInfo, UINT method_index) static
Definition at line 6722 of file win32ole.c.
References FIX2INT, ole_method_invkind(), rb_str_new2, and type.
Referenced by folemethod_invoke_kind().
static VALUE ole_method_offset_vtbl (ITypeInfo * pTypeInfo, UINT method_index) static
Definition at line 7070 of file win32ole.c.
References HRESULT(), INT2FIX, and Qnil.
Referenced by folemethod_offset_vtbl().
static VALUE ole_method_params (ITypeInfo * pTypeInfo, UINT method_index) static
Definition at line 7164 of file win32ole.c.
References ALLOCA_N, cWIN32OLE_PARAM, Data_Make_Struct, HRESULT(), i, oleparamdata::index, oleparamdata::method_index, OLE_ADDREF, oleparam_free(), param, oleparamdata::pTypeInfo, rb_ary_new(), rb_ary_push(), rb_intern, rb_ivar_set(), and WC2VSTR.
Referenced by folemethod_params().
static VALUE ole_method_return_type (ITypeInfo * pTypeInfo, UINT method_index) static
Definition at line 6606 of file win32ole.c.
References eWIN32OLERuntimeError, HRESULT(), ole_raise(), ole_typedesc2val(), Qnil, and type.
Referenced by folemethod_return_type().
static VALUE ole_method_return_type_detail (ITypeInfo * pTypeInfo, UINT method_index) static
Definition at line 6674 of file win32ole.c.
References HRESULT(), ole_typedesc2val(), rb_ary_new(), and type.
Referenced by folemethod_return_type_detail().
static VALUE ole_method_return_vtype (ITypeInfo * pTypeInfo, UINT method_index) static
Definition at line 6640 of file win32ole.c.
References eWIN32OLERuntimeError, HRESULT(), INT2FIX, and ole_raise().
Referenced by folemethod_return_vtype().
static VALUE ole_method_size_opt_params (ITypeInfo * pTypeInfo, UINT method_index) static
Definition at line 7133 of file win32ole.c.
References HRESULT(), INT2FIX, and Qnil.
Referenced by folemethod_size_opt_params().
static VALUE ole_method_size_params (ITypeInfo * pTypeInfo, UINT method_index) static
Definition at line 7101 of file win32ole.c.
References HRESULT(), INT2FIX, and Qnil.
Referenced by folemethod_size_params().
static VALUE ole_method_sub (VALUE self, ITypeInfo * pOwnerTypeInfo, ITypeInfo * pTypeInfo, VALUE name) static
Definition at line 4099 of file win32ole.c.
References eWIN32OLERuntimeError, HRESULT(), i, NULL, OLE_GET_TYPEATTR, ole_raise(), OLE_RELEASE_TYPEATTR, olemethod_set_member(), Qnil, strcasecmp, StringValuePtr, and WC2VSTR.
Referenced by olemethod_from_typeinfo().
static VALUE ole_method_visible (ITypeInfo * pTypeInfo, UINT method_index) static
Definition at line 6779 of file win32ole.c.
References HRESULT(), Qfalse, and Qtrue.
Referenced by folemethod_visible().
static VALUE ole_methods (VALUE self, int mask) static
Definition at line 4275 of file win32ole.c.
References HRESULT(), ole_methods_from_typeinfo(), OLE_RELEASE, OLEData_Get_Struct, rb_ary_concat(), rb_ary_new(), and typeinfo_from_ole().
Referenced by fole_func_methods(), fole_get_methods(), fole_methods(), and fole_put_methods().
static VALUE ole_methods_from_typeinfo (ITypeInfo * pTypeInfo, int mask) static
Definition at line 4205 of file win32ole.c.
References eWIN32OLERuntimeError, HRESULT(), i, OLE_GET_TYPEATTR, ole_methods_sub(), ole_raise(), OLE_RELEASE, OLE_RELEASE_TYPEATTR, and rb_ary_new().
Referenced by foletype_methods(), and ole_methods().
static VALUE ole_methods_sub (ITypeInfo * pOwnerTypeInfo, ITypeInfo * pTypeInfo, VALUE methods, int mask) static
Definition at line 4167 of file win32ole.c.
References cWIN32OLE_METHOD, eWIN32OLERuntimeError, folemethod_s_allocate(), HRESULT(), i, NULL, OLE_GET_TYPEATTR, ole_raise(), OLE_RELEASE_TYPEATTR, olemethod_set_member(), rb_ary_push(), and WC2VSTR.
Referenced by ole_methods_from_typeinfo().
static void ole_msg_loop (void) static
Definition at line 1251 of file win32ole.c.
References msg, and NULL.
Referenced by fev_s_msg_loop(), and fev_unadvise().
static VALUE ole_ole_type (ITypeInfo * pTypeInfo) static
Definition at line 5601 of file win32ole.c.
References HRESULT(), OLE_GET_TYPEATTR, OLE_RELEASE_TYPEATTR, Qnil, rb_str_new2, and type.
Referenced by foletype_ole_type().
static VALUE ole_param_default (ITypeInfo * pTypeInfo, UINT method_index, UINT index) static
Definition at line 7494 of file win32ole.c.
References HRESULT(), oleparamdata::index, ole_variant2val(), Qnil, and V_UNION1.
Referenced by foleparam_default().
static VALUE ole_param_flag_mask (ITypeInfo * pTypeInfo, UINT method_index, UINT index, USHORT mask) static
Definition at line 7397 of file win32ole.c.
References HRESULT(), Qfalse, Qtrue, and V_UNION1.
Referenced by foleparam_input(), foleparam_optional(), foleparam_output(), and foleparam_retval().
static VALUE ole_param_ole_type (ITypeInfo * pTypeInfo, UINT method_index, UINT index) static
Definition at line 7329 of file win32ole.c.
References HRESULT(), ole_typedesc2val(), Qnil, rb_str_new2, and type.
Referenced by foleparam_ole_type().
static VALUE ole_param_ole_type_detail (ITypeInfo * pTypeInfo, UINT method_index, UINT index) static
Definition at line 7363 of file win32ole.c.
References HRESULT(), ole_typedesc2val(), and rb_ary_new().
Referenced by foleparam_ole_type_detail().
static VALUE ole_propertyput (VALUE self, VALUE property, VALUE value) static
Definition at line 3898 of file win32ole.c.
References cWIN32OLE_lcid, eWIN32OLERuntimeError, HRESULT(), NULL, ole_excepinfo2msg(), ole_raise(), ole_val2variant(), ole_vstr2wc(), OLEData_Get_Struct, oledata::pDispatch, Qnil, StringValuePtr, and v.
Referenced by fole_missing().
static VALUE ole_ptrtype2val (ITypeInfo * pTypeInfo, TYPEDESC * pTypeDesc, VALUE typedetails) static
Definition at line 4592 of file win32ole.c.
References ole_typedesc2val(), rb_str_new2, type, and V_UNION1.
Referenced by ole_typedesc2val().
static void ole_raise (HRESULT hr, VALUE ecs, const char * fmt, ...) static
Definition at line 1193 of file win32ole.c.
References args, buf, ole_hresult2msg(), Qnil, rb_raise(), StringValuePtr, va_init_list, and vsnprintf.
Referenced by ev_advise(), fole_activex_initialize(), fole_each(), fole_initialize(), fole_method_help(), fole_query_interface(), fole_s_connect(), fole_s_const_load(), fole_s_create_guid(), fole_type(), fole_typelib(), foletype_initialize(), foletypelib_library_name(), foletypelib_name(), foletypelib_path(), folevariant_ary_aref(), folevariant_ary_aset(), get_locked_safe_array(), ole_bind_obj(), ole_create_dcom(), ole_initialize(), ole_invoke(), ole_invoke2(), ole_mb2wc(), ole_method_invkind(), ole_method_return_type(), ole_method_return_vtype(), ole_method_sub(), ole_methods_from_typeinfo(), ole_methods_sub(), ole_propertyput(), ole_set_safe_array(), ole_type_major_version(), ole_type_minor_version(), ole_type_typekind(), ole_val2olevariantdata(), ole_variable_ole_type(), ole_variable_ole_type_detail(), ole_variables(), ole_vstr2wc(), ole_wc2mb(), olemethod_from_typeinfo(), oleparam_ole_param_from_index(), oletypelib_get_libattr(), typeinfo_from_ole(), unlock_safe_array(), and val2variant_ptr().
static VALUE ole_search_event (VALUE ary, VALUE ev, BOOL * is_default) static
Definition at line 7683 of file win32ole.c.
References FALSE, i, NIL_P, Qnil, RARRAY_LEN, rb_ary_entry(), rb_str_cmp(), and TRUE.
Referenced by EVENTSINK_Invoke().
static long ole_search_event_at (VALUE ary, VALUE ev) static
Definition at line 7658 of file win32ole.c.
References i, NIL_P, RARRAY_LEN, rb_ary_entry(), rb_str_cmp(), T_STRING, and TYPE.
Referenced by ole_delete_event().
static VALUE ole_search_handler_method (VALUE handler, VALUE ev, BOOL * is_default_handler) static
Definition at line 7707 of file win32ole.c.
References FALSE, Qnil, rb_intern, rb_respond_to(), rb_sprintf(), rb_to_id(), StringValuePtr, and TRUE.
Referenced by EVENTSINK_Invoke().
static void ole_set_byref (VARIANT * realvar, VARIANT * var, VARTYPE vt) static
Definition at line 1799 of file win32ole.c.
References eWIN32OLERuntimeError, rb_raise(), olevariantdata::realvar, V_I1REF, V_INT, V_INTREF, V_UI2REF, V_UINT, and V_UINTREF.
Referenced by ole_val2olevariantdata().
static VALUE ole_set_member (VALUE self, IDispatch * dispatch) static
Definition at line 2010 of file win32ole.c.
References Data_Get_Struct, NULL, OLE_RELEASE, and oledata::pDispatch.
Referenced by create_win32ole_object(), fole_initialize(), and ole_create_dcom().
static void ole_set_safe_array (long n, SAFEARRAY * psa, long * pid, long * pub, VALUE val, long dim, VARTYPE vt) static
Definition at line 1492 of file win32ole.c.
References eWIN32OLERuntimeError, HRESULT(), i, is_all_index_under(), NULL, ole_ary_m_entry(), ole_raise(), Qtrue, rb_eRuntimeError, rb_raise(), S_OK, and val2variant_ptr().
Referenced by ole_val_ary2variant_ary().
static HWND ole_show_help (VALUE helpfile, VALUE helpcontext) static
Definition at line 2947 of file win32ole.c.
References ghhctrl, NUM2INT, and StringValuePtr.
Referenced by fole_s_show_help().
static VALUE ole_type_from_itypeinfo (ITypeInfo * pTypeInfo) static
Definition at line 4360 of file win32ole.c.
References cWIN32OLE_TYPE, foletype_s_allocate(), HRESULT(), NULL, OLE_RELEASE, oletype_set_member(), Qnil, type, and WC2VSTR.
Referenced by fole_type(), and ole_type_impl_ole_types().
static VALUE ole_type_guid (ITypeInfo * pTypeInfo) static
Definition at line 5663 of file win32ole.c.
References FALSE, HRESULT(), OLE_GET_TYPEATTR, OLE_RELEASE_TYPEATTR, ole_wc2vstr(), and Qnil.
Referenced by foletype_guid().
static VALUE ole_type_helpcontext (ITypeInfo * pTypeInfo) static
Definition at line 5951 of file win32ole.c.
References HRESULT(), INT2FIX, NULL, ole_docinfo_from_type(), and Qnil.
Referenced by foletype_helpcontext().
static VALUE ole_type_helpfile (ITypeInfo * pTypeInfo) static
Definition at line 5922 of file win32ole.c.
References HRESULT(), NULL, ole_docinfo_from_type(), Qnil, and WC2VSTR.
Referenced by foletype_helpfile().
static VALUE ole_type_helpstring (ITypeInfo * pTypeInfo) static
Definition at line 5859 of file win32ole.c.
References HRESULT(), NULL, ole_docinfo_from_type(), Qnil, and WC2VSTR.
Referenced by foletype_helpstring().
static VALUE ole_type_impl_ole_types (ITypeInfo * pTypeInfo, int implflags) static
Definition at line 5996 of file win32ole.c.
References HRESULT(), i, OLE_GET_TYPEATTR, OLE_RELEASE, OLE_RELEASE_TYPEATTR, ole_type_from_itypeinfo(), Qnil, rb_ary_new(), rb_ary_push(), and type.
Referenced by foletype_default_event_sources(), foletype_default_ole_types(), foletype_impl_ole_types(), and foletype_source_ole_types().
static VALUE ole_type_major_version (ITypeInfo * pTypeInfo) static
Definition at line 5768 of file win32ole.c.
References eWIN32OLERuntimeError, HRESULT(), INT2FIX, OLE_GET_TYPEATTR, ole_raise(), and OLE_RELEASE_TYPEATTR.
Referenced by foletype_major_version().
static VALUE ole_type_minor_version (ITypeInfo * pTypeInfo) static
Definition at line 5798 of file win32ole.c.
References eWIN32OLERuntimeError, HRESULT(), INT2FIX, OLE_GET_TYPEATTR, ole_raise(), and OLE_RELEASE_TYPEATTR.
Referenced by foletype_minor_version().
static VALUE ole_type_progid (ITypeInfo * pTypeInfo) static
Definition at line 5698 of file win32ole.c.
References FALSE, HRESULT(), OLE_GET_TYPEATTR, OLE_RELEASE_TYPEATTR, ole_wc2vstr(), and Qnil.
Referenced by foletype_progid().
static VALUE ole_type_src_type (ITypeInfo * pTypeInfo) static
Definition at line 5887 of file win32ole.c.
References alias, HRESULT(), OLE_GET_TYPEATTR, OLE_RELEASE_TYPEATTR, ole_typedesc2val(), and Qnil.
Referenced by foletype_src_type().
static VALUE ole_type_typekind (ITypeInfo * pTypeInfo) static
Definition at line 5828 of file win32ole.c.
References eWIN32OLERuntimeError, HRESULT(), INT2FIX, OLE_GET_TYPEATTR, ole_raise(), and OLE_RELEASE_TYPEATTR.
Referenced by foletype_typekind().
static VALUE ole_type_visible (ITypeInfo * pTypeInfo) static
Definition at line 5734 of file win32ole.c.
References HRESULT(), OLE_GET_TYPEATTR, OLE_RELEASE_TYPEATTR, Qfalse, and Qtrue.
Referenced by foletype_visible().
static VALUE ole_typedesc2val (ITypeInfo * pTypeInfo, TYPEDESC * pTypeDesc, VALUE typedetails) static
Definition at line 4605 of file win32ole.c.
References INT2FIX, ole_ptrtype2val(), ole_usertype2val(), Qnil, rb_ary_push(), rb_fix2str(), rb_str_concat(), and rb_str_new2.
Referenced by ole_method_return_type(), ole_method_return_type_detail(), ole_param_ole_type(), ole_param_ole_type_detail(), ole_ptrtype2val(), ole_type_src_type(), ole_variable_ole_type(), and ole_variable_ole_type_detail().
static VALUE ole_typelib_from_itypeinfo (ITypeInfo * pTypeInfo) static
Definition at line 4416 of file win32ole.c.
References cWIN32OLE_TYPELIB, HRESULT(), oletypelib_set_member(), Qnil, rb_funcall(), and rb_intern.
Referenced by fole_typelib(), and foletype_ole_typelib().
static VALUE ole_types_from_typelib (ITypeLib * pTypeLib, VALUE classes) static
Definition at line 2865 of file win32ole.c.
References count, cWIN32OLE_TYPE, foletype_s_allocate(), HRESULT(), i, NULL, OLE_RELEASE, oletype_set_member(), rb_ary_push(), rb_secure(), type, and WC2VSTR.
Referenced by foletypelib_ole_types().
void ole_uninitialize (void)
Definition at line 1212 of file win32ole.c.
References FALSE, g_ole_initialized, and g_ole_initialized_set.
Referenced by fole_s_ole_uninitialize(), and ole_uninitialize_hook().
static void ole_uninitialize_hook (rb_event_flag_t evflag, VALUE data, VALUE self, ID mid, VALUE klass) static
Definition at line 1220 of file win32ole.c.
References ole_uninitialize().
Referenced by ole_initialize().
static VALUE ole_usertype2val (ITypeInfo * pTypeInfo, TYPEDESC * pTypeDesc, VALUE typedetails) static
Definition at line 4567 of file win32ole.c.
References HRESULT(), NULL, ole_docinfo_from_type(), OLE_RELEASE, Qnil, rb_ary_push(), type, V_UNION1, and WC2VSTR.
Referenced by ole_typedesc2val().
static void ole_val2olevariantdata (VALUE val, VARTYPE vt, struct olevariantdata * pvar) static
Definition at line 1886 of file win32ole.c.
References cWIN32OLE_lcid, eWIN32OLERuntimeError, HRESULT(), NULL, ole_raise(), ole_set_byref(), ole_val2variant_ex(), ole_val_ary2variant_ary(), Qnil, rb_eRuntimeError, rb_raise(), olevariantdata::realvar, RSTRING_LEN, RSTRING_PTR, S_OK, T_STRING, TYPE, and olevariantdata::var.
Referenced by folevariant_initialize(), and folevariant_set_value().
static void ole_val2ptr_variant (VALUE val, VARIANT * var) static
Definition at line 1731 of file win32ole.c.
References NUM2CHR, NUM2DBL, NUM2INT, ole_vstr2wc(), rb_big2dbl(), T_BIGNUM, T_FALSE, T_FIXNUM, T_FLOAT, T_STRING, T_TRUE, and TYPE.
Referenced by ary2ptr_dispparams(), and hash2ptr_dispparams().
static void ole_val2variant (VALUE val, VARIANT * var) static
Definition at line 1630 of file win32ole.c.
References cWIN32OLE, cWIN32OLE_VARIANT, Data_Get_Struct, g_nil_to, NUM2DBL, NUM2INT, OLE_ADDREF, ole_val_ary2variant_ary(), ole_vstr2wc(), oledata::pDispatch, rb_big2dbl(), rb_cTime, rb_obj_is_kind_of(), rbtime2vtdate(), T_ARRAY, T_BIGNUM, T_FALSE, T_FIXNUM, T_FLOAT, T_NIL, T_STRING, T_TRUE, TYPE, val2dispatch(), and olevariantdata::var.
Referenced by EVENTSINK_Invoke(), folevariant_initialize(), hash2named_arg(), ole_invoke(), ole_invoke2(), ole_propertyput(), and ole_val2variant2().
ole_val2variant (v , pVarResult)
static void ole_val2variant2 (VALUE val, VARIANT * var) static
Definition at line 1983 of file win32ole.c.
References g_nil_to, and ole_val2variant().
Referenced by ole_invoke(), and ole_val2variant_ex().
static void ole_val2variant_ex (VALUE val, VARIANT * var, VARTYPE vt) static
Definition at line 1696 of file win32ole.c.
References NULL, NUM2I8, NUM2UI8, ole_val2variant2(), and Qnil.
Referenced by ole_val2olevariantdata(), and val2variant_ptr().
static HRESULT ole_val_ary2variant_ary (VALUE val, VARIANT * var, VARTYPE vt) static
Definition at line 1569 of file win32ole.c.
References ALLOC_N, ary_len_of_dim(), Check_Type, dimension(), free(), HRESULT(), i, NULL, ole_set_safe_array(), rb_eRuntimeError, rb_raise(), S_OK, and T_ARRAY.
Referenced by ole_val2olevariantdata(), and ole_val2variant().
static VALUE ole_variable_kind (ITypeInfo * pTypeInfo, UINT var_index) static
Definition at line 6410 of file win32ole.c.
References HRESULT(), and rb_str_new2.
Referenced by folevariable_variable_kind().
static VALUE ole_variable_ole_type (ITypeInfo * pTypeInfo, UINT var_index) static
Definition at line 6244 of file win32ole.c.
References eWIN32OLERuntimeError, HRESULT(), ole_raise(), ole_typedesc2val(), Qnil, and type.
Referenced by folevariable_ole_type().
static VALUE ole_variable_ole_type_detail (ITypeInfo * pTypeInfo, UINT var_index) static
Definition at line 6286 of file win32ole.c.
References eWIN32OLERuntimeError, HRESULT(), ole_raise(), ole_typedesc2val(), rb_ary_new(), and type.
Referenced by folevariable_ole_type_detail().
static VALUE ole_variable_value (ITypeInfo * pTypeInfo, UINT var_index) static
Definition at line 6320 of file win32ole.c.
References HRESULT(), ole_variant2val(), Qnil, V_UNION1, and val.
Referenced by folevariable_value().
static VALUE ole_variable_varkind (ITypeInfo * pTypeInfo, UINT var_index) static
Definition at line 6466 of file win32ole.c.
References HRESULT(), INT2FIX, and Qnil.
Referenced by folevariable_varkind().
static VALUE ole_variable_visible (ITypeInfo * pTypeInfo, UINT var_index) static
Definition at line 6364 of file win32ole.c.
References HRESULT(), Qfalse, and Qtrue.
Referenced by folevariable_visible().
static VALUE ole_variables (ITypeInfo * pTypeInfo) static
Definition at line 6122 of file win32ole.c.
References cWIN32OLE_VARIABLE, Data_Make_Struct, eWIN32OLERuntimeError, HRESULT(), i, olevariabledata::index, NULL, OLE_ADDREF, OLE_GET_TYPEATTR, ole_raise(), OLE_RELEASE_TYPEATTR, olevariable_free(), olevariabledata::pTypeInfo, rb_ary_new(), rb_ary_push(), rb_intern, rb_ivar_set(), and WC2VSTR.
Referenced by foletype_variables().
static VALUE ole_variant2val (VARIANT * pvar) static
Definition at line 2076 of file win32ole.c.
References ALLOC_N, ary_new_dim(), ary_store_dim(), create_win32ole_object(), cWIN32OLE, cWIN32OLE_lcid, FALSE, free(), HRESULT(), i, I8_2_NUM, INT2NUM, NULL, OLE_ADDREF, ole_wc2vstr(), p, oledata::pDispatch, Qfalse, Qnil, Qtrue, rb_ary_new(), rb_eRuntimeError, rb_float_new(), rb_raise(), UI8_2_NUM, V_I1REF, V_INT, V_INTREF, V_UI2REF, V_UINT, V_UINTREF, val, and vtdate2rbtime().
Referenced by EVENTSINK_Invoke(), folevariant_ary_aref(), folevariant_value(), for(), ole_const_load(), ole_each_sub(), ole_invoke(), ole_invoke2(), ole_param_default(), ole_variable_value(), and set_argv().
static LPWSTR ole_vstr2wc (VALUE vstr) static
Definition at line 1304 of file win32ole.c.
References code_page_installed(), conv_51932, eWIN32OLERuntimeError, HRESULT(), NULL, ole_encoding2cp(), ole_raise(), pIMultiLanguage, rb_enc_get(), rb_enc_name, rb_raise(), RSTRING_LEN, RSTRING_LENINT, RSTRING_PTR, size, st_insert(), and st_lookup().
Referenced by fole_initialize(), fole_query_interface(), fole_respond_to(), fole_s_connect(), fole_s_const_load(), foletype_initialize(), foletypelib_initialize(), hash2named_arg(), ole_bind_obj(), ole_create_dcom(), ole_invoke(), ole_propertyput(), ole_val2ptr_variant(), ole_val2variant(), and oletypelib_from_guid().
static char * ole_wc2mb (LPWSTR pw) static
Definition at line 1067 of file win32ole.c.
References ALLOC_N, conv_51932, cWIN32OLE_cp, eWIN32OLERuntimeError, HRESULT(), NULL, ole_raise(), pIMultiLanguage, and size.
Referenced by find_iid(), ole_const_load(), ole_excepinfo2msg(), and ole_wc2vstr().
static VALUE ole_wc2vstr (LPWSTR pw, BOOL isfree) static
Definition at line 1387 of file win32ole.c.
References free(), ole_wc2mb(), rb_enc_str_new(), and strlen().
Referenced by fole_s_create_guid(), foletypelib_guid(), ole_type_guid(), ole_type_progid(), and ole_variant2val().
static VALUE oleclass_from_typelib (VALUE self, ITypeLib * pTypeLib, VALUE oleclass) static
Definition at line 4900 of file win32ole.c.
References count, HRESULT(), i, NULL, OLE_RELEASE, oletype_set_member(), oletypedata::pTypeInfo, Qfalse, Qtrue, rb_str_cmp(), and WC2VSTR.
Referenced by foletype_initialize().
static void olemethod_free (struct olemethoddata * polemethod) static
Definition at line 1281 of file win32ole.c.
References free(), OLE_FREE, olemethoddata::pOwnerTypeInfo, and olemethoddata::pTypeInfo.
Referenced by folemethod_s_allocate().
static VALUE olemethod_from_typeinfo (VALUE self, ITypeInfo * pTypeInfo, VALUE name) static
Definition at line 4136 of file win32ole.c.
References eWIN32OLERuntimeError, HRESULT(), i, OLE_GET_TYPEATTR, ole_method_sub(), ole_raise(), OLE_RELEASE, OLE_RELEASE_TYPEATTR, and Qnil.
Referenced by fole_method_help(), and folemethod_initialize().
static VALUE olemethod_set_member (VALUE self, ITypeInfo * pTypeInfo, ITypeInfo * pOwnerTypeInfo, int index, VALUE name) static
Definition at line 6528 of file win32ole.c.
References Data_Get_Struct, olemethoddata::index, OLE_ADDREF, olemethoddata::pOwnerTypeInfo, olemethoddata::pTypeInfo, rb_intern, and rb_ivar_set().
Referenced by ole_method_sub(), and ole_methods_sub().
static void oleparam_free (struct oleparamdata * pole) static
Definition at line 1296 of file win32ole.c.
References free(), OLE_FREE, and oleparamdata::pTypeInfo.
Referenced by foleparam_s_allocate(), and ole_method_params().
static VALUE oleparam_ole_param (VALUE self, VALUE olemethod, int n) static
Definition at line 7295 of file win32ole.c.
References Data_Get_Struct, olemethoddata::index, oleparam_ole_param_from_index(), and olemethoddata::pTypeInfo.
Referenced by foleparam_initialize().
static VALUE oleparam_ole_param_from_index (VALUE self, ITypeInfo * pTypeInfo, UINT method_index, int param_index) static
Definition at line 7257 of file win32ole.c.
References ALLOCA_N, Data_Get_Struct, HRESULT(), oleparamdata::index, oleparamdata::method_index, OLE_ADDREF, ole_raise(), oleparamdata::pTypeInfo, rb_eIndexError, rb_eRuntimeError, rb_intern, rb_ivar_set(), rb_raise(), and WC2VSTR.
Referenced by oleparam_ole_param().
static void oletype_free (struct oletypedata * poletype) static
Definition at line 1274 of file win32ole.c.
References free(), OLE_FREE, and oletypedata::pTypeInfo.
Referenced by foletype_s_allocate().
static VALUE oletype_set_member (VALUE self, ITypeInfo * pTypeInfo, VALUE name) static
Definition at line 4889 of file win32ole.c.
References Data_Get_Struct, OLE_ADDREF, oletypedata::pTypeInfo, rb_intern, and rb_ivar_set().
Referenced by ole_type_from_itypeinfo(), ole_types_from_typelib(), and oleclass_from_typelib().
static void oletypelib_free (struct oletypelibdata * poletypelib) static
Definition at line 1267 of file win32ole.c.
References free(), OLE_FREE, and oletypelibdata::pTypeLib.
Referenced by foletypelib_s_allocate().
static HRESULT oletypelib_from_guid (VALUE guid, VALUE version, ITypeLib ** ppTypeLib) static
Definition at line 5395 of file win32ole.c.
References HRESULT(), ole_vstr2wc(), oletypelib_path(), and Qnil.
Referenced by foletypelib_s_typelibs(), oletypelib_search_registry(), and oletypelib_search_registry2().
static void oletypelib_get_libattr (ITypeLib * pTypeLib, TLIBATTR ** ppTLibAttr) static
Definition at line 4955 of file win32ole.c.
References eWIN32OLERuntimeError, HRESULT(), and ole_raise().
Referenced by foletypelib_guid(), foletypelib_major_version(), foletypelib_minor_version(), foletypelib_path(), foletypelib_version(), and foletypelib_visible().
static ITypeLib * oletypelib_get_typelib (VALUE self) static
Definition at line 4947 of file win32ole.c.
References Data_Get_Struct, and oletypelibdata::pTypeLib.
Referenced by foletypelib_guid(), foletypelib_library_name(), foletypelib_major_version(), foletypelib_minor_version(), foletypelib_name(), foletypelib_ole_types(), foletypelib_path(), foletypelib_version(), and foletypelib_visible().
static VALUE oletypelib_path (VALUE guid, VALUE version) static
Definition at line 5362 of file win32ole.c.
References err, key, Qnil, rb_str_cat2(), rb_str_concat(), rb_str_new2, reg_enum_key(), reg_get_typelib_file_path(), and reg_open_vkey().
Referenced by oletypelib_from_guid().
static VALUE oletypelib_search_registry (VALUE self, VALUE typelib) static
Definition at line 5109 of file win32ole.c.
References err, HRESULT(), i, NULL, oletypelib_from_guid(), oletypelib_set_member(), oletypelibdata::pTypeLib, Qfalse, Qnil, Qtrue, rb_str_cmp(), reg_enum_key(), reg_get_val(), reg_open_key(), and reg_open_vkey().
Referenced by foletypelib_initialize().
static VALUE oletypelib_search_registry2 (VALUE self, VALUE args) static
Definition at line 5037 of file win32ole.c.
References err, HRESULT(), make_version_str(), NULL, oletypelib_from_guid(), oletypelib_set_member(), oletypelibdata::pTypeLib, Qfalse, Qnil, Qtrue, rb_ary_entry(), reg_enum_key(), reg_get_val(), reg_open_key(), reg_open_vkey(), StringValuePtr, and version().
Referenced by foletypelib_initialize().
static VALUE oletypelib_set_member (VALUE self, ITypeLib * pTypeLib) static
Definition at line 4938 of file win32ole.c.
References Data_Get_Struct, and oletypelibdata::pTypeLib.
Referenced by foletypelib_initialize(), foletypelib_s_typelibs(), ole_typelib_from_itypeinfo(), oletypelib_search_registry(), and oletypelib_search_registry2().
static void olevariable_free (struct olevariabledata * polevar) static
Definition at line 1289 of file win32ole.c.
References free(), OLE_FREE, and olevariabledata::pTypeInfo.
Referenced by ole_variables().
static void olevariant_free (struct olevariantdata * pvar) static
Definition at line 8640 of file win32ole.c.
References free(), olevariantdata::realvar, and olevariantdata::var.
Referenced by folevariant_s_allocate().
static double rbtime2vtdate (VALUE tmobj) static
Definition at line 825 of file win32ole.c.
References FIX2INT, rb_funcall(), and rb_intern.
Referenced by ole_val2variant().
static ULONG reference_count (struct oledata * pole) static
Definition at line 2897 of file win32ole.c.
References OLE_ADDREF, OLE_RELEASE, oledata::pDispatch, and ULONG().
Referenced by fole_s_free(), and fole_s_reference_count().
static VALUE reg_enum_key (HKEY hkey, DWORD i) static
Definition at line 2343 of file win32ole.c.
References buf, err, NULL, Qnil, and rb_str_new2.
Referenced by foletype_s_progids(), foletypelib_s_typelibs(), oletypelib_path(), oletypelib_search_registry(), oletypelib_search_registry2(), and typelib_file_from_typelib().
static VALUE reg_get_typelib_file_path (HKEY hkey) static
Definition at line 2403 of file win32ole.c.
References Qnil, and reg_get_val2().
Referenced by oletypelib_path(), and typelib_file_from_typelib().
static VALUE reg_get_val (HKEY hkey, const char * subkey) static
Definition at line 2358 of file win32ole.c.
References ALLOC_N, err, free(), NULL, Qnil, rb_str_new2, size, and val.
Referenced by oletypelib_search_registry(), oletypelib_search_registry2(), reg_get_val2(), and typelib_file_from_typelib().
static VALUE reg_get_val2 (HKEY hkey, const char * subkey) static
Definition at line 2386 of file win32ole.c.
References err, NULL, Qnil, reg_get_val(), and val.
Referenced by foletype_s_progids(), foletypelib_s_typelibs(), reg_get_typelib_file_path(), and typelib_file_from_clsid().
static LONG reg_open_key (HKEY hkey, const char * name, HKEY * phkey) static
Definition at line 2331 of file win32ole.c.
Referenced by foletype_s_progids(), foletypelib_s_typelibs(), oletypelib_search_registry(), oletypelib_search_registry2(), reg_open_vkey(), typelib_file_from_clsid(), and typelib_file_from_typelib().
static LONG reg_open_vkey (HKEY hkey, VALUE key, HKEY * phkey) static
Definition at line 2337 of file win32ole.c.
References reg_open_key(), and StringValuePtr.
Referenced by foletype_s_progids(), foletypelib_s_typelibs(), oletypelib_path(), oletypelib_search_registry(), oletypelib_search_registry2(), and typelib_file_from_typelib().
static VALUE rescue_callback (VALUE arg) static
Definition at line 7797 of file win32ole.c.
References msg, Qnil, rb_ary_entry(), rb_backtrace(), rb_errinfo, rb_funcall(), rb_intern, rb_obj_classname(), rb_sprintf(), rb_write_error(), ruby_finalize(), and StringValuePtr.
Referenced by EVENTSINK_Invoke().
static VALUE set_argv (VARIANTARG * realargs, unsigned int beg, unsigned int end) static
Definition at line 3323 of file win32ole.c.
References argv, Check_Type, cWIN32OLE, ole_variant2val(), rb_ary_clear(), rb_ary_push(), rb_const_get(), rb_intern, and T_ARRAY.
Referenced by ole_invoke(), and ole_invoke2().
static void set_ole_codepage (UINT cp) static
Definition at line 961 of file win32ole.c.
References code_page_installed(), cWIN32OLE_cp, eWIN32OLERuntimeError, load_conv_function51932, ole_cp2encoding(), and rb_raise().
Referenced by fole_s_set_code_page(), and ole_init_cp().
STDMETHODIMP_ (ULONG)
Definition at line 7611 of file win32ole.c.
References EVENTSINK_Destructor(), and tagIEVENTSINKOBJ::m_cRef.
static HRESULT typeinfo_from_ole (struct oledata * pole, ITypeInfo ** ppti) static
Definition at line 4234 of file win32ole.c.
References count, cWIN32OLE_lcid, HRESULT(), i, NULL, ole_raise(), OLE_RELEASE, oledata::pDispatch, rb_eRuntimeError, rb_str_cmp(), type, and WC2VSTR.
Referenced by fole_method_help(), and ole_methods().
static VALUE typelib_file (VALUE ole) static
Definition at line 2505 of file win32ole.c.
References Qnil, typelib_file_from_clsid(), and typelib_file_from_typelib().
Referenced by fole_s_const_load(), and foletype_initialize().
static VALUE typelib_file_from_clsid (VALUE ole) static
Definition at line 2419 of file win32ole.c.
References err, Qnil, rb_str_new2, reg_get_val2(), reg_open_key(), and StringValuePtr.
Referenced by typelib_file().
static VALUE typelib_file_from_typelib (VALUE ole) static
Definition at line 2447 of file win32ole.c.
References err, FALSE, i, NULL, Qnil, rb_str_cmp(), reg_enum_key(), reg_get_typelib_file_path(), reg_get_val(), reg_open_key(), reg_open_vkey(), StringValuePtr, and TRUE.
Referenced by typelib_file().
static ULONG (STDMETHODCALLTYPE AddRef) static
Definition at line 614 of file win32ole.c.
Referenced by fole_s_free(), nkf_locale_charmap(), ole_bind_obj(), rb_w32_getppid(), and reference_count().
static void unlock_safe_array (SAFEARRAY * psa) static
Definition at line 8833 of file win32ole.c.
References HRESULT(), ole_raise(), and rb_eRuntimeError.
Referenced by folevariant_ary_aref(), and folevariant_ary_aset().
static IDispatch * val2dispatch (VALUE val) static
Definition at line 804 of file win32ole.c.
References ALLOC, com_hash, com_vtbl, DATA_PTR, _Win32OLEIDispatch::dispatch, FIXNUM_FLAG, _Win32OLEIDispatch::obj, _Win32OLEIDispatch::refcount, st_insert(), and st_lookup().
Referenced by ole_val2variant().
static VOID * val2variant_ptr (VALUE val, VARIANT * var, VARTYPE vt) static
Definition at line 8898 of file win32ole.c.
References cWIN32OLE_lcid, get_ptr_of_variant(), HRESULT(), NULL, ole_raise(), ole_val2variant_ex(), p, rb_eRuntimeError, rb_raise(), S_OK, and olevariantdata::var.
Referenced by folevariant_ary_aset(), and ole_set_safe_array().
static VALUE vtdate2rbtime (double date) static
Definition at line 842 of file win32ole.c.
References INT2FIX, rb_cTime, rb_float_new(), rb_funcall(), rb_intern, and v.
Referenced by ole_variant2val().
Variable Documentation
int args = pDispParams->cArgs
Definition at line 785 of file win32ole.c.
Referenced by ary2sv(), ary_join_1(), assoc_i(), autoload_const_set(), basic_obj_respond_to(), bind_eval(), bmcall(), check_exec_options_i_extract(), check_funcall_respond_to(), chown_internal(), console_dev(), copy_stream_body(), create_ip_exc(), date_strftime_with_tmx(), deflate_run(), dvar_defined_gen(), enc_names(), enum_zip(), enumerator_each(), ev_on_event(), EVENTSINK_Invoke(), gc_mark_children(), generator_each(), GetVpValueWithPrec(), glob_func_caller(), hash2kv(), hash2kv_enc(), inflate_run(), initialize(), int_ossl_asn1_decode0_cons(), int_ossl_asn1_decode0_prim(), interrupt_init(), ip_ruby_cmd(), iseq_compile_each(), iseq_data_to_ary(), iseq_load(), iseq_set_arguments(), key_i(), lazy_drop_func(), lazy_init_iterator(), lazy_take_func(), local_id_gen(), make_curry_proc(), make_no_method_exception(), mark(), name_err_mesg_to_str(), new_args_gen(), new_args_tail_gen(), next_ii(), nometh_err_initialize(), obj_respond_to(), objspace_each_objects(), ole_raise(), onig_snprintf_with_pattern(), onig_syntax_warn(), open_key_args(), ossl_debug(), ossl_exc_new(), ossl_raise(), ossl_tmp_dh_callback(), ossl_x509name_initialize(), parse(), path_binread(), path_each_entry(), path_each_line(), path_open(), path_opendir(), path_read(), path_readlines(), path_s_glob(), path_sysopen(), pipe_open(), process_sflag(), protected_alias(), protected_end_document(), protected_scalar(), protected_start_document(), protected_start_mapping(), protected_start_sequence(), protected_start_stream(), range_each(), range_init(), range_step(), rassoc_i(), rb_autoload_load(), rb_bug(), rb_compile_bug(), rb_compile_error(), rb_compile_error_append(), rb_compile_error_with_enc(), rb_compile_warn(), rb_compile_warning(), rb_deflate_s_deflate(), rb_enc_raise(), rb_execarg_extract_options(), rb_exit(), rb_f_abort(), rb_fatal(), rb_fiber_start(), rb_glob_caller(), rb_hash_assoc(), rb_hash_key(), rb_hash_rassoc(), rb_inflate_s_inflate(), rb_int2num_inline(), rb_io_s_pipe(), rb_iseq_parameters(), rb_loaderror(), rb_loaderror_with_path(), rb_name_error(), rb_name_error_str(), rb_obj_respond_to(), rb_proc_exec_n(), rb_raise(), rb_reg_s_union(), rb_rescue2(), rb_str_upto(), rb_strftime_with_timespec(), rb_struct_new(), rb_sys_warning(), rb_warn(), rb_warning(), rb_yield_values(), run_finalizer(), run_single_final(), take_items(), thread_create_core(), thread_start_func_2(), warn_printf(), yyparse(), zip_ary(), zip_i(), zstream_run_func(), and zstream_unblock_func().
VALUE ary_ole_event static
Definition at line 215 of file win32ole.c.
Referenced by evs_delete(), evs_entry(), evs_length(), evs_push(), and Init_win32ole().
static REFIID LPOLESTR __RPC_FAR UINT cNames
Definition at line 305 of file win32ole.c.
VALUE com_hash static
Definition at line 233 of file win32ole.c.
Referenced by Init_win32ole(), and val2dispatch().
IDispatchVtbl com_vtbl static
Definition at line 234 of file win32ole.c.
Referenced by Init_win32ole(), and val2dispatch().
VALUE cWIN32OLE
Definition at line 203 of file win32ole.c.
Referenced by ev_advise(), fole_query_interface(), fole_s_const_load(), folevariant_initialize(), Init_win32ole(), ole_val2variant(), ole_variant2val(), and set_argv().
UINT cWIN32OLE_cp = CP_ACP static
Definition at line 235 of file win32ole.c.
Referenced by fole_s_get_code_page(), ole_mb2wc(), ole_wc2mb(), and set_ole_codepage().
rb_encoding* cWIN32OLE_enc static
Definition at line 237 of file win32ole.c.
VALUE cWIN32OLE_EVENT
Definition at line 209 of file win32ole.c.
Referenced by EVENTSINK_Invoke(), and Init_win32ole().
LCID cWIN32OLE_lcid = LOCALE_SYSTEM_DEFAULT static
Definition at line 236 of file win32ole.c.
Referenced by find_default_source(), find_iid(), fole_each(), fole_respond_to(), fole_s_const_load(), fole_s_get_locale(), fole_s_set_locale(), fole_type(), fole_typelib(), foletypelib_path(), ole_hresult2msg(), ole_invoke(), ole_invoke2(), ole_propertyput(), ole_val2olevariantdata(), ole_variant2val(), typeinfo_from_ole(), and val2variant_ptr().
VALUE cWIN32OLE_METHOD
Definition at line 207 of file win32ole.c.
Referenced by fole_method_help(), fole_s_show_help(), foleparam_initialize(), Init_win32ole(), and ole_methods_sub().
VALUE cWIN32OLE_PARAM
Definition at line 208 of file win32ole.c.
Referenced by Init_win32ole(), and ole_method_params().
VALUE cWIN32OLE_PROPERTY
Definition at line 213 of file win32ole.c.
VALUE cWIN32OLE_TYPE
Definition at line 205 of file win32ole.c.
Referenced by fole_s_show_help(), folemethod_initialize(), Init_win32ole(), ole_type_from_itypeinfo(), and ole_types_from_typelib().
VALUE cWIN32OLE_TYPELIB
Definition at line 204 of file win32ole.c.
Referenced by foletype_s_ole_classes(), foletypelib_s_typelibs(), Init_win32ole(), and ole_typelib_from_itypeinfo().
VALUE cWIN32OLE_VARIABLE
Definition at line 206 of file win32ole.c.
Referenced by Init_win32ole(), and ole_variables().
VALUE cWIN32OLE_VARIANT
Definition at line 210 of file win32ole.c.
Referenced by folevariant_initialize(), Init_win32ole(), ole_invoke(), and ole_val2variant().
static DISPID dispIdMember
Definition at line 306 of file win32ole.c.
DWORD dwCallType
Definition at line 628 of file win32ole.c.
HTASK DWORD DWORD dwPendingType
Initial value:
{
    if (rb_during_gc()) {
        return PENDINGMSG_WAITNOPROCESS;
    }
    if (previous_filter) {
        return previous_filter->lpVtbl->MessagePending(previous_filter,
                                               threadIDCallee,
                                               dwTickCount,
                                               dwPendingType);
    }
    return PENDINGMSG_WAITNOPROCESS
Definition at line 682 of file win32ole.c.
HTASK DWORD DWORD dwRejectType
Initial value:
{
    if (previous_filter) {
        return previous_filter->lpVtbl->RetryRejectedCall(previous_filter,
                                                  threadIDCallee,
                                                  dwTickCount,
                                                  dwRejectType);
    }
    return 1000
Definition at line 666 of file win32ole.c.
static HTASK DWORD dwTickCount
Definition at line 628 of file win32ole.c.
st_table* enc2cp_table static
Definition at line 241 of file win32ole.c.
VALUE eWIN32OLERuntimeError
Definition at line 211 of file win32ole.c.
Referenced by ev_on_event(), failed_load_conv51932(), fole_activex_initialize(), fole_each(), fole_initialize(), fole_method_help(), fole_query_interface(), fole_s_connect(), fole_s_const_load(), fole_s_create_guid(), fole_s_set_locale(), folemethod_initialize(), foletype_initialize(), foletypelib_initialize(), foletypelib_library_name(), foletypelib_name(), foletypelib_path(), folevariant_ary_aref(), folevariant_ary_aset(), folevariant_set_value(), Init_win32ole(), ole_bind_obj(), ole_cp2encoding(), ole_create_dcom(), ole_invoke(), ole_invoke2(), ole_mb2wc(), ole_method_invkind(), ole_method_return_type(), ole_method_return_vtype(), ole_method_sub(), ole_methods_from_typeinfo(), ole_methods_sub(), ole_propertyput(), ole_set_byref(), ole_set_safe_array(), ole_type_major_version(), ole_type_minor_version(), ole_type_typekind(), ole_val2olevariantdata(), ole_variable_ole_type(), ole_variable_ole_type_detail(), ole_variables(), ole_vstr2wc(), ole_wc2mb(), olemethod_from_typeinfo(), oletypelib_get_libattr(), and set_ole_codepage().
BOOL g_cp_installed = FALSE static
Definition at line 228 of file win32ole.c.
Referenced by code_page_installed(), and installed_code_page_proc().
UINT g_cp_to_check = CP_ACP static
Definition at line 238 of file win32ole.c.
Referenced by code_page_installed(), and installed_code_page_proc().
BOOL g_IsEventSinkVtblInitialized = FALSE static
Definition at line 7580 of file win32ole.c.
BOOL g_lcid_installed = FALSE static
Definition at line 229 of file win32ole.c.
Referenced by installed_lcid_proc(), and lcid_installed().
char g_lcid_to_check[8+1] static
Definition at line 239 of file win32ole.c.
Referenced by installed_lcid_proc(), and lcid_installed().
VARTYPE g_nil_to = VT_ERROR static
Definition at line 240 of file win32ole.c.
Referenced by ole_val2variant(), and ole_val2variant2().
volatile DWORD g_ole_initialized_key = TLS_OUT_OF_INDEXES static
Definition at line 222 of file win32ole.c.
BOOL g_uninitialize_hooked = FALSE static
Definition at line 227 of file win32ole.c.
Referenced by ole_initialize().
FNCOCREATEINSTANCEEX* gCoCreateInstanceEx = NULL static
Definition at line 232 of file win32ole.c.
Referenced by ole_create_dcom().
HINSTANCE ghhctrl = NULL static
Definition at line 230 of file win32ole.c.
Referenced by ole_show_help().
HINSTANCE gole32 = NULL static
Definition at line 231 of file win32ole.c.
Referenced by ole_create_dcom().
int i
Definition at line 784 of file win32ole.c.
Referenced by add_char_amb_opt_map_info(), add_ctype_to_cc_by_range(), add_heap_slots(), add_packed_direct(), alloc_invoke_arguments(), allocate(), allocate_sorted_heaps(), alt_merge_opt_exact_info(), alt_merge_opt_map_info(), and_code_range1(), and_code_range_buf(), append_extmod(), apply2files(), ary2ptr_dispparams(), ary2safe_array_index(), ary_add_hash(), ary_add_hash_by(), ary_join_0(), ary_join_1(), ary_new_dim(), ary_reject(), ary_reject_bang(), assoc2kv(), assoc2kv_enc(), backtrace_collect(), backtrace_each(), backtrace_mark(), base64decode(), big2dbl(), big2str_orig(), big_fdiv(), big_lshift(), big_rshift(), bigadd_core(), bigadd_int(), bigand_int(), bigdivrem(), bigdivrem1(), biglsh_bang(), BigMath_s_exp(), BigMath_s_log(), bigmul1_balance(), bigmul1_karatsuba(), bigmul1_normal(), bigor_int(), bigrsh_bang(), bigsqr_fast(), bigsub_core(), bigsub_int(), bigxor_int(), bigzero_p(), bitset_and(), bitset_copy(), bitset_invert(), bitset_invert_to(), bitset_is_empty(), bitset_or(), bitset_set_range(), bm_search(), bsock_setsockopt(), bubblebabble_str_new(), c_find_ldom(), c_find_ldoy(), call_queue_mark(), callback(), cbsubst_get_subst_arg(), cbsubst_get_subst_key(), check_class(), check_exec_fds(), check_exec_fds_1(), check_exec_redirect1(), chfunc(), clear_coverage_i(), cmp(), code_page(), collect_caller_bindings(), collect_local_variables_in_iseq(), compat_init_setproctitle(), compile_array_(), compile_massign_opt(), compile_quantifier_node(), compile_tree(), compile_tree_n_times(), concat_opt_exact_info(), concat_opt_exact_info_str(), convert_type(), count_nodes(), count_objects(), count_objects_size(), coverage(), create_encoding_table_core(), crypt(), d2b(), d_lite_plus(), date__strptime_internal(), date_strftime_with_tmx(), date_zone_to_diff(), day_num(), dbl2big(), decorate_convpath(), delete_slaves(), delpair(), des_setkey(), diff(), dir_globs(), disable_noname_group_capture(), dlhandle_sym(), dln_find_1(), dup2(), dvar_defined_gen(), e2w_combining(), econv_convpath(), econv_equal(), enc_autoload(), enc_pred_char(), enc_succ_char(), encodes(), encrypt(), enum_cycle(), enum_reverse_each(), enum_sort_by(), enum_zip(), env_each_key(), env_each_pair(), env_each_value(), env_inspect(), env_reject_bang(), env_replace(), env_select_bang(), env_size(), env_values_at(), envix(), error_print(), EVENTSINK_Invoke(), expand_case_fold_string_alt(), fdbm_delete_if(), fdbm_length(), fdbm_values_at(), fetch_named_backref_token(), fgdbm_delete_if(), fgdbm_length(), fgdbm_values_at(), fiddle_handle_sym(), filename_completion_proc_call(), find_coclass(), find_i(), find_packed_index(), find_str_position(), first_i(), fix_abs(), fix_aref(), fix_succ(), flatten(), flo_cmp(), flock_winnt(), foletype_s_progids(), foletypelib_s_typelibs(), folevariant_s_array(), for(), free_invoke_arguments(), free_unused_heaps(), fsdbm_delete_if(), fsdbm_length(), fsdbm_values_at(), function_call(), gc_profile_dump_on(), gc_profile_record_get(), gc_profile_total_time(), generate_json_array(), generate_json_object(), get2comp(), get_addr(), get_backup_filename(), get_dyna_var_idx_at_raw(), get_line_info(), get_loaded_features_index(), get_max_match_length(), get_min_match_length(), getaddrinfo(), getnameinfo(), getpair(), gmtimew_noleapsecond(), hash2named_arg(), hash2ptr_dispparams(), hexencode_str_new(), hist_delete_at(), hist_each(), hist_get(), httpdate_type1_cb(), httpdate_type2_cb(), httpdate_type3_cb(), i2b(), i_apply_case_fold(), i_renumber_name(), init_by_array(), Init_curses(), init_des(), Init_Encoding(), init_mark_stack(), Init_Object(), Init_ossl_asn1(), Init_ossl_ssl(), init_perm(), Init_RandomSeed(), initialize(), inject_i(), inject_op_i(), insn_make_insn_table(), insn_operand_intern(), inspect_ary(), inspect_errno(), inspect_int(), inspect_struct(), int_chr(), int_dotimes(), int_downto(), int_pair_to_real_inclusive(), int_pred(), int_sip_pad_final_block(), int_sip_round(), int_succ(), int_upto(), intern_str(), invoke_block_from_c(), invoke_tcl_proc(), io_puts_ary(), io_wait_readable(), io_wait_writable(), ip_invoke_core(), ip_ruby_cmd(), is_command_com(), is_not_included(), is_onechar_cclass(), iseq_build_from_ary_body(), iseq_build_from_ary_exception(), iseq_compile_each(), iseq_data_to_ary(), iseq_load(), iseq_set_arguments(), iseq_set_exception_table(), iseq_set_optargs_table(), iso2022jp_check_conv(), iso8601_bas_datetime_cb(), iso8601_ext_datetime_cb(), iso8601_ext_time_cb(), jisx0301_cb(), lazy_flat_map_func(), lazy_flat_map_to_ary(), lazy_grep_func(), lazy_grep_iter(), lazy_zip(), lazy_zip_arrays_func(), lazy_zip_func(), lgamma_r(), limited_big_rand(), limited_rand(), loaded_feature_path(), lshift(), m_core_hash_from_ary(), m_core_hash_merge_ary(), m_core_hash_merge_ptr(), main(), make_econv_exception(), make_struct(), map_position_value(), match_array(), match_at(), match_begin(), match_end(), match_inspect(), match_inspect_name_iter(), match_offset(), max_by_i(), max_i(), max_ii(), MD5_Finish(), md5_process(), mem_is_in_memp(), mime_begin(), mime_begin_strict(), mime_putc(), min_by_i(), min_i(), min_ii(), minmax_by_i(), minmax_i(), minmax_i_update(), minmax_ii(), minmax_ii_update(), mk_ary_of_str(), mon_num(), month_arg(), moreswitches(), mt_state(), multadd(), n2i(), name_add(), name_err_mesg_equal(), new_insn_body(), new_size(), nfc_getc(), nkf_enc_find_index(), nkf_split_options(), nkf_str_caseeql(), node_new_backref(), node_new_cclass_by_codepoint_range(), not_code_range_buf(), nsdr(), num_step(), numchar_getc(), objspace_each_objects(), ole_docinfo_from_type(), ole_invoke(), ole_invoke2(), ole_method_event(), ole_method_params(), ole_method_sub(), ole_methods_from_typeinfo(), ole_methods_sub(), ole_search_event(), ole_search_event_at(), ole_set_safe_array(), ole_type_impl_ole_types(), ole_types_from_typelib(), ole_val_ary2variant_ary(), ole_variables(), ole_variant2val(), oleclass_from_typelib(), olemethod_from_typeinfo(), oletypelib_search_registry(), onig_compile(), onig_name_to_backref_number(), onig_number_of_capture_histories(), onig_region_clear(), onig_region_copy(), onigenc_apply_all_case_fold_with_map(), onigenc_ascii_apply_all_case_fold(), onigenc_get_case_fold_codes_by_str_with_map(), onigenc_mbn_mbc_case_fold(), onigenc_mbn_mbc_to_code(), open_ifs_socket(), open_mime(), opt_enc_index(), optimize_node_left(), options(), or_code_range_buf(), ossl_pkcs7_get_recipient(), ossl_pkcs7_get_signer(), ossl_pkcs7_sym2typeid(), ossl_ssl_get_peer_cert_chain(), ossl_ssl_session_to_pem(), ossl_ssl_shutdown(), ossl_sslctx_add_extra_chain_cert_i(), ossl_sslctx_get_ciphers(), ossl_sslctx_initialize(), ossl_sslctx_set_ciphers(), ossl_sslctx_set_ssl_version(), ossl_sslctx_setup(), ossl_x509_get_extensions(), ossl_x509_set_extensions(), ossl_x509_verify(), ossl_x509crl_get_extensions(), ossl_x509crl_get_revoked(), ossl_x509crl_set_extensions(), ossl_x509crl_set_revoked(), ossl_x509name_to_a(), ossl_x509req_get_attributes(), ossl_x509req_set_attributes(), ossl_x509req_verify(), ossl_x509revoked_get_extensions(), ossl_x509revoked_set_extensions(), ossl_x509stctx_get_chain(), pack_pack(), pack_unpack(), parse_char_class(), parse_enclose(), parse_main(), parse_posix_bracket(), parser_magic_comment(), parser_set_encode(), parser_yyerror(), path_entries(), path_s_glob(), PEM_def_callback(), permute0(), pow5mult(), power_cache_get_power(), power_cache_get_power0(), power_cache_init(), process_options(), pty_close_pty(), qpencode(), quad_buf_complement(), r_long(), r_object0(), rand_init(), range_each(), range_step(), rb_ary_and(), rb_ary_assoc(), rb_ary_collect(), rb_ary_collect_bang(), rb_ary_combination(), rb_ary_cycle(), rb_ary_diff(), rb_ary_drop_while(), rb_ary_each(), rb_ary_each_index(), rb_ary_fill(), rb_ary_includes(), rb_ary_index(), rb_ary_initialize(), rb_ary_join(), rb_ary_new3(), rb_ary_or(), rb_ary_permutation(), rb_ary_product(), rb_ary_rassoc(), rb_ary_repeated_combination(), rb_ary_repeated_permutation(), rb_ary_rindex(), rb_ary_sample(), rb_ary_select(), rb_ary_shuffle_bang(), rb_ary_take_while(), rb_ary_transpose(), rb_ary_uniq(), rb_ary_uniq_bang(), rb_ary_zip(), rb_backtrace_print_as_bugreport(), rb_big_and(), rb_big_aref(), rb_big_neg(), rb_big_or(), rb_big_pack(), rb_big_unpack(), rb_big_xor(), rb_check_argv(), rb_check_backtrace(), rb_construct_expanded_load_path(), rb_cstr_to_inum(), rb_dlcfunc_call(), rb_dvar_defined(), rb_econv_add_transcoder_at(), rb_econv_binmode(), rb_econv_close(), rb_econv_init_by_convpath(), rb_econv_memsize(), rb_econv_open(), rb_econv_open_by_transcoder_entries(), rb_enc_find_index(), rb_enc_get_index(), rb_env_clear(), rb_exec_fillarg(), rb_execarg_fixup(), rb_execarg_run_options(), rb_f_global_variables(), rb_f_kill(), rb_f_local_variables(), rb_f_p_internal(), rb_f_select(), rb_feature_p(), rb_file_join(), rb_find_file_ext_safe(), rb_find_file_safe(), rb_fix_rshift(), rb_funcall(), rb_get_next_signal(), rb_get_values_at(), rb_hash_s_create(), rb_hash_values_at(), rb_id2str(), rb_insns_name(), rb_insns_name_array(), rb_io_print(), rb_io_puts(), rb_iseq_build_for_ruby2cext(), rb_iseq_build_from_ary(), rb_iseq_disasm(), rb_iseq_parameters(), rb_iseq_translate_threaded_code(), rb_ivar_count(), rb_ivar_set(), rb_local_defined(), rb_memsearch_qs(), rb_memsearch_qs_utf8(), rb_mod_attr_accessor(), rb_mod_attr_reader(), rb_mod_attr_writer(), rb_mod_include(), rb_mod_modfunc(), rb_mod_prepend(), rb_mod_remove_method(), rb_mod_undef_method(), rb_obj_extend(), rb_objspace_call_finalizer(), rb_objspace_free(), rb_proc_exec_n(), rb_random_bytes(), rb_reg_match_last(), rb_reg_preprocess_dregexp(), rb_reg_s_union(), rb_scan_args(), rb_stat_inspect(), rb_str_count(), rb_str_delete_bang(), rb_str_end_with(), rb_str_enumerate_bytes(), rb_str_enumerate_chars(), rb_str_format(), rb_str_include(), rb_str_slice_bang(), rb_str_split_m(), rb_str_squeeze_bang(), rb_str_start_with(), rb_strftime_with_timespec(), rb_struct_aref(), rb_struct_aref_id(), rb_struct_aset(), rb_struct_aset_id(), rb_struct_each(), rb_struct_each_pair(), rb_struct_getmember(), rb_struct_new(), rb_struct_s_def(), rb_struct_select(), rb_struct_set(), rb_struct_to_h(), rb_threadptr_pending_interrupt_check_mask(), rb_threadptr_pending_interrupt_deque(), rb_threadptr_pending_interrupt_include_p(), rb_trans_conv(), rb_uint2big(), rb_vm_bugreport(), rb_vm_mark(), rb_vmdebug_debug_print_pre(), rb_vmdebug_env_dump_raw(), rb_w32_fdclr(), rb_w32_map_errno(), rb_w32_strerror(), rb_yield_values(), rb_zlib_crc_table(), readline_attempted_completion_function(), recalc_add_ruby_vm_event_flags(), recalc_remove_ruby_vm_event_flags(), recursive_cmp(), recursive_eql(), recursive_equal(), recursive_hash(), reduce0(), reg_named_captures_iter(), reinit(), renumber_node_backref(), rfc2822_cb(), rfc3339_cb(), RMD160_Finish(), RMD160_Update(), rpermute0(), rsa_generate(), rt_complete_frags(), ruby_dtoa(), ruby_float_step(), ruby_set_argv(), ruby_setenv(), ruby_strtod(), run_exec_close(), run_exec_dup2(), run_exec_dup2_child(), run_exec_open(), run_finalizer(), s2b(), scan_env_add_mem_entry(), scan_env_clear(), scan_once(), seepair(), select_end(), select_internal(), set_arg0(), set_bm_backward_skip(), set_bm_skip(), set_const_visibility(), set_method_visibility(), set_optimize_map_info(), set_state_ivars(), setkey(), setup_args(), setup_tree(), SHA1_Finish(), SHA1_Update(), SHA256_End(), SHA384_End(), SHA512_End(), signbit(), sockopt_bool(), sockopt_int(), sockopt_s_bool(), sockopt_s_int(), sort_by_i(), st_cleanup_safe(), st_clear(), st_delete(), st_delete_safe(), st_foreach(), st_foreach_check(), st_get_key(), st_hash_uint(), st_insert(), st_insert2(), st_lookup(), st_update(), STACK_OF(), start_document(), str_exist_check_with_esc(), strdup_with_null(), string2hex(), strscan_aref(), strscan_rest_size(), strscan_set_pos(), stub_sysinit(), subst_free(), swallow(), test_check(), tgamma(), time_mdump(), time_mload(), time_timespec(), tk_funcall(), tr_setup_table(), tr_trans(), tracepoint_new_s(), trans_sweep(), type_cclass_hash(), typeinfo_from_ole(), typelib_file_from_typelib(), unicode_iconv_combine(), unknown_keyword_error(), unpack_entries(), unset_addr_list_fix(), update_char_offset(), update_encoding_table(), update_string_node_case_fold(), usage(), username_completion_proc_call(), vm_call0_body(), vm_call_iseq_setup_normal(), vm_call_iseq_setup_tailcall(), vm_call_opt_send(), vm_callee_setup_arg_complex(), vm_callee_setup_keyword_arg(), vm_caller_setup_args(), vm_exec(), vm_expandarray(), vm_make_env_each(), vm_push_frame(), vm_throw(), vm_yield_setup_block_args(), vm_yield_setup_block_args_complex(), VpAddSub(), VpAlloc(), VpCtoV(), VpDivd(), VpDtoV(), VpFormatSt(), VpMidRound(), VpMult(), VpNmlz(), VpSzMantissa(), VpToFString(), VpToString(), vtable_included(), vtable_tblcpy(), w16e_conv(), w_long(), w_object(), w_objivar(), warn_unused_var(), wmap_finalize(), x0213_combining_p(), x0213_wait_combining_p(), X509_CRL_sort(), xmlschema_datetime_cb(), xmlschema_time_cb(), xmlschema_trunc_cb(), zip_ary(), and zip_i().
ID id_events static
Definition at line 216 of file win32ole.c.
Referenced by add_event_call_back(), EVENTSINK_Invoke(), fev_initialize(), fev_off_event(), and Init_win32ole().
IMessageFilter imessage_filter = { &message_filter } static
Definition at line 243 of file win32ole.c.
Referenced by ole_initialize().
static UINT iTInfo
Definition at line 304 of file win32ole.c.
static DISPID REFIID LCID lcid
Definition at line 304 of file win32ole.c.
Referenced by fole_s_set_locale().
DWORD HTASK DWORD LPINTERFACEINFO lpInterfaceInfo
Initial value:
{
    switch (dwCallType)
    {
    case CALLTYPE_ASYNC:
    case CALLTYPE_TOPLEVEL_CALLPENDING:
    case CALLTYPE_ASYNC_CALLPENDING:
        if (rb_during_gc()) {
            return SERVERCALL_RETRYLATER;
        }
        break;
    default:
        break;
    }
    if (previous_filter) {
        return previous_filter->lpVtbl->HandleInComingCall(previous_filter,
                                                   dwCallType,
                                                   threadIDCaller,
                                                   dwTickCount,
                                                   lpInterfaceInfo);
    }
    return SERVERCALL_ISHANDLED
Definition at line 633 of file win32ole.c.
IMessageFilterVtbl message_filter static
Definition at line 242 of file win32ole.c.
Referenced by Init_win32ole().
VALUE mWIN32OLE_VARIANT
Definition at line 212 of file win32ole.c.
Referenced by Init_win32ole().
Win32OLEIDispatch* p = (Win32OLEIDispatch*)This
Definition at line 786 of file win32ole.c.
Referenced by add_multi_byte_cclass(), add_slot_local_freelist(), allocate_sorted_heaps(), appendline(), argf_alloc(), ASN1_put_eoc(), assign_heap_slot(), autoload_i_free(), autoload_i_mark(), autoload_provided(), backref_match_at_nested_level(), backward_search_range(), BigDecimal_hash(), BigDecimal_IsFinite(), BigDecimal_IsInfinite(), BigDecimal_IsNaN(), BigDecimal_prec(), BigDecimal_to_f(), BigDecimal_to_i(), BigDecimal_to_r(), bm_search(), bm_search_backward(), bm_search_ic(), bm_search_notrev(), bracket(), BSD__sfvwrite(), BSD_vfprintf(), bubblebabble_str_new(), check_valid_dir(), chopped_length(), cmdglob(), code_status(), compile_length_string_node(), compile_string_node(), compile_tree(), concat_opt_exact_info(), concat_opt_exact_info_str(), constat_handle(), constat_reset(), convert_UTF8_to_JSON(), count_objects(), cParser_parse_quirks_mode(), cParser_parse_strict(), date_strftime_internal(), date_zone_to_diff(), deallocate(), decode_bool(), decode_bstr(), decode_enum(), decode_int(), decode_null(), decode_obj(), decode_time(), dln_find_1(), dln_load(), e2w_conv(), enc_strlen(), entry_repeat_range(), enumerator_mark(), establishShell(), ev_advise(), expand_case_fold_string(), features_index_add(), fetch_char_property_to_ctype(), fetch_escaped_value(), fetch_name(), fetch_name_with_level(), fetch_named_backref_token(), fetch_range_quantifier(), fetch_token(), fetch_token_in_cc(), finalize_deferred(), find_default_source(), find_inputcode_byfunc(), find_str_position(), finish_writeconv_sync(), flo_to_s(), float_rationalize(), fnmatch(), fnmatch_helper(), fole_activex_initialize(), fole_each(), fole_initialize(), fole_query_interface(), fole_s_connect(), forward_search_range(), generator_mark(), get_device_once(), get_digest_base_metadata(), get_guessed_code(), getnameinfo(), glob_helper(), glob_make_pattern(), gzfile_read_header(), gzfile_read_raw_until_zero(), gzreader_charboundary(), gzreader_gets(), gzreader_skip_linebreaks(), h_conv(), hexencode_str_new(), include_modules_at(), init_funcname_len(), Init_ossl_dh(), Init_ossl_dsa(), Init_ossl_rsa(), inspect_sockaddr(), int_ossl_asn1_decode0_prim(), internal_object_p(), io_binwrite_string(), io_encname_bom_p(), is_not_included(), is_pointer_to_heap(), isArrayOrObject(), isUNCRoot(), join_argv(), JSON_parse_float(), JSON_parse_integer(), JSON_parse_string(), JSON_parse_value(), json_string_unescape(), kanji_convert(), load_file_internal(), loaded_feature_path(), loaded_feature_path_i(), mark_dump_arg(), mark_load_arg(), mark_marshal_compat_i(), match_aref(), match_at(), MD5_Update(), mime_begin_strict(), module_connection(), moreswitches(), name_add(), name_err_mesg_mark(), next_state(), nl_langinfo_codeset(), node_new_backref(), node_new_str_raw_char(), nurat_rationalize(), ole_bind_obj(), ole_variant2val(), onig_error_code_to_format(), onig_error_code_to_str(), onig_node_str_cat(), onig_parse_make_tree(), onig_reduce_nested_quantifier(), onig_scan_unsigned_number(), onig_vsnprintf_with_pattern(), onigenc_get_right_adjust_char_head(), onigenc_get_right_adjust_char_head_with_prev(), onigenc_mbclen_approximate(), onigenc_mbn_mbc_case_fold(), onigenc_str_bytelen_null(), onigenc_strlen_null(), open_dir_handle(), open_mime(), opendir_internal(), option_to_str(), options(), os_obj_of_i(), ossl_asn1_decode(), ossl_asn1_decode0(), ossl_asn1_decode_all(), ossl_asn1_traverse(), ossl_asn1cons_to_der(), ossl_asn1data_to_der(), ossl_asn1prim_to_der(), ossl_dh_to_der(), ossl_dsa_to_der(), ossl_pkcs12_to_der(), ossl_pkcs7_to_der(), ossl_rsa_to_der(), ossl_spki_initialize(), ossl_spki_to_der(), ossl_ssl_session_to_der(), ossl_x509_to_der(), ossl_x509attr_get_value(), ossl_x509attr_initialize(), ossl_x509attr_to_der(), ossl_x509ext_initialize(), ossl_x509ext_to_der(), ossl_x509name_initialize(), ossl_x509name_to_der(), ossl_x509req_to_der(), ossl_x509stctx_set_purpose(), ossl_x509store_set_purpose(), output_hex_charref(), pack_pack(), pack_unpack(), parse_char_class(), parse_enclose(), parse_mode_enc(), parse_posix_bracket(), parse_time2_cb(), parser_here_document(), parser_new(), parser_peek_variable_name(), parser_yyerror(), path_check_0(), path_sub_ext(), proc_exec_cmd(), proc_options(), process_sflag(), push_include(), r_object0(), rb_ary_compact_bang(), rb_ary_count(), rb_ary_fill(), rb_ary_permutation(), rb_ary_repeated_combination(), rb_ary_repeated_permutation(), rb_cstr_to_dbl(), rb_dlptr_initialize(), rb_econv_add_transcoder_at(), rb_enc_aliases_enc_i(), rb_enc_strlen_cr(), rb_exec_fillarg(), rb_execarg_fixup(), rb_feature_p(), rb_fiddle_ptr_initialize(), rb_file_dirname(), rb_file_expand_path_internal(), rb_file_open_internal(), rb_file_s_basename(), rb_gzfile_set_comment(), rb_gzfile_set_orig_name(), rb_home_dir(), rb_io_each_byte(), rb_io_extract_encoding_option(), rb_io_extract_modeenc(), rb_io_getline_1(), rb_io_getline_fast(), rb_io_modestr_fmode(), rb_mod_ancestors(), rb_mod_const_get(), rb_mod_include_p(), rb_mod_included_modules(), rb_objspace_call_finalizer(), rb_path_check(), rb_path_to_class(), rb_push_glob(), rb_reg_adjust_startpos(), rb_reg_check_preprocess(), rb_reg_expr_str(), rb_reg_preprocess_dregexp(), rb_reg_regsub(), rb_scan_args(), rb_str_cat(), rb_str_chomp_bang(), rb_str_coderange_scan_restartable(), rb_str_dump(), rb_str_end_with(), rb_str_enumerate_lines(), rb_str_format(), rb_str_inspect(), rb_str_justify(), rb_str_reverse(), rb_str_splice(), rb_str_sub_bang(), rb_str_subpos(), rb_str_sum(), rb_str_to_dbl(), rb_str_to_inum(), rb_vmdebug_stack_dump_raw(), rb_w32_cmdvector(), rb_w32_getcwd(), rb_w32_pipe(), rb_w32_spawn(), rb_w32_strerror(), rb_w32_system_tmpdir(), read_escaped_byte(), regulate_path(), reinit(), remove_backslashes(), remove_from_join_list(), rmext(), ruby_brace_expand(), ruby_enc_find_basename(), ruby_enc_find_extname(), ruby_init_loadpath_safe(), ruby_qsort(), scan_env_add_mem_entry(), scan_unsigned_hexadecimal_number(), scan_unsigned_octal_number(), set_bm_skip(), set_iconv(), setup_tree(), skipprefixroot(), slot_sweep(), slow_search(), slow_search_backward(), str_byte_substr(), str_end_cmp(), str_end_hash(), str_node_split_last_char(), str_nth(), str_nth_len(), str_offset(), str_strlen(), strio_free(), strio_getc(), strio_getline(), strio_mark(), strio_memsize(), strio_set_pos(), strio_ungetc(), strscan_aref(), strscan_bol_p(), strscan_concat(), strscan_do_scan(), strscan_eos_p(), strscan_free(), strscan_get_byte(), strscan_get_charpos(), strscan_get_pos(), strscan_get_string(), strscan_getch(), strscan_initialize(), strscan_inspect(), strscan_mark(), strscan_matched(), strscan_matched_p(), strscan_matched_size(), strscan_memsize(), strscan_peek(), strscan_post_match(), strscan_pre_match(), strscan_reset(), strscan_rest(), strscan_rest_p(), strscan_rest_size(), strscan_s_allocate(), strscan_set_pos(), strscan_set_string(), strscan_terminate(), strscan_unscan(), strtol(), stub_sysinit(), swallow(), thread_join_sleep(), time_mdump(), time_mload(), time_strftime(), to_ascii(), token_info_get_column(), token_info_has_nonspaces(), transcode_restartable0(), translate_char(), translate_wchar(), type_cclass_hash(), unescape_escaped_nonascii(), unescape_unicode_bmp(), unescape_unicode_list(), unicode_to_jis_common2(), unset_addr_list_add(), unset_addr_list_init(), update_char_offset(), update_string_node_case_fold(), val2variant_ptr(), vm_make_env_object(), VpMemAlloc(), VpMemRealloc(), w_float(), window_free(), window_memsize(), winnt_stat(), wstati64(), yielder_mark(), and zlib_mem_alloc().
VALUE* parg = ALLOCA_N(VALUE, args)
Definition at line 787 of file win32ole.c.
static UINT __RPC_FAR * pctinfo
Initial value:
{
    return E_NOTIMPL
Definition at line 303 of file win32ole.c.
static DISPID REFIID LCID WORD DISPPARAMS __RPC_FAR * pDispParams
Definition at line 306 of file win32ole.c.
static DISPID REFIID LCID WORD DISPPARAMS __RPC_FAR VARIANT __RPC_FAR EXCEPINFO __RPC_FAR * pExcepInfo
Definition at line 306 of file win32ole.c.
static UINT LCID ITypeInfo __RPC_FAR *__RPC_FAR * ppTInfo
Initial value:
{
    return E_NOTIMPL
Definition at line 304 of file win32ole.c.
static REFIID void __RPC_FAR *__RPC_FAR * ppvObject
Initial value:
{
    if (MEMCMP(riid, &IID_IUnknown, GUID, 1) == 0
        || MEMCMP(riid, &IID_IMessageFilter, GUID, 1) == 0)
    {
        *ppvObject = &message_filter;
        return S_OK;
    }
    return E_NOINTERFACE
Definition at line 300 of file win32ole.c.
IMessageFilter* previous_filter static
Definition at line 244 of file win32ole.c.
Referenced by ole_initialize().
static DISPID REFIID LCID WORD DISPPARAMS __RPC_FAR VARIANT __RPC_FAR EXCEPINFO __RPC_FAR UINT __RPC_FAR * puArgErr
Initial value:
{
    VALUE v
Definition at line 306 of file win32ole.c.
static DISPID REFIID LCID WORD DISPPARAMS __RPC_FAR VARIANT __RPC_FAR * pVarResult
Definition at line 306 of file win32ole.c.
* rgDispId
Initial value:
{
    char* psz = ole_wc2mb(*rgszNames)
Definition at line 305 of file win32ole.c.
static REFIID LPOLESTR __RPC_FAR * rgszNames
Definition at line 305 of file win32ole.c.
static DISPID REFIID riid
Definition at line 300 of file win32ole.c.
return S_OK
Definition at line 769 of file win32ole.c.
Referenced by clsid_from_remote(), find_coclass(), fole_activex_initialize(), foletypelib_initialize(), foletypelib_path(), ole_each_sub(), ole_invoke2(), ole_set_safe_array(), ole_val2olevariantdata(), ole_val_ary2variant_ary(), and val2variant_ptr().
static HTASK threadIDCallee
Definition at line 662 of file win32ole.c.
DWORD HTASK threadIDCaller
Definition at line 628 of file win32ole.c.
v = rb_funcall2(p->obj, dispIdMember, args, parg)
Definition at line 798 of file win32ole.c.
Referenced by add64_to(), addrinfo_mload(), argf_init(), ary2ptr_dispparams(), ary_add_hash_by(), ary_reject(), ary_reject_bang(), Bfree(), bigsqr_fast(), bsock_setsockopt(), case_when_optimizable_literal(), check_exec_redirect1(), CHECK_INTEGER(), chunk_ii(), cn_i(), coerce_rescue(), cos_i(), cparse_params_mark(), cto_i(), d_lite_hash(), date_strftime_with_tmx(), dir_s_glob(), each_cons_i(), each_slice_i(), econv_convpath(), econv_opts(), econv_primitive_convert(), enumerator_feed(), env_select(), establishShell(), extract_binmode(), fdbm_select(), fetch_escaped_value(), fgdbm_select(), fsdbm_select(), gmtimew_noleapsecond(), initialize_params(), insn_data_to_s_detail(), int_pow(), int_sip_dump(), ip_invoke_real(), is_not_included(), iseq_build_from_ary_exception(), iseq_set_sequence(), JSON_parse_array(), JSON_parse_object(), lazy_zip(), lazy_zip_func(), lexer_i(), lexer_iter(), loggamma(), mark_current_machine_context(), mark_locations_array(), marshal_load(), match_inspect(), math_lgamma(), max_by_i(), method_inspect(), min_by_i(), mnew(), more_char(), n2i(), new_insn_body(), next_state_val(), nucomp_hash(), num_exact(), nurat_hash(), objspace_each_objects(), ole_invoke(), ole_invoke2(), ole_propertyput(), open_dir_handle(), open_key_args(), os_obj_of_i(), ossl_sslctx_set_ciphers(), pack_pack(), pack_unpack(), parse_char_class(), parser_nextc(), path2class(), path2module(), proc_options(), process_sflag(), quantifiers_memory_node_info(), r_byte(), r_entry0(), r_leave(), r_object0(), racc_cparse(), racc_yyparse(), rand_random(), rand_range(), range_dumper(), range_each_func(), range_include(), range_init(), range_step(), rb_ary_and(), rb_ary_assoc(), rb_ary_bsearch(), rb_ary_cmp(), rb_ary_delete(), rb_ary_fill(), rb_ary_or(), rb_ary_rassoc(), rb_ary_select_bang(), rb_ary_uniq(), rb_ary_uniq_bang(), rb_check_convert_type(), rb_check_to_integer(), rb_const_remove(), rb_convert_type(), rb_econv_asciicompat_encoding(), rb_econv_prepare_options(), rb_f_rand(), rb_feature_p(), rb_file_expand_path_internal(), rb_float_new(), rb_float_value(), rb_hash_s_create(), rb_io_extract_encoding_option(), rb_io_extract_modeenc(), rb_mod_remove_method(), rb_mod_to_s(), rb_mod_undef_method(), rb_num2fix(), rb_num_to_uint(), rb_obj_remove_instance_variable(), rb_print_undef(), rb_proc_exec_n(), rb_random_real(), rb_random_ulong_limited(), rb_reg_s_union(), rb_reg_s_union_m(), rb_stat_inspect(), rb_str_format(), rb_str_to_dbl(), rb_str_to_inum(), rb_time_unmagnify_to_float(), rb_to_integer(), rb_w32_aspawn_flags(), rb_w32_spawn(), rb_yield_splat(), read_all(), read_digits(), recursive_cmp(), recursive_hash(), reduce0(), rotl64_swap(), rotl64_to(), rsock_sockaddr_string_value(), RUBY_ALIAS_FUNCTION(), ruby_executable_node(), search_convpath_i(), set_const_visibility(), set_method_visibility(), sockopt_data(), sockopt_inspect(), sort_by_i(), st_hash_uint(), time_mdump(), time_round(), time_to_r(), timelocalw(), total_i(), tr_find(), vm_expandarray(), VpAlloc(), VpLeftRound(), VpMidRound(), vtdate2rbtime(), vtm_add_offset(), w_object(), warn_unused_var(), wstati64(), xor64_to(), and zip_i().
IEventSinkVtbl vtEventSink static
Definition at line 7579 of file win32ole.c.
Referenced by EVENTSINK_Constructor().
static DISPID REFIID LCID WORD wFlags
Definition at line 306 of file win32ole.c.