Ruby: internal.h File Reference
internal.h File Reference
Data Structures
struct rb_deprecated_classext_struct
struct rb_classext_struct
struct rb_execarg
Macros
#define MUL_OVERFLOW_SIGNED_INTEGER_P(a, b, min, max)
#define MUL_OVERFLOW_FIXNUM_P(a, b) MUL_OVERFLOW_SIGNED_INTEGER_P(a, b, FIXNUM_MIN, FIXNUM_MAX)
#define MUL_OVERFLOW_LONG_P(a, b) MUL_OVERFLOW_SIGNED_INTEGER_P(a, b, LONG_MIN, LONG_MAX)
#define RCLASS_EXT(c) (RCLASS(c)->ptr)
#define RCLASS_SUPER(c) (RCLASS_EXT(c)->super)
#define RCLASS_IV_TBL(c) (RCLASS_EXT(c)->iv_tbl)
#define RCLASS_CONST_TBL(c) (RCLASS_EXT(c)->const_tbl)
#define RCLASS_M_TBL(c) (RCLASS(c)->m_tbl)
#define RCLASS_IV_INDEX_TBL(c) (RCLASS(c)->iv_index_tbl)
#define RCLASS_ORIGIN(c) (RCLASS_EXT(c)->origin)
#define RCLASS_REFINED_CLASS(c) (RCLASS_EXT(c)->refined_class)
#define RB_MAX_GROUPS (65536)
#define ARGVSTR2ARGC(argv_str) (RSTRING_LEN(argv_str) / sizeof(char *) - 2)
#define ARGVSTR2ARGV(argv_str) ((char **)RSTRING_PTR(argv_str) + 1)
#define QUOTE(str) rb_str_quote_unprintable(str)
#define QUOTE_ID(id) rb_id_quote_unprintable(id)
#define MUL_OVERFLOW_SIGNED_INTEGER_P(a, b, min, max)
#define MUL_OVERFLOW_FIXNUM_P(a, b) MUL_OVERFLOW_SIGNED_INTEGER_P(a, b, FIXNUM_MIN, FIXNUM_MAX)
#define MUL_OVERFLOW_LONG_P(a, b) MUL_OVERFLOW_SIGNED_INTEGER_P(a, b, LONG_MIN, LONG_MAX)
#define RCLASS_EXT(c) (RCLASS(c)->ptr)
#define RCLASS_SUPER(c) (RCLASS_EXT(c)->super)
#define RCLASS_IV_TBL(c) (RCLASS_EXT(c)->iv_tbl)
#define RCLASS_CONST_TBL(c) (RCLASS_EXT(c)->const_tbl)
#define RCLASS_M_TBL(c) (RCLASS(c)->m_tbl)
#define RCLASS_IV_INDEX_TBL(c) (RCLASS(c)->iv_index_tbl)
#define RCLASS_ORIGIN(c) (RCLASS_EXT(c)->origin)
#define RCLASS_REFINED_CLASS(c) (RCLASS_EXT(c)->refined_class)
#define RB_MAX_GROUPS (65536)
#define ARGVSTR2ARGC(argv_str) (RSTRING_LEN(argv_str) / sizeof(char *) - 2)
#define ARGVSTR2ARGV(argv_str) ((char **)RSTRING_PTR(argv_str) + 1)
#define QUOTE(str) rb_str_quote_unprintable(str)
#define QUOTE_ID(id) rb_id_quote_unprintable(id)
#define MUL_OVERFLOW_SIGNED_INTEGER_P(a, b, min, max)
#define MUL_OVERFLOW_FIXNUM_P(a, b) MUL_OVERFLOW_SIGNED_INTEGER_P(a, b, FIXNUM_MIN, FIXNUM_MAX)
#define MUL_OVERFLOW_LONG_P(a, b) MUL_OVERFLOW_SIGNED_INTEGER_P(a, b, LONG_MIN, LONG_MAX)
#define RCLASS_EXT(c) (RCLASS(c)->ptr)
#define RCLASS_SUPER(c) (RCLASS_EXT(c)->super)
#define RCLASS_IV_TBL(c) (RCLASS_EXT(c)->iv_tbl)
#define RCLASS_CONST_TBL(c) (RCLASS_EXT(c)->const_tbl)
#define RCLASS_M_TBL(c) (RCLASS(c)->m_tbl)
#define RCLASS_IV_INDEX_TBL(c) (RCLASS(c)->iv_index_tbl)
#define RCLASS_ORIGIN(c) (RCLASS_EXT(c)->origin)
#define RCLASS_REFINED_CLASS(c) (RCLASS_EXT(c)->refined_class)
#define RB_MAX_GROUPS (65536)
#define ARGVSTR2ARGC(argv_str) (RSTRING_LEN(argv_str) / sizeof(char *) - 2)
#define ARGVSTR2ARGV(argv_str) ((char **)RSTRING_PTR(argv_str) + 1)
#define QUOTE(str) rb_str_quote_unprintable(str)
#define QUOTE_ID(id) rb_id_quote_unprintable(id)
Typedefs
typedef void rb_check_funcall_hook (int, VALUE, ID, int, VALUE *, VALUE)
Functions
VALUE rb_ary_last (int, VALUE *, VALUE)
void rb_ary_set_len (VALUE, long)
VALUE rb_ary_cat (VALUE, const VALUE *, long)
void rb_ary_delete_same (VALUE, VALUE)
VALUE rb_big_fdiv (VALUE x, VALUE y)
VALUE rb_big_uminus (VALUE x)
VALUE rb_integer_float_cmp (VALUE x, VALUE y)
VALUE rb_integer_float_eq (VALUE x, VALUE y)
VALUE rb_obj_methods (int argc, VALUE *argv, VALUE obj)
VALUE rb_obj_protected_methods (int argc, VALUE *argv, VALUE obj)
VALUE rb_obj_private_methods (int argc, VALUE *argv, VALUE obj)
VALUE rb_obj_public_methods (int argc, VALUE *argv, VALUE obj)
int rb_obj_basic_to_s_p (VALUE)
VALUE rb_special_singleton_class (VALUE)
VALUE rb_singleton_class_clone_and_attach (VALUE obj, VALUE attach)
void Init_class_hierarchy (void)
VALUE rb_invcmp (VALUE, VALUE)
int rb_dvar_defined (ID)
int rb_local_defined (ID)
int rb_parse_in_eval (void)
int rb_parse_in_main (void)
const char * rb_insns_name (int i)
VALUE rb_insns_name_array (void)
VALUE rb_obj_is_fiber (VALUE)
void rb_fiber_reset_root_local_storage (VALUE)
PRINTF_ARGS (void ruby_debug_printf(const char *,...), 1, 2)
void Init_ext (void)
ID rb_id_encoding (void)
void rb_gc_mark_encodings (void)
NORETURN (PRINTF_ARGS(void rb_compile_bug(const char *, int, const char *,...), 3, 4))
VALUE rb_check_backtrace (VALUE)
NORETURN (void rb_async_bug_errno(const char *, int))
const char * rb_builtin_type_name (int t)
const char * rb_builtin_class_name (VALUE x)
VALUE rb_refinement_module_get_refined_class (VALUE module)
void ruby_error_print (void)
VALUE rb_get_backtrace (VALUE info)
void rb_call_end_proc (VALUE data)
void rb_mark_end_proc (void)
VALUE rb_home_dir (const char *user, VALUE result)
VALUE rb_realpath_internal (VALUE basedir, VALUE path, int strict)
void rb_file_const (const char *, VALUE)
int rb_file_load_ok (const char *)
VALUE rb_file_expand_path_fast (VALUE, VALUE)
VALUE rb_file_expand_path_internal (VALUE, VALUE, int, int, VALUE)
VALUE rb_get_path_check_to_string (VALUE, int)
VALUE rb_get_path_check_convert (VALUE, VALUE, int)
void Init_File (void)
void Init_heap (void)
void * ruby_mimmalloc (size_t size)
void rb_call_inits (void)
const char * ruby_get_inplace_mode (void)
void ruby_set_inplace_mode (const char *)
ssize_t rb_io_bufread (VALUE io, void *buf, size_t size)
void rb_stdio_set_default_encoding (void)
void rb_write_error_str (VALUE mesg)
VALUE rb_iseq_clone (VALUE iseqval, VALUE newcbase)
VALUE rb_get_load_path (void)
VALUE rb_get_expanded_load_path (void)
NORETURN (void rb_load_fail(VALUE, const char *))
VALUE rb_math_atan2 (VALUE, VALUE)
VALUE rb_math_cos (VALUE)
VALUE rb_math_cosh (VALUE)
VALUE rb_math_exp (VALUE)
VALUE rb_math_hypot (VALUE, VALUE)
VALUE rb_math_log (int argc, VALUE *argv)
VALUE rb_math_sin (VALUE)
VALUE rb_math_sinh (VALUE)
VALUE rb_math_sqrt (VALUE)
void Init_newline (void)
int rb_num_to_uint (VALUE val, unsigned int *ret)
VALUE num_interval_step_size (VALUE from, VALUE to, VALUE step, int excl)
int ruby_float_step (VALUE from, VALUE to, VALUE step, int excl)
double ruby_float_mod (double x, double y)
int rb_num_negative_p (VALUE)
VALUE rb_obj_equal (VALUE obj1, VALUE obj2)
VALUE rb_parser_get_yydebug (VALUE)
VALUE rb_parser_set_yydebug (VALUE, VALUE)
int rb_is_const_name (VALUE name)
int rb_is_class_name (VALUE name)
int rb_is_global_name (VALUE name)
int rb_is_instance_name (VALUE name)
int rb_is_attrset_name (VALUE name)
int rb_is_local_name (VALUE name)
int rb_is_method_name (VALUE name)
int rb_is_junk_name (VALUE name)
void rb_gc_mark_parser (void)
void rb_gc_mark_symbols (void)
VALUE rb_proc_location (VALUE self)
st_index_t rb_hash_proc (st_index_t hash, VALUE proc)
rb_pid_t rb_fork_ruby (int *status)
void rb_last_status_clear (void)
VALUE rb_lcm (VALUE x, VALUE y)
VALUE rb_rational_reciprocal (VALUE x)
VALUE rb_reg_compile (VALUE str, int options, const char *sourcefile, int sourceline)
VALUE rb_reg_check_preprocess (VALUE)
int rb_get_next_signal (void)
int rb_sigaltstack_size (void)
int rb_str_buf_cat_escaped_char (VALUE result, unsigned int c, int unicode_p)
int rb_str_symname_p (VALUE)
VALUE rb_str_quote_unprintable (VALUE)
VALUE rb_id_quote_unprintable (ID)
VALUE rb_struct_init_copy (VALUE copy, VALUE s)
struct timeval rb_time_timeval (VALUE)
VALUE rb_obj_is_mutex (VALUE obj)
VALUE rb_suppress_tracing (VALUE(*func)(VALUE), VALUE arg)
void rb_thread_execute_interrupts (VALUE th)
void rb_clear_trace_func (void)
VALUE rb_get_coverages (void)
VALUE rb_thread_shield_new (void)
VALUE rb_thread_shield_wait (VALUE self)
VALUE rb_thread_shield_release (VALUE self)
VALUE rb_thread_shield_destroy (VALUE self)
void rb_mutex_allow_trap (VALUE self, int val)
VALUE rb_uninterruptible (VALUE(*b_proc)(ANYARGS), VALUE data)
VALUE rb_mutex_owned_p (VALUE self)
void Init_native_thread (void)
VALUE rb_obj_is_thread (VALUE obj)
void rb_vm_mark (void *ptr)
void Init_BareVM (void)
VALUE rb_vm_top_self (void)
void rb_thread_recycle_stack_release (VALUE *)
void rb_vm_change_state (void)
void rb_vm_inc_const_missing_count (void)
void rb_thread_mark (void *th)
const void ** rb_vm_get_insns_address_table (void)
VALUE rb_sourcefilename (void)
void rb_vm_bugreport (void)
void Init_vm_eval (void)
VALUE rb_current_realfilepath (void)
VALUE rb_check_block_call (VALUE, ID, int, VALUE *, VALUE(*)(ANYARGS), VALUE)
VALUE rb_check_funcall_with_hook (VALUE recv, ID mid, int argc, VALUE *argv, rb_check_funcall_hook *hook, VALUE arg)
void Init_eval_method (void)
int rb_method_defined_by (VALUE obj, ID mid, VALUE(*cfunc)(ANYARGS))
void Init_prelude (void)
void Init_vm_backtrace (void)
VALUE vm_thread_backtrace (int argc, VALUE *argv, VALUE thval)
VALUE vm_thread_backtrace_locations (int argc, VALUE *argv, VALUE thval)
VALUE rb_make_backtrace (void)
void rb_backtrace_print_as_bugreport (void)
int rb_backtrace_p (VALUE obj)
VALUE rb_backtrace_to_str_ary (VALUE obj)
VALUE rb_vm_backtrace_object ()
const char * rb_objspace_data_type_name (VALUE obj)
VALUE rb_thread_io_blocking_region (rb_blocking_function_t *func, void *data1, int fd)
void rb_maygvl_fd_fix_cloexec (int fd)
int rb_exec_async_signal_safe (const struct rb_execarg *e, char *errmsg, size_t errmsg_buflen)
rb_pid_t rb_fork_async_signal_safe (int *status, int(*chfunc)(void *, char *, size_t), void *charg, VALUE fds, char *errmsg, size_t errmsg_buflen)
VALUE rb_execarg_new (int argc, VALUE *argv, int accept_shell)
struct rb_execarg * rb_execarg_get (VALUE execarg_obj)
VALUE rb_execarg_init (int argc, VALUE *argv, int accept_shell, VALUE execarg_obj)
int rb_execarg_addopt (VALUE execarg_obj, VALUE key, VALUE val)
void rb_execarg_fixup (VALUE execarg_obj)
int rb_execarg_run_options (const struct rb_execarg *e, struct rb_execarg *s, char *errmsg, size_t errmsg_buflen)
VALUE rb_execarg_extract_options (VALUE execarg_obj, VALUE opthash)
void rb_execarg_setenv (VALUE execarg_obj, VALUE env)
void rb_gc_mark_global_tbl (void)
void rb_mark_generic_ivar (VALUE)
void rb_mark_generic_ivar_tbl (void)
Macro Definition Documentation
#define ARGVSTR2ARGC (argv_str) (RSTRING_LEN(argv_str) / sizeof(char *) - 2)
Referenced by rb_spawn_process().
#define ARGVSTR2ARGC (argv_str) (RSTRING_LEN(argv_str) / sizeof(char *) - 2)
#define ARGVSTR2ARGC (argv_str) (RSTRING_LEN(argv_str) / sizeof(char *) - 2)
Definition at line 253 of file parse.y.
#define ARGVSTR2ARGV (argv_str) ((char **)RSTRING_PTR(argv_str) + 1)
#define ARGVSTR2ARGV (argv_str) ((char **)RSTRING_PTR(argv_str) + 1)
Referenced by pipe_open(), proc_exec_cmd(), and rb_spawn_process().
#define ARGVSTR2ARGV (argv_str) ((char **)RSTRING_PTR(argv_str) + 1)
Definition at line 254 of file parse.y.
#define MUL_OVERFLOW_FIXNUM_P (a, b) MUL_OVERFLOW_SIGNED_INTEGER_P(a, b, FIXNUM_MIN, FIXNUM_MAX)
#define MUL_OVERFLOW_FIXNUM_P (a, b) MUL_OVERFLOW_SIGNED_INTEGER_P(a, b, FIXNUM_MIN, FIXNUM_MAX)
Definition at line 29 of file parse.y.
#define MUL_OVERFLOW_FIXNUM_P (a, b) MUL_OVERFLOW_SIGNED_INTEGER_P(a, b, FIXNUM_MIN, FIXNUM_MAX)
Referenced by fix_mul(), and int_pow().
#define MUL_OVERFLOW_LONG_P (a, b) MUL_OVERFLOW_SIGNED_INTEGER_P(a, b, LONG_MIN, LONG_MAX)
Definition at line 30 of file parse.y.
#define MUL_OVERFLOW_LONG_P (a, b) MUL_OVERFLOW_SIGNED_INTEGER_P(a, b, LONG_MIN, LONG_MAX)
#define MUL_OVERFLOW_LONG_P (a, b) MUL_OVERFLOW_SIGNED_INTEGER_P(a, b, LONG_MIN, LONG_MAX)
Referenced by f_imul(), and rb_ary_product().
#define MUL_OVERFLOW_SIGNED_INTEGER_P (a, b, min, max)
Value:
(\
    (a) == 0 ? 0 : \
    (a) == -1 ? (b) < -(max) : \
    (a) > 0 ? \
      ((b) > 0 ? (max) / (a) < (b) : (min) / (a) > (b)) : \
      ((b) > 0 ? (min) / (a) < (b) : (max) / (a) > (b)))
#define MUL_OVERFLOW_SIGNED_INTEGER_P (a, b, min, max)
Value:
(\
    (a) == 0 ? 0 : \
    (a) == -1 ? (b) < -(max) : \
    (a) > 0 ? \
      ((b) > 0 ? (max) / (a) < (b) : (min) / (a) > (b)) : \
      ((b) > 0 ? (min) / (a) < (b) : (max) / (a) > (b)))
#define MUL_OVERFLOW_SIGNED_INTEGER_P (a, b, min, max)
Value:
(\
    (a) == 0 ? 0 : \
    (a) == -1 ? (b) < -(max) : \
    (a) > 0 ? \
      ((b) > 0 ? (max) / (a) < (b) : (min) / (a) > (b)) : \
      ((b) > 0 ? (min) / (a) < (b) : (max) / (a) > (b)))
Definition at line 23 of file parse.y.
#define QUOTE (str) rb_str_quote_unprintable(str)
#define QUOTE (str) rb_str_quote_unprintable(str)
Referenced by rb_f_untrace_var(), rb_method_name_error(), rb_mod_const_defined(), rb_mod_const_get(), rb_mod_cvar_defined(), rb_mod_cvar_get(), rb_mod_remove_const(), rb_mod_remove_cvar(), rb_obj_ivar_defined(), rb_obj_ivar_get(), rb_obj_remove_instance_variable(), rb_path_to_class(), rb_print_undef_str(), and set_const_visibility().
#define QUOTE (str) rb_str_quote_unprintable(str)
Definition at line 284 of file parse.y.
#define QUOTE_ID (id) rb_id_quote_unprintable(id)
Referenced by generic_ivar_get(), ivar_get(), rb_autoload(), rb_const_get_0(), rb_const_remove(), rb_const_set(), rb_cvar_get(), rb_cvar_set(), rb_f_untrace_var(), rb_mod_const_defined(), rb_mod_const_get(), rb_mod_const_set(), rb_mod_cvar_defined(), rb_mod_cvar_get(), rb_mod_cvar_set(), rb_mod_remove_const(), rb_mod_remove_cvar(), rb_obj_ivar_defined(), rb_obj_ivar_get(), rb_obj_ivar_set(), rb_obj_remove_instance_variable(), rb_obj_respond_to(), rb_print_undef(), rb_undef(), readonly_setter(), set_const_visibility(), undef_getter(), and uninitialized_constant().
#define QUOTE_ID (id) rb_id_quote_unprintable(id)
Definition at line 285 of file parse.y.
#define QUOTE_ID (id) rb_id_quote_unprintable(id)
#define RB_MAX_GROUPS (65536)
#define RB_MAX_GROUPS (65536)
Referenced by rb_group_member().
#define RB_MAX_GROUPS (65536)
Definition at line 205 of file parse.y.
#define RCLASS_CONST_TBL (c) (RCLASS_EXT(c)->const_tbl)
#define RCLASS_CONST_TBL (c) (RCLASS_EXT(c)->const_tbl)
Definition at line 49 of file parse.y.
#define RCLASS_CONST_TBL (c) (RCLASS_EXT(c)->const_tbl)
Referenced by autoload_defined_p(), autoload_delete(), class_alloc(), fc_i(), find_class_path(), init_copy(), obj_free(), rb_autoload(), rb_const_defined_0(), rb_const_get_0(), rb_const_remove(), rb_const_set(), rb_include_class_new(), rb_mod_const_at(), rb_mod_init_copy(), rb_singleton_class_clone_and_attach(), set_const_visibility(), and vm_get_ev_const().
#define RCLASS_EXT (c) (RCLASS(c)->ptr)
Referenced by class_alloc(), rb_define_alloc_func(), rb_get_alloc_func(), rb_mod_init_copy(), and rb_singleton_class_clone_and_attach().
#define RCLASS_EXT (c) (RCLASS(c)->ptr)
#define RCLASS_EXT (c) (RCLASS(c)->ptr)
Definition at line 46 of file parse.y.
#define RCLASS_IV_INDEX_TBL (c) (RCLASS(c)->iv_index_tbl)
Referenced by class_alloc(), memsize_of(), obj_free(), and rb_ivar_set().
#define RCLASS_IV_INDEX_TBL (c) (RCLASS(c)->iv_index_tbl)
#define RCLASS_IV_INDEX_TBL (c) (RCLASS(c)->iv_index_tbl)
Definition at line 51 of file parse.y.
#define RCLASS_IV_TBL (c) (RCLASS_EXT(c)->iv_tbl)
Referenced by autoload_data(), autoload_delete(), class_alloc(), classname(), cvar_lookup_at(), fc_path(), find_class_path(), init_copy(), ivar_get(), memsize_of(), mod_cvar_at(), obj_free(), rb_autoload(), rb_cvar_get(), rb_cvar_set(), rb_include_class_new(), rb_ivar_count(), rb_ivar_defined(), rb_ivar_foreach(), rb_ivar_set(), rb_mod_init_copy(), rb_mod_remove_cvar(), rb_obj_remove_instance_variable(), rb_singleton_class_attached(), rb_singleton_class_clone_and_attach(), and rb_tmp_class_path().
#define RCLASS_IV_TBL (c) (RCLASS_EXT(c)->iv_tbl)
Definition at line 48 of file parse.y.
#define RCLASS_IV_TBL (c) (RCLASS_EXT(c)->iv_tbl)
#define RCLASS_M_TBL (c) (RCLASS(c)->m_tbl)
Definition at line 50 of file parse.y.
#define RCLASS_M_TBL (c) (RCLASS(c)->m_tbl)
#define RCLASS_M_TBL (c) (RCLASS(c)->m_tbl)
Referenced by add_opt_method(), class_alloc(), class_instance_method_list(), include_modules_at(), lookup_method_table(), memsize_of(), obj_free(), rb_class_boot(), rb_class_inherited_p(), rb_include_class_new(), rb_method_entry_make(), rb_mod_init_copy(), rb_module_new(), rb_obj_is_kind_of(), rb_obj_singleton_methods(), rb_prepend_module(), rb_singleton_class_clone_and_attach(), rb_using_refinement(), rb_vm_check_redefinition_by_prepend(), and remove_method().
#define RCLASS_ORIGIN (c) (RCLASS_EXT(c)->origin)
#define RCLASS_ORIGIN (c) (RCLASS_EXT(c)->origin)
Referenced by class_alloc(), class_instance_method_list(), include_modules_at(), rb_class_inherited_p(), rb_export_method(), rb_include_class_new(), rb_include_module(), rb_method_entry_make(), rb_mod_ancestors(), rb_mod_included_modules(), rb_obj_is_kind_of(), rb_prepend_module(), rb_vm_check_redefinition_by_prepend(), remove_method(), vm_search_normal_superclass(), and w_extended().
#define RCLASS_ORIGIN (c) (RCLASS_EXT(c)->origin)
Definition at line 52 of file parse.y.
#define RCLASS_REFINED_CLASS (c) (RCLASS_EXT(c)->refined_class)
Definition at line 53 of file parse.y.
#define RCLASS_REFINED_CLASS (c) (RCLASS_EXT(c)->refined_class)
Referenced by add_activated_refinement(), class_alloc(), rb_using_refinement(), and vm_search_super_method().
#define RCLASS_REFINED_CLASS (c) (RCLASS_EXT(c)->refined_class)
#define RCLASS_SUPER (c) (RCLASS_EXT(c)->super)
#define RCLASS_SUPER (c) (RCLASS_EXT(c)->super)
#define RCLASS_SUPER (c) (RCLASS_EXT(c)->super)
Definition at line 47 of file parse.y.
Typedef Documentation
typedef void rb_check_funcall_hook(int, VALUE, ID, int, VALUE *, VALUE)
Definition at line 328 of file internal.h.
Function Documentation
void Init_BareVM (void)
Definition at line 2394 of file vm.c.
References EXIT_FAILURE, Init_native_thread(), MEMZERO, rb_vm_struct::objspace, rb_objspace_alloc(), rb_thread_set_current_raw, ruby_mimmalloc(), ruby_thread_init_stack(), th_init(), rb_thread_struct::vm, and vm_init2().
void Init_eval_method (void)
Definition at line 1618 of file vm_method.c.
References added, attached, idRespond_to, idRespond_to_missing, NOEX_PRIVATE, NOEX_PUBLIC, obj_respond_to(), obj_respond_to_missing(), object_id, rb_cModule, rb_define_method(), rb_define_private_method(), rb_eException, rb_intern, rb_mKernel, rb_mod_alias_method(), rb_mod_method_defined(), rb_mod_modfunc(), rb_mod_private(), rb_mod_private_method(), rb_mod_private_method_defined(), rb_mod_protected(), rb_mod_protected_method_defined(), rb_mod_public(), rb_mod_public_method(), rb_mod_public_method_defined(), rb_mod_remove_method(), rb_mod_undef_method(), rb_singleton_class(), rb_vm_top_self(), removed, REPLICATE_METHOD, singleton_added, singleton_removed, singleton_undefined, top_private(), top_public(), and undefined.
void Init_ext (void)
Definition at line 2 of file dmyext.c.
Referenced by init_libraries_internal(), and require_libraries().
void Init_File (void)
Definition at line 5488 of file file.c.
References define_filetest_function(), INT2FIX, LOCK_EX, LOCK_NB, LOCK_SH, LOCK_UN, O_BINARY, O_NONBLOCK, PATH_SEP, Qnil, rb_cIO, rb_cObject, rb_define_alloc_func(), rb_define_class(), rb_define_class_under(), rb_define_const(), rb_define_global_function(), rb_define_method(), rb_define_module(), rb_define_module_under(), rb_define_singleton_method(), rb_f_test(), rb_file_atime(), rb_file_blockdev_p(), rb_file_chardev_p(), rb_file_chmod(), rb_file_chown(), rb_file_ctime(), rb_file_directory_p(), rb_file_executable_p(), rb_file_executable_real_p(), rb_file_exist_p(), rb_file_file_p(), rb_file_flock(), rb_file_grpowned_p(), rb_file_identical_p(), rb_file_lstat(), rb_file_mtime(), rb_file_owned_p(), rb_file_path(), rb_file_pipe_p(), rb_file_readable_p(), rb_file_readable_real_p(), rb_file_s_absolute_path(), rb_file_s_atime(), rb_file_s_basename(), rb_file_s_chmod(), rb_file_s_chown(), rb_file_s_ctime(), rb_file_s_dirname(), rb_file_s_expand_path(), rb_file_s_extname(), rb_file_s_ftype(), rb_file_s_join(), rb_file_s_lchmod, rb_file_s_lchown, rb_file_s_link, rb_file_s_lstat(), rb_file_s_mtime(), rb_file_s_path(), rb_file_s_readlink, rb_file_s_realdirpath(), rb_file_s_realpath(), rb_file_s_rename(), rb_file_s_size(), rb_file_s_split(), rb_file_s_stat(), rb_file_s_symlink, rb_file_s_truncate, rb_file_s_umask(), rb_file_s_unlink(), rb_file_s_utime(), rb_file_sgid_p(), rb_file_size(), rb_file_size_p(), rb_file_socket_p(), rb_file_sticky_p(), rb_file_suid_p(), rb_file_symlink_p(), rb_file_truncate, rb_file_world_readable_p(), rb_file_world_writable_p(), rb_file_writable_p(), rb_file_writable_real_p(), rb_file_zero_p(), rb_include_module(), rb_io_stat(), rb_mComparable, rb_obj_freeze(), rb_stat_atime(), rb_stat_b(), rb_stat_blksize(), rb_stat_blocks(), rb_stat_c(), rb_stat_cmp(), rb_stat_ctime(), rb_stat_d(), rb_stat_dev(), rb_stat_dev_major(), rb_stat_dev_minor(), rb_stat_f(), rb_stat_ftype(), rb_stat_gid(), rb_stat_grpowned(), rb_stat_init(), rb_stat_init_copy(), rb_stat_ino(), rb_stat_inspect(), rb_stat_l(), rb_stat_mode(), rb_stat_mtime(), rb_stat_nlink(), rb_stat_owned(), rb_stat_p(), rb_stat_r(), rb_stat_R(), rb_stat_rdev(), rb_stat_rdev_major(), rb_stat_rdev_minor(), rb_stat_S(), rb_stat_s(), rb_stat_s_alloc(), rb_stat_sgid(), rb_stat_size(), rb_stat_sticky(), rb_stat_suid(), rb_stat_uid(), rb_stat_w(), rb_stat_W(), rb_stat_wr(), rb_stat_ww(), rb_stat_x(), rb_stat_X(), rb_stat_z(), rb_str_new2, rb_usascii_str_new2, and rb_w32_init_file().
void Init_heap (void)
Definition at line 1039 of file gc.c.
References init_heap().
void Init_native_thread (void)
void Init_newline (void)
Definition at line 183 of file newline.c.
References rb_cr_newline, rb_crlf_newline, rb_register_transcoder(), and rb_universal_newline.
void Init_prelude (void)
void Init_vm_backtrace (void)
Definition at line 944 of file vm_backtrace.c.
References backtrace_alloc(), backtrace_dump_data(), backtrace_load_data(), CLASS_OF, location_absolute_path_m(), location_base_label_m(), location_inspect_m(), location_label_m(), location_lineno_m(), location_path_m(), location_to_str_m(), rb_cArray, rb_cBacktrace, rb_cBacktraceLocation, rb_cObject, rb_cThread, rb_define_alloc_func(), rb_define_class_under(), rb_define_global_function(), rb_define_method(), rb_f_caller(), rb_f_caller_locations(), rb_marshal_define_compat(), rb_undef_alloc_func(), and rb_undef_method().
void Init_vm_eval (void)
Definition at line 1944 of file vm_eval.c.
References rb_add_method(), rb_cBasicObject, rb_cModule, rb_define_global_function(), rb_define_method(), rb_define_private_method(), rb_f_block_given_p(), rb_f_catch(), rb_f_eval(), rb_f_local_variables(), rb_f_loop(), rb_f_public_send(), rb_f_send(), rb_f_throw(), rb_intern, rb_method_missing(), rb_mKernel, rb_mod_module_eval(), rb_mod_module_exec(), rb_obj_instance_eval(), rb_obj_instance_exec(), and VM_METHOD_TYPE_OPTIMIZED.
NORETURN (PRINTF_ARGS(void rb_compile_bug(const char *, int, const char *,...), 3, 4))
NORETURN (void rb_async_bug_errnoconst char *, int)
NORETURN (void rb_load_failVALUE, const char *)
VALUE num_interval_step_size (VALUE from, VALUE to, VALUE step, int excl)
Definition at line 1814 of file numeric.c.
References cmp, DBL2NUM, diff(), FIX2LONG, FIXNUM_P, id_div, INT2FIX, isinf(), LONG2FIX, NUM2DBL, rb_funcall(), RB_TYPE_P, result, RTEST, ruby_float_step_size(), and T_FLOAT.
PRINTF_ARGS (void ruby_debug_printfconst char *,..., 1 , 2)
VALUE rb_ary_cat (VALUE , const VALUE * , long)
Definition at line 846 of file array.c.
References ary_ensure_room_for_push(), ARY_SET_LEN, MEMCPY, RARRAY_LEN, and RARRAY_PTR.
Referenced by enumerator_each(), features_index_add_single(), generator_each(), lazy_init_iterator(), and rb_ary_push_m().
void rb_ary_delete_same (VALUE , VALUE)
Definition at line 2790 of file array.c.
References ary_resize_smaller(), RARRAY_LEN, RARRAY_PTR, and rb_ary_store().
Referenced by wmap_final_func().
VALUE rb_ary_last (int , VALUE * , VALUE)
Definition at line 1258 of file array.c.
References ary_take_first_or_last(), ARY_TAKE_LAST, Qnil, RARRAY_LEN, and RARRAY_PTR.
Referenced by Init_Array(), and range_last().
void rb_ary_set_len (VALUE , long)
Definition at line 1490 of file array.c.
References ARY_CAPA, ARY_SET_LEN, ARY_SHARED_P, rb_ary_modify_check(), rb_bug(), rb_eRuntimeError, and rb_raise().
Referenced by method_missing().
int rb_backtrace_p (VALUE obj)
Definition at line 413 of file vm_backtrace.c.
References rb_typeddata_is_kind_of().
void rb_backtrace_print_as_bugreport (void)
Definition at line 750 of file vm_backtrace.c.
References backtrace_each(), oldbt_arg::data, oldbt_arg::func, GET_THREAD(), i, oldbt_bugreport(), oldbt_init(), oldbt_iter_cfunc(), and oldbt_iter_iseq().
VALUE rb_backtrace_to_str_ary (VALUE obj)
Definition at line 586 of file vm_backtrace.c.
References rb_backtrace_struct::backtrace_size, backtrace_to_str_ary(), bt_iter_arg::bt, GetCoreDataFromValue, and rb_backtrace_struct::strary.
VALUE rb_big_fdiv (VALUE x, VALUE y)
Definition at line 3123 of file bignum.c.
References big2dbl(), big_fdiv(), DBL2NUM, FIX2LONG, isinf(), isnan, rb_big2dbl(), rb_intern, rb_num_coerce_bin(), RFLOAT_VALUE, T_BIGNUM, T_FIXNUM, T_FLOAT, and TYPE.
Referenced by fix_fdiv(), and Init_Bignum().
VALUE rb_big_uminus (VALUE x)
Definition at line 1754 of file bignum.c.
References bignorm(), rb_big_clone(), RBIGNUM_SET_SIGN, and RBIGNUM_SIGN.
Referenced by Init_Bignum().
const char* rb_builtin_class_name (VALUE x)
Definition at line 414 of file error.c.
References FIXNUM_P, NIL_P, rb_obj_classname(), RB_TYPE_P, SYMBOL_P, T_FALSE, and T_TRUE.
Referenced by rb_hash_s_create().
const char* rb_builtin_type_name (int t)
Definition at line 403 of file error.c.
References builtin_types, name, and numberof.
Referenced by rb_check_type().
void rb_call_end_proc (VALUE data)
Definition at line 11 of file eval_jump.c.
References rb_ary_new(), and rb_proc_call().
Referenced by m_core_set_postexe(), and rb_f_at_exit().
void rb_call_inits (void)
Definition at line 18 of file inits.c.
References CALL, signal(), sym, and version().
VALUE rb_check_backtrace (VALUE)
Definition at line 710 of file error.c.
References err, i, NIL_P, RARRAY_LEN, RARRAY_PTR, rb_ary_new3(), rb_backtrace_p(), rb_eTypeError, rb_raise(), RB_TYPE_P, T_ARRAY, and T_STRING.
Referenced by exc_set_backtrace(), and get_backtrace().
VALUE rb_check_block_call (VALUE , ID , int , VALUE * , VALUE(*)(ANYARGS) , VALUE)
Definition at line 1153 of file vm_eval.c.
References argc, iter_method_arg::argc, argv, iter_method_arg::argv, iterate_check_method(), iter_method_arg::mid, iter_method_arg::obj, and rb_iterate().
VALUE rb_check_funcall_with_hook (VALUE recv, ID mid, int argc, VALUE * argv, rb_check_funcall_hook * hook, VALUE arg)
Definition at line 427 of file vm_eval.c.
References arg, argc, argv, check_funcall_callable(), check_funcall_missing(), check_funcall_respond_to(), CLASS_OF, FALSE, GET_THREAD(), NOEX_OK, Qundef, rb_search_method_entry(), rescue_funcall_args::recv, stack_check(), TRUE, and vm_call0().
void rb_clear_trace_func (void)
Definition at line 215 of file vm_trace.c.
References clear_trace_func_i(), GET_VM, rb_remove_event_hook(), and st_foreach().
VALUE rb_current_realfilepath (void)
Definition at line 1934 of file vm_eval.c.
References rb_iseq_location_struct::absolute_path, rb_thread_struct::cfp, GET_THREAD(), rb_control_frame_struct::iseq, rb_iseq_struct::location, Qnil, RUBY_VM_PREVIOUS_CONTROL_FRAME, and vm_get_ruby_level_caller_cfp().
int rb_dvar_defined (ID)
Definition at line 5832 of file compile.c.
References rb_thread_struct::base_block, GET_THREAD(), i, rb_block_struct::iseq, rb_iseq_struct::local_table, rb_iseq_struct::local_table_size, rb_iseq_struct::parent_iseq, and rb_iseq_struct::type.
Referenced by dvar_defined_gen().
int rb_exec_async_signal_safe (const struct rb_execarg * e, char * errmsg, size_t errmsg_buflen)
Definition at line 3019 of file process.c.
References after_exec_async_signal_safe(), before_exec_async_signal_safe(), rb_execarg::cmd, rb_execarg::envp_str, rb_execarg::invoke, NIL_P, NULL, preserving_errno, proc_exec_cmd(), proc_exec_sh(), rb_execarg_run_options(), RSTRING_PTR, rb_execarg::sh, and rb_execarg::use_shell.
int rb_execarg_addopt (VALUE execarg_obj, VALUE key, VALUE val)
Definition at line 1606 of file process.c.
References rb_execarg::chdir_dir, rb_execarg::chdir_given, check_exec_redirect(), check_gid_switch(), check_uid_switch(), rb_execarg::close_others_do, rb_execarg::close_others_given, FilePathValue, rb_execarg::gid, rb_execarg::gid_given, hide_obj(), id, INT2FIX, INT2NUM, mode_t, rb_execarg::new_pgroup_flag, rb_execarg::new_pgroup_given, NIL_P, NUM2MODET, NUM2PIDT, OBJ2GID, OBJ2UID, rb_execarg::pgroup_given, rb_execarg::pgroup_pgid, PREPARE_GETGRNAM, PREPARE_GETPWNAM, Qfalse, Qtrue, RARRAY_LEN, rb_ary_entry(), rb_ary_new(), rb_ary_new3(), rb_ary_push(), rb_check_array_type(), rb_eArgError, rb_eNotImpError, rb_execarg_get(), RB_GC_GUARD, rb_id2name(), rb_intern, rb_raise(), rb_secure(), rb_str_dup(), rb_to_int(), rb_execarg::rlimit_limits, RTEST, ST_CONTINUE, ST_STOP, SYM2ID, T_ARRAY, T_FILE, T_FIXNUM, T_SYMBOL, TYPE, rb_execarg::uid, rb_execarg::uid_given, rb_execarg::umask_given, rb_execarg::umask_mask, rb_execarg::unsetenv_others_do, and rb_execarg::unsetenv_others_given.
VALUE rb_execarg_extract_options (VALUE execarg_obj, VALUE opthash)
Definition at line 1897 of file process.c.
References args, check_exec_options_i_extract(), Qnil, RHASH_EMPTY_P, RHASH_TBL, and st_foreach().
void rb_execarg_fixup (VALUE execarg_obj)
Definition at line 2254 of file process.c.
References check_exec_fds(), rb_execarg::dup2_tmpbuf, rb_execarg::env_modification, rb_execarg::envp_buf, rb_execarg::envp_str, envtbl, rb_execarg::fd_dup2, fill_envp_buf_i(), hide_obj(), i, key, NIL_P, NULL, p, Qfalse, RARRAY_LEN, RARRAY_PTR, rb_cObject, rb_const_get(), rb_convert_type(), rb_execarg_get(), RB_GC_GUARD, rb_hash_new(), rb_intern, rb_str_buf_cat(), rb_str_buf_new(), rb_str_new(), rb_str_set_len(), rb_execarg::redirect_fds, RHASH_SIZE, RHASH_TBL, RSTRING_LEN, RSTRING_PTR, run_exec_dup2_tmpbuf_size(), st_delete(), st_foreach(), st_insert(), strlen(), T_HASH, tmpbuf, rb_execarg::unsetenv_others_do, rb_execarg::unsetenv_others_given, and val.
struct rb_execarg* rb_execarg_get (VALUE execarg_obj) read
Definition at line 2201 of file process.c.
References exec_arg_data_type, and TypedData_Get_Struct.
VALUE rb_execarg_init (int argc, VALUE * argv, int accept_shell, VALUE execarg_obj)
Definition at line 2209 of file process.c.
References rb_execarg::cmd, env, rb_execarg::invoke, Qnil, rb_exec_fillarg(), rb_exec_getargs(), rb_execarg_get(), RB_GC_GUARD, rb_execarg::sh, and rb_execarg::use_shell.
VALUE rb_execarg_new (int argc, VALUE * argv, int accept_shell)
Definition at line 2190 of file process.c.
References exec_arg_data_type, hide_obj(), rb_cData, rb_execarg_init(), and TypedData_Make_Struct.
int rb_execarg_run_options (const struct rb_execarg * e, struct rb_execarg * s, char * errmsg, size_t errmsg_buflen)
Definition at line 2872 of file process.c.
References rb_execarg::chdir_dir, rb_execarg::chdir_given, rb_execarg::close_others_do, rb_execarg::close_others_given, rb_execarg::close_others_maxhint, rb_execarg::dup2_tmpbuf, rb_execarg::env_modification, ERRMSG, rb_execarg::fd_close, rb_execarg::fd_dup2, rb_execarg::fd_dup2_child, rb_execarg::fd_open, rb_execarg::gid, rb_execarg::gid_given, hide_obj(), i, key, MEMZERO, mode_t, my_getcwd, NIL_P, rb_execarg::pgroup_given, Qfalse, Qnil, RARRAY_LEN, RARRAY_PTR, rb_close_before_exec(), rb_env_clear(), rb_str_new(), rb_str_new2, rb_str_set_len(), rb_warn(), rb_execarg::redirect_fds, rb_execarg::rlimit_limits, RSTRING_PTR, ruby_setenv(), run_exec_close(), run_exec_dup2(), run_exec_dup2_child(), run_exec_dup2_tmpbuf_size(), run_exec_open(), save_env(), setgid(), setuid(), StringValueCStr, tmpbuf, rb_execarg::uid, rb_execarg::uid_given, umask(), rb_execarg::umask_given, rb_execarg::umask_mask, rb_execarg::unsetenv_others_do, rb_execarg::unsetenv_others_given, val, and xfree.
void rb_execarg_setenv (VALUE execarg_obj, VALUE env)
Definition at line 2228 of file process.c.
References rb_execarg::env_modification, NIL_P, Qfalse, rb_check_exec_env(), and rb_execarg_get().
void rb_fiber_reset_root_local_storage (VALUE)
Definition at line 1370 of file cont.c.
References rb_fiber_struct::cont, rb_thread_struct::fiber, GetFiberPtr, GetThreadPtr, rb_thread_struct::local_storage, rb_thread_struct::root_fiber, and rb_context_struct::saved_thread.
Referenced by ruby_vm_destruct().
void rb_file_const (const char * , VALUE)
Definition at line 5144 of file file.c.
References rb_define_const().
VALUE rb_file_expand_path_fast (VALUE , VALUE)
Definition at line 3321 of file file.c.
References EXPAND_PATH_BUFFER, and rb_file_expand_path_internal().
VALUE rb_file_expand_path_internal (VALUE , VALUE , int , int , VALUE)
Definition at line 2960 of file file.c.
References ALLOCA_N, ALLOCV_END, ALLOCV_N, append_fspath(), buf, BUFCHECK, BUFINIT, chompdirsep(), code_page(), convert_mb_to_wchar(), ENC_CODERANGE_7BIT, ENC_CODERANGE_CLEAR, fix_string_encoding(), get_user_from_path(), home_dir(), Inc, INVALID_CODE_PAGE, IS_DIR_SEPARATOR_P, IS_DIR_UNC_P, isdirsep, istrailinggarbage, RString::len, lstat, MAXPATHLEN, my_getcwd, nextdirsep, NIL_P, NULL, OBJ_TAINT, OBJ_TAINTED, p, PATH_BUFFER_SIZE, Qnil, rb_eArgError, rb_enc_associate(), rb_enc_check(), rb_enc_copy(), rb_enc_from_encoding(), rb_enc_get(), rb_enc_str_coderange(), rb_file_expand_path_internal(), rb_filesystem_encoding(), rb_home_dir(), rb_is_absolute_path(), rb_raise(), rb_str_buf_cat(), rb_str_encode(), rb_str_encode_ospath(), rb_str_modify(), rb_str_resize(), rb_str_set_len(), rb_utf8_encoding(), remove_invalid_alternative_data(), replace_to_long_name(), replace_wchar(), result, RSTRING_LEN, RSTRING_PTR, S_ISLNK, size, skipprefix, skiproot(), stat, STRCASECMP, StringValuePtr, strlcat(), strlen(), strncasecmp, strrdirsep, system_code_page(), TOLOWER, v, xfree, and xmalloc.
int rb_file_load_ok (const char *)
Definition at line 5260 of file file.c.
References PepperInstance::as_int, PepperInstance::async_call_args, PepperInstance::async_call_result, PepperInstance::cond, core_interface, fstat, GET_PEPPER_INSTANCE, PepperInstance::instance, INVALID_FILE_ATTRIBUTES, load_ok_internal(), PepperInstance::mutex, NULL, pruby_file_fetch_check_response(), rb_cloexec_open(), rb_update_max_fd(), S_ISREG, and stat.
rb_pid_t rb_fork_async_signal_safe (int * status, int(*)(void *, char *, size_t) chfunc, void * charg, VALUE fds, char * errmsg, size_t errmsg_buflen)
rb_pid_t rb_fork_ruby (int * status)
void rb_gc_mark_encodings (void)
Definition at line 211 of file encoding.c.
Referenced by gc_marks().
void rb_gc_mark_global_tbl (void)
Definition at line 547 of file variable.c.
References mark_global_entry(), and st_foreach_safe().
void rb_gc_mark_parser (void)
Definition at line 15480 of file ripper.c.
Referenced by gc_marks().
void rb_gc_mark_symbols (void)
Definition at line 15653 of file ripper.c.
References global_symbols, symbols::id_str, numberof, symbols::op_sym, rb_gc_mark_locations, and rb_mark_tbl().
Referenced by gc_marks().
VALUE rb_get_backtrace (VALUE info)
Definition at line 53 of file eval_error.c.
References get_backtrace().
Referenced by eval_string_with_cref().
VALUE rb_get_coverages (void)
Definition at line 5155 of file thread.c.
VALUE rb_get_expanded_load_path (void)
Definition at line 110 of file load.c.
References EXPAND_ALL, EXPAND_HOME, EXPAND_NON_CACHE, EXPAND_RELATIVE, rb_vm_struct::expanded_load_path, GET_VM, rb_vm_struct::load_path, rb_vm_struct::load_path_check_cache, load_path_getcwd(), rb_vm_struct::load_path_snapshot, Qtrue, rb_ary_shared_with_p(), rb_construct_expanded_load_path(), and rb_str_equal().
VALUE rb_get_load_path (void)
Definition at line 33 of file load.c.
References GET_VM.
int rb_get_next_signal (void)
Definition at line 590 of file signal.c.
References ATOMIC_DEC, i, RUBY_NSIG, and signal_buff.
VALUE rb_get_path_check_convert (VALUE , VALUE , int)
Definition at line 197 of file file.c.
References check_path_encoding(), file_path_convert(), insecure_obj_p, rb_insecure_operation(), rb_str_new4, and StringValueCStr.
VALUE rb_get_path_check_to_string (VALUE , int)
Definition at line 175 of file file.c.
References CONST_ID, insecure_obj_p, Qundef, rb_check_funcall(), rb_insecure_operation(), RB_TYPE_P, StringValue, and T_STRING.
st_index_t rb_hash_proc (st_index_t hash, VALUE proc)
Definition at line 804 of file proc.c.
References rb_proc_t::block, rb_proc_t::envval, rb_block_struct::ep, GetProcPtr, rb_block_struct::iseq, and rb_hash_uint.
VALUE rb_home_dir (const char * user, VALUE result)
Definition at line 2888 of file file.c.
References buf, getenv(), Inc, p, Qnil, rb_eArgError, rb_enc_associate(), rb_filesystem_encoding(), rb_raise(), rb_str_resize(), result, RSTRING_PTR, and strlen().
ID rb_id_encoding (void)
Definition at line 681 of file encoding.c.
References CONST_ID, and id_encoding.
Referenced by enc_set_index(), id2encidx(), rb_enc_get_index(), w_encoding(), and w_obj_each().
VALUE rb_id_quote_unprintable (ID)
Definition at line 7841 of file string.c.
References rb_id2str(), and rb_str_quote_unprintable().
const char* rb_insns_name (int i)
Definition at line 5475 of file compile.c.
References i.
VALUE rb_insns_name_array (void)
Definition at line 5481 of file compile.c.
References i, numberof, rb_ary_new(), rb_ary_push(), rb_obj_freeze(), and rb_str_new2.
Referenced by Init_VM().
VALUE rb_integer_float_cmp (VALUE x, VALUE y)
Definition at line 1459 of file bignum.c.
References FIX2LONG, FIXNUM_MAX, FIXNUM_MIN, FIXNUM_P, INT2FIX, isinf(), isnan, Qnil, rb_big_cmp(), rb_dbl2big(), and RFLOAT_VALUE.
Referenced by big_op(), fix_cmp(), fix_ge(), fix_gt(), fix_le(), fix_lt(), flo_cmp(), flo_ge(), flo_gt(), flo_le(), flo_lt(), and rb_big_cmp().
VALUE rb_integer_float_eq (VALUE x, VALUE y)
Definition at line 1509 of file bignum.c.
References FIX2LONG, FIXNUM_P, isinf(), isnan, LONG_MAX, LONG_MIN, Qfalse, Qtrue, rb_big_eq(), rb_dbl2big(), and RFLOAT_VALUE.
Referenced by fix_equal(), flo_eq(), and rb_big_eq().
VALUE rb_invcmp (VALUE , VALUE)
Definition at line 42 of file compar.c.
References INT2FIX, invcmp_recursive(), NIL_P, Qnil, Qundef, rb_cmpint(), rb_exec_recursive(), and result.
Referenced by rb_str_cmp_m(), and time_cmp().
ssize_t rb_io_bufread (VALUE io, void * buf, size_t size)
Definition at line 2038 of file io.c.
References binwrite_arg::fptr, GetOpenFile, io_bufread(), and rb_io_check_readable().
int rb_is_attrset_name (VALUE name)
Definition at line 16261 of file ripper.c.
References ID_ATTRSET, and rb_str_symname_type().
Referenced by rb_check_id(), and rb_check_id_cstr().
int rb_is_class_name (VALUE name)
Definition at line 16243 of file ripper.c.
References ID_CLASS, and rb_str_symname_type().
Referenced by rb_mod_cvar_defined(), rb_mod_cvar_get(), and rb_mod_remove_cvar().
int rb_is_const_name (VALUE name)
Definition at line 16237 of file ripper.c.
References ID_CONST, and rb_str_symname_type().
Referenced by rb_mod_const_defined(), and rb_mod_remove_const().
int rb_is_global_name (VALUE name)
Definition at line 16249 of file ripper.c.
References ID_GLOBAL, and rb_str_symname_type().
int rb_is_instance_name (VALUE name)
Definition at line 16255 of file ripper.c.
References ID_INSTANCE, and rb_str_symname_type().
Referenced by rb_obj_ivar_defined(), rb_obj_ivar_get(), and rb_obj_remove_instance_variable().
int rb_is_junk_name (VALUE name)
Definition at line 16283 of file ripper.c.
References rb_str_symname_type().
int rb_is_local_name (VALUE name)
Definition at line 16267 of file ripper.c.
References ID_LOCAL, and rb_str_symname_type().
int rb_is_method_name (VALUE name)
Definition at line 16273 of file ripper.c.
References FALSE, ID_ATTRSET, ID_JUNK, ID_LOCAL, rb_str_symname_type(), and TRUE.
VALUE rb_iseq_clone (VALUE iseqval, VALUE newcbase)
Definition at line 1884 of file iseq.c.
References rb_iseq_struct::cref_stack, GetISeqPtr, iseq_alloc(), rb_iseq_struct::klass, rb_iseq_struct::local_iseq, NEW_CREF, rb_iseq_struct::orig, rb_cISeq, and rb_iseq_struct::self.
void rb_last_status_clear (void)
Definition at line 285 of file process.c.
References GET_THREAD(), rb_thread_struct::last_status, and Qnil.
VALUE rb_lcm (VALUE x, VALUE y)
Definition at line 1711 of file rational.c.
References f_lcm(), and nurat_int_value().
int rb_local_defined (ID)
Definition at line 5857 of file compile.c.
References rb_thread_struct::base_block, GET_THREAD(), i, rb_block_struct::iseq, rb_iseq_struct::local_iseq, rb_iseq_struct::local_table, and rb_iseq_struct::local_table_size.
Referenced by local_id_gen().
VALUE rb_make_backtrace (void)
Definition at line 772 of file vm_backtrace.c.
References GET_THREAD(), and vm_backtrace_str_ary().
void rb_mark_end_proc (void)
Definition at line 80 of file eval_jump.c.
References end_proc_data::data, end_procs, ephemeral_end_procs, link(), end_proc_data::next, and rb_gc_mark().
Referenced by gc_marks().
void rb_mark_generic_ivar (VALUE)
Definition at line 985 of file variable.c.
References rb_mark_tbl(), and st_lookup().
void rb_mark_generic_ivar_tbl (void)
Definition at line 1015 of file variable.c.
References givar_i(), and st_foreach_safe().
VALUE rb_math_atan2 (VALUE , VALUE)
VALUE rb_math_cos (VALUE)
VALUE rb_math_cosh (VALUE)
VALUE rb_math_exp (VALUE)
VALUE rb_math_hypot (VALUE , VALUE)
VALUE rb_math_log (int argc, VALUE * argv)
VALUE rb_math_sin (VALUE)
VALUE rb_math_sinh (VALUE)
VALUE rb_math_sqrt (VALUE)
void rb_maygvl_fd_fix_cloexec (int fd)
Definition at line 179 of file io.c.
References errno, fcntl(), rb_bug(), and strerror().
int rb_method_defined_by (VALUE obj, ID mid, VALUE(*)(ANYARGS) cfunc)
void rb_mutex_allow_trap (VALUE self, int val)
Definition at line 4540 of file thread.c.
References rb_mutex_struct::allow_trap, and GetMutexPtr.
VALUE rb_mutex_owned_p (VALUE self)
Definition at line 4367 of file thread.c.
References GET_THREAD(), GetMutexPtr, Qfalse, Qtrue, and rb_mutex_struct::th.
int rb_num_negative_p (VALUE)
Definition at line 189 of file numeric.c.
References negative_int_p().
int rb_num_to_uint (VALUE val, unsigned int * ret)
Definition at line 122 of file numeric.c.
References DIGSPERLONG, FIX2LONG, FIXNUM_P, NUMERR_NEGATIVE, NUMERR_TOOLARGE, NUMERR_TYPE, rb_big2ulong(), RBIGNUM_LEN, RBIGNUM_NEGATIVE_P, T_BIGNUM, TYPE, and v.
VALUE rb_obj_equal (VALUE obj1, VALUE obj2)
Definition at line 109 of file object.c.
References Qfalse, and Qtrue.
VALUE rb_obj_is_fiber (VALUE)
Definition at line 333 of file cont.c.
References Qfalse, Qtrue, and rb_typeddata_is_kind_of().
Referenced by rb_objspace_call_finalizer().
VALUE rb_obj_is_mutex (VALUE obj)
Definition at line 4134 of file thread.c.
References Qfalse, Qtrue, and rb_typeddata_is_kind_of().
VALUE rb_obj_is_thread (VALUE obj)
Definition at line 1928 of file vm.c.
References Qfalse, Qtrue, rb_typeddata_is_kind_of(), and thread_data_type.
const char* rb_objspace_data_type_name (VALUE obj)
Definition at line 749 of file gc.c.
References RTYPEDDATA_P, and RTYPEDDATA_TYPE.
int rb_parse_in_eval (void)
Definition at line 5876 of file compile.c.
References GET_THREAD(), and rb_thread_struct::parse_in_eval.
Referenced by parser_compile_string(), and rb_parser_compile_file().
int rb_parse_in_main (void)
Definition at line 5882 of file compile.c.
References GET_THREAD(), and rb_thread_struct::parse_in_eval.
Referenced by yyparse().
VALUE rb_parser_get_yydebug (VALUE)
Definition at line 16488 of file ripper.c.
VALUE rb_parser_set_yydebug (VALUE , VALUE)
Definition at line 16503 of file ripper.c.
VALUE rb_proc_location (VALUE self)
Definition at line 758 of file proc.c.
References get_proc_iseq, and iseq_location().
VALUE rb_rational_reciprocal (VALUE x)
Definition at line 1675 of file rational.c.
References CLASS_OF, f_rational_new_no_reduce2(), and get_dat1.
VALUE rb_realpath_internal (VALUE basedir, VALUE path, int strict)
Definition at line 3502 of file file.c.
References chompdirsep(), FilePathValue, Inc, NIL_P, NULL, OBJ_TAINT, Qnil, rb_dir_getwd(), rb_enc_get(), rb_hash_new(), rb_secure(), rb_str_dup_frozen, rb_str_set_len(), rb_str_subseq(), realpath_rec(), RSTRING_GETMEM, and skipprefixroot().
VALUE rb_refinement_module_get_refined_class (VALUE module)
Definition at line 1129 of file eval.c.
References CONST_ID, and rb_attr_get().
Referenced by include_modules_at(), rb_method_entry_make(), and rb_mod_to_s().
VALUE rb_reg_check_preprocess (VALUE)
Definition at line 2304 of file re.c.
References buf, err, p, Qnil, rb_enc_get(), RB_GC_GUARD, rb_reg_error_desc(), rb_reg_preprocess(), RSTRING_LEN, RSTRING_PTR, and StringValue.
VALUE rb_reg_compile (VALUE str, int options, const char * sourcefile, int sourceline)
Definition at line 2530 of file re.c.
References err, FL_SET, Qnil, rb_reg_alloc(), rb_reg_error_desc(), rb_reg_initialize_str(), rb_set_errinfo(), rb_str_new(), and REG_LITERAL.
int rb_sigaltstack_size (void)
VALUE rb_sourcefilename (void)
Definition at line 788 of file vm.c.
References rb_thread_struct::cfp, GET_THREAD(), rb_control_frame_struct::iseq, rb_iseq_struct::location, rb_iseq_location_struct::path, Qnil, and rb_vm_get_ruby_level_next_cfp().
void rb_stdio_set_default_encoding (void)
Definition at line 10332 of file io.c.
References Qnil, rb_io_set_encoding(), rb_stderr, rb_stdin, rb_stdout, and val.
int rb_str_buf_cat_escaped_char (VALUE result, unsigned int c, int unicode_p)
Definition at line 4455 of file string.c.
References buf, CHAR_ESC_LEN, ISPRINT, rb_str_buf_cat(), snprintf, and strlen().
VALUE rb_str_quote_unprintable (VALUE)
Definition at line 7820 of file string.c.
References Check_Type, NULL, rb_default_external_encoding(), rb_default_internal_encoding(), rb_str_inspect(), rb_str_is_ascii_only_p(), RSTRING_LEN, RSTRING_PTR, STR_ENC_GET, sym_printable(), and T_STRING.
int rb_str_symname_p (VALUE)
Definition at line 7801 of file string.c.
References FALSE, NULL, rb_default_external_encoding(), rb_default_internal_encoding(), rb_enc_symname_p(), rb_str_is_ascii_only_p(), RSTRING_LEN, RSTRING_PTR, STR_ENC_GET, strlen(), sym_printable(), and TRUE.
VALUE rb_struct_init_copy (VALUE copy, VALUE s)
Definition at line 620 of file struct.c.
References MEMCPY, OBJ_INIT_COPY, rb_eTypeError, rb_raise(), RSTRUCT_LEN, and RSTRUCT_PTR.
VALUE rb_suppress_tracing (VALUE(*)(VALUE) func, VALUE arg)
Definition at line 344 of file vm_trace.c.
References arg, GET_THREAD(), JUMP_TAG, Qnil, rb_threadptr_reset_raised(), rb_threadptr_set_raised(), result, rb_thread_struct::state, TH_EXEC_TAG, TH_POP_TAG, TH_PUSH_TAG, rb_thread_struct::trace_arg, rb_vm_struct::trace_running, and rb_thread_struct::vm.
void rb_thread_execute_interrupts (VALUE th)
Definition at line 1973 of file thread.c.
References GetThreadPtr, and rb_threadptr_execute_interrupts().
VALUE rb_thread_io_blocking_region (rb_blocking_function_t * func, void * data1, int fd)
Definition at line 1331 of file thread.c.
References BLOCKING_REGION, errno, EXEC_TAG, FALSE, func, GET_THREAD(), JUMP_TAG, Qundef, RUBY_VM_CHECK_INTS_BLOCKING, TH_POP_TAG, TH_PUSH_TAG, and rb_thread_struct::waiting_fd.
void rb_thread_mark (void * th)
Definition at line 1788 of file vm.c.
References rb_thread_struct::cfp, rb_thread_struct::errinfo, rb_thread_struct::event_hooks, rb_thread_struct::fiber, rb_thread_struct::first_args, rb_thread_struct::first_proc, GET_THREAD(), rb_control_frame_struct::iseq, rb_control_frame_struct::klass, rb_thread_struct::last_status, rb_thread_struct::local_storage, rb_thread_struct::locking_mutex, rb_thread_struct::machine_regs, rb_thread_struct::machine_stack_end, rb_thread_struct::machine_stack_start, rb_thread_struct::mark_stack_len, rb_control_frame_struct::me, NULL, rb_thread_struct::pending_interrupt_mask_stack, rb_thread_struct::pending_interrupt_queue, rb_control_frame_struct::proc, rb_objspace::ptr, rb_gc_mark(), rb_gc_mark_locations, rb_gc_mark_machine_stack(), rb_mark_method_entry(), rb_mark_tbl(), rb_thread_struct::root_fiber, rb_thread_struct::root_svar, RUBY_MARK_ENTER, RUBY_MARK_LEAVE, RUBY_MARK_UNLESS_NULL, RUBY_VM_NORMAL_ISEQ_P, RUBY_VM_PREVIOUS_CONTROL_FRAME, rb_iseq_struct::self, rb_control_frame_struct::self, rb_control_frame_struct::sp, rb_thread_struct::stack, rb_thread_struct::stack_size, rb_thread_struct::stat_insn_usage, rb_thread_struct::thgroup, rb_thread_struct::top_self, rb_thread_struct::top_wrapper, rb_thread_struct::value, and vm_trace_mark_event_hooks().
void rb_thread_recycle_stack_release (VALUE *)
Definition at line 1766 of file vm.c.
References RECYCLE_MAX, and ruby_xfree().
VALUE rb_thread_shield_destroy (VALUE self)
Definition at line 4642 of file thread.c.
References DATA_PTR, GetThreadShieldPtr, Qfalse, Qtrue, rb_mutex_unlock(), and rb_thread_shield_waiting.
VALUE rb_thread_shield_new (void)
Definition at line 4595 of file thread.c.
References DATA_PTR, rb_cThreadShield, rb_mutex_lock(), and thread_shield_alloc().
VALUE rb_thread_shield_release (VALUE self)
Definition at line 4631 of file thread.c.
References GetThreadShieldPtr, Qfalse, Qtrue, rb_mutex_unlock(), and rb_thread_shield_waiting.
VALUE rb_thread_shield_wait (VALUE self)
Definition at line 4611 of file thread.c.
References DATA_PTR, GET_THREAD(), GetMutexPtr, GetThreadShieldPtr, Qfalse, Qnil, Qtrue, rb_mutex_lock(), rb_mutex_unlock(), rb_thread_shield_waiting, rb_thread_shield_waiting_dec(), rb_thread_shield_waiting_inc(), and rb_mutex_struct::th.
struct timeval rb_time_timeval (VALUE) read
Definition at line 2497 of file time.c.
References FALSE, GetTimeval, IsTimeval, time_timeval(), timew2timespec(), timespec::tv_nsec, timeval::tv_sec, timespec::tv_sec, timeval::tv_usec, TYPEOF_TIMEVAL_TV_SEC, and TYPEOF_TIMEVAL_TV_USEC.
VALUE rb_uninterruptible (VALUE(*)(ANYARGS) b_proc, VALUE data)
Definition at line 5175 of file thread.c.
References GET_THREAD(), rb_thread_struct::pending_interrupt_mask_stack, rb_ary_pop(), rb_ary_push(), rb_cObject, rb_ensure(), rb_hash_aset(), rb_hash_new(), and sym_never.
VALUE rb_vm_backtrace_object ()
Definition at line 532 of file vm_backtrace.c.
References backtrace_object(), and GET_THREAD().
void rb_vm_bugreport (void)
Definition at line 609 of file vm_dump.c.
void rb_vm_change_state (void)
Definition at line 103 of file vm.c.
const void** rb_vm_get_insns_address_table (void)
Definition at line 107 of file vm_exec.c.
References vm_exec_core().
void rb_vm_inc_const_missing_count (void)
Definition at line 128 of file vm.c.
void rb_vm_mark (void * ptr)
Definition at line 1549 of file vm.c.
References rb_vm_struct::cmd, rb_vm_struct::coverages, DEFINED_EXPR, rb_vm_struct::defined_strings, rb_vm_struct::event_hooks, rb_vm_struct::expanded_load_path, i, rb_vm_struct::living_threads, rb_vm_struct::load_path, rb_vm_struct::load_path_check_cache, rb_vm_struct::load_path_snapshot, rb_vm_struct::loaded_features, rb_vm_struct::loaded_features_index, rb_vm_struct::loaded_features_snapshot, rb_vm_struct::loading_table, rb_vm_struct::mark_object_ary, rb_gc_mark(), rb_gc_mark_locations, rb_mark_tbl(), RUBY_GC_INFO, RUBY_MARK_ENTER, RUBY_MARK_LEAVE, RUBY_MARK_UNLESS_NULL, RUBY_NSIG, ruby_special_error_count, rb_vm_struct::special_exceptions, st_foreach(), rb_vm_struct::thgroup_default, rb_vm_struct::top_self, rb_vm_struct::trap_list, vm_mark_each_thread_func(), and vm_trace_mark_event_hooks().
VALUE rb_vm_top_self (void)
Definition at line 2427 of file vm.c.
References GET_VM.
void rb_write_error_str (VALUE mesg)
Definition at line 7027 of file io.c.
References rb_io_t::fd, orig_stderr, RB_GC_GUARD, rb_io_write(), rb_stderr, RFILE, RSTRING_LEN, and RSTRING_PTR.
void ruby_error_print (void)
Definition at line 200 of file eval_error.c.
References error_print().
Referenced by rb_f_abort().
double ruby_float_mod (double x, double y)
Definition at line 903 of file numeric.c.
References flodivmod(), and mod.
int ruby_float_step (VALUE from, VALUE to, VALUE step, int excl)
Definition at line 1788 of file numeric.c.
References DBL2NUM, FALSE, i, isinf(), NUM2DBL, RB_TYPE_P, rb_yield(), ruby_float_step_size(), T_FLOAT, and TRUE.
const char* ruby_get_inplace_mode (void)
Definition at line 11369 of file io.c.
References ARGF.
void* ruby_mimmalloc (size_t size)
Definition at line 3660 of file gc.c.
References malloc.
void ruby_set_inplace_mode (const char *)
Definition at line 11375 of file io.c.
References ARGF, free, and strdup.
VALUE vm_thread_backtrace (int argc, VALUE * argv, VALUE thval)
Definition at line 859 of file vm_backtrace.c.
References thread_backtrace_to_ary().
VALUE vm_thread_backtrace_locations (int argc, VALUE * argv, VALUE thval)
Definition at line 865 of file vm_backtrace.c.
References thread_backtrace_to_ary().