Ruby: object.c File Reference
object.c File Reference
#include "ruby/ruby.h"
#include "ruby/st.h"
#include "ruby/util.h"
#include "ruby/encoding.h"
#include <stdio.h>
#include <errno.h>
#include <ctype.h>
#include <math.h>
#include <float.h>
#include "constant.h"
#include "internal.h"
#include "probes.h"
Data Structures
struct conv_method_tbl
Macros
#define CLASS_OR_MODULE_P(obj)
#define IMPLICIT_CONVERSIONS 7
#define OutOfRange()
#define rb_intern(str) rb_intern_const(str)
Functions
VALUE rb_equal (VALUE obj1, VALUE obj2)
int rb_eql (VALUE obj1, VALUE obj2)
VALUE rb_obj_equal (VALUE obj1, VALUE obj2)
VALUE rb_obj_hash (VALUE obj)
VALUE rb_obj_not (VALUE obj)
VALUE rb_obj_not_equal (VALUE obj1, VALUE obj2)
VALUE rb_class_real (VALUE cl)
VALUE rb_obj_class (VALUE obj)
static VALUE rb_obj_singleton_class (VALUE obj)
static void init_copy (VALUE dest, VALUE obj)
VALUE rb_obj_clone (VALUE obj)
VALUE rb_obj_dup (VALUE obj)
VALUE rb_obj_init_copy (VALUE obj, VALUE orig)
VALUE rb_obj_init_dup_clone (VALUE obj, VALUE orig)
VALUE rb_any_to_s (VALUE obj)
VALUE rb_inspect (VALUE obj)
static int inspect_i (st_data_t k, st_data_t v, st_data_t a)
static VALUE inspect_obj (VALUE obj, VALUE str, int recur)
static VALUE rb_obj_inspect (VALUE obj)
static VALUE class_or_module_required (VALUE c)
VALUE rb_obj_is_instance_of (VALUE obj, VALUE c)
VALUE rb_obj_is_kind_of (VALUE obj, VALUE c)
VALUE rb_obj_tap (VALUE obj)
static VALUE rb_obj_dummy (void)
VALUE rb_obj_tainted (VALUE obj)
VALUE rb_obj_taint (VALUE obj)
VALUE rb_obj_untaint (VALUE obj)
VALUE rb_obj_untrusted (VALUE obj)
VALUE rb_obj_untrust (VALUE obj)
VALUE rb_obj_trust (VALUE obj)
void rb_obj_infect (VALUE obj1, VALUE obj2)
VALUE rb_obj_freeze (VALUE obj)
VALUE rb_obj_frozen_p (VALUE obj)
static VALUE nil_to_i (VALUE obj)
static VALUE nil_to_f (VALUE obj)
static VALUE nil_to_s (VALUE obj)
static VALUE nil_to_a (VALUE obj)
static VALUE nil_to_h (VALUE obj)
static VALUE nil_inspect (VALUE obj)
static VALUE true_to_s (VALUE obj)
static VALUE true_and (VALUE obj, VALUE obj2)
static VALUE true_or (VALUE obj, VALUE obj2)
static VALUE true_xor (VALUE obj, VALUE obj2)
static VALUE false_to_s (VALUE obj)
static VALUE false_and (VALUE obj, VALUE obj2)
static VALUE false_or (VALUE obj, VALUE obj2)
static VALUE false_xor (VALUE obj, VALUE obj2)
static VALUE rb_true (VALUE obj)
static VALUE rb_false (VALUE obj)
static VALUE rb_obj_match (VALUE obj1, VALUE obj2)
static VALUE rb_obj_not_match (VALUE obj1, VALUE obj2)
static VALUE rb_obj_cmp (VALUE obj1, VALUE obj2)
static VALUE rb_mod_to_s (VALUE klass)
static VALUE rb_mod_freeze (VALUE mod)
static VALUE rb_mod_eqq (VALUE mod, VALUE arg)
VALUE rb_class_inherited_p (VALUE mod, VALUE arg)
static VALUE rb_mod_lt (VALUE mod, VALUE arg)
static VALUE rb_mod_ge (VALUE mod, VALUE arg)
static VALUE rb_mod_gt (VALUE mod, VALUE arg)
static VALUE rb_mod_cmp (VALUE mod, VALUE arg)
static VALUE rb_module_s_alloc (VALUE klass)
static VALUE rb_class_s_alloc (VALUE klass)
static VALUE rb_mod_initialize (VALUE module)
static VALUE rb_class_initialize (int argc, VALUE *argv, VALUE klass)
VALUE rb_obj_alloc (VALUE klass)
static VALUE rb_class_allocate_instance (VALUE klass)
VALUE rb_class_new_instance (int argc, VALUE *argv, VALUE klass)
VALUE rb_class_superclass (VALUE klass)
VALUE rb_class_get_superclass (VALUE klass)
static VALUE rb_mod_attr_reader (int argc, VALUE *argv, VALUE klass)
VALUE rb_mod_attr (int argc, VALUE *argv, VALUE klass)
static VALUE rb_mod_attr_writer (int argc, VALUE *argv, VALUE klass)
static VALUE rb_mod_attr_accessor (int argc, VALUE *argv, VALUE klass)
static VALUE rb_mod_const_get (int argc, VALUE *argv, VALUE mod)
static VALUE rb_mod_const_set (VALUE mod, VALUE name, VALUE value)
static VALUE rb_mod_const_defined (int argc, VALUE *argv, VALUE mod)
static VALUE rb_obj_ivar_get (VALUE obj, VALUE iv)
static VALUE rb_obj_ivar_set (VALUE obj, VALUE iv, VALUE val)
static VALUE rb_obj_ivar_defined (VALUE obj, VALUE iv)
static VALUE rb_mod_cvar_get (VALUE obj, VALUE iv)
static VALUE rb_mod_cvar_set (VALUE obj, VALUE iv, VALUE val)
static VALUE rb_mod_cvar_defined (VALUE obj, VALUE iv)
static VALUE convert_type (VALUE val, const char *tname, const char *method, int raise)
VALUE rb_convert_type (VALUE val, int type, const char *tname, const char *method)
VALUE rb_check_convert_type (VALUE val, int type, const char *tname, const char *method)
static VALUE rb_to_integer (VALUE val, const char *method)
VALUE rb_check_to_integer (VALUE val, const char *method)
VALUE rb_to_int (VALUE val)
VALUE rb_check_to_int (VALUE val)
static VALUE rb_convert_to_integer (VALUE val, int base)
VALUE rb_Integer (VALUE val)
static VALUE rb_f_integer (int argc, VALUE *argv, VALUE obj)
double rb_cstr_to_dbl (const char *p, int badcheck)
double rb_str_to_dbl (VALUE str, int badcheck)
VALUE rb_Float (VALUE val)
static VALUE rb_f_float (VALUE obj, VALUE arg)
VALUE rb_to_float (VALUE val)
VALUE rb_check_to_float (VALUE val)
double rb_num2dbl (VALUE val)
VALUE rb_String (VALUE val)
static VALUE rb_f_string (VALUE obj, VALUE arg)
VALUE rb_Array (VALUE val)
static VALUE rb_f_array (VALUE obj, VALUE arg)
VALUE rb_Hash (VALUE val)
static VALUE rb_f_hash (VALUE obj, VALUE arg)
void Init_Object (void)
Initializes the world of objects and classes.
Variables
VALUE rb_cBasicObject
VALUE rb_mKernel
VALUE rb_cObject
VALUE rb_cModule
VALUE rb_cClass
VALUE rb_cData
VALUE rb_cNilClass
VALUE rb_cTrueClass
VALUE rb_cFalseClass
static ID id_eq
static ID id_eql
static ID id_match
static ID id_inspect
static ID id_init_copy
static ID id_init_clone
static ID id_init_dup
static ID id_const_missing
static st_table * immediate_frozen_tbl = 0
static struct conv_method_tbl conv_method_names []
Macro Definition Documentation
#define CLASS_OR_MODULE_P (obj)
Value:
(!SPECIAL_CONST_P(obj) && \
     (BUILTIN_TYPE(obj) == T_CLASS || BUILTIN_TYPE(obj) == T_MODULE))
Definition at line 42 of file object.c.
Referenced by rb_class_inherited_p(), rb_mod_cmp(), rb_mod_ge(), and rb_mod_to_s().
#define IMPLICIT_CONVERSIONS 7
Definition at line 2314 of file object.c.
Referenced by convert_type().
#define OutOfRange ()
Value:
((end - p > max_width) ? \
                      (w = max_width, ellipsis = "...") : \
                      (w = (int)(end - p), ellipsis = ""))
Referenced by rb_cstr_to_dbl().
#define rb_intern (str) rb_intern_const(str)
Function Documentation
static VALUE class_or_module_required (VALUE c) static
Definition at line 511 of file object.c.
References BUILTIN_TYPE, c, rb_eTypeError, rb_raise(), SPECIAL_CONST_P, T_CLASS, T_ICLASS, and T_MODULE.
Referenced by rb_obj_is_instance_of(), and rb_obj_is_kind_of().
static VALUE convert_type (VALUE val, const char * tname, const char * method, int raise) static
Definition at line 2317 of file object.c.
References conv_method_names, i, conv_method_tbl::id, IMPLICIT_CONVERSIONS, conv_method_tbl::method, NIL_P, Qfalse, Qnil, Qtrue, Qundef, rb_check_funcall(), rb_eTypeError, rb_intern, rb_obj_classname(), and rb_raise().
Referenced by rb_check_convert_type(), rb_check_to_integer(), rb_convert_to_integer(), rb_convert_type(), and rb_to_integer().
static VALUE false_and (VALUE obj, VALUE obj2) static
Definition at line 1219 of file object.c.
References Qfalse.
Referenced by Init_Object().
static VALUE false_or (VALUE obj, VALUE obj2) static
Definition at line 1235 of file object.c.
References Qfalse, Qtrue, and RTEST.
Referenced by Init_Object().
static VALUE false_to_s (VALUE obj) static
Definition at line 1203 of file object.c.
References rb_usascii_str_new2.
Referenced by Init_Object().
static VALUE false_xor (VALUE obj, VALUE obj2) static
Definition at line 1254 of file object.c.
References Qfalse, Qtrue, and RTEST.
Referenced by Init_Object().
static void init_copy (VALUE dest, VALUE obj) static
Definition at line 223 of file object.c.
References ALLOC_N, FL_EXIVAR, FL_TAINT, FL_UNTRUSTED, MEMCPY, OBJ_FROZEN, rb_copy_generic_ivar(), rb_eTypeError, rb_free_const_table(), rb_gc_copy_finalizer(), rb_obj_classname(), rb_raise(), RBASIC, RCLASS_CONST_TBL, RCLASS_IV_TBL, ROBJECT, ROBJECT_EMBED, ROBJECT_EMBED_LEN_MAX, ROBJECT_IVPTR, st_copy(), st_free_table(), T_CLASS, T_MASK, T_MODULE, T_OBJECT, TYPE, and xfree.
Referenced by rb_obj_clone(), and rb_obj_dup().
static int inspect_i (st_data_t k, st_data_t v, st_data_t a) static
Definition at line 417 of file object.c.
References CLASS_OF, OBJ_INFECT, rb_id2name(), rb_inspect(), rb_is_instance_id(), rb_str_append(), rb_str_cat2(), RSTRING_PTR, and ST_CONTINUE.
Referenced by inspect_obj().
static VALUE inspect_obj (VALUE obj, VALUE str, int recur) static
Definition at line 446 of file object.c.
References inspect_i(), OBJ_INFECT, rb_ivar_foreach(), rb_str_cat2(), and RSTRING_PTR.
Referenced by rb_obj_inspect().
static VALUE nil_inspect (VALUE obj) static
Definition at line 1103 of file object.c.
References rb_usascii_str_new2.
Referenced by Init_Object().
static VALUE nil_to_a (VALUE obj) static
Definition at line 1073 of file object.c.
References rb_ary_new2().
Referenced by Init_Object().
static VALUE nil_to_f (VALUE obj) static
Definition at line 1043 of file object.c.
References DBL2NUM.
Referenced by Init_Object().
static VALUE nil_to_h (VALUE obj) static
Definition at line 1090 of file object.c.
References rb_hash_new().
Referenced by Init_Object().
static VALUE nil_to_i (VALUE obj) static
Definition at line 1028 of file object.c.
References INT2FIX.
Referenced by Init_Object().
static VALUE nil_to_s (VALUE obj) static
Definition at line 1056 of file object.c.
References rb_usascii_str_new().
Referenced by Init_Object().
VALUE rb_any_to_s (VALUE obj)
Definition at line 384 of file object.c.
References CLASS_OF, OBJ_INFECT, PRIsVALUE, rb_class_name(), and rb_sprintf().
Referenced by Init_Object(), name_err_mesg_to_str(), rb_hash_fetch_m(), rb_io_inspect(), rb_mod_to_s(), rb_obj_as_string(), rb_obj_basic_to_s_p(), rb_obj_inspect(), and rb_reg_inspect().
VALUE rb_Array (VALUE val)
Definition at line 2747 of file object.c.
References NIL_P, rb_ary_new3(), rb_check_array_type(), rb_check_convert_type(), and T_ARRAY.
Referenced by dir_entries(), range_last(), rb_f_array(), and readline_attempted_completion_function().
VALUE rb_check_convert_type (VALUE val, int type, const char * tname, const char * method)
Definition at line 2364 of file object.c.
References convert_type(), FALSE, NIL_P, Qnil, rb_eTypeError, rb_obj_classname(), rb_raise(), T_DATA, TYPE, and v.
Referenced by ary_join_1(), check_exec_redirect_fd(), rb_Array(), rb_check_array_type(), rb_check_hash_type(), rb_check_regexp_type(), rb_check_string_type(), rb_check_to_float(), rb_file_initialize(), rb_gzwriter_initialize(), rb_hash_set_default_proc(), rb_io_check_io(), rb_stat(), and vm_caller_setup_args().
VALUE rb_check_to_float (VALUE val)
Definition at line 2687 of file object.c.
References Qnil, rb_check_convert_type(), rb_cNumeric, rb_obj_is_kind_of(), RB_TYPE_P, and T_FLOAT.
Referenced by rand_random(), and rand_range().
VALUE rb_check_to_int (VALUE val)
Definition at line 2418 of file object.c.
References rb_check_to_integer().
Referenced by exit_initialize().
VALUE rb_check_to_integer (VALUE val, const char * method)
Definition at line 2398 of file object.c.
References convert_type(), FALSE, FIXNUM_P, Qnil, rb_cInteger, rb_obj_is_kind_of(), RB_TYPE_P, T_BIGNUM, and v.
Referenced by esignal_init(), num_exact(), rand_random(), rand_range(), range_include(), range_step(), rb_check_to_int(), rb_io_extract_modeenc(), rb_io_s_sysopen(), and sockopt_s_linger().
static VALUE rb_class_allocate_instance (VALUE klass) static
Definition at line 1737 of file object.c.
References NEWOBJ_OF, and T_OBJECT.
Referenced by Init_Object().
VALUE rb_class_get_superclass (VALUE klass)
Definition at line 1804 of file object.c.
References RCLASS_SUPER.
VALUE rb_class_inherited_p (VALUE mod, VALUE arg)
Definition at line 1461 of file object.c.
References CLASS_OR_MODULE_P, mod, Qfalse, Qnil, Qtrue, rb_eTypeError, rb_raise(), RCLASS_M_TBL, RCLASS_ORIGIN, and RCLASS_SUPER.
Referenced by Init_Object(), r_object0(), rb_mod_cmp(), rb_mod_define_method(), rb_mod_ge(), rb_mod_lt(), and rb_threadptr_pending_interrupt_include_p().
static VALUE rb_class_initialize (int argc, VALUE * argv, VALUE klass) static
Definition at line 1654 of file object.c.
References rb_cBasicObject, rb_check_inheritable(), rb_class_inherited(), rb_cObject, rb_eTypeError, rb_make_metaclass(), rb_mod_initialize(), rb_raise(), rb_scan_args(), RBASIC, and RCLASS_SUPER.
Referenced by Init_Object().
VALUE rb_class_new_instance (int argc, VALUE * argv, VALUE klass)
Definition at line 1756 of file object.c.
References rb_obj_alloc(), and rb_obj_call_init().
Referenced by console_dev(), copy_stream_body(), each_entry_i(), float_value(), glob_i(), gzfile_wrap(), Init_Exception(), Init_IO(), Init_Object(), Init_Regexp(), io_new_instance(), JSON_parse_array(), JSON_parse_object(), make_no_method_exception(), make_struct(), mark(), new_wrap(), path_basename(), path_dirname(), path_entries(), path_expand_path(), path_f_pathname(), path_readlink(), path_realdirpath(), path_realpath(), path_s_getwd(), path_s_glob(), path_split(), path_sub(), path_sub_ext(), process_sflag(), rb_dl_dlopen(), rb_exit(), rb_f_abort(), rb_fiddle_new_function(), rb_io_initialize(), rb_io_s_new(), rb_io_s_open(), rb_name_error(), rb_name_error_str(), rb_reg_s_union(), rb_struct_alloc(), rb_struct_new(), rb_syserr_new_str(), strio_s_open(), time_s_now(), and tk_s_new().
VALUE rb_class_real (VALUE cl)
Definition at line 171 of file object.c.
References BUILTIN_TYPE, FL_SINGLETON, RBASIC, RCLASS_SUPER, and T_ICLASS.
Referenced by class2path(), make_singleton_class(), rb_class_name(), rb_define_class(), rb_define_class_id_under(), rb_f_autoload(), rb_obj_alloc(), rb_obj_class(), uninitialized_constant(), w_class(), and w_uclass().
static VALUE rb_class_s_alloc (VALUE klass) static
Definition at line 1583 of file object.c.
References rb_class_boot().
Referenced by Init_Object().
VALUE rb_class_superclass (VALUE klass)
Definition at line 1786 of file object.c.
References Qnil, rb_cBasicObject, rb_eTypeError, rb_raise(), RB_TYPE_P, RCLASS_SUPER, and T_ICLASS.
Referenced by get_digest_base_metadata(), Init_Object(), and ossl_asn1_default_tag().
static VALUE rb_convert_to_integer (VALUE val, int base) static
Definition at line 2424 of file object.c.
References convert_type(), FALSE, FIXNUM_MAX, FIXNUM_MIN, NIL_P, rb_check_string_type(), rb_dbl2big(), rb_eArgError, rb_eTypeError, rb_raise(), rb_str_to_inum(), rb_to_integer(), RFLOAT_VALUE, T_BIGNUM, T_FIXNUM, T_FLOAT, T_NIL, T_STRING, TRUE, and TYPE.
Referenced by rb_f_integer(), and rb_Integer().
VALUE rb_convert_type (VALUE val, int type, const char * tname, const char * method)
Definition at line 2349 of file object.c.
References convert_type(), rb_eTypeError, rb_obj_classname(), rb_raise(), TRUE, TYPE, and v.
Referenced by addrinfo_mload(), cParser_initialize(), cState_configure(), iseq_build_from_ary_body(), iseq_build_from_ary_exception(), m_core_hash_merge_kwd(), nucomp_s_convert(), nurat_s_convert(), open_key_args(), path_entries(), path_s_glob(), rb_execarg_fixup(), rb_Float(), rb_io_get_io(), rb_str_to_str(), rb_String(), rb_thread_s_handle_interrupt(), rb_to_float(), register_label(), strio_copy(), symbol2event_flag(), tk_symbolkey2str(), to_ary(), and to_hash().
double rb_cstr_to_dbl (const char * p, int badcheck)
Definition at line 2516 of file object.c.
References bad, buf, DBL_DIG, errno, ISDIGIT, ISSPACE, OutOfRange, p, rb_eArgError, rb_invalid_str(), rb_raise(), rb_warning(), and strtod.
Referenced by JSON_parse_float(), rb_str_to_dbl(), str2num(), and tkstr_to_float().
int rb_eql (VALUE obj1, VALUE obj2)
Definition at line 67 of file object.c.
References id_eql, rb_funcall(), and RTEST.
Referenced by cdhash_cmp(), eql_i(), hash_equal(), rb_any_cmp(), and recursive_eql().
VALUE rb_equal (VALUE obj1, VALUE obj2)
Definition at line 56 of file object.c.
References id_eq, Qfalse, Qtrue, rb_funcall(), result, and RTEST.
Referenced by assoc_i(), chunk_ii(), count_i(), eql_i(), exc_equal(), find_index_i(), hash_equal(), Init_Object(), key_i(), member_i(), name_err_mesg_equal(), num_div(), num_eql(), num_remainder(), num_step(), num_zero_p(), pst_equal(), range_bsearch(), rassoc_i(), rb_ary_assoc(), rb_ary_count(), rb_ary_delete(), rb_ary_equal(), rb_ary_includes(), rb_ary_index(), rb_ary_rassoc(), rb_ary_rindex(), rb_big_eq(), rb_hash_search_value(), rb_method_definition_eq(), rb_obj_cmp(), rb_str_equal(), recursive_equal(), syserr_eqq(), time_eql(), time_mdump(), and vtm_add_offset().
static VALUE rb_f_array (VALUE obj, VALUE arg) static
Definition at line 2772 of file object.c.
References rb_Array().
Referenced by Init_Object().
static VALUE rb_f_float (VALUE obj, VALUE arg) static
Definition at line 2667 of file object.c.
References rb_Float().
Referenced by Init_Object().
static VALUE rb_f_hash (VALUE obj, VALUE arg) static
Definition at line 2807 of file object.c.
References rb_Hash().
Referenced by Init_Object().
static VALUE rb_f_integer (int argc, VALUE * argv, VALUE obj) static
Definition at line 2497 of file object.c.
References arg, NULL, NUM2INT, Qnil, rb_convert_to_integer(), and rb_scan_args().
Referenced by Init_Object().
static VALUE rb_f_string (VALUE obj, VALUE arg) static
Definition at line 2741 of file object.c.
References rb_String().
Referenced by Init_Object().
static VALUE rb_false (VALUE obj) static
Definition at line 1282 of file object.c.
References Qfalse.
Referenced by Init_Object().
VALUE rb_Float (VALUE val)
Definition at line 2628 of file object.c.
References DBL2NUM, FIX2LONG, rb_big2dbl(), rb_convert_type(), rb_eTypeError, rb_raise(), rb_str_to_dbl(), T_BIGNUM, T_FIXNUM, T_FLOAT, T_NIL, T_STRING, TRUE, TYPE, and UNREACHABLE.
Referenced by flo_coerce(), foletypelib_version(), int_round(), num_ceil(), num_coerce(), num_fdiv(), num_floor(), num_round(), num_truncate(), range_bsearch(), rb_f_float(), rb_num2dbl(), rb_str_format(), time_minus(), and time_to_f().
VALUE rb_Hash (VALUE val)
Definition at line 2778 of file object.c.
References NIL_P, RARRAY_LEN, rb_check_hash_type(), rb_eTypeError, rb_hash_new(), rb_obj_classname(), rb_raise(), RB_TYPE_P, and T_ARRAY.
Referenced by rb_f_hash().
VALUE rb_inspect (VALUE obj)
Definition at line 402 of file object.c.
References id_inspect, rb_default_external_encoding(), rb_eEncCompatError, rb_enc_asciicompat, rb_enc_get(), rb_enc_str_asciionly_p(), rb_funcall(), rb_obj_as_string(), and rb_raise().
Referenced by advice_arg_check(), bit_coerce(), cannot_be_coerced_into_BigDecimal(), coerce_rescue(), control_frame_dump(), env_inspect(), get_exception_sym2type(), insn_data_to_s_detail(), insn_operand_intern(), inspect_ary(), inspect_enumerator(), inspect_i(), inspect_range(), inspect_struct(), iseq_build_from_ary_body(), method_inspect(), name_err_mesg_to_str(), ossl_x509_inspect(), rb_check_id(), rb_cmperr(), rb_hash_fetch_m(), rb_mod_to_s(), rb_p(), rb_stat_inspect(), rb_str_format(), rb_throw_obj(), rb_to_id(), rb_vmdebug_debug_print_post(), rb_vmdebug_proc_dump_raw(), recursive_pop(), ruby__sfvextra(), ruby_debug_print_value(), and vm_check_if_namespace().
VALUE rb_Integer (VALUE val)
Definition at line 2469 of file object.c.
References rb_convert_to_integer().
Referenced by function_call(), get_freefunc(), ossl_x509stctx_set_time(), rb_dlcfunc_initialize(), rb_dlptr_initialize(), rb_dlptr_s_to_ptr(), rb_fiddle_ptr_initialize(), rb_fiddle_ptr_s_to_ptr(), rb_gzfile_set_mtime(), rb_str_format(), time_mdump(), time_to_time_t(), and value_to_generic().
VALUE rb_mod_attr (int argc, VALUE * argv, VALUE klass)
Definition at line 1831 of file object.c.
References Qfalse, Qnil, Qtrue, rb_attr(), rb_mod_attr_reader(), rb_to_id(), rb_warning(), RTEST, and TRUE.
Referenced by Init_Object().
static VALUE rb_mod_attr_accessor (int argc, VALUE * argv, VALUE klass) static
Definition at line 1876 of file object.c.
References argc, i, Qnil, rb_attr(), rb_to_id(), and TRUE.
Referenced by Init_Object().
static VALUE rb_mod_attr_reader (int argc, VALUE * argv, VALUE klass) static
Definition at line 1820 of file object.c.
References argc, FALSE, i, Qnil, rb_attr(), rb_to_id(), and TRUE.
Referenced by Init_Object(), and rb_mod_attr().
static VALUE rb_mod_attr_writer (int argc, VALUE * argv, VALUE klass) static
Definition at line 1850 of file object.c.
References argc, FALSE, i, Qnil, rb_attr(), rb_to_id(), and TRUE.
Referenced by Init_Object().
static VALUE rb_mod_cmp (VALUE mod, VALUE arg) static
Definition at line 1556 of file object.c.
References CLASS_OR_MODULE_P, cmp, INT2FIX, NIL_P, Qnil, and rb_class_inherited_p().
Referenced by Init_Object().
static VALUE rb_mod_const_defined (int argc, VALUE * argv, VALUE mod) static
Definition at line 2058 of file object.c.
References id, name, PRIsVALUE, Qfalse, Qtrue, QUOTE, QUOTE_ID, rb_check_id(), rb_const_defined(), rb_const_defined_at(), rb_is_const_id(), rb_is_const_name(), rb_name_error(), rb_name_error_str(), rb_scan_args(), recur, and RTEST.
Referenced by Init_Object().
static VALUE rb_mod_const_get (int argc, VALUE * argv, VALUE mod) static
Definition at line 1921 of file object.c.
References Check_Type, CLASS_OF, id, id_const_missing, ISUPPER, mod, name, p, PRIsVALUE, Qtrue, QUOTE, QUOTE_ID, rb_check_id_cstr(), rb_check_string_type(), rb_cObject, rb_const_get(), rb_const_get_at(), rb_eArgError, rb_eNameError, rb_enc_asciicompat, rb_enc_get(), rb_enc_symname2_p(), rb_eTypeError, rb_intern3(), rb_is_const_id(), rb_method_basic_definition_p(), rb_name_error(), rb_name_error_str(), rb_raise(), rb_scan_args(), rb_str_subseq(), rb_sym_to_s(), RB_TYPE_P, recur, RSTRING_LEN, RSTRING_PTR, RTEST, SYMBOL_P, T_CLASS, T_MODULE, and T_STRING.
Referenced by Init_Object().
static VALUE rb_mod_const_set (VALUE mod, VALUE name, VALUE value) static
Definition at line 2030 of file object.c.
References PRIsVALUE, QUOTE_ID, rb_const_set(), rb_is_const_id(), rb_name_error(), and rb_to_id().
Referenced by Init_Object().
static VALUE rb_mod_cvar_defined (VALUE obj, VALUE iv) static
Definition at line 2279 of file object.c.
References PRIsVALUE, Qfalse, QUOTE, QUOTE_ID, rb_check_id(), rb_cvar_defined(), rb_is_class_id(), rb_is_class_name(), rb_name_error(), and rb_name_error_str().
Referenced by Init_Object().
static VALUE rb_mod_cvar_get (VALUE obj, VALUE iv) static
Definition at line 2213 of file object.c.
References PRIsVALUE, QUOTE, QUOTE_ID, rb_check_id(), rb_class_name(), rb_cvar_get(), rb_is_class_id(), rb_is_class_name(), rb_name_error(), and rb_name_error_str().
Referenced by Init_Object().
static VALUE rb_mod_cvar_set (VALUE obj, VALUE iv, VALUE val) static
Definition at line 2252 of file object.c.
References PRIsVALUE, QUOTE_ID, rb_cvar_set(), rb_is_class_id(), rb_name_error(), and rb_to_id().
Referenced by Init_Object().
static VALUE rb_mod_eqq (VALUE mod, VALUE arg) static
Definition at line 1443 of file object.c.
References rb_obj_is_kind_of().
Referenced by Init_Object().
static VALUE rb_mod_freeze (VALUE mod) static
Definition at line 1426 of file object.c.
References rb_class_name(), and rb_obj_freeze().
Referenced by Init_Object().
static VALUE rb_mod_ge (VALUE mod, VALUE arg) static
Definition at line 1516 of file object.c.
References CLASS_OR_MODULE_P, rb_class_inherited_p(), rb_eTypeError, and rb_raise().
Referenced by Init_Object(), and rb_mod_gt().
static VALUE rb_mod_gt (VALUE mod, VALUE arg) static
Definition at line 1537 of file object.c.
References Qfalse, and rb_mod_ge().
Referenced by Init_Object().
static VALUE rb_mod_initialize (VALUE module) static
Definition at line 1615 of file object.c.
References Qnil, rb_block_given_p(), and rb_mod_module_exec().
Referenced by Init_Object(), and rb_class_initialize().
static VALUE rb_mod_lt (VALUE mod, VALUE arg) static
Definition at line 1496 of file object.c.
References Qfalse, and rb_class_inherited_p().
Referenced by Init_Object().
static VALUE rb_mod_to_s (VALUE klass) static
Definition at line 1382 of file object.c.
References CLASS_OR_MODULE_P, CONST_ID, FL_SINGLETON, FL_TEST, NIL_P, rb_any_to_s(), rb_attr_get(), rb_class_name(), rb_inspect(), rb_iv_get(), rb_refinement_module_get_refined_class(), rb_str_append(), rb_str_cat2(), rb_str_concat(), rb_str_dup(), rb_usascii_str_new2, and v.
Referenced by Init_Object().
static VALUE rb_module_s_alloc (VALUE klass) static
Definition at line 1574 of file object.c.
References mod, rb_module_new(), and RBASIC.
Referenced by Init_Object().
double rb_num2dbl (VALUE val)
Definition at line 2697 of file object.c.
References rb_eTypeError, rb_Float(), rb_raise(), RFLOAT_VALUE, T_FLOAT, T_NIL, T_STRING, and TYPE.
Referenced by thread_join_m().
VALUE rb_obj_alloc (VALUE klass)
Definition at line 1702 of file object.c.
References FL_SINGLETON, FL_TEST, PRIsVALUE, rb_cBasicObject, rb_class2name(), rb_class_real(), rb_eTypeError, rb_get_alloc_func(), rb_obj_class(), rb_raise(), rb_sourcefile, rb_sourceline(), RCLASS_SUPER, RUBY_DTRACE_OBJECT_CREATE, and RUBY_DTRACE_OBJECT_CREATE_ENABLED.
Referenced by bsock_s_for_fd(), build_exception(), enum_chunk(), enum_slice_before(), Init_Hash(), Init_Object(), Init_readline(), Init_Thread(), Init_tkutil(), Init_top_self(), int_ossl_asn1_decode0_cons(), int_ossl_asn1_decode0_prim(), obj_alloc_by_klass(), ossl_sslctx_session_new_cb(), ossl_sslctx_session_remove_cb(), prep_window(), pty_getpty(), pty_open(), r_object0(), rb_catch(), rb_class_new_instance(), rb_digest_class_s_digest(), rb_f_catch(), rb_io_s_for_fd(), rb_last_status_set(), rb_obj_clone(), rb_obj_dup(), rb_range_new(), rsock_s_accept(), rsock_s_accept_nonblock(), and RUBY_ALIAS_FUNCTION().
VALUE rb_obj_class (VALUE obj)
Definition at line 194 of file object.c.
References CLASS_OF, and rb_class_real().
Referenced by ary_make_shared_copy(), cannot_be_coerced_into_BigDecimal(), cbsubst_initialize(), copy_path_class(), d_lite_plus(), dup_obj(), dup_obj_as_complex(), encoded_dup(), exc_equal(), Init_Object(), inspect_struct(), io_reopen(), ip_eval(), ip_invoke_with_position(), mString_to_json_raw_object(), name_err_mesg_equal(), NOINSERT_UPDATE_CALLBACK(), ossl_cipher_init(), ossl_x509_inspect(), path_basename(), path_dirname(), path_each_entry(), path_entries(), path_expand_path(), path_readlink(), path_realdirpath(), path_realpath(), path_split(), path_sub(), path_sub_ext(), random_equal(), rb_ary_slice_bang(), rb_ary_subseq(), rb_ary_times(), rb_ary_to_a(), rb_ary_uniq(), rb_digest_base_block_length(), rb_digest_base_copy(), rb_digest_base_digest_length(), rb_digest_base_finish(), rb_digest_base_reset(), rb_digest_base_update(), rb_hash_dup(), rb_hash_to_h(), rb_ivar_set(), rb_obj_alloc(), rb_obj_clone(), rb_obj_dup(), rb_obj_init_copy(), rb_obj_is_instance_of(), rb_stat_cmp(), rb_str_dup(), rb_str_new_frozen(), rb_str_new_shared(), rb_str_substr(), rb_str_to_s(), rb_struct_eql(), rb_struct_equal(), rb_struct_initialize_m(), rb_struct_members(), rb_struct_members_m(), rb_tmp_class_path(), recursive_hash(), RUBY_ALIAS_FUNCTION(), str_byte_substr(), str_gsub(), syserr_initialize(), tcl_protect_core(), time_dup(), tk_funcall(), and window_subwin().
VALUE rb_obj_clone (VALUE obj)
Definition at line 296 of file object.c.
References FL_FINALIZE, FL_FREEZE, FL_SINGLETON, FL_TAINT, FL_TEST, FL_UNTRUSTED, id_init_clone, init_copy(), rb_eTypeError, rb_funcall(), rb_obj_alloc(), rb_obj_class(), rb_obj_classname(), rb_raise(), rb_singleton_class_attached(), rb_singleton_class_clone_and_attach(), rb_special_const_p(), and RBASIC.
Referenced by exc_exception(), Init_Object(), rb_digest_instance_digest(), rb_digest_instance_hexdigest(), rb_digest_instance_new(), rb_eval_string_wrap(), and rb_load_internal().
static VALUE rb_obj_cmp (VALUE obj1, VALUE obj2) static
Definition at line 1337 of file object.c.
References INT2FIX, Qnil, and rb_equal().
Referenced by Init_Object().
static VALUE rb_obj_dummy (void) static
Definition at line 830 of file object.c.
References Qnil.
Referenced by Init_Object().
VALUE rb_obj_dup (VALUE obj)
Definition at line 338 of file object.c.
References id_init_dup, init_copy(), rb_eTypeError, rb_funcall(), rb_obj_alloc(), rb_obj_class(), rb_obj_classname(), rb_raise(), and rb_special_const_p().
Referenced by argf_initialize_copy(), chunk_i(), enumerator_each(), Init_Object(), lib_fromUTF8_core(), path_initialize(), path_to_s(), rb_hash_merge(), rb_hash_reject(), rb_io_init_copy(), setup_exception(), and slicebefore_i().
VALUE rb_obj_equal (VALUE obj1, VALUE obj2)
Definition at line 109 of file object.c.
References Qfalse, and Qtrue.
Referenced by Init_Object(), and opt_eq_func().
VALUE rb_obj_freeze (VALUE obj)
Definition at line 971 of file object.c.
References OBJ_FREEZE, OBJ_FROZEN, OBJ_UNTRUSTED, Qtrue, rb_eSecurityError, rb_raise(), rb_safe_level, SPECIAL_CONST_P, st_init_numtable(), and st_insert().
Referenced by console_dev(), create_encoding_table_core(), env_str_new(), Init_eval(), Init_File(), Init_GC(), Init_Object(), Init_ossl_ssl(), Init_Proc(), Init_strscan(), Init_tcltklib(), Init_tkutil(), Init_VM(), mk_ary_of_str(), ossl_sslctx_setup(), prep_io(), process_options(), pty_getpty(), pty_open(), rb_ary_flatten_bang(), rb_ary_freeze(), rb_construct_expanded_load_path(), rb_f_getenv(), rb_hash_freeze(), rb_insns_name_array(), rb_mod_freeze(), rb_str_freeze(), rb_str_upto(), ruby_init_loadpath_safe(), run_finalizer(), set_arg0(), tcltklib_compile_info(), update_encoding_table(), and vm_default_params().
VALUE rb_obj_frozen_p (VALUE obj)
Definition at line 1000 of file object.c.
References OBJ_FROZEN, Qfalse, Qtrue, SPECIAL_CONST_P, and st_lookup().
Referenced by generic_ivar_set(), and Init_Object().
VALUE rb_obj_hash (VALUE obj)
Definition at line 129 of file object.c.
References LONG2FIX, NUM2LONG, rb_hash_end, rb_hash_start(), and rb_obj_id().
Referenced by Init_Object().
void rb_obj_infect (VALUE obj1, VALUE obj2)
Definition at line 942 of file object.c.
References OBJ_INFECT.
VALUE rb_obj_init_copy (VALUE obj, VALUE orig)
Definition at line 354 of file object.c.
References rb_check_frozen, rb_check_trusted, rb_eTypeError, rb_obj_class(), rb_raise(), and TYPE.
Referenced by Init_Object(), and rb_mod_init_copy().
VALUE rb_obj_init_dup_clone (VALUE obj, VALUE orig)
Definition at line 367 of file object.c.
References id_init_copy, and rb_funcall().
Referenced by Init_Object().
static VALUE rb_obj_inspect (VALUE obj) static
Definition at line 496 of file object.c.
References c, CLASS_OF, inspect_obj(), PRIsVALUE, rb_any_to_s(), rb_class_name(), rb_exec_recursive(), rb_ivar_count(), and rb_sprintf().
Referenced by Init_Object().
VALUE rb_obj_is_instance_of (VALUE obj, VALUE c)
Definition at line 545 of file object.c.
References class_or_module_required(), Qfalse, Qtrue, and rb_obj_class().
Referenced by error_handle(), Init_Object(), ossl_pkey_initialize(), ossl_ssl_session_initialize(), ossl_ssl_session_set_time(), ossl_sslctx_flush_sessions(), and ossl_sslctx_session_get_cb().
VALUE rb_obj_is_kind_of (VALUE obj, VALUE c)
Definition at line 582 of file object.c.
References CLASS_OF, class_or_module_required(), Qfalse, Qtrue, RCLASS_M_TBL, RCLASS_ORIGIN, and RCLASS_SUPER.
Referenced by case_when_optimizable_literal(), check_match(), cState_from_state_s(), discrete_object_p(), encoding_table_get_name_core(), encoding_table_get_obj_core(), error_handle(), ev_advise(), eval_string_with_cref(), EVENTSINK_Invoke(), f_kind_of_p(), fole_s_const_load(), fole_s_show_help(), folemethod_initialize(), foleparam_initialize(), folevariant_initialize(), get_eval_string_core(), GetBNPtr(), gzfile_read_raw_rescue(), host_str(), Init_Object(), ip_eval(), ip_invoke_with_position(), ip_is_slave_of_p(), ip_rbTkWaitCommand(), ip_rbUpdateCommand(), ip_rbVwaitCommand(), make_exception(), ole_invoke(), ole_val2variant(), os_obj_of_i(), ossl_asn1cons_to_der(), ossl_asn1data_to_der(), ossl_bn_coerce(), ossl_bn_initialize(), parse(), path_cmp(), path_eq(), pending_exception_check0(), pending_exception_check1(), range_eq(), range_eql(), range_include(), range_max(), range_size(), range_step(), range_step_size(), rb_ary_bsearch(), rb_check_to_float(), rb_check_to_integer(), rb_digest_instance_equal(), rb_dlptr2cptr(), rb_dlptr_aset(), rb_dlptr_cmp(), rb_dlptr_eql(), rb_dlptr_s_to_ptr(), rb_enumeratorize_with_size(), rb_fiddle_ptr2cptr(), rb_fiddle_ptr_aset(), rb_fiddle_ptr_cmp(), rb_fiddle_ptr_eql(), rb_fiddle_ptr_s_to_ptr(), rb_method_call_status(), rb_mod_eqq(), rb_range_values(), rb_rescue2(), rb_set_errinfo(), rb_stat_cmp(), rb_thread_pending_interrupt_p(), rb_to_float(), rb_to_integer(), ruby_cleanup(), setup_exception(), syserr_eqq(), tcl_protect_core(), thread_start_func_2(), tk_funcall(), total_i(), umethod_bind(), vm_call_method(), and vm_search_super_method().
static VALUE rb_obj_ivar_defined (VALUE obj, VALUE iv) static
Definition at line 2178 of file object.c.
References PRIsVALUE, Qfalse, QUOTE, QUOTE_ID, rb_check_id(), rb_is_instance_id(), rb_is_instance_name(), rb_ivar_defined(), rb_name_error(), and rb_name_error_str().
Referenced by Init_Object().
static VALUE rb_obj_ivar_get (VALUE obj, VALUE iv) static
Definition at line 2107 of file object.c.
References PRIsVALUE, Qnil, QUOTE, QUOTE_ID, rb_check_id(), rb_is_instance_id(), rb_is_instance_name(), rb_ivar_get(), rb_name_error(), and rb_name_error_str().
Referenced by Init_Object().
static VALUE rb_obj_ivar_set (VALUE obj, VALUE iv, VALUE val) static
Definition at line 2148 of file object.c.
References PRIsVALUE, QUOTE_ID, rb_is_instance_id(), rb_ivar_set(), rb_name_error(), and rb_to_id().
Referenced by Init_Object().
static VALUE rb_obj_match (VALUE obj1, VALUE obj2) static
Definition at line 1298 of file object.c.
References Qnil.
Referenced by Init_Object().
VALUE rb_obj_not (VALUE obj)
Definition at line 151 of file object.c.
References Qfalse, Qtrue, and RTEST.
Referenced by Init_Object().
VALUE rb_obj_not_equal (VALUE obj1, VALUE obj2)
Definition at line 164 of file object.c.
References id_eq, Qfalse, Qtrue, rb_funcall(), result, and RTEST.
Referenced by Init_Object().
static VALUE rb_obj_not_match (VALUE obj1, VALUE obj2) static
Definition at line 1312 of file object.c.
References id_match, Qfalse, Qtrue, rb_funcall(), result, and RTEST.
Referenced by Init_Object().
static VALUE rb_obj_singleton_class (VALUE obj) static
Definition at line 217 of file object.c.
References rb_singleton_class().
Referenced by Init_Object().
VALUE rb_obj_taint (VALUE obj)
Definition at line 860 of file object.c.
References OBJ_TAINT, OBJ_TAINTED, rb_check_frozen, and rb_secure().
Referenced by Init_Object(), pack_pack(), path_taint(), rb_file_path(), rsock_s_recvfrom(), rsock_s_recvfrom_nonblock(), and tk_obj_untrust().
VALUE rb_obj_tainted (VALUE obj)
Definition at line 843 of file object.c.
References OBJ_TAINTED, Qfalse, and Qtrue.
Referenced by Init_Object().
VALUE rb_obj_tap (VALUE obj)
Definition at line 613 of file object.c.
References rb_yield().
Referenced by Init_Object().
VALUE rb_obj_trust (VALUE obj)
Definition at line 931 of file object.c.
References FL_UNSET, FL_UNTRUSTED, OBJ_UNTRUSTED, rb_check_frozen, and rb_secure().
Referenced by Init_Object().
VALUE rb_obj_untaint (VALUE obj)
Definition at line 879 of file object.c.
References FL_TAINT, FL_UNSET, OBJ_TAINTED, rb_check_frozen, and rb_secure().
Referenced by Init_Object(), path_untaint(), and time_zone().
VALUE rb_obj_untrust (VALUE obj)
Definition at line 912 of file object.c.
References OBJ_UNTRUST, OBJ_UNTRUSTED, rb_check_frozen, and rb_secure().
Referenced by Init_Object(), and tk_obj_untrust().
VALUE rb_obj_untrusted (VALUE obj)
Definition at line 897 of file object.c.
References OBJ_UNTRUSTED, Qfalse, and Qtrue.
Referenced by Init_Object().
double rb_str_to_dbl (VALUE str, int badcheck)
Definition at line 2600 of file object.c.
References ALLOCV, ALLOCV_END, MEMCPY, p, rb_cstr_to_dbl(), rb_eArgError, rb_raise(), RSTRING_LEN, RSTRING_PTR, StringValue, and v.
Referenced by f_to_f(), rb_Float(), and rb_str_to_f().
VALUE rb_String (VALUE val)
Definition at line 2719 of file object.c.
References NIL_P, rb_check_string_type(), rb_convert_type(), and T_STRING.
Referenced by exc_to_s(), GetBNPtr(), make_version_str(), ossl_sslctx_set_ciphers(), and rb_f_string().
VALUE rb_to_float (VALUE val)
Definition at line 2673 of file object.c.
References NIL_P, Qfalse, Qtrue, rb_cNumeric, rb_convert_type(), rb_eTypeError, rb_obj_classname(), rb_obj_is_kind_of(), rb_raise(), RB_TYPE_P, and T_FLOAT.
Referenced by pack_pack(), and rand_range().
VALUE rb_to_int (VALUE val)
Definition at line 2412 of file object.c.
References rb_to_integer().
Referenced by check_exec_redirect(), econv_args(), econv_primitive_convert(), enumerator_initialize(), fix_aref(), obj2vint(), pack_pack(), rand_init(), random_bytes(), random_load(), range_bsearch(), range_step(), range_step_size(), rb_big_lshift(), rb_big_pack(), rb_big_rshift(), rb_dlcfunc_call(), rb_execarg_addopt(), rb_f_rand(), rb_hash(), rb_num2long(), rb_num2ulong(), rb_quad_pack(), time_nsec(), time_round(), and time_usec().
static VALUE rb_to_integer (VALUE val, const char * method) static
Definition at line 2382 of file object.c.
References convert_type(), FIXNUM_P, rb_cInteger, rb_eTypeError, rb_obj_classname(), rb_obj_is_kind_of(), rb_raise(), RB_TYPE_P, T_BIGNUM, TRUE, and v.
Referenced by rb_convert_to_integer(), and rb_to_int().
static VALUE rb_true (VALUE obj) static
Definition at line 1267 of file object.c.
References Qtrue.
Referenced by Init_Object().
static VALUE true_and (VALUE obj, VALUE obj2) static
Definition at line 1141 of file object.c.
References Qfalse, Qtrue, and RTEST.
Referenced by Init_Object().
static VALUE true_or (VALUE obj, VALUE obj2) static
Definition at line 1163 of file object.c.
References Qtrue.
Referenced by Init_Object().
static VALUE true_to_s (VALUE obj) static
Definition at line 1126 of file object.c.
References rb_usascii_str_new2.
Referenced by Init_Object().
static VALUE true_xor (VALUE obj, VALUE obj2) static
Definition at line 1179 of file object.c.
References Qfalse, Qtrue, and RTEST.
Referenced by Init_Object().
Variable Documentation
struct conv_method_tbl conv_method_names[] static
Initial value:
= {
    {"to_int", 0},
    {"to_ary", 0},
    {"to_str", 0},
    {"to_sym", 0},
    {"to_hash", 0},
    {"to_proc", 0},
    {"to_io", 0},
    {"to_a", 0},
    {"to_s", 0},
    {NULL, 0}
}
Referenced by convert_type(), and Init_Object().
ID id_const_missing static
Definition at line 40 of file object.c.
Referenced by Init_Object(), and rb_mod_const_get().
ID id_eq static
Definition at line 38 of file object.c.
Referenced by Init_Object(), rb_equal(), and rb_obj_not_equal().
ID id_eql static
Definition at line 38 of file object.c.
Referenced by Init_Object(), and rb_eql().
ID id_init_clone static
Definition at line 39 of file object.c.
Referenced by Init_Object(), and rb_obj_clone().
ID id_init_copy static
Definition at line 39 of file object.c.
Referenced by Init_Object(), and rb_obj_init_dup_clone().
ID id_init_dup static
Definition at line 39 of file object.c.
Referenced by Init_Object(), and rb_obj_dup().
ID id_inspect static
Definition at line 38 of file object.c.
Referenced by Init_Object(), and rb_inspect().
ID id_match static
Definition at line 38 of file object.c.
Referenced by Init_Object(), and rb_obj_not_match().
st_table* immediate_frozen_tbl = 0 static
Definition at line 947 of file object.c.
VALUE rb_cBasicObject
Definition at line 27 of file object.c.
VALUE rb_cClass
Definition at line 31 of file object.c.
VALUE rb_cData
Definition at line 32 of file object.c.
VALUE rb_cFalseClass
Definition at line 36 of file object.c.
VALUE rb_cModule
Definition at line 30 of file object.c.
VALUE rb_cNilClass
Definition at line 34 of file object.c.
VALUE rb_cObject
Definition at line 29 of file object.c.
VALUE rb_cTrueClass
Definition at line 35 of file object.c.
VALUE rb_mKernel
Definition at line 28 of file object.c.