Ruby: error.c File Reference
error.c File Reference
#include "ruby/ruby.h"
#include "ruby/st.h"
#include "ruby/encoding.h"
#include "internal.h"
#include "vm_core.h"
#include <stdio.h>
#include <stdarg.h>
#include <errno.h>
#include "known_errors.inc"
Macros
#define numberof(array) (int)(sizeof(array) / sizeof((array)[0]))
#define EXIT_SUCCESS 0
#define WIFEXITED(status) 1
#define WEXITSTATUS(status) (status)
#define REPORTBUG_MSG
#define defined_error(name, num) if (err == (num)) return (name);
#define undefined_error(name)
#define write_or_abort(fd, str, len) (write((fd), (str), (len)) < 0 ? abort() : (void)0)
#define WRITE_CONST(fd, str) write_or_abort((fd),(str),sizeof(str) - 1)
#define builtin_class_name rb_builtin_class_name
#define NAME_ERR_MESG_COUNT 3
#define name_err_mesg_free RUBY_TYPED_DEFAULT_FREE
#define defined_error(name, num) set_syserr((num), (name));
#define undefined_error(name) set_syserr(0, (name));
Functions
static const char * rb_strerrno (int err)
static int err_position_0 (char *buf, long len, const char *file, int line)
static VALUE compile_snprintf (rb_encoding *enc, const char *pre, const char *file, int line, const char *fmt, va_list args)
static void compile_err_append (VALUE mesg)
void rb_compile_error_with_enc (const char *file, int line, void *enc, const char *fmt,...)
void rb_compile_error (const char *file, int line, const char *fmt,...)
void rb_compile_error_append (const char *fmt,...)
static void compile_warn_print (const char *file, int line, const char *fmt, va_list args)
void rb_compile_warn (const char *file, int line, const char *fmt,...)
void rb_compile_warning (const char *file, int line, const char *fmt,...)
static void warn_print (const char *fmt, va_list args)
void rb_warn (const char *fmt,...)
void rb_warning (const char *fmt,...)
static VALUE rb_warn_m (int argc, VALUE *argv, VALUE exc)
static void report_bug (const char *file, int line, const char *fmt, va_list args)
void rb_bug (const char *fmt,...)
void rb_bug_errno (const char *mesg, int errno_arg)
void rb_async_bug_errno (const char *mesg, int errno_arg)
void rb_compile_bug (const char *file, int line, const char *fmt,...)
const char * rb_builtin_type_name (int t)
const char * rb_builtin_class_name (VALUE x)
void rb_check_type (VALUE x, int t)
int rb_typeddata_inherited_p (const rb_data_type_t *child, const rb_data_type_t *parent)
int rb_typeddata_is_kind_of (VALUE obj, const rb_data_type_t *data_type)
void * rb_check_typeddata (VALUE obj, const rb_data_type_t *data_type)
VALUE rb_exc_new (VALUE etype, const char *ptr, long len)
VALUE rb_exc_new2 (VALUE etype, const char *s)
VALUE rb_exc_new3 (VALUE etype, VALUE str)
static VALUE exc_initialize (int argc, VALUE *argv, VALUE exc)
static VALUE exc_exception (int argc, VALUE *argv, VALUE self)
static VALUE exc_to_s (VALUE exc)
static VALUE exc_message (VALUE exc)
static VALUE exc_inspect (VALUE exc)
static VALUE exc_backtrace (VALUE exc)
VALUE rb_check_backtrace (VALUE bt)
static VALUE exc_set_backtrace (VALUE exc, VALUE bt)
VALUE rb_exc_set_backtrace (VALUE exc, VALUE bt)
static VALUE try_convert_to_exception (VALUE obj)
static VALUE exc_equal (VALUE exc, VALUE obj)
static VALUE exit_initialize (int argc, VALUE *argv, VALUE exc)
static VALUE exit_status (VALUE exc)
static VALUE exit_success_p (VALUE exc)
void rb_name_error (ID id, const char *fmt,...)
void rb_name_error_str (VALUE str, const char *fmt,...)
static VALUE name_err_initialize (int argc, VALUE *argv, VALUE self)
static VALUE name_err_name (VALUE self)
static VALUE name_err_to_s (VALUE exc)
static VALUE nometh_err_initialize (int argc, VALUE *argv, VALUE self)
static void name_err_mesg_mark (void *p)
static size_t name_err_mesg_memsize (const void *p)
VALUE rb_name_err_mesg_new (VALUE obj, VALUE mesg, VALUE recv, VALUE method)
static VALUE name_err_mesg_equal (VALUE obj1, VALUE obj2)
static VALUE name_err_mesg_to_str (VALUE obj)
static VALUE name_err_mesg_dump (VALUE obj, VALUE limit)
static VALUE name_err_mesg_load (VALUE klass, VALUE str)
static VALUE nometh_err_args (VALUE self)
void rb_invalid_str (const char *str, const char *type)
static VALUE set_syserr (int n, const char *name)
static VALUE get_syserr (int n)
static VALUE syserr_initialize (int argc, VALUE *argv, VALUE self)
static VALUE syserr_errno (VALUE self)
static VALUE syserr_eqq (VALUE self, VALUE exc)
void Init_Exception (void)
void rb_enc_raise (rb_encoding *enc, VALUE exc, const char *fmt,...)
void rb_raise (VALUE exc, const char *fmt,...)
NORETURN (static void raise_loaderror(VALUE path, VALUE mesg))
static void raise_loaderror (VALUE path, VALUE mesg)
void rb_loaderror (const char *fmt,...)
void rb_loaderror_with_path (VALUE path, const char *fmt,...)
void rb_notimplement (void)
void rb_fatal (const char *fmt,...)
static VALUE make_errno_exc (const char *mesg)
static VALUE make_errno_exc_str (VALUE mesg)
VALUE rb_syserr_new (int n, const char *mesg)
VALUE rb_syserr_new_str (int n, VALUE arg)
void rb_syserr_fail (int e, const char *mesg)
void rb_syserr_fail_str (int e, VALUE mesg)
void rb_sys_fail (const char *mesg)
void rb_sys_fail_str (VALUE mesg)
void rb_mod_sys_fail (VALUE mod, const char *mesg)
void rb_mod_sys_fail_str (VALUE mod, VALUE mesg)
void rb_mod_syserr_fail (VALUE mod, int e, const char *mesg)
void rb_mod_syserr_fail_str (VALUE mod, int e, VALUE mesg)
void rb_sys_warning (const char *fmt,...)
void rb_load_fail (VALUE path, const char *err)
void rb_error_frozen (const char *what)
void rb_check_frozen (VALUE obj)
void rb_error_untrusted (VALUE obj)
void rb_check_trusted (VALUE obj)
void rb_check_copyable (VALUE obj, VALUE orig)
void Init_syserr (void)
Variables
const char ruby_description []
static const char builtin_types [][10]
VALUE rb_eException
VALUE rb_eSystemExit
VALUE rb_eInterrupt
VALUE rb_eSignal
VALUE rb_eFatal
VALUE rb_eStandardError
VALUE rb_eRuntimeError
VALUE rb_eTypeError
VALUE rb_eArgError
VALUE rb_eIndexError
VALUE rb_eKeyError
VALUE rb_eRangeError
VALUE rb_eNameError
VALUE rb_eEncodingError
VALUE rb_eEncCompatError
VALUE rb_eNoMethodError
VALUE rb_eSecurityError
VALUE rb_eNotImpError
VALUE rb_eNoMemError
VALUE rb_cNameErrorMesg
VALUE rb_eScriptError
VALUE rb_eSyntaxError
VALUE rb_eLoadError
VALUE rb_eSystemCallError
VALUE rb_mErrno
static VALUE rb_eNOERROR
static const rb_data_type_t name_err_mesg_data_type
static st_table * syserr_tbl
Macro Definition Documentation
#define builtin_class_name rb_builtin_class_name
Definition at line 412 of file error.c.
Referenced by rb_check_type(), and rb_check_typeddata().
#define defined_error (name, num) if (err == (num)) return (name);
#define defined_error (name, num) set_syserr((num), (name));
#define EXIT_SUCCESS 0
Definition at line 31 of file error.c.
Referenced by error_handle(), exit_initialize(), exit_success_p(), goruby_run_node(), options(), rb_thread_kill(), ruby_cleanup(), and ruby_executable_node().
#define NAME_ERR_MESG_COUNT 3
Definition at line 999 of file error.c.
Referenced by Init_Exception(), name_err_mesg_equal(), name_err_mesg_mark(), name_err_mesg_memsize(), name_err_mesg_to_str(), and rb_name_err_mesg_new().
#define name_err_mesg_free RUBY_TYPED_DEFAULT_FREE
Definition at line 1008 of file error.c.
#define numberof (array) (int)(sizeof(array) / sizeof((array)[0]))
Definition at line 28 of file error.c.
Referenced by rb_builtin_type_name().
#define REPORTBUG_MSG
Value:
"[NOTE]\n" \
        "You may have encountered a bug in the Ruby interpreter" \
        " or extension libraries.\n" \
        "Bug reports are welcome.\n" \
        "For details: http://www.ruby-lang.org/bugreport.html\n\n" \
Definition at line 44 of file error.c.
Referenced by rb_async_bug_errno(), and report_bug().
#define undefined_error (name)
#define undefined_error (name) set_syserr(0, (name));
#define WEXITSTATUS (status) (status)
Definition at line 39 of file error.c.
Referenced by exit_success_p().
#define WIFEXITED (status) 1
Definition at line 35 of file error.c.
Referenced by exit_success_p().
#define WRITE_CONST (fd, str) write_or_abort((fd),(str),sizeof(str) - 1)
Definition at line 331 of file error.c.
Referenced by rb_async_bug_errno().
#define write_or_abort (fd, str, len) (write((fd), (str), (len)) < 0 ? abort() : (void)0)
Definition at line 330 of file error.c.
Referenced by rb_async_bug_errno().
Function Documentation
static void compile_err_append (VALUE mesg) static
Definition at line 92 of file error.c.
References rb_thread_struct::base_block, err, rb_thread_struct::errinfo, GET_THREAD(), rb_thread_struct::mild_compile_error, rb_eSyntaxError, rb_exc_new2(), rb_exc_new3(), rb_obj_as_string(), rb_str_append(), rb_str_cat2(), rb_write_error_str(), and RTEST.
Referenced by rb_compile_error(), rb_compile_error_append(), and rb_compile_error_with_enc().
static VALUE compile_snprintf (rb_encoding * enc, const char * pre, const char * file, int line, const char * fmt, va_list args) static
Definition at line 77 of file error.c.
References rb_enc_str_new(), rb_str_cat2(), rb_str_catf(), and rb_str_vcatf().
Referenced by compile_warn_print(), rb_compile_error(), and rb_compile_error_with_enc().
static void compile_warn_print (const char * file, int line, const char * fmt, va_list args) static
Definition at line 162 of file error.c.
References compile_snprintf(), NULL, rb_str_cat2(), and rb_write_error_str().
Referenced by rb_compile_warn(), and rb_compile_warning().
static int err_position_0 (char * buf, long len, const char * file, int line) static
Definition at line 63 of file error.c.
References snprintf.
Referenced by report_bug().
static VALUE exc_backtrace (VALUE exc) static
Definition at line 693 of file error.c.
References CONST_ID, enumerator::obj, rb_attr_get(), rb_backtrace_p(), and rb_backtrace_to_str_ary().
Referenced by exc_equal(), and Init_Exception().
static VALUE exc_equal (VALUE exc, VALUE obj) static
Definition at line 770 of file error.c.
References CONST_ID, exc_backtrace(), Qfalse, Qnil, Qtrue, Qundef, rb_attr_get(), rb_check_funcall(), rb_equal(), rb_obj_class(), rb_protect(), rb_set_errinfo(), and try_convert_to_exception().
Referenced by Init_Exception().
static VALUE exc_exception (int argc, VALUE * argv, VALUE self) static
Definition at line 588 of file error.c.
References exc_initialize(), and rb_obj_clone().
Referenced by Init_Exception().
static VALUE exc_initialize (int argc, VALUE * argv, VALUE exc) static
Definition at line 563 of file error.c.
References arg, Qnil, rb_iv_set(), and rb_scan_args().
Referenced by exc_exception(), and Init_Exception().
static VALUE exc_inspect (VALUE exc) static
Definition at line 643 of file error.c.
References CLASS_OF, rb_class_name(), rb_obj_as_string(), rb_str_buf_append(), rb_str_buf_cat(), rb_str_buf_new2, rb_str_dup(), and RSTRING_LEN.
Referenced by Init_Exception().
static VALUE exc_message (VALUE exc) static
Definition at line 630 of file error.c.
References rb_funcall(), and rb_intern.
Referenced by Init_Exception().
static VALUE exc_set_backtrace (VALUE exc, VALUE bt) static
Definition at line 741 of file error.c.
References rb_check_backtrace(), and rb_iv_set().
Referenced by Init_Exception(), and rb_exc_set_backtrace().
static VALUE exc_to_s (VALUE exc) static
Definition at line 609 of file error.c.
References CLASS_OF, NIL_P, Qnil, rb_attr_get(), rb_class_name(), rb_intern, and rb_String().
Referenced by Init_Exception().
static VALUE exit_initialize (int argc, VALUE * argv, VALUE exc) static
Definition at line 820 of file error.c.
References argc, argv, EXIT_FAILURE, EXIT_SUCCESS, INT2FIX, NIL_P, Qfalse, Qtrue, rb_call_super(), rb_check_to_int(), and rb_iv_set().
Referenced by Init_Exception().
static VALUE exit_status (VALUE exc) static
Definition at line 870 of file error.c.
References rb_attr_get(), and rb_intern.
Referenced by Init_Exception().
static VALUE exit_success_p (VALUE exc) static
Definition at line 884 of file error.c.
References EXIT_SUCCESS, NIL_P, NUM2INT, Qfalse, Qtrue, rb_attr_get(), rb_intern, WEXITSTATUS, and WIFEXITED.
Referenced by Init_Exception().
static VALUE get_syserr (int n) static
Definition at line 1196 of file error.c.
References name, set_syserr(), snprintf, and st_lookup().
Referenced by rb_syserr_new_str().
void Init_Exception (void)
Definition at line 1698 of file error.c.
References exc_backtrace(), exc_equal(), exc_exception(), exc_initialize(), exc_inspect(), exc_message(), exc_set_backtrace(), exc_to_s(), exit_initialize(), exit_status(), exit_success_p(), name_err_initialize(), NAME_ERR_MESG_COUNT, name_err_mesg_dump(), name_err_mesg_equal(), name_err_mesg_load(), name_err_mesg_to_str(), name_err_name(), name_err_to_s(), nometh_err_args(), nometh_err_initialize(), Qfalse, rb_attr(), rb_cData, rb_cEncoding, rb_class_new_instance(), rb_cNameErrorMesg, rb_cObject, rb_define_class(), rb_define_class_under(), rb_define_global_function(), rb_define_method(), rb_define_module(), rb_define_singleton_method(), rb_eArgError, rb_eEncCompatError, rb_eEncodingError, rb_eException, rb_eFatal, rb_eIndexError, rb_eInterrupt, rb_eKeyError, rb_eLoadError, rb_eNameError, rb_eNoMemError, rb_eNoMethodError, rb_eNotImpError, rb_eRangeError, rb_eRuntimeError, rb_eScriptError, rb_eSecurityError, rb_eSignal, rb_eStandardError, rb_eSyntaxError, rb_eSystemCallError, rb_eSystemExit, rb_eTypeError, rb_intern, rb_mErrno, rb_name_err_mesg_new(), rb_warn_m(), st_init_numtable(), syserr_eqq(), syserr_errno(), and syserr_initialize().
void Init_syserr (void)
Definition at line 2016 of file error.c.
References rb_eNOERROR, and set_syserr().
static VALUE make_errno_exc (const char * mesg) static
Definition at line 1847 of file error.c.
References errno, rb_bug(), and rb_syserr_new().
Referenced by rb_mod_sys_fail(), and rb_sys_fail().
static VALUE make_errno_exc_str (VALUE mesg) static
Definition at line 1859 of file error.c.
References errno, NIL_P, Qnil, rb_bug(), rb_syserr_new_str(), and RSTRING_PTR.
Referenced by rb_mod_sys_fail_str(), and rb_sys_fail_str().
static VALUE name_err_initialize (int argc, VALUE * argv, VALUE self) static
Definition at line 938 of file error.c.
References name, Qnil, rb_call_super(), and rb_iv_set().
Referenced by Init_Exception(), and nometh_err_initialize().
static VALUE name_err_mesg_dump (VALUE obj, VALUE limit) static
Definition at line 1112 of file error.c.
References name_err_mesg_to_str().
Referenced by Init_Exception().
static VALUE name_err_mesg_equal (VALUE obj1, VALUE obj2) static
Definition at line 1044 of file error.c.
References i, NAME_ERR_MESG_COUNT, Qfalse, Qtrue, rb_cNameErrorMesg, rb_equal(), rb_obj_class(), and TypedData_Get_Struct.
Referenced by Init_Exception().
static VALUE name_err_mesg_load (VALUE klass, VALUE str) static
Definition at line 1119 of file error.c.
Referenced by Init_Exception().
static void name_err_mesg_mark (void * p) static
Definition at line 1002 of file error.c.
References NAME_ERR_MESG_COUNT, p, and rb_gc_mark_locations.
static size_t name_err_mesg_memsize (const void * p) static
Definition at line 1011 of file error.c.
References NAME_ERR_MESG_COUNT.
static VALUE name_err_mesg_to_str (VALUE obj) static
Definition at line 1064 of file error.c.
References args, CLASS_OF, NAME_ERR_MESG_COUNT, NIL_P, Qfalse, Qnil, Qtrue, rb_any_to_s(), rb_class_name(), rb_f_sprintf(), rb_inspect(), rb_protect(), rb_set_errinfo(), rb_str_append(), rb_str_cat2(), rb_str_dup(), rb_str_new2, RSTRING_LEN, RSTRING_PTR, and TypedData_Get_Struct.
Referenced by Init_Exception(), and name_err_mesg_dump().
static VALUE name_err_name (VALUE self) static
Definition at line 956 of file error.c.
References rb_attr_get(), and rb_intern.
Referenced by Init_Exception().
static VALUE name_err_to_s (VALUE exc) static
Definition at line 969 of file error.c.
References CLASS_OF, NIL_P, rb_attr_get(), rb_class_name(), rb_intern, and StringValue.
Referenced by Init_Exception().
static VALUE nometh_err_args (VALUE self) static
Definition at line 1133 of file error.c.
References rb_attr_get(), and rb_intern.
Referenced by Init_Exception().
static VALUE nometh_err_initialize (int argc, VALUE * argv, VALUE self) static
Definition at line 990 of file error.c.
References args, name_err_initialize(), Qnil, and rb_iv_set().
Referenced by Init_Exception().
NORETURN (static void raise_loaderrorVALUE path, VALUE mesg)
static void raise_loaderror (VALUE path, VALUE mesg) static
Definition at line 1794 of file error.c.
References err, rb_eLoadError, rb_exc_new3(), rb_exc_raise(), rb_intern, and rb_ivar_set().
Referenced by rb_load_fail(), rb_loaderror(), and rb_loaderror_with_path().
void rb_async_bug_errno (const char * mesg, int errno_arg)
Definition at line 334 of file error.c.
References rb_strerrno(), REPORTBUG_MSG, ruby_description, strlen(), WRITE_CONST, and write_or_abort.
void rb_bug (const char * fmt, ...)
Definition at line 290 of file error.c.
References args, GET_THREAD(), NULL, rb_sourcefile, rb_sourceline(), and report_bug().
Referenced by add_opt_method(), assign_heap_slot(), backtrace_collect(), big2str_find_n1(), big_fdiv(), BigDecimalCmp(), catch_type(), check_env_value(), check_match(), classname(), compile_array_(), cont_free(), econv_convert(), econv_finish(), error_handle(), eval_queue_handler(), exception_type2symbol(), fiber_store(), fiber_switch(), gc_mark_children(), gc_prof_timer_start(), get_dyna_var_idx(), get_local_var_idx(), glob_helper(), insn_operand_intern(), insn_set_specialized_instruction(), ip_rb_threadUpdateCommand(), ip_rbUpdateCommand(), ip_rbVwaitCommand(), iseq_compile_each(), iseq_data_to_ary(), iseq_set_arguments(), iseq_set_sequence(), location_absolute_path(), location_base_label(), location_label(), location_lineno(), location_path(), location_to_str(), m_core_set_postexe(), make_errno_exc(), make_errno_exc_str(), memsize_of(), mutex_free(), newobj(), obj_free(), pack_pack(), pack_unpack(), power_cache_get_power(), rb_add_method(), rb_ary_set_len(), rb_bug_errno(), rb_check_deadlock(), rb_check_type(), rb_dlhandle_initialize(), rb_dlptr_aref(), rb_dlptr_aset(), rb_dlptr_s_malloc(), rb_dlptr_to_s(), rb_dlptr_to_str(), rb_econv_open_opts(), rb_enc_from_encoding_index(), rb_fiber_start(), rb_fiddle_handle_initialize(), rb_fiddle_ptr_aref(), rb_fiddle_ptr_aset(), rb_fiddle_ptr_s_malloc(), rb_fiddle_ptr_to_s(), rb_fiddle_ptr_to_str(), rb_hash_method_definition(), rb_iseq_compile_node(), rb_maygvl_fd_fix_cloexec(), rb_memsearch_ss(), rb_method_definition_eq(), rb_method_entry_min_max_arity(), rb_str_set_len(), rb_struct_eql(), rb_struct_equal(), rb_thread_call_with_gvl(), rb_thread_terminate_all(), rb_threadptr_unlock_all_locking_mutexes(), rb_tracearg_raised_exception(), rb_tracearg_return_value(), rb_trans_conv(), rb_update_max_fd(), rb_vm_get_cref(), rb_vm_make_proc(), rsock_s_recvfrom(), rsock_s_recvfrom_nonblock(), ruby_node_name(), setup_args(), singleton_class_of(), tcl_protect(), thread_free(), thread_start_func_2(), type2sym(), verify_list(), vm_base_ptr(), vm_call0_body(), vm_call0_cfunc_with_frame(), vm_call_cfunc_with_frame(), vm_call_method(), vm_call_super(), vm_exec_core(), vm_get_cvar_base(), vm_getspecial(), vm_make_env_each(), vm_throw(), VpDivd(), vtable_add(), and warn_unused_var().
void rb_bug_errno (const char * mesg, int errno_arg)
Definition at line 313 of file error.c.
References rb_bug(), rb_strerrno(), and strerror().
const char * rb_builtin_class_name (VALUE x)
Definition at line 414 of file error.c.
References FIXNUM_P, NIL_P, rb_obj_classname(), RB_TYPE_P, SYMBOL_P, T_FALSE, and T_TRUE.
Referenced by rb_hash_s_create().
const char * rb_builtin_type_name (int t)
Definition at line 403 of file error.c.
References builtin_types, name, and numberof.
Referenced by rb_check_type().
VALUE rb_check_backtrace (VALUE bt)
Definition at line 710 of file error.c.
References err, i, NIL_P, RARRAY_LEN, RARRAY_PTR, rb_ary_new3(), rb_backtrace_p(), rb_eTypeError, rb_raise(), RB_TYPE_P, T_ARRAY, and T_STRING.
Referenced by exc_set_backtrace(), and get_backtrace().
void rb_check_copyable (VALUE obj, VALUE orig)
Definition at line 2001 of file error.c.
References FL_ABLE, FL_TAINT, FL_UNTRUSTED, PRIsVALUE, rb_check_frozen_internal, rb_check_trusted_internal, rb_eSecurityError, rb_raise(), rb_safe_level, and RBASIC.
Referenced by random_init(), and random_load().
void rb_check_frozen (VALUE obj)
Definition at line 1979 of file error.c.
References rb_check_frozen, and rb_check_frozen_internal.
void rb_check_trusted (VALUE obj)
Definition at line 1995 of file error.c.
References rb_check_trusted, and rb_check_trusted_internal.
void rb_check_type (VALUE x, int t)
Definition at line 440 of file error.c.
References builtin_class_name, Qundef, rb_bug(), rb_builtin_type_name(), rb_eTypeError, rb_fatal(), rb_raise(), RTYPEDDATA_P, T_DATA, T_MASK, and TYPE.
Referenced by tcl2rb_bool(), tcl2rb_num_or_nil(), tcl2rb_num_or_str(), tcl2rb_string(), and tkstr_to_number().
void * rb_check_typeddata (VALUE obj, const rb_data_type_t * data_type)
Definition at line 483 of file error.c.
References builtin_class_name, DATA_PTR, rb_eTypeError, rb_obj_classname(), rb_raise(), RB_TYPE_P, rb_typeddata_inherited_p(), RTYPEDDATA_P, RTYPEDDATA_TYPE, T_DATA, and rb_data_type_struct::wrap_struct_name.
Referenced by BigDecimal_initialize(), BigDecimal_initialize_copy(), check_addrinfo(), check_strscan(), dir_check(), dir_open_dir(), and econv_init().
void rb_compile_bug (const char * file, int line, const char * fmt, ...)
Definition at line 358 of file error.c.
References args, and report_bug().
void rb_compile_error (const char * file, int line, const char * fmt, ...)
Definition at line 138 of file error.c.
References args, compile_err_append(), compile_snprintf(), and NULL.
Referenced by iseq_build_from_ary_body(), iseq_set_sequence(), iseq_set_sequence_stackcaching(), and rb_iseq_compile_node().
void rb_compile_error_append (const char * fmt, ...)
Definition at line 150 of file error.c.
References args, compile_err_append(), and rb_vsprintf().
Referenced by parser_yyerror().
void rb_compile_error_with_enc (const char * file, int line, void * enc, const char * fmt, ...)
Definition at line 126 of file error.c.
References args, compile_err_append(), compile_snprintf(), and NULL.
void rb_compile_warn (const char * file, int line, const char * fmt, ...)
Definition at line 172 of file error.c.
References args, compile_warn_print(), NIL_P, and ruby_verbose.
Referenced by onig_syntax_warn(), parser_warn(), rb_const_set(), rb_obj_respond_to(), and token_info_pop().
void rb_compile_warning (const char * file, int line, const char * fmt, ...)
Definition at line 185 of file error.c.
References args, compile_warn_print(), RTEST, and ruby_verbose.
Referenced by parser_set_token_info(), parser_warning(), rb_method_entry_make(), and when_vals().
void rb_enc_raise (rb_encoding * enc, VALUE exc, const char * fmt, ...)
Definition at line 1767 of file error.c.
References args, rb_enc_vsprintf(), rb_exc_new3(), and rb_exc_raise().
Referenced by rb_str_format().
void rb_error_frozen (const char * what)
Definition at line 1972 of file error.c.
References rb_eRuntimeError, and rb_raise().
Referenced by fdbm_modify(), generic_ivar_set(), rb_frozen_class_p(), rb_gdbm_modify(), rb_thread_local_aset(), and rb_thread_variable_set().
void rb_error_untrusted (VALUE obj)
Definition at line 1985 of file error.c.
References rb_eSecurityError, rb_obj_classname(), rb_raise(), and rb_safe_level.
VALUE rb_exc_new (VALUE etype, const char * ptr, long len)
Definition at line 536 of file error.c.
References rb_funcall(), rb_intern, and rb_str_new().
Referenced by ossl_make_error(), rb_exc_new2(), rb_threadptr_raise(), and setup_exception().
VALUE rb_exc_new2 (VALUE etype, const char * s)
Definition at line 542 of file error.c.
References rb_exc_new(), and strlen().
Referenced by compile_err_append(), create_ip_exc(), fiber_switch(), gzfile_raise(), Init_Thread(), ip_create_slave_core(), ip_eval_real(), ip_get_variable2_core(), ip_invoke_core(), ip_make_safe_core(), ip_rb_threadTkWaitCommand(), ip_rb_threadUpdateCommand(), ip_rb_threadVwaitCommand(), ip_rbTkWaitCommand(), ip_rbUpdateCommand(), ip_rbVwaitCommand(), ip_ruby_cmd(), ip_ruby_eval(), ip_RubyExitCommand(), ip_set_variable2_core(), lib_eventloop_core(), lib_eventloop_main(), lib_restart_core(), make_localjump_error(), next_i(), raise_from_check(), raise_zlib_error(), tcl_protect_core(), and tcltkip_init_tk().
VALUE rb_exc_new3 (VALUE etype, VALUE str)
Definition at line 548 of file error.c.
References rb_funcall(), rb_intern, and StringValue.
Referenced by cannot_be_coerced_into_BigDecimal(), compile_err_append(), finish_writeconv(), Init_eval(), Init_GC(), Init_Proc(), ip_eval(), ip_invoke_with_position(), make_econv_exception(), make_exception(), raise_loaderror(), rand_random(), rb_arg_error_new(), rb_econv_open_exc(), rb_enc_raise(), rb_enc_reg_error_desc(), rb_fatal(), rb_raise(), tcl_protect_core(), and tk_funcall().
VALUE rb_exc_set_backtrace (VALUE exc, VALUE bt)
Definition at line 747 of file error.c.
References exc_set_backtrace().
Referenced by set_backtrace().
void rb_fatal (const char * fmt, ...)
Definition at line 1834 of file error.c.
References args, rb_eFatal, rb_exc_fatal(), rb_exc_new3(), and rb_vsprintf().
Referenced by argf_next_argv(), proc_options(), rb_check_type(), rb_scan_args(), rb_w32_asynchronize(), StartSockets(), and VpException().
void rb_invalid_str (const char * str, const char * type)
Definition at line 1139 of file error.c.
References PRIsVALUE, rb_eArgError, rb_raise(), and rb_str_new2.
Referenced by rb_cstr_to_dbl(), and rb_cstr_to_inum().
void rb_load_fail (VALUE path, const char * err)
Definition at line 1963 of file error.c.
References raise_loaderror(), rb_str_append(), rb_str_buf_new_cstr(), and rb_str_cat2().
Referenced by load_failed(), and load_file_internal().
void rb_loaderror (const char * fmt, ...)
Definition at line 1802 of file error.c.
References args, Qnil, raise_loaderror(), rb_enc_vsprintf(), and rb_locale_encoding().
Referenced by dln_load(), load_file_internal(), and rb_f_require_relative().
void rb_loaderror_with_path (VALUE path, const char * fmt, ...)
Definition at line 1814 of file error.c.
References args, raise_loaderror(), rb_enc_vsprintf(), and rb_locale_encoding().
void rb_mod_sys_fail (VALUE mod, const char * mesg)
Definition at line 1911 of file error.c.
References make_errno_exc(), rb_exc_raise(), and rb_extend_object().
Referenced by io_getpartial(), rb_io_write_nonblock(), rsock_s_accept_nonblock(), rsock_s_recvfrom_nonblock(), and sock_connect_nonblock().
void rb_mod_sys_fail_str (VALUE mod, VALUE mesg)
Definition at line 1919 of file error.c.
References make_errno_exc_str(), rb_exc_raise(), and rb_extend_object().
void rb_mod_syserr_fail (VALUE mod, int e, const char * mesg)
Definition at line 1927 of file error.c.
References rb_exc_raise(), rb_extend_object(), and rb_syserr_new().
void rb_mod_syserr_fail_str (VALUE mod, int e, VALUE mesg)
Definition at line 1935 of file error.c.
References rb_exc_raise(), rb_extend_object(), and rb_syserr_new_str().
VALUE rb_name_err_mesg_new (VALUE obj, VALUE mesg, VALUE recv, VALUE method)
Definition at line 1027 of file error.c.
References ALLOC_N, NAME_ERR_MESG_COUNT, rb_cNameErrorMesg, RB_GC_GUARD, result, and TypedData_Wrap_Struct.
Referenced by Init_Exception(), and make_no_method_exception().
void rb_name_error (ID id, const char * fmt, ...)
Definition at line 899 of file error.c.
References args, argv, ID2SYM, rb_class_new_instance(), rb_eNameError, rb_exc_raise(), and rb_vsprintf().
Referenced by make_struct(), mnew(), range_initialize(), rb_attr(), rb_const_get_0(), rb_const_remove(), rb_cv_get(), rb_cv_set(), rb_cvar_get(), rb_define_class_id_under(), rb_define_class_variable(), rb_f_untrace_var(), rb_mod_const_defined(), rb_mod_const_get(), rb_mod_const_set(), rb_mod_cvar_defined(), rb_mod_cvar_get(), rb_mod_cvar_set(), rb_mod_remove_const(), rb_mod_remove_cvar(), rb_obj_ivar_defined(), rb_obj_ivar_get(), rb_obj_ivar_set(), rb_obj_remove_instance_variable(), rb_print_undef(), rb_struct_aref_id(), rb_struct_aset_id(), rb_struct_getmember(), rb_struct_set(), rb_undef(), readonly_setter(), remove_method(), set_const_visibility(), and uninitialized_constant().
void rb_name_error_str (VALUE str, const char * fmt, ...)
Definition at line 914 of file error.c.
References args, argv, rb_class_new_instance(), rb_eNameError, rb_exc_raise(), and rb_vsprintf().
Referenced by rb_f_untrace_var(), rb_method_name_error(), rb_mod_const_defined(), rb_mod_const_get(), rb_mod_cvar_defined(), rb_mod_cvar_get(), rb_mod_remove_const(), rb_mod_remove_cvar(), rb_mod_remove_method(), rb_obj_ivar_defined(), rb_obj_ivar_get(), rb_obj_remove_instance_variable(), rb_print_undef_str(), and set_const_visibility().
void rb_notimplement (void)
Definition at line 1826 of file error.c.
References rb_eNotImpError, rb_frame_this_func(), rb_id2name(), and rb_raise().
Referenced by flock(), ip_create_console_core(), ip_make_menu_embeddable_core(), p_gid_change_privilege(), p_gid_exchange(), p_uid_change_privilege(), p_uid_exchange(), pipe_open(), proc_exec_cmd(), proc_exec_sh(), rb_f_notimplement(), rb_io_set_sync(), rb_remove_history(), rb_setegid_core(), rb_seteuid_core(), and strio_unimpl().
void rb_raise (VALUE exc, const char * fmt, ...)
Definition at line 1780 of file error.c.
References args, rb_exc_new3(), rb_exc_raise(), and rb_vsprintf().
Referenced by addrinfo_initialize(), addrinfo_ip_address(), addrinfo_ip_port(), addrinfo_ip_unpack(), addrinfo_mdump(), addrinfo_mload(), advice_arg_check(), argf_fileno(), argf_rewind(), argf_seek_m(), argf_set_encoding(), argf_set_pos(), argf_tell(), argf_write_io(), ary2safe_array_index(), ary_join_1(), ary_new(), ary_new_dim(), ary_take_first_or_last(), big2str_find_n1(), big2ulong(), BigDecimal_DoDivmod(), BigDecimal_limit(), BigDecimal_load(), BigDecimal_mode(), BigDecimal_new(), BigDecimal_power(), BigDecimal_to_i(), BigMath_s_exp(), BigMath_s_log(), bit_coerce(), bsock_close_read(), bsock_close_write(), bsock_shutdown(), bubblebabble_str_new(), call_getaddrinfo(), callback(), cbsubst_def_attr_aliases(), cbsubst_get_subst_arg(), cbsubst_table_setup(), check_autoload_required(), check_before_mod_set(), check_dump_arg(), check_econv(), check_exec_env_i(), check_exec_fds(), check_exec_fds_1(), check_exec_options_i(), check_exec_redirect(), check_exec_redirect_fd(), check_funcall_respond_to(), check_gid_switch(), check_load_arg(), check_match(), check_modifiable(), check_path_encoding(), check_rounding_mode(), check_uid_switch(), check_ushort(), chunk_ii(), class2path(), class_init_copy_check(), class_or_module_required(), closed_dbm(), closed_sdbm(), coerce_rescue(), constant_arg(), convert_encoding(), convert_type(), convert_UTF8_to_JSON_ASCII(), copy_stream_body(), copy_stream_fallback(), copy_stream_finalize(), count_nodes(), count_objects(), count_objects_size(), count_tdata_objects(), cParser_initialize(), cParser_parse_quirks_mode(), cParser_parse_strict(), create_dummy_encoding_for_tk_core(), create_encoding_table_core(), cState_configure(), cState_generate(), cState_init_copy(), curses_char(), curses_init_screen(), d_lite_initialize_copy(), d_lite_marshal_load(), d_lite_minus(), d_lite_plus(), d_lite_rshift(), d_lite_step(), d_new_by_frags(), date_s__parse_internal(), date_s__strptime_internal(), date_s_civil(), date_s_commercial(), date_s_ordinal(), date_strftime_internal(), datetime_s_civil(), datetime_s_commercial(), datetime_s_jd(), datetime_s_ordinal(), dbl2big(), default_proc_arity_check(), define_final(), define_final0(), dir_check(), dir_closed(), dir_rewind(), dir_s_chdir(), divmodv(), dlhandle_sym(), do_coerce(), do_writeconv(), dt_new_by_frags(), dump_disasm_list(), each_attr_def(), econv_convert(), econv_get_replacement(), econv_init(), econv_insert_output(), econv_opts(), econv_primitive_convert(), econv_set_replacement(), emit(), enc_check_duplication(), encoding_table_get_name_core(), enum_chunk(), enum_drop(), enum_each_cons(), enum_each_cons_size(), enum_each_slice(), enum_each_slice_size(), enum_sort_by(), enum_take(), enum_zip(), enumerator_feed(), enumerator_init(), enumerator_init_copy(), enumerator_ptr(), env_aset(), env_assoc(), env_delete(), env_fetch(), env_has_key(), errat_setter(), esignal_init(), etc_getgrgid(), etc_getgrnam(), etc_getpwnam(), etc_getpwuid(), ev_advise(), ev_on_event(), eval_string_with_cref(), extract_binmode(), extract_user_token(), f_round_common(), failed_load_conv51932(), fdbm_clear(), fdbm_delete(), fdbm_delete_if(), fdbm_fetch_m(), fdbm_store(), fev_off_event(), fgdbm_clear(), fgdbm_fetch_m(), fgdbm_initialize(), fgdbm_set_cachesize(), fgdbm_set_fastmode(), fgdbm_set_syncmode(), fgdbm_store(), fiber_switch(), fiber_t_alloc(), fiddle_handle_sym(), file_inspect_join(), flatten(), fole_initialize(), fole_method_help(), fole_missing(), fole_query_interface(), fole_respond_to(), fole_s_connect(), fole_s_const_load(), fole_s_create_guid(), fole_s_set_locale(), fole_s_show_help(), fole_type(), fole_typelib(), folemethod_initialize(), foleparam_initialize(), foletype_initialize(), foletypelib_initialize(), folevariant_ary_aref(), folevariant_ary_aset(), folevariant_initialize(), folevariant_s_array(), folevariant_set_value(), forbid_setid(), frame_get(), fsdbm_clear(), fsdbm_delete(), fsdbm_delete_if(), fsdbm_fetch_m(), fsdbm_store(), function_call(), gc_stat(), generate_json_array(), generate_json_float(), generate_json_object(), generator_init(), generator_init_copy(), generator_initialize(), generator_ptr(), generic_to_value(), get_addrinfo(), get_device_once(), get_digest_base_metadata(), get_exception_sym2type(), get_gzfile(), get_hash(), get_locked_safe_array(), get_new_timeval(), get_stat(), get_strio(), get_strpath(), get_timeval(), get_trace_arg(), get_zstream(), GetPositiveInt(), GetVpValueWithPrec(), gzfile_check_footer(), gzfile_fill(), gzfile_read_header(), gzfile_read_more(), gzfile_read_raw_until_zero(), gzfile_readpartial(), gzfile_s_open(), handle_interrupt_arg_check_i(), hash2named_arg(), hash_foreach_call(), hash_foreach_iter(), hexencode_str_new(), hist_delete_at(), hist_get(), host_str(), id2ref(), init_addrinfo(), init_copy(), Init_tcltklib(), initialize(), initialize_params(), insn_data_to_s_detail(), int_chr(), int_to_ffi_type(), intern_str(), io_getc(), io_getpartial(), io_needed(), io_read(), io_reopen(), io_ungetbyte(), ip_allow_ruby_exit_p(), ip_allow_ruby_exit_set(), ip_cancel_eval_core(), ip_create_console(), ip_create_console_core(), ip_create_slave(), ip_init(), ip_invoke_with_position(), ip_is_safe_p(), ip_is_slave_of_p(), ip_make_menu_embeddable_core(), ip_make_safe(), ip_restart(), ip_ruby_cmd(), ip_ruby_eval(), is_popen_fork(), iseq_build_from_ary_body(), iseq_build_from_ary_exception(), iseq_build_load_iseq(), iseq_check(), iseq_load(), JSON_parse_array(), JSON_parse_object(), JSON_parse_value(), lazy_drop(), lazy_drop_while(), lazy_flat_map(), lazy_initialize(), lazy_map(), lazy_reject(), lazy_select(), lazy_take(), lazy_take_while(), lazy_zip(), lexer_i(), lib_do_one_event_core(), lib_fromUTF8_core(), lib_get_reltype_name(), lib_mainloop_watchdog(), lib_restart(), lib_set_system_encoding(), lib_split_tklist_core(), lib_toUTF8_core(), long_toobig(), make_addrinfo(), make_compile_option(), make_exception(), marshal_load(), match_backref_number(), match_begin(), match_check(), match_end(), match_offset(), mSyslog_close(), mSyslog_log(), mSyslog_open(), mSyslog_set_mask(), must_be_ascii_compatible(), must_encoding(), must_not_be_anonymous(), must_respond_to(), name_to_backref_number(), negative_size_allocation_error(), negative_size_allocation_error_with_gvl(), new_size(), no_new_key(), no_window(), nucomp_coerce(), nucomp_marshal_load(), nucomp_rationalize(), nucomp_real_check(), nucomp_s_convert(), nucomp_to_f(), nucomp_to_i(), nucomp_to_r(), num_exact(), num_init_copy(), num_members(), num_sadded(), num_step(), nurat_coerce(), nurat_int_check(), nurat_marshal_load(), nurat_s_convert(), offset_to_sec(), old_to_new(), ole_cp2encoding(), ole_create_dcom(), ole_invoke(), ole_invoke2(), ole_raise(), ole_set_byref(), ole_set_safe_array(), ole_val2olevariantdata(), ole_val_ary2variant_ary(), ole_variant2val(), ole_vstr2wc(), oleparam_ole_param_from_index(), onigenc_single_byte_code_to_mbc(), open_key_args(), opt_enc_index(), pack_pack(), pack_unpack(), parse_keyword_arg_i(), parse_main(), path2class(), path2module(), path_initialize(), permute0(), port_str(), prep_window(), prepare_getline_args(), proc_binding(), proc_new(), proc_options(), r_object0(), r_symbol(), r_symlink(), racc_yyparse(), raise_method_missing(), rand_init(), random_load(), range_bsearch(), range_each(), range_failed(), range_loader(), range_max(), range_step(), range_step_size(), rb_add_method_cfunc(), rb_alias(), rb_alias_variable(), rb_ary_bsearch(), rb_ary_combination(), rb_ary_drop(), rb_ary_fetch(), rb_ary_fill(), rb_ary_initialize(), rb_ary_modify_check(), rb_ary_product(), rb_ary_resize(), rb_ary_sample(), rb_ary_set_len(), rb_ary_shuffle_bang(), rb_ary_splice(), rb_ary_store(), rb_ary_take(), rb_ary_times(), rb_ary_transpose(), rb_attr(), rb_autoload(), rb_big2long(), rb_big2str0(), rb_big2ulong(), rb_big_coerce(), rb_binding_new_with_cfp(), rb_check_argv(), rb_check_backtrace(), rb_check_convert_type(), rb_check_copyable(), rb_check_id(), rb_check_inheritable(), rb_check_safe_str(), rb_check_type(), rb_check_typeddata(), rb_class_inherited_p(), rb_class_initialize(), rb_class_superclass(), rb_cmperr(), rb_const_remove(), rb_const_set(), rb_cont_call(), rb_convert_to_integer(), rb_convert_type(), rb_coverage_result(), rb_cstr_to_dbl(), rb_cstr_to_inum(), rb_cstr_to_rat(), rb_declare_transcoder(), rb_define_class(), rb_define_class_id_under(), rb_define_final(), rb_define_module(), rb_define_module_id_under(), rb_digest_base_alloc(), rb_digest_class_s_digest(), rb_digest_instance_method_unimpl(), rb_dlcfunc2ptr(), rb_dlcfunc_call(), rb_dlhandle_close(), rb_dlhandle_initialize(), rb_dlhandle_sym(), rb_dlptr2cptr(), rb_dlptr_aref(), rb_dlptr_aset(), rb_dlptr_s_to_ptr(), rb_econv_init_by_convpath(), rb_econv_prepare_options(), rb_econv_substr_append(), rb_enc_associate_index(), rb_enc_check(), rb_enc_codelen(), rb_enc_codepoint_len(), rb_enc_cr_str_buf_cat(), rb_enc_find_index(), rb_enc_register(), rb_enc_set_default_external(), rb_enc_uint_chr(), rb_enc_vsprintf(), rb_eof_error(), rb_error_frozen(), rb_error_untrusted(), rb_execarg_addopt(), rb_f_at_exit(), rb_f_autoload(), rb_f_eval(), rb_f_getenv(), rb_f_kill(), rb_f_test(), rb_f_trace_var(), rb_fiber_resume(), rb_fiddle_handle_close(), rb_fiddle_handle_initialize(), rb_fiddle_handle_sym(), rb_fiddle_ptr2cptr(), rb_fiddle_ptr_aref(), rb_fiddle_ptr_aset(), rb_fiddle_ptr_s_to_ptr(), rb_file_expand_path_internal(), rb_file_initialize(), rb_file_join(), rb_find_file_ext_safe(), rb_find_file_safe(), rb_fix2str(), rb_Float(), rb_gdbm_delete(), rb_gdbm_fatal(), rb_gvar_set(), rb_gzfile_set_comment(), rb_gzfile_set_mtime(), rb_gzfile_set_orig_name(), rb_gzreader_read(), rb_gzreader_readbyte(), rb_gzreader_readchar(), rb_gzreader_readline(), rb_gzreader_readpartial(), rb_Hash(), rb_hash_fetch_m(), rb_hash_modify_check(), rb_hash_rehash(), rb_hash_s_create(), rb_hash_set_default_proc(), rb_home_dir(), rb_include_module(), rb_insecure_operation(), rb_inspect(), rb_interrupt(), rb_invalid_str(), rb_io_check_byte_readable(), rb_io_check_char_readable(), rb_io_check_closed(), rb_io_check_initialized(), rb_io_check_writable(), rb_io_close_m(), rb_io_close_read(), rb_io_close_write(), rb_io_each_codepoint(), rb_io_each_line(), rb_io_extract_modeenc(), rb_io_fmode_modestr(), rb_io_initialize(), rb_io_modestr_fmode(), rb_io_oflags_modestr(), rb_io_readlines(), rb_io_reopen(), rb_io_s_popen(), rb_io_sysread(), rb_io_sysseek(), rb_io_taint_check(), rb_io_ungetc(), rb_io_wait_readable(), rb_io_wait_writable(), rb_ioctl(), rb_iseq_line_trace_specify(), rb_ivar_set(), rb_marshal_define_compat(), rb_method_call_status(), rb_method_call_with_block(), rb_method_entry_make(), rb_mod_const_get(), rb_mod_define_method(), rb_mod_ge(), rb_mod_modfunc(), rb_mod_refine(), rb_mod_remove_cvar(), rb_must_asciicompat(), rb_mutex_lock(), rb_mutex_synchronize_m(), rb_mutex_unlock(), rb_nkf_convert(), rb_notimplement(), rb_num2dbl(), rb_num2fix(), rb_num2long(), rb_num2ulong(), rb_num_zerodiv(), rb_obj_alloc(), rb_obj_clone(), rb_obj_dup(), rb_obj_encoding(), rb_obj_freeze(), rb_obj_init_copy(), rb_obj_remove_instance_variable(), rb_out_of_short(), rb_path_to_class(), rb_prepend_module(), rb_provide_feature(), rb_random_real(), rb_random_ulong_limited(), rb_range_beg_len(), rb_reg_check(), rb_reg_initialize(), rb_reg_prepare_enc(), rb_reg_prepare_re(), rb_reg_preprocess_dregexp(), rb_reg_raise(), rb_reg_regsub(), rb_reg_s_union(), rb_register_transcoder(), rb_search_method_entry(), rb_secure(), rb_set_errinfo(), rb_str_aset(), rb_str_buf_cat(), rb_str_cat(), rb_str_check_dummy_enc(), rb_str_concat(), rb_str_crypt(), rb_str_ellipsize(), rb_str_format(), rb_str_index_m(), rb_str_justify(), rb_str_match(), rb_str_modify_expand(), rb_str_new_cstr(), rb_str_partition(), rb_str_resize(), rb_str_rindex_m(), rb_str_rpartition(), rb_str_set_len(), rb_str_setbyte(), rb_str_setter(), rb_str_splice(), rb_str_split_m(), rb_str_sub_bang(), rb_str_subpat_set(), rb_str_times(), rb_str_to_dbl(), rb_str_to_i(), rb_str_unlocktmp(), rb_string_value_cstr(), rb_struct_aref(), rb_struct_aset(), rb_struct_aset_id(), rb_struct_init_copy(), rb_struct_initialize_m(), rb_struct_members(), rb_struct_s_members(), rb_thread_local_aref(), rb_thread_local_aset(), rb_thread_pending_interrupt_p(), rb_thread_s_handle_interrupt(), rb_thread_shield_waiting_dec(), rb_thread_shield_waiting_inc(), rb_thread_stop(), rb_thread_variable_get(), rb_thread_variable_set(), rb_thread_wait_fd_rw(), rb_thread_wakeup(), rb_threadptr_pending_interrupt_check_mask(), rb_throw_obj(), rb_time_new(), rb_to_float(), rb_to_id(), rb_to_integer(), rb_tracearg_raised_exception(), rb_tracearg_return_value(), rb_undef(), rb_uv_to_utf8(), rb_vm_cbase(), rb_waitpid(), rb_yield_splat(), rcombinate0(), readable(), readline_readline(), readline_s_set_completion_proc(), recursive_join(), recursive_pop(), reduce0(), reg_enc_error(), remain_size(), remove_method(), return_fiber(), ripper_token2eventid(), rpermute0(), rscheck(), rsock_getaddrinfo(), rsock_init_sock(), rsock_io_socket_addrinfo(), rsock_raise_socket_error(), rsock_revlookup_flag(), rsock_s_recvfrom(), rsock_s_recvfrom_nonblock(), ruby__sfvextra(), ruby__sfvwrite(), RUBY_ALIAS_FUNCTION(), ruby_xrealloc2(), safe_setter(), secure_visibility(), security(), send_internal(), set_arg0(), set_const_visibility(), set_eventloop_tick(), set_eventloop_weight(), set_max_block_time(), set_no_event_wait(), set_ole_codepage(), set_option_encoding_once(), set_trace_func(), sig_trap(), singleton_class_of(), sock_s_gethostbyaddr(), sock_s_getnameinfo(), sock_s_getservbyname(), sock_s_getservbyport(), sock_s_unpack_sockaddr_in(), sock_sockaddr(), sockopt_bool(), sockopt_int(), sockopt_linger(), sort_by_cmp(), sort_by_i(), sort_reentered(), st_foreach_safe(), start_document(), str_buf_cat(), str_find_encindex(), str_gsub(), str_mod_check(), str_modifiable(), str_new(), str_to_encindex(), str_transcode0(), string_to_c_strict(), string_to_r(), string_to_r_strict(), strio_close(), strio_close_read(), strio_close_write(), strio_each(), strio_read(), strio_readlines(), strio_seek(), strio_size(), strscan_do_scan(), strscan_set_pos(), strscan_unscan(), sym_call(), sym_check_asciionly(), symbol2event_flag(), syserr_initialize(), syslog_write(), take_items(), tcl_stubs_check(), thgroup_add(), thread_add_trace_func(), thread_create_core(), thread_initialize(), thread_join(), thread_s_new(), time_fixoff(), time_gmtime(), time_localtime(), time_mdump(), time_mload(), time_overflow_p(), time_plus(), time_round(), time_strftime(), time_timespec(), timegmw(), timelocalw(), timew2timespec(), tk_conv_args(), tk_hash_kv(), tkstr_invalid_numstr(), too_short(), top_using(), tracepoint_new_s(), transcode_loop(), transcode_restartable0(), trap_handler(), trap_signm(), trnext(), umethod_bind(), unknown_keyword_error(), update_i(), uscore_get(), utc_offset_arg(), utf8_to_uv(), val2variant_ptr(), validate_enc_binmode(), validate_utc_offset(), validate_vtm(), value_to_generic(), value_to_id(), vm_backtrace_to_ary(), vm_call_method(), vm_call_opt_send(), vm_caller_setup_args(), vm_check_if_namespace(), vm_define_method(), vm_get_cvar_base(), vm_search_super_method(), vm_set_top_stack(), vm_setivar(), vm_super_outside(), VpException(), w_extended(), w_long(), w_object(), w_symbol(), wdivmod(), writable(), wv2timet(), xmalloc2_size(), yielder_init(), and yielder_ptr().
static const char* rb_strerrno (int err) static
Definition at line 52 of file error.c.
References NULL.
Referenced by rb_async_bug_errno(), and rb_bug_errno().
void rb_sys_fail (const char * mesg)
Definition at line 1899 of file error.c.
References make_errno_exc(), and rb_exc_raise().
Referenced by bsock_getpeername(), bsock_getsockname(), bsock_local_address(), bsock_remote_address(), bsock_shutdown(), console_echo_p(), console_iflush(), console_ioflush(), console_oflush(), console_set_cooked(), console_set_echo(), console_set_raw(), copy_stream_body(), copy_stream_finalize(), date_s_today(), date_strftime_alloc(), datetime_s_now(), dir_read(), establishShell(), fdbm_store(), fgdbm_store(), flush_before_seek(), fsdbm_store(), init_inetsock_internal(), initialize(), io_reopen(), io_wait_readable(), io_wait_writable(), ip_addr(), ip_peeraddr(), make_fd_nonblock(), ossl_obj2bio(), ossl_ssl_read_internal(), ossl_ssl_write_internal(), ossl_start_ssl(), p_gid_change_privilege(), p_gid_exchange(), p_gid_switch(), p_uid_change_privilege(), p_uid_exchange(), p_uid_switch(), pipe_open(), proc_wait(), proc_waitall(), pty_getpty(), raise_zlib_error(), rb_f_exec(), rb_f_kill(), rb_f_spawn(), rb_f_system(), rb_fdopen(), rb_io_check_char_readable(), rb_io_flush(), rb_io_initialize(), rb_io_reopen(), rb_io_s_pipe(), rb_io_write_nonblock(), rb_setegid_core(), rb_seteuid_core(), rb_str_crypt(), rb_strftime_alloc(), rb_thread_wait_fd_rw(), remain_size(), rsock_bsock_send(), rsock_fd_socket_addrinfo(), rsock_init_sock(), rsock_raise_socket_error(), rsock_s_accept(), rsock_s_accept_nonblock(), rsock_s_recvfrom(), rsock_s_recvfrom_nonblock(), rsock_sock_listen(), ruby_dup(), ruby_getcwd(), ruby_setenv(), select_internal(), sock_bind(), sock_connect(), sock_connect_nonblock(), sock_initialize(), strio_init(), time_init_0(), ttymode(), udp_bind(), udp_connect(), udp_init(), and udp_send().
void rb_sys_fail_str (VALUE mesg)
Definition at line 1905 of file error.c.
References make_errno_exc_str(), and rb_exc_raise().
Referenced by fdbm_initialize(), fgdbm_initialize(), fsdbm_initialize(), pipe_open(), rb_f_exec(), rb_f_spawn(), and rb_strftime_alloc().
void rb_sys_warning (const char * fmt, ...)
Definition at line 1943 of file error.c.
References args, buf, errno, RTEST, ruby_verbose, snprintf, strerror(), strlen(), and warn_print().
Referenced by sys_warning_1().
void rb_syserr_fail (int e, const char * mesg)
Definition at line 1887 of file error.c.
References rb_exc_raise(), and rb_syserr_new().
void rb_syserr_fail_str (int e, VALUE mesg)
Definition at line 1893 of file error.c.
References rb_exc_raise(), and rb_syserr_new_str().
VALUE rb_syserr_new (int n, const char * mesg)
Definition at line 1873 of file error.c.
References arg, Qnil, rb_str_new2, and rb_syserr_new_str().
Referenced by make_errno_exc(), rb_mod_syserr_fail(), and rb_syserr_fail().
VALUE rb_syserr_new_str (int n, VALUE arg)
Definition at line 1881 of file error.c.
References get_syserr(), and rb_class_new_instance().
Referenced by make_errno_exc_str(), rb_mod_syserr_fail_str(), rb_syserr_fail_str(), and rb_syserr_new().
int rb_typeddata_inherited_p (const rb_data_type_t * child, const rb_data_type_t * parent)
Definition at line 463 of file error.c.
References rb_data_type_struct::parent.
Referenced by rb_check_typeddata(), and rb_typeddata_is_kind_of().
int rb_typeddata_is_kind_of (VALUE obj, const rb_data_type_t * data_type)
Definition at line 473 of file error.c.
References RB_TYPE_P, rb_typeddata_inherited_p(), RTYPEDDATA_P, RTYPEDDATA_TYPE, and T_DATA.
Referenced by econv_equal(), enc_check_encoding(), is_kind_of_BigDecimal(), rb_backtrace_p(), rb_dlcfunc2ptr(), rb_dlcfunc_kind_p(), rb_obj_is_fiber(), rb_obj_is_method(), rb_obj_is_mutex(), rb_obj_is_proc(), rb_obj_is_thread(), reachable_objects_from(), and try_get_rnd().
void rb_warn (const char * fmt, ...)
Definition at line 216 of file error.c.
References args, NIL_P, ruby_verbose, and warn_print().
Referenced by _nativethread_consistency_check(), argf_bytes(), argf_chars(), argf_codepoints(), argf_lines(), argf_next_argv(), curry(), dir_s_chdir(), disable_option(), dump_option(), enable_option(), enum_count(), enum_find_index(), enumerator_initialize(), env_fetch(), env_index(), fdbm_index(), fgdbm_index(), fsdbm_index(), generator_initialize(), ignorecase_getter(), ignorecase_setter(), ip_eval_real(), ip_invoke_core(), kcode_getter(), kcode_setter(), make_struct(), marshal_load(), nucomp_expt(), nurat_expt(), onig_syntax_warn(), ossl_cipher_init(), ossl_make_error(), ossl_verify_cb(), path_check_0(), proc_new(), rb_ary_count(), rb_ary_fetch(), rb_ary_index(), rb_ary_initialize(), rb_ary_rindex(), rb_big_pow(), rb_const_get_0(), rb_const_set(), rb_define_class(), rb_define_class_id_under(), rb_define_const(), rb_enc_find_index(), rb_execarg_run_options(), rb_f_lambda(), rb_fdopen(), rb_gzreader_bytes(), rb_gzreader_lines(), rb_hash_fetch_m(), rb_hash_index(), rb_hash_s_create(), rb_io_bytes(), rb_io_chars(), rb_io_codepoints(), rb_io_extract_encoding_option(), rb_io_lines(), rb_io_reopen(), rb_io_s_new(), rb_io_sysseek(), rb_io_syswrite(), rb_method_entry_make(), rb_obj_respond_to(), rb_reg_initialize_m(), rb_reg_prepare_enc(), rb_str_enumerate_bytes(), rb_str_enumerate_chars(), rb_str_enumerate_codepoints(), rb_str_enumerate_lines(), rb_str_format(), rb_time_succ(), rb_undef(), re_warn(), remove_method(), strio_bytes(), strio_chars(), strio_codepoints(), strio_lines(), unsupported_encoding(), vm_get_cvar_base(), VpCtoV(), and warn_refinements_once().
static VALUE rb_warn_m (int argc, VALUE * argv, VALUE exc) static
Definition at line 257 of file error.c.
References NIL_P, Qnil, rb_io_puts(), rb_stderr, and ruby_verbose.
Referenced by Init_Exception().
void rb_warning (const char * fmt, ...)
Definition at line 229 of file error.c.
References args, RTEST, ruby_verbose, and warn_print().
Referenced by _nativethread_consistency_check(), asn1time_to_time(), d_new_by_frags(), datetime_s_now(), dt_new_by_frags(), enum_inject(), generic_ivar_get(), get_eval_string_core(), ip_eval_real(), ip_invoke_core(), ivar_get(), lib_fromUTF8_core(), lib_toUTF8_core(), load_lock(), offset_to_sec(), old_to_new(), ossl_default_tmp_dh_callback(), ossl_pem_passwd_cb(), ossl_ssl_read_internal(), ossl_ssl_write_internal(), ossl_sslctx_get_ciphers(), ossl_sslctx_setup(), pack_pack(), pack_unpack(), process_options(), rb_ary_initialize(), rb_attr(), rb_big2dbl(), rb_cstr_to_dbl(), rb_cvar_get(), rb_cvar_set(), rb_deflate_params(), rb_enable_super(), rb_glob2(), rb_method_entry_make(), rb_mod_attr(), rb_str_enumerate_bytes(), rb_str_enumerate_chars(), rb_str_enumerate_codepoints(), rb_str_enumerate_lines(), rb_str_format(), safe_setter(), set_const_visibility(), set_default_external(), set_default_internal(), set_method_visibility(), strscan_clear(), strscan_empty_p(), strscan_getbyte(), strscan_peep(), strscan_restsize(), time_strftime(), top_define_method(), top_include(), undef_getter(), vm_getivar(), and zstream_end().
static void report_bug (const char * file, int line, const char * fmt, va_list args) static
Definition at line 266 of file error.c.
References buf, err_position_0(), rb_vm_bugreport(), REPORTBUG_MSG, ruby_description, snprintf, and vsnprintf.
Referenced by rb_bug(), and rb_compile_bug().
static VALUE set_syserr (int n, const char * name) static
Definition at line 1180 of file error.c.
References INT2NUM, rb_define_class_under(), rb_define_const(), rb_eSystemCallError, rb_mErrno, st_add_direct(), and st_lookup().
Referenced by get_syserr(), and Init_syserr().
static VALUE syserr_eqq (VALUE self, VALUE exc) static
Definition at line 1294 of file error.c.
References CONST_ID, FIXNUM_P, NIL_P, Qfalse, Qtrue, rb_attr_get(), rb_const_get(), rb_equal(), rb_eSystemCallError, rb_funcall(), rb_intern, rb_obj_is_kind_of(), and rb_respond_to().
Referenced by Init_Exception().
static VALUE syserr_errno (VALUE self) static
Definition at line 1280 of file error.c.
References rb_attr_get(), and rb_intern.
Referenced by Init_Exception().
static VALUE syserr_initialize (int argc, VALUE * argv, VALUE self) static
Definition at line 1221 of file error.c.
References err, FIXNUM_P, le, NIL_P, NUM2INT, NUM2LONG, OBJ_INFECT, PRIsVALUE, Qnil, rb_call_super(), rb_const_get(), rb_enc_asciicompat, rb_enc_associate(), rb_enc_get(), rb_eSystemCallError, rb_eTypeError, rb_intern, rb_iv_set(), rb_locale_encoding(), rb_obj_class(), rb_raise(), rb_scan_args(), rb_sprintf(), rb_str_new2, RB_TYPE_P, RBASIC, st_lookup(), strerror(), StringValue, and T_OBJECT.
Referenced by Init_Exception().
static VALUE try_convert_to_exception (VALUE obj) static
Definition at line 753 of file error.c.
References CONST_ID, and rb_check_funcall().
Referenced by exc_equal().
static void warn_print (const char * fmt, va_list args) static
Definition at line 197 of file error.c.
References NIL_P, rb_sourcefilename(), rb_sourceline(), rb_str_append(), rb_str_cat2(), rb_str_catf(), rb_str_new(), rb_str_vcatf(), and rb_write_error_str().
Referenced by rb_sys_warning(), rb_warn(), and rb_warning().
Variable Documentation
const char builtin_types[][10] static
Definition at line 369 of file error.c.
Referenced by rb_builtin_type_name().
const rb_data_type_t name_err_mesg_data_type static
Initial value:
= {
    "name_err_mesg",
    {
        name_err_mesg_mark,
        name_err_mesg_free,
        name_err_mesg_memsize,
    },
}
Definition at line 1016 of file error.c.
RUBY_EXTERN VALUE rb_cNameErrorMesg
Definition at line 523 of file error.c.
Referenced by Init_Exception(), name_err_mesg_equal(), and rb_name_err_mesg_new().
RUBY_EXTERN VALUE rb_eArgError
Definition at line 512 of file error.c.
Referenced by argf_fileno(), argf_rewind(), argf_seek_m(), argf_set_encoding(), argf_set_pos(), argf_tell(), ary2safe_array_index(), ary_join_1(), ary_new(), ary_take_first_or_last(), BigDecimal_limit(), BigDecimal_mode(), BigDecimal_new(), BigMath_s_exp(), BigMath_s_log(), bsock_shutdown(), cbsubst_def_attr_aliases(), cbsubst_get_subst_arg(), cbsubst_table_setup(), check_autoload_required(), check_exec_env_i(), check_exec_fds(), check_exec_fds_1(), check_exec_options_i(), check_exec_redirect(), check_exec_redirect_fd(), check_funcall_respond_to(), check_rounding_mode(), copy_stream_fallback(), cParser_initialize(), create_dummy_encoding_for_tk_core(), cState_configure(), cState_init_copy(), curses_char(), d_lite_initialize_copy(), d_lite_marshal_load(), d_lite_rshift(), d_lite_step(), d_new_by_frags(), date_s__parse_internal(), date_s__strptime_internal(), date_s_civil(), date_s_commercial(), date_s_ordinal(), date_strftime_internal(), datetime_s_civil(), datetime_s_commercial(), datetime_s_jd(), datetime_s_ordinal(), define_final(), define_final0(), dir_s_chdir(), do_writeconv(), dt_new_by_frags(), DupPrivPKeyPtr(), each_attr_def(), econv_convert(), econv_insert_output(), econv_opts(), econv_primitive_convert(), enc_check_duplication(), encoding_table_get_name_core(), enum_chunk(), enum_drop(), enum_each_cons(), enum_each_cons_size(), enum_each_slice(), enum_each_slice_size(), enum_take(), enumerator_init(), enumerator_init_copy(), enumerator_ptr(), env_aset(), env_assoc(), env_delete(), env_fetch(), env_has_key(), errat_setter(), esignal_init(), etc_getgrgid(), etc_getgrnam(), etc_getpwnam(), etc_getpwuid(), extract_binmode(), extract_user_token(), file_inspect_join(), flatten(), foletypelib_initialize(), folevariant_initialize(), frame_get(), function_call(), generator_init(), generator_init_copy(), generator_ptr(), get_hash(), GetPositiveInt(), GetPrivPKeyPtr(), GetVpValueWithPrec(), gzfile_fill(), gzfile_readpartial(), gzfile_s_open(), handle_interrupt_arg_check_i(), host_str(), init_addrinfo(), Init_Exception(), io_getpartial(), io_read(), io_reopen(), ip_invoke_with_position(), ip_is_slave_of_p(), ip_make_menu_embeddable_core(), ip_ruby_cmd(), ip_ruby_eval(), lazy_drop(), lazy_drop_while(), lazy_flat_map(), lazy_initialize(), lazy_map(), lazy_reject(), lazy_select(), lazy_take(), lazy_take_while(), lexer_i(), lib_fromUTF8_core(), lib_set_system_encoding(), lib_toUTF8_core(), mSyslog_log(), must_be_ascii_compatible(), nucomp_marshal_load(), num_step(), nurat_marshal_load(), old_to_new(), open_key_args(), ossl_bn_initialize(), ossl_bn_to_s(), ossl_cipher_update(), ossl_pkcs12_s_create(), ossl_pkcs7_initialize(), ossl_pkey_new_from_data(), ossl_pkey_sign(), ossl_ssl_session_initialize(), ossl_sslctx_flush_sessions(), ossl_sslctx_set_ssl_version(), pack_pack(), pack_unpack(), parse_keyword_arg_i(), parse_main(), parser_set_encode(), path2class(), path2module(), path_initialize(), port_str(), prepare_getline_args(), proc_binding(), proc_new(), r_object0(), r_symbol(), r_symlink(), racc_yyparse(), raise_method_missing(), rand_random(), random_load(), range_failed(), range_step(), range_step_size(), rb_add_method_cfunc(), rb_arg_error_new(), rb_ary_drop(), rb_ary_fill(), rb_ary_initialize(), rb_ary_sample(), rb_ary_take(), rb_ary_times(), rb_attr(), rb_autoload(), rb_big2str0(), rb_check_argv(), rb_cmperr(), rb_convert_to_integer(), rb_cstr_to_dbl(), rb_cstr_to_inum(), rb_declare_transcoder(), rb_define_final(), rb_digest_class_s_digest(), rb_econv_init_by_convpath(), rb_econv_prepare_options(), rb_econv_substr_append(), rb_enc_associate_index(), rb_enc_codelen(), rb_enc_codepoint_len(), rb_enc_cr_str_buf_cat(), rb_enc_find_index(), rb_enc_register(), rb_enc_set_default_external(), rb_enc_vsprintf(), rb_execarg_addopt(), rb_f_at_exit(), rb_f_getenv(), rb_f_kill(), rb_f_test(), rb_file_expand_path_internal(), rb_file_join(), rb_fix2str(), rb_gzreader_read(), rb_gzreader_readpartial(), rb_hash_s_create(), rb_home_dir(), rb_include_module(), rb_invalid_str(), rb_io_each_codepoint(), rb_io_each_line(), rb_io_extract_modeenc(), rb_io_fmode_modestr(), rb_io_initialize(), rb_io_modestr_fmode(), rb_io_oflags_modestr(), rb_io_readlines(), rb_io_reopen(), rb_io_s_popen(), rb_ioctl(), rb_mod_const_get(), rb_mod_refine(), rb_nkf_convert(), rb_path_to_class(), rb_prepend_module(), rb_reg_prepare_enc(), rb_reg_prepare_re(), rb_reg_preprocess_dregexp(), rb_reg_s_union(), rb_register_transcoder(), rb_str_buf_cat(), rb_str_cat(), rb_str_crypt(), rb_str_format(), rb_str_justify(), rb_str_modify_expand(), rb_str_new_cstr(), rb_str_resize(), rb_str_split_m(), rb_str_times(), rb_str_to_dbl(), rb_str_to_i(), rb_string_value_cstr(), rb_struct_initialize_m(), rb_thread_s_handle_interrupt(), rb_throw_obj(), rb_waitpid(), rb_yield_splat(), readline_s_set_completion_proc(), recursive_join(), rsock_init_sock(), rsock_revlookup_flag(), ruby_xrealloc2(), send_internal(), set_eventloop_tick(), set_eventloop_weight(), set_max_block_time(), set_no_event_wait(), sig_trap(), sock_s_getnameinfo(), sock_s_unpack_sockaddr_in(), str_buf_cat(), str_find_encindex(), str_new(), str_to_encindex(), str_transcode0(), string_to_c_strict(), string_to_r_strict(), strio_each(), strio_read(), strio_readlines(), sym_call(), symbol2event_flag(), syslog_write(), tcl2rb_num_or_str(), time_fixoff(), time_gmtime(), time_localtime(), time_mdump(), time_overflow_p(), time_round(), time_strftime(), time_timespec(), timegmw(), timelocalw(), timew2timespec(), tk_conv_args(), tk_hash_kv(), tkstr_invalid_numstr(), tkstr_rescue_float(), tkstr_to_number(), too_short(), transcode_loop(), trap_handler(), trap_signm(), trnext(), unknown_keyword_error(), update_i(), utc_offset_arg(), utf8_to_uv(), validate_enc_binmode(), validate_utc_offset(), validate_vtm(), vm_backtrace_to_ary(), vm_call_opt_send(), w_object(), xmalloc2_size(), yielder_init(), and yielder_ptr().
RUBY_EXTERN VALUE rb_eEncCompatError
Definition at line 518 of file error.c.
Referenced by check_path_encoding(), Init_Exception(), rb_enc_check(), rb_enc_cr_str_buf_cat(), rb_inspect(), rb_must_asciicompat(), rb_str_check_dummy_enc(), rb_str_sub_bang(), and reg_enc_error().
RUBY_EXTERN VALUE rb_eEncodingError
Definition at line 517 of file error.c.
Referenced by Init_Exception(), Init_transcode(), and sym_check_asciionly().
RUBY_EXTERN VALUE rb_eException
Definition at line 504 of file error.c.
Referenced by Init_eval_method(), Init_Exception(), Init_gdbm(), Init_Proc(), ip_eval(), ip_eval_real(), ip_invoke_core(), ip_invoke_with_position(), lib_eventloop_core(), lib_eventloop_main(), make_exception(), pending_exception_check0(), pending_exception_check1(), rb_set_errinfo(), tcl_protect_core(), and tk_funcall().
RUBY_EXTERN VALUE rb_eFatal
Definition at line 508 of file error.c.
Referenced by Init_eval(), Init_Exception(), ip_eval_real(), ip_invoke_core(), lib_eventloop_core(), lib_eventloop_main(), rb_check_deadlock(), rb_fatal(), and tcl_protect_core().
RUBY_EXTERN VALUE rb_eIndexError
Definition at line 513 of file error.c.
Referenced by fdbm_fetch_m(), fgdbm_fetch_m(), fsdbm_fetch_m(), hist_delete_at(), hist_get(), Init_Exception(), InitVM_Enumerator(), match_backref_number(), match_begin(), match_end(), match_offset(), name_to_backref_number(), oleparam_ole_param_from_index(), rb_ary_fetch(), rb_ary_resize(), rb_ary_splice(), rb_ary_store(), rb_ary_transpose(), rb_str_aset(), rb_str_ellipsize(), rb_str_setbyte(), rb_str_splice(), rb_str_subpat_set(), rb_struct_aref(), and rb_struct_aset().
RUBY_EXTERN VALUE rb_eInterrupt
Definition at line 506 of file error.c.
Referenced by Init_Exception(), Init_signal(), ip_rbTkWaitCommand(), ip_rbUpdateCommand(), ip_rbVwaitCommand(), rb_interrupt(), and tcl_protect_core().
RUBY_EXTERN VALUE rb_eKeyError
Definition at line 514 of file error.c.
Referenced by env_fetch(), Init_Exception(), rb_hash_fetch_m(), and rb_str_format().
RUBY_EXTERN VALUE rb_eLoadError
Definition at line 527 of file error.c.
Referenced by Init_Exception(), Init_tcltklib(), ip_init(), raise_loaderror(), tcl_stubs_check(), and tcltkip_init_tk().
RUBY_EXTERN VALUE rb_eNameError
Definition at line 516 of file error.c.
Referenced by Init_Exception(), ip_invoke_core(), process_sflag(), raise_method_missing(), rb_autoload(), rb_mod_const_get(), rb_name_error(), and rb_name_error_str().
VALUE rb_eNOERROR static
Definition at line 531 of file error.c.
Referenced by Init_syserr().
RUBY_EXTERN VALUE rb_eNoMemError
Definition at line 522 of file error.c.
Referenced by Init_Exception(), Init_GC(), negative_size_allocation_error(), and negative_size_allocation_error_with_gvl().
RUBY_EXTERN VALUE rb_eNoMethodError
Definition at line 519 of file error.c.
Referenced by check_funcall_missing(), gzfile_read_raw(), gzfile_read_raw_rescue(), Init_Exception(), make_no_method_exception(), ole_invoke(), raise_method_missing(), send_internal(), vm_call_opt_send(), and vm_super_outside().
RUBY_EXTERN VALUE rb_eNotImpError
Definition at line 521 of file error.c.
Referenced by advice_arg_check(), copy_stream_finalize(), Init_Exception(), ip_cancel_eval_core(), is_popen_fork(), lib_mainloop_watchdog(), ossl_pkey_initialize(), rb_digest_base_alloc(), rb_execarg_addopt(), rb_notimplement(), and rb_search_method_entry().
RUBY_EXTERN VALUE rb_eRangeError
Definition at line 515 of file error.c.
Referenced by big2str_find_n1(), big2ulong(), check_ushort(), id2ref(), Init_Exception(), Init_Numeric(), int_chr(), nucomp_rationalize(), nucomp_to_f(), nucomp_to_i(), nucomp_to_r(), onigenc_single_byte_code_to_mbc(), pack_pack(), pack_unpack(), rb_ary_product(), rb_big2long(), rb_big2ulong(), rb_enc_uint_chr(), rb_num2fix(), rb_num2long(), rb_num2ulong(), rb_out_of_short(), rb_random_real(), rb_random_ulong_limited(), rb_range_beg_len(), rb_str_concat(), rb_time_new(), rb_uv_to_utf8(), sock_s_getservbyport(), strscan_set_pos(), time_overflow_p(), time_timespec(), and wv2timet().
RUBY_EXTERN VALUE rb_eRuntimeError
Definition at line 510 of file error.c.
Referenced by ary2safe_array_index(), ary_new_dim(), bubblebabble_str_new(), callback(), check_dump_arg(), check_gid_switch(), check_load_arg(), check_uid_switch(), chunk_ii(), closed_dbm(), create_dummy_encoding_for_tk_core(), create_encoding_table_core(), curses_init_screen(), emit(), enum_sort_by(), error_print(), ev_advise(), eval_string_with_cref(), fiber_t_alloc(), flatten(), fole_each(), fole_method_help(), fole_missing(), fole_query_interface(), fole_s_const_load(), fole_s_create_guid(), fole_s_show_help(), fole_type(), fole_typelib(), folevariant_ary_aset(), folevariant_s_array(), generic_to_value(), get_device_once(), get_digest_base_metadata(), get_locked_safe_array(), get_trace_arg(), GetDigestPtr(), hash_foreach_call(), hash_foreach_iter(), hexencode_str_new(), Init_cparse(), Init_Exception(), Init_pty(), Init_win32ole(), initialize(), int_to_ffi_type(), intern_str(), ip_allow_ruby_exit_p(), ip_allow_ruby_exit_set(), ip_create_console(), ip_create_console_core(), ip_create_slave(), ip_create_slave_core(), ip_eval_real(), ip_get_variable2_core(), ip_init(), ip_invoke_core(), ip_is_safe_p(), ip_make_menu_embeddable_core(), ip_make_safe(), ip_make_safe_core(), ip_rb_threadTkWaitCommand(), ip_rb_threadUpdateCommand(), ip_rb_threadVwaitCommand(), ip_rbTkWaitCommand(), ip_rbUpdateCommand(), ip_rbVwaitCommand(), ip_restart(), ip_ruby_cmd(), ip_ruby_eval(), ip_set_variable2_core(), ip_unset_variable2_core(), lib_do_one_event_core(), lib_get_reltype_name(), lib_restart(), lib_restart_core(), lib_split_tklist_core(), make_exception(), mSyslog_close(), mSyslog_open(), mSyslog_set_mask(), new_size(), no_new_key(), no_window(), ole_create_dcom(), ole_initialize(), ole_invoke(), ole_set_safe_array(), ole_val2olevariantdata(), ole_val_ary2variant_ary(), ole_variant2val(), oleparam_ole_param_from_index(), opt_enc_index(), ossl_cipher_initialize(), ossl_digest_alloc(), pack_pack(), permute0(), prep_window(), proc_options(), rb_alias_variable(), rb_ary_combination(), rb_ary_product(), rb_ary_set_len(), rb_ary_shuffle_bang(), rb_binding_new_with_cfp(), rb_cont_call(), rb_coverage_result(), rb_digest_instance_method_unimpl(), rb_error_frozen(), rb_file_initialize(), rb_hash_rehash(), rb_provide_feature(), rb_reg_regsub(), rb_str_set_len(), rb_str_unlocktmp(), rb_thread_shield_waiting_dec(), rb_thread_shield_waiting_inc(), rb_threadptr_raise(), rb_tracearg_raised_exception(), rb_tracearg_return_value(), rb_vm_cbase(), rcombinate0(), ripper_token2eventid(), rpermute0(), rscheck(), rsock_s_recvfrom(), ruby__sfvextra(), ruby__sfvwrite(), RUBY_ALIAS_FUNCTION(), set_arg0(), set_option_encoding_once(), setup_exception(), sort_by_cmp(), sort_by_i(), sort_reentered(), st_foreach_safe(), start_document(), str_gsub(), str_mod_check(), str_modifiable(), syslog_write(), tcl_stubs_check(), tcltkip_init_tk(), top_using(), transcode_restartable0(), typeinfo_from_ole(), unlock_safe_array(), val2variant_ptr(), value_to_generic(), vm_search_super_method(), and w_object().
RUBY_EXTERN VALUE rb_eScriptError
Definition at line 525 of file error.c.
Referenced by Init_Exception().
RUBY_EXTERN VALUE rb_eSecurityError
Definition at line 520 of file error.c.
Referenced by bsock_close_read(), bsock_close_write(), bsock_shutdown(), check_before_mod_set(), dir_check(), dir_rewind(), env_aset(), ev_advise(), fole_initialize(), fole_s_connect(), forbid_setid(), function_call(), Init_Exception(), io_reopen(), ip_allow_ruby_exit_set(), ip_init(), rb_alias_variable(), rb_ary_modify_check(), rb_check_copyable(), rb_const_remove(), rb_error_untrusted(), rb_f_eval(), rb_f_trace_var(), rb_find_file_ext_safe(), rb_find_file_safe(), rb_gvar_set(), rb_hash_modify_check(), rb_insecure_operation(), rb_io_close_m(), rb_io_close_read(), rb_io_close_write(), rb_io_taint_check(), rb_ivar_set(), rb_method_call_status(), rb_method_entry_make(), rb_mod_remove_cvar(), rb_obj_freeze(), rb_obj_remove_instance_variable(), rb_reg_initialize(), rb_secure(), rb_thread_local_aref(), rb_thread_local_aset(), rb_thread_variable_get(), rb_thread_variable_set(), rb_undef(), remove_method(), safe_setter(), secure_visibility(), security(), set_const_visibility(), sig_trap(), str_modifiable(), vm_call_method(), and vm_setivar().
RUBY_EXTERN VALUE rb_eSignal
Definition at line 507 of file error.c.
Referenced by error_handle(), Init_Exception(), Init_signal(), rb_threadptr_signal_raise(), and ruby_cleanup().
RUBY_EXTERN VALUE rb_eStandardError
Definition at line 509 of file error.c.
Referenced by exp1(), Init_Cont(), Init_dbm(), Init_dl(), Init_Exception(), Init_fiddle(), Init_gdbm(), Init_IO(), Init_Numeric(), Init_openssl(), Init_Proc(), Init_Regexp(), Init_sdbm(), Init_strscan(), Init_tcltklib(), Init_Thread(), Init_zlib(), iseq_compile_each(), rb_rescue(), and rsock_init_socket_init().
RUBY_EXTERN VALUE rb_eSyntaxError
Definition at line 526 of file error.c.
Referenced by compile_err_append(), dump_disasm_list(), get_exception_sym2type(), Init_Exception(), insn_data_to_s_detail(), iseq_build_from_ary_body(), iseq_build_from_ary_exception(), and iseq_build_load_iseq().
RUBY_EXTERN VALUE rb_eSystemCallError
Definition at line 529 of file error.c.
Referenced by float_value(), Init_Exception(), rb_io_initialize(), set_syserr(), syserr_eqq(), and syserr_initialize().
RUBY_EXTERN VALUE rb_eSystemExit
Definition at line 505 of file error.c.
Referenced by error_handle(), Init_Exception(), ip_rbTkWaitCommand(), ip_rbUpdateCommand(), ip_rbVwaitCommand(), ip_RubyExitCommand(), rb_exit(), rb_f_abort(), rb_threadptr_signal_exit(), ruby_cleanup(), setup_exception(), tcl_protect_core(), and thread_start_func_2().
RUBY_EXTERN VALUE rb_eTypeError
Definition at line 511 of file error.c.
Referenced by addrinfo_initialize(), addrinfo_mload(), advice_arg_check(), asn1integer_to_num(), asn1time_to_time(), BigDecimal_load(), BigDecimal_mode(), BigDecimal_power(), bit_coerce(), check_econv(), check_match(), class2path(), class_init_copy_check(), class_or_module_required(), coerce_rescue(), convert_type(), count_nodes(), count_objects(), count_objects_size(), count_tdata_objects(), cParser_initialize(), d_lite_marshal_load(), d_lite_minus(), d_lite_plus(), default_proc_arity_check(), divmodv(), do_coerce(), econv_init(), enum_zip(), enumerator_feed(), enumerator_init_copy(), ev_advise(), ev_on_event(), eval_string_with_cref(), extract_user_token(), f_round_common(), fev_off_event(), fole_respond_to(), fole_s_const_load(), fole_s_show_help(), folemethod_initialize(), foleparam_initialize(), folevariant_initialize(), gc_stat(), generator_initialize(), get_addrinfo(), get_locked_safe_array(), get_new_timeval(), get_stat(), get_strpath(), get_timeval(), GetBNPtr(), GetVpValueWithPrec(), hash2named_arg(), init_copy(), Init_Exception(), io_needed(), iseq_build_from_ary_body(), iseq_check(), iseq_load(), lazy_zip(), long_toobig(), make_compile_option(), make_exception(), marshal_load(), match_check(), mSyslog_log(), must_encoding(), must_not_be_anonymous(), must_respond_to(), nucomp_coerce(), nucomp_real_check(), nucomp_s_convert(), num_exact(), num_init_copy(), num_members(), num_sadded(), num_to_asn1integer(), nurat_coerce(), nurat_int_check(), nurat_s_convert(), obj_to_asn1bool(), offset_to_sec(), ole_invoke(), ole_invoke2(), ossl_bn_coerce(), ossl_dh_new(), ossl_dsa_new(), ossl_rsa_new(), r_object0(), rand_init(), range_bsearch(), range_each(), range_loader(), range_max(), range_step(), rb_alias(), rb_ary_bsearch(), rb_big_coerce(), rb_check_backtrace(), rb_check_convert_type(), rb_check_id(), rb_check_inheritable(), rb_check_safe_str(), rb_check_type(), rb_check_typeddata(), rb_class_inherited_p(), rb_class_initialize(), rb_class_superclass(), rb_const_set(), rb_convert_to_integer(), rb_convert_type(), rb_define_class(), rb_define_class_id_under(), rb_define_module(), rb_define_module_id_under(), rb_dlcfunc2ptr(), rb_dlptr2cptr(), rb_f_autoload(), rb_fiddle_ptr2cptr(), rb_Float(), rb_Hash(), rb_hash_set_default_proc(), rb_iseq_line_trace_specify(), rb_marshal_define_compat(), rb_method_call_with_block(), rb_method_entry_make(), rb_mod_const_get(), rb_mod_define_method(), rb_mod_ge(), rb_mod_modfunc(), rb_num2dbl(), rb_num2long(), rb_num2ulong(), rb_obj_alloc(), rb_obj_clone(), rb_obj_dup(), rb_obj_encoding(), rb_obj_init_copy(), rb_path_to_class(), rb_reg_check(), rb_reg_initialize(), rb_set_errinfo(), rb_str_index_m(), rb_str_match(), rb_str_partition(), rb_str_rindex_m(), rb_str_rpartition(), rb_str_setter(), rb_struct_aset_id(), rb_struct_init_copy(), rb_struct_members(), rb_struct_s_members(), rb_thread_pending_interrupt_p(), rb_to_float(), rb_to_id(), rb_to_integer(), rb_undef(), recursive_pop(), rsock_io_socket_addrinfo(), rsock_s_recvfrom(), set_trace_func(), singleton_class_of(), sock_s_getnameinfo(), sockopt_bool(), sockopt_int(), sockopt_linger(), syserr_initialize(), take_items(), thread_add_trace_func(), time_mload(), time_plus(), time_timespec(), umethod_bind(), uscore_get(), value_to_id(), vm_caller_setup_args(), vm_check_if_namespace(), vm_define_method(), vm_get_cvar_base(), vm_search_super_method(), vm_set_top_stack(), w_extended(), w_long(), w_object(), w_symbol(), and wdivmod().
RUBY_EXTERN VALUE rb_mErrno
Definition at line 530 of file error.c.
Referenced by Init_Exception(), path_unlink(), and set_syserr().
const char ruby_description[]
Definition at line 64 of file version.c.
Referenced by rb_async_bug_errno(), and report_bug().
st_table* syserr_tbl static
Definition at line 1177 of file error.c.