Ruby: nacl/unistd.h File Reference
unistd.h File Reference
Functions
int seteuid (pid_t pid)
int setegid (pid_t pid)
int truncate (const char *path, off_t new_size)
int ftruncate (int fd, off_t new_size)
Function Documentation
int ftruncate (int fd, off_t new_size)
int setegid (pid_t pid)
Referenced by p_gid_change_privilege(), and rb_setegid_core().
int seteuid (pid_t pid)
Referenced by chfunc(), p_uid_change_privilege(), and rb_seteuid_core().
int truncate (const char * path, off_t new_size)