Ruby: ext/socket/sockssocket.c File Reference
sockssocket.c File Reference
#include "rubysocket.h"
Functions
void rsock_init_sockssocket (void)
Function Documentation
void rsock_init_sockssocket (void)
Definition at line 55 of file sockssocket.c.
References rb_cTCPSocket, rb_define_class(), and rb_define_method().
Referenced by rsock_init_socket_init().