Ruby: dmydln.c File Reference
dmydln.c File Reference
#include "ruby/ruby.h"
Functions
void * dln_load (const char *file)
Function Documentation
void* dln_load (const char * file)
Definition at line 4 of file dmydln.c.
References buf, DLN_ERROR, dln_load(), dln_loaderror(), dln_notimplement, dln_strerror(), errno, free, init_funcname, MAXPATHLEN, NULL, p, rb_loaderror(), strdup, strerror(), strlcat(), strlcpy(), strlen(), translit_separator, and UNREACHABLE.