Ruby: ext/fiddle/function.h File Reference
function.h File Reference
#include <fiddle.h>
Functions
void Init_fiddle_function ()
Function Documentation
void Init_fiddle_function ()
Definition at line 173 of file function.c.
References allocate(), cFiddleFunction, function_call(), initialize(), INT2NUM, mFiddle, rb_cObject, rb_define_alloc_func(), rb_define_class_under(), rb_define_const(), and rb_define_method().
Referenced by Init_fiddle().