requires "Kossy", 0.19;
requires "DBIx::Sunny";
requires "JSON::XS";
requires "Digest::SHA";
requires "File::Temp";
requires "Time::Piece";

requires "DBD::mysql";
requires "Starman";
requires "Plack::Session";
requires "Cache::Memcached::Fast";
requires "Server::Starter";
requires "Net::Server::SS::PreFork";
requires "DDP";
requires "DBIx::QueryLog";
requires "Text::Markdown";
requires "Text::Markdown::Discount";

requires "MySQL::Warmer";
